import crypto from'crypto';import type{AiPlatformStore}from'../storage/aiPlatformStore.js';import{insertId}from'../storage/aiPlatformStore.js';import type{BusinessActionContext,BusinessActionStatus}from'./actionTypes.js';
export class ActionRepository{constructor(private readonly store:AiPlatformStore){}
 async create(context:BusinessActionContext,definitionId:number,input:unknown,inputHash:string){const result:any=await this.store.query(`INSERT INTO ai_actions(tenant_id,trace_id,conversation_id,voice_session_id,agent_id,agent_version_id,action_key,action_version,status,risk_level,autonomy_decision,approval_mode,requested_by_type,requested_by_id,input_json,input_hash,idempotency_key,requested_at,expires_at,metadata_json)VALUES(?,?,?,?,?,?,? ,1,'requested','low','allowed','customer_consent',?,?,?, ?,?,NOW(),DATE_ADD(NOW(),INTERVAL 10 MINUTE),?)`,[context.tenantId,context.traceId,context.conversationId,context.voiceSessionId,context.agentId,context.agentVersionId,'business.create_callback_request',context.actorType,context.actorId,JSON.stringify(input),inputHash,context.idempotencyKey,JSON.stringify({sourceChannel:context.sourceChannel,definitionId})]);return insertId(result)}
 async update(id:number,status:BusinessActionStatus,fields:{output?:unknown;summary?:string;errorCode?:string|null}={}){await this.store.query(`UPDATE ai_actions SET status=?,output_json=COALESCE(?,output_json),safe_summary=COALESCE(?,safe_summary),error_code=?,approved_at=CASE WHEN ?='approved' THEN NOW() ELSE approved_at END,started_at=CASE WHEN ?='running' THEN NOW() ELSE started_at END,completed_at=CASE WHEN ?='completed' THEN NOW() ELSE completed_at END,failed_at=CASE WHEN ? IN('failed','timed_out','denied','cancelled') THEN NOW() ELSE failed_at END WHERE id=?`,[status,fields.output===undefined?null:JSON.stringify(fields.output),fields.summary??null,fields.errorCode??null,status,status,status,status,id])}
 get(tenantId:number,id:number){return this.store.query('SELECT * FROM ai_actions WHERE tenant_id=? AND id=? LIMIT 1',[tenantId,id])}
 findReplay(tenantId:number,key:string){return this.store.query(`SELECT * FROM ai_actions WHERE tenant_id=? AND idempotency_key=? ORDER BY id DESC LIMIT 1`,[tenantId,key])}
 async findActiveCallback(tenantId:number,conversationId:number|null,phoneHash:string){return this.store.query(`SELECT a.id action_id,c.id callback_id,a.safe_summary FROM ai_callback_requests c JOIN ai_actions a ON a.id=c.created_by_action_id WHERE c.tenant_id=? AND ((? IS NOT NULL AND c.conversation_id=?) OR c.phone_hash=?) AND c.status IN('new','acknowledged','assigned','in_progress') ORDER BY c.id DESC LIMIT 1`,[tenantId,conversationId,conversationId,phoneHash])}
 hash(input:unknown){return crypto.createHash('sha256').update(JSON.stringify(input)).digest('hex')}
}
