import type { Express, Request, Response } from 'express';
import { AiPlatformError } from '../../core/errors.js';
import { parseJsonObject, redactAiPlatformValue } from '../../core/redaction.js';
import type { AiPlatformStore } from '../../storage/aiPlatformStore.js';
import type { AiAuditService } from '../../audit/aiAuditService.js';
import type { LifecycleActor } from '../../agents/agentLifecycleService.js';
import { TrainingService } from '../core/trainingService.js';
type Handler=(req:Request,res:Response)=>Promise<any>;
export interface TrainingRouteRuntime { authenticated:any[];permit:(permission:string)=>any;enabled:any;wrap:(handler:Handler)=>any;getTenantId:()=>Promise<number>;actor:(req:Request)=>LifecycleActor;store:AiPlatformStore;audit:AiAuditService;positiveInt:(value:unknown,name:string)=>number;page:(req:Request)=>{limit:number;offset:number} }
export function registerTrainingRoutes(app:Express,r:TrainingRouteRuntime){const service=new TrainingService(r.store,r.audit);
  app.get('/api/ai-platform/training',...r.authenticated,r.permit('view_ai_training'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),p=r.page(req),agentId=req.query.agentId?r.positiveInt(req.query.agentId,'agent id'):null;const rows=await r.store.query(`SELECT id,agent_id,type,title,input_text,expected_output,rule_json,status,created_by,created_at FROM ai_training_items WHERE tenant_id=? ${agentId?'AND agent_id=?':''} ORDER BY id DESC LIMIT ? OFFSET ?`,agentId?[tenantId,agentId,p.limit,p.offset]:[tenantId,p.limit,p.offset]);res.json({success:true,rows:rows.map(row=>({...row,input_text:redactAiPlatformValue(row.input_text).value,expected_output:redactAiPlatformValue(row.expected_output).value,rule:redactAiPlatformValue(parseJsonObject(row.rule_json,'rule_json')).value,rule_json:undefined})),page:Math.floor(p.offset/p.limit)+1,limit:p.limit})}));
  app.post('/api/ai-platform/training',...r.authenticated,r.permit('manage_ai_training'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId();res.status(201).json({success:true,data:await service.createTrainingItem(tenantId,{agentId:r.positiveInt(req.body?.agentId,'agent id'),type:req.body?.type,title:req.body?.title,inputText:req.body?.inputText,expectedOutput:req.body?.expectedOutput,rule:req.body?.rule},r.actor(req))})}));
  app.get('/api/ai-platform/training/:id',...r.authenticated,r.permit('view_ai_training'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),id=r.positiveInt(req.params.id,'training item id');const rows=await r.store.query('SELECT id,agent_id,type,title,input_text,expected_output,rule_json,status,created_by,created_at FROM ai_training_items WHERE id=? AND tenant_id=? LIMIT 1',[id,tenantId]);if(!rows.length)throw new AiPlatformError('not_found',404,'Training item not found');const row=rows[0];res.json({success:true,data:{...row,input_text:redactAiPlatformValue(row.input_text).value,expected_output:redactAiPlatformValue(row.expected_output).value,rule:redactAiPlatformValue(parseJsonObject(row.rule_json,'rule_json')).value,rule_json:undefined}})}));
  app.post('/api/ai-platform/training/:id/publish',...r.authenticated,r.permit('publish_ai_training'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),itemId=r.positiveInt(req.params.id,'training item id');const items=await r.store.query('SELECT agent_id FROM ai_training_items WHERE id=? AND tenant_id=? LIMIT 1',[itemId,tenantId]);if(!items.length)throw new AiPlatformError('not_found',404,'Training item not found');const agentId=Number(items[0].agent_id);let versionId=req.body?.versionId?r.positiveInt(req.body.versionId,'training version id'):undefined;if(!versionId)versionId=(await service.createTrainingVersion(tenantId,agentId,r.actor(req))).id;res.json({success:true,data:await service.publishTraining(tenantId,agentId,versionId,r.actor(req))})}));
}
