import type{AiAuditService}from'../../audit/aiAuditService.js';import type{AriClientAdapter}from'./ariClientAdapter.js';import type{AriEventHandler,AriHealth}from'./ariTypes.js';
export class AriConnectionManager{
 private running=false;private connecting:Promise<void>|null=null;private timer:ReturnType<typeof setTimeout>|null=null;private generation=0;private reconnectCount=0;private lastDisconnectedAt:string|null=null;
 constructor(private adapter:AriClientAdapter,private audit:AiAuditService,private tenantId:()=>Promise<number>,private handler:AriEventHandler,private delays={initial:500,max:30000}){adapter.onDisconnect?.(()=>this.disconnected())}
 async start(traceId:string){if(this.running)return;if(this.connecting)return this.connecting;this.running=true;this.adapter.subscribe(this.handler);return this.connect(traceId)}
 private connect(traceId:string){if(this.connecting)return this.connecting;const generation=++this.generation;this.connecting=this.adapter.connect().then(async()=>{this.reconnectCount=0;await this.emit(traceId,'ari_connected','connected')}).catch(async error=>{await this.emit(traceId,'voice_gateway_start_failed','failed',{errorCode:'ari_connection_failed'});this.schedule(traceId,generation);throw error}).finally(()=>{this.connecting=null});return this.connecting}
 private disconnected(){if(!this.running)return;this.lastDisconnectedAt=new Date().toISOString();const generation=++this.generation;void this.emit('ari-reconnect','ari_disconnected','disconnected');this.schedule('ari-reconnect',generation)}
 private schedule(traceId:string,generation:number){if(!this.running||generation!==this.generation||this.timer)return;const delay=Math.min(this.delays.max,this.delays.initial*2**Math.min(this.reconnectCount++,10))+Math.floor(Math.random()*100);void this.emit(traceId,'ari_reconnect_scheduled','scheduled',{reconnectCount:this.reconnectCount,delayMs:delay});this.timer=setTimeout(()=>{this.timer=null;void this.connect(traceId).catch(()=>{})},delay);this.timer.unref?.()}
 async stop(traceId:string){this.running=false;this.generation++;if(this.timer)clearTimeout(this.timer);this.timer=null;this.adapter.unsubscribe(this.handler);await this.adapter.disconnect();this.lastDisconnectedAt=new Date().toISOString();await this.emit(traceId,'ari_disconnected','disconnected')}
 private async emit(traceId:string,eventType:any,decision:string,details:unknown={}){await this.audit.append({tenantId:await this.tenantId(),traceId,actorType:'service',eventType,entityType:'voice_gateway',decision,details})}
 status(){const h:AriHealth=this.adapter.getHealth();return{...h,running:this.running,reconnectCount:this.reconnectCount,lastDisconnectedAt:this.lastDisconnectedAt,generation:this.generation}}
}
