import type{AiAuditService}from'../../audit/aiAuditService.js';import type{AriClientAdapter}from'./ariClientAdapter.js';import type{AriEventHandler,AriHealth}from'./ariTypes.js';
export class AriConnectionManager{
 private running=false;private connecting:Promise<void>|null=null;private timer:ReturnType<typeof setTimeout>|null=null;private generation=0;private reconnectCount=0;private lastDisconnectedAt:string|null=null;
 constructor(private adapter:AriClientAdapter,private audit:AiAuditService,private tenantId:()=>Promise<number>,private handler:AriEventHandler,private delays={initial:500,max:30000}){}
 async start(traceId:string){if(this.running)return;if(this.connecting)return this.connecting;this.running=true;this.adapter.subscribe(this.handler);return this.connect(traceId)}
 private connect(traceId:string){if(this.connecting)return this.connecting;const generation=++this.generation;this.connecting=this.adapter.connect().then(()=>this.emit(traceId,'ari_connected','connected')).catch(async error=>{await this.emit(traceId,'voice_gateway_start_failed','failed',{errorCode:'ari_connection_failed'});await this.emit(traceId,'ari_reconnect_scheduled','scheduled',{reconnectCount:this.reconnectCount});if(this.running&&generation===this.generation){const delay=Math.min(this.delays.max,this.delays.initial*2**this.reconnectCount++)+Math.floor(Math.random()*100);this.timer=setTimeout(()=>{this.connecting=null;void this.connect(traceId).catch(()=>{})},delay)}throw error}).finally(()=>{this.connecting=null});return this.connecting}
 async stop(traceId:string){this.running=false;this.generation++;if(this.timer)clearTimeout(this.timer);this.timer=null;this.adapter.unsubscribe(this.handler);await this.adapter.disconnect();this.lastDisconnectedAt=new Date().toISOString();await this.emit(traceId,'ari_disconnected','disconnected')}
 private async emit(traceId:string,eventType:any,decision:string,details:unknown={}){await this.audit.append({tenantId:await this.tenantId(),traceId,actorType:'service',eventType,entityType:'voice_gateway',decision,details})}
 status(){const h:AriHealth=this.adapter.getHealth();return{...h,running:this.running,reconnectCount:this.reconnectCount,lastDisconnectedAt:this.lastDisconnectedAt,generation:this.generation}}
}
