import React, { useEffect, useMemo, useState } from 'react';
import { Clock, Download, Info, PhoneCall, PhoneMissed, PhoneOutgoing, Target, Users } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { StatsKpiCard } from './StatsKpiCard';

type Props={startDate:string;endDate:string;group:string;department:string;employee:string;extensions:string[];emptyDepartmentSelection:boolean;refreshKey:number};
const colors=['#2563eb','#16a34a','#f59e0b','#ef4444','#8b5cf6','#64748b'];
const input='h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold dark:border-slate-700 dark:bg-slate-900';
function token(){try{return JSON.parse(localStorage.getItem('asterisk_cdr_session')||'{}').token||''}catch{return ''}}
function duration(v:any){if(v==null)return '—';const n=Math.round(Number(v)||0);return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
function Panel({title,subtitle,children,className=''}:{title:string;subtitle?:string;children:React.ReactNode;className?:string}){return <section className={`rounded-2xl border border-slate-200/70 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 ${className}`}><div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="text-sm font-black text-slate-950 dark:text-white">{title}</h3>{subtitle&&<p className="mt-1 text-[11px] font-semibold text-slate-500 dark:text-slate-400">{subtitle}</p>}</div><Info className="h-4 w-4 shrink-0 text-slate-400"/></div>{children}</section>}
export function OutgoingDashboard({startDate,endDate,group,department,employee,extensions,emptyDepartmentSelection,refreshKey}:Props){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [page,setPage]=useState(1),[heatMetric,setHeatMetric]=useState('attempts');
 const params=useMemo(()=>{const p=new URLSearchParams({startDate,endDate,group,department,employee,page:String(page),pageSize:'25'});if(extensions.length)p.set('extensions',extensions.join(','));if(emptyDepartmentSelection)p.set('emptySelection','true');return p},[startDate,endDate,group,department,employee,extensions.join(','),emptyDepartmentSelection,page]);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/reports/outgoing?'+params,{headers:{Authorization:'Bearer '+token()}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Ошибка отчёта');setData(j)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{setPage(1)},[startDate,endDate,group,department,employee,extensions.join(','),emptyDepartmentSelection]);
 useEffect(()=>{load()},[params.toString(),refreshKey]);
 const k=data?.kpis||{};const retry=data?.retries||{};const retryChart=['first','second','third','fourth','fifthPlus','never'].map((key,i)=>({name:['1-я','2-я','3-я','4-я','5+','Нет дозвона'][i],count:retry[key]?.numbers||0,rate:retry[key]?.attempts?100*(retry[key]?.answered||0)/retry[key].attempts:0}));
 const resultLabels:Record<string,string>={answered:'Отвечено',no_answer:'Нет ответа',busy:'Занято',failed:'Ошибка',congestion:'Перегрузка',other:'Другие'};
 const resultData=(data?.results||[]).map((row:any)=>({...row,label:resultLabels[row.result]||row.result}));
 const heat=Array.from({length:7},(_,day)=>({day:['Пн','Вт','Ср','Чт','Пт','Сб','Вс'][day],hours:Array.from({length:24},(_,hour)=>{const x=data?.heatmap?.find((r:any)=>Number(r.weekday)===day&&Number(r.hour)===hour)||{};return heatMetric==='answerRate'?(Number(x.attempts)?100*Number(x.answered)/Number(x.attempts):0):Number(x[heatMetric]||0)})}));
 return <div className="space-y-4">
  {error&&<div className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
  <div className="grid grid-cols-2 gap-3 xl:grid-cols-5">
   <StatsKpiCard label="Всего попыток" value={Number(k.totalAttempts||0).toLocaleString('ru')} hint="Уникальные linkedid" icon={PhoneOutgoing} tone="blue"/><StatsKpiCard label="Уникальные номера" value={Number(k.uniqueNumbers||0).toLocaleString('ru')} hint="Внешние назначения" icon={Users} tone="purple"/><StatsKpiCard label="Успешные дозвоны" value={Number(k.answered||0).toLocaleString('ru')} hint="ANSWERED и billsec > 0" icon={PhoneCall} tone="green"/><StatsKpiCard label="Недозвоны" value={Number(k.unanswered||0).toLocaleString('ru')} hint="Без разговора" icon={PhoneMissed} tone="red"/><StatsKpiCard label="Процент дозвона" value={Number(k.answerRate||0).toFixed(1)+'%'} hint="Успешные / попытки" icon={Target} tone="green"/>
   <StatsKpiCard label="Среднее ожидание" value={duration(k.averageWaitSeconds)} hint="Fallback duration − billsec" icon={Clock} tone="orange"/><StatsKpiCard label="Медиана ожидания" value={duration(k.medianWaitSeconds)} hint="Только отвеченные" icon={Clock} tone="orange"/><StatsKpiCard label="Средний разговор" value={duration(k.averageTalkSeconds)} hint="По billsec" icon={PhoneCall} tone="blue"/><StatsKpiCard label="Разговорное время" value={duration(k.totalTalkSeconds)} hint="Сумма billsec" icon={PhoneCall} tone="purple"/><StatsKpiCard label="С первой попытки" value={Number(k.firstAttemptRate||0).toFixed(1)+'%'} hint="В пределах периода" icon={Target} tone="green"/>
  </div>
  <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
   <Panel title="Динамика исходящих" subtitle="Фактические попытки CDR по выбранному периоду" className="flex h-[330px] flex-col"><div className="min-h-0 flex-1"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data?.timeline||[]} margin={{top:5,right:5,left:-25,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="bucket" tickLine={false} axisLine={false} tick={{fill:'#94a3b8',fontSize:9,fontWeight:700}}/><YAxis tickLine={false} axisLine={false} tick={{fill:'#94a3b8',fontSize:9,fontWeight:700}}/><Tooltip contentStyle={{backgroundColor:'#1e293b',border:'none',borderRadius:'10px'}} labelStyle={{color:'#f8fafc'}}/><Legend/><Bar dataKey="attempts" name="Попытки" fill="#3b82f6" radius={[3,3,0,0]}/><Line type="monotone" dataKey="answered" name="Отвеченные" stroke="#10b981" strokeWidth={2}/><Line type="monotone" dataKey="unanswered" name="Неотвеченные" stroke="#ef4444" strokeWidth={2}/></ComposedChart></ResponsiveContainer></div></Panel>
   <Panel title="Процент дозвона" subtitle="ANSWERED с billsec > 0 / все попытки" className="flex h-[330px] flex-col"><div className="min-h-0 flex-1"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data?.timeline||[]} margin={{top:5,right:5,left:-25,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="bucket" tickLine={false} axisLine={false} tick={{fill:'#94a3b8',fontSize:9,fontWeight:700}}/><YAxis domain={[0,100]} tickFormatter={v=>`${v}%`} tickLine={false} axisLine={false} tick={{fill:'#94a3b8',fontSize:9,fontWeight:700}}/><Tooltip contentStyle={{backgroundColor:'#1e293b',border:'none',borderRadius:'10px'}} labelStyle={{color:'#f8fafc'}}/><Line type="monotone" dataKey="answer_rate" stroke="#10b981" strokeWidth={2} dot={{r:3}} name="Дозвон, %"/></ComposedChart></ResponsiveContainer></div></Panel>
   <Panel title="Ожидание ответа" subtitle="Расчёт по реальным duration и billsec" className="flex h-[330px] flex-col"><div className="min-h-0 flex-1"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data?.timeline||[]} margin={{top:5,right:5,left:-25,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="bucket" tickLine={false} axisLine={false} tick={{fill:'#94a3b8',fontSize:9,fontWeight:700}}/><YAxis tickLine={false} axisLine={false} tick={{fill:'#94a3b8',fontSize:9,fontWeight:700}}/><Tooltip contentStyle={{backgroundColor:'#1e293b',border:'none',borderRadius:'10px'}} labelStyle={{color:'#f8fafc'}}/><Legend/><Line type="monotone" dataKey="avg_wait" stroke="#3b82f6" strokeWidth={2} dot={{r:3}} name="Среднее"/><Line type="monotone" dataKey="median_wait" stroke="#8b5cf6" strokeWidth={2} dot={{r:3}} name="Медиана"/></ComposedChart></ResponsiveContainer></div></Panel>
  </div>
  <div className="grid gap-4 xl:grid-cols-2"><Panel title="Результаты звонков" subtitle="Только фактические disposition из CDR"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={resultData} dataKey="count" nameKey="label" innerRadius={55} outerRadius={90} paddingAngle={2}>{resultData.map((_:any,i:number)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></Panel><Panel title="Тепловая карта" subtitle="День недели и час по calldate"><select className={input+' mb-2'} value={heatMetric} onChange={e=>setHeatMetric(e.target.value)}><option value="attempts">Попытки</option><option value="answerRate">Дозвон, %</option><option value="avg_wait">Среднее ожидание</option><option value="avg_talk">Средний разговор</option></select><div className="overflow-x-auto"><div className="grid min-w-[720px] grid-cols-[40px_repeat(24,1fr)] gap-1 text-[10px]">{heat.map(row=><React.Fragment key={row.day}><b>{row.day}</b>{row.hours.map((v,i)=><div key={i} title={`${row.day} ${i}:00 — ${v.toFixed(1)}`} className="h-7 rounded" style={{backgroundColor:`rgba(37,99,235,${Math.min(.9,.08+v/Math.max(1,...row.hours))})`}}/>)}</React.Fragment>)}</div></div></Panel></div>
  <div className="grid gap-4 xl:grid-cols-2"><Panel title="Исходящие по внутренним номерам"><ResponsiveContainer width="100%" height={280}><BarChart layout="vertical" data={data?.extensions||[]}><XAxis type="number"/><YAxis type="category" dataKey="internal_extension"/><Tooltip/><Bar dataKey="attempts" fill="#2563eb"/><Bar dataKey="answered" fill="#16a34a"/></BarChart></ResponsiveContainer></Panel><Panel title="Статистика по транкам"><div className="overflow-auto"><table className="w-full text-xs"><thead><tr>{['Транк','Попытки','Дозвоны','Дозвон','Ожидание','Разговор','Ошибки'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{data?.trunks?.map((x:any)=><tr key={x.trunk} className="border-t dark:border-slate-800"><td className="p-2">{x.trunk}</td><td>{x.attempts}</td><td>{x.answered}</td><td>{Number(x.answer_rate).toFixed(1)}%</td><td>{duration(x.avg_wait)}</td><td>{duration(x.avg_talk)}</td><td>{x.technical_errors}</td></tr>)}</tbody></table></div></Panel></div>
  <div className="grid gap-4 xl:grid-cols-2"><Panel title="Распределение ожидания"><ResponsiveContainer width="100%" height={220}><BarChart data={data?.waitBuckets||[]}><XAxis dataKey="bucket"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#f59e0b"/></BarChart></ResponsiveContainer></Panel><Panel title="Распределение разговоров"><ResponsiveContainer width="100%" height={220}><BarChart data={data?.durationBuckets||[]}><XAxis dataKey="bucket"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#8b5cf6"/></BarChart></ResponsiveContainer></Panel></div>
  <div className="grid gap-4 xl:grid-cols-2"><Panel title="Попытка первого дозвона (в пределах периода)"><ResponsiveContainer width="100%" height={220}><BarChart data={retryChart}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#2563eb"/></BarChart></ResponsiveContainer></Panel><Panel title="Эффективность повторных попыток"><ResponsiveContainer width="100%" height={220}><BarChart data={retryChart.filter(x=>x.name!=='Нет дозвона')}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="rate" fill="#16a34a"/></BarChart></ResponsiveContainer></Panel></div>
  <div className="rounded-2xl border border-slate-200/70 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900" id="outgoing-call-details-card">
   <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
    <div>
     <h3 className="text-base font-black text-slate-950 dark:text-white">Детализация исходящих звонков</h3>
     <p className="text-xs font-semibold text-slate-500 dark:text-slate-400">Один звонок на связанный набор CDR по linkedid; экспорт учитывает текущий поиск и общие фильтры отчёта</p>
    </div>
    <div className="flex flex-wrap items-center gap-2">
     <button type="button" disabled={!data?.details?.rows?.length} className="inline-flex h-9 items-center gap-2 rounded-lg bg-emerald-600 px-3 text-xs font-black text-white transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-50" onClick={()=>{const rows=data?.details?.rows||[];const escape=(value:any)=>`"${String(value??'').replace(/"/g,'""')}"`;const csv=[['Дата и время','Внутренний номер','Пользователь','Внешний номер','Транк','Результат','Ожидание, сек','Разговор, сек','Попыток по номеру'].map(escape).join(';'),...rows.map((r:any)=>[r.calldate,r.internalExtension,r.user||'',r.externalNumber,r.trunk,r.result,r.waitSeconds??'',r.billsec,r.attemptsForNumber].map(escape).join(';'))].join('\n');const a=document.createElement('a');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.href=url;a.download=`outgoing-calls-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}}><Download className="h-4 w-4"/>Экспорт CSV</button>
    </div>
   </div>
   <div className="overflow-x-auto">
    <table className="w-full min-w-[1050px] text-left text-xs">
     <thead><tr className="border-b border-slate-200 text-[10px] font-black uppercase tracking-wide text-slate-400 dark:border-slate-800">{['Дата и время','Внутренний','Пользователь','Внешний номер','Транк','Результат','Ожидание','Разговор','Попыток'].map(label=><th key={label} className="px-2 py-3">{label}</th>)}</tr></thead>
     <tbody className="divide-y divide-slate-100 dark:divide-slate-800">{data?.details?.rows?.map((r:any)=><tr key={r.callId} className="hover:bg-slate-50 dark:hover:bg-slate-950/30" title={`ID: ${r.technicalId}`}><td className="whitespace-nowrap px-2 py-3 font-mono">{r.calldate}</td><td className="px-2 py-3 font-mono">{r.internalExtension||'—'}</td><td className="px-2 py-3">{r.user||'—'}</td><td className="px-2 py-3 font-bold">{r.externalNumber||'—'}</td><td className="px-2 py-3">{r.trunk||'—'}</td><td className="px-2 py-3">{r.result==='answered'?'Отвечено':r.result==='no_answer'?'Нет ответа':r.result}</td><td className="px-2 py-3 font-mono">{duration(r.waitSeconds)}</td><td className="px-2 py-3 font-mono">{duration(r.billsec)}</td><td className="px-2 py-3 font-mono">{r.attemptsForNumber}</td></tr>)}</tbody>
    </table>
    {!data?.details?.rows?.length&&<div className="py-12 text-center text-xs font-semibold text-slate-400">Исходящие звонки по выбранным фильтрам не найдены</div>}
   </div>
   <div className="mt-4 flex items-center justify-between text-xs font-semibold text-slate-500"><span>Найдено: {Number(data?.details?.total||0).toLocaleString('ru-RU')}</span><div className="flex items-center gap-2"><button type="button" disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="h-8 rounded-lg border border-slate-200 px-3 disabled:opacity-40 dark:border-slate-700">Назад</button><span>{page} / {Math.max(1,Math.ceil(Number(data?.details?.total||0)/25))}</span><button type="button" disabled={page*25>=Number(data?.details?.total||0)} onClick={()=>setPage(p=>p+1)} className="h-8 rounded-lg border border-slate-200 px-3 disabled:opacity-40 dark:border-slate-700">Далее</button></div></div>
  </div>
  <div className="text-xs text-slate-500">CDR этой АТС не содержит точных полей answer/end. Ожидание рассчитано как duration − billsec. Технический ANSWERED может означать автоответчик или голосовую почту.</div>
 </div>
}
