import React, { useEffect, useMemo, useState } from 'react';
import { Clock, Download, PhoneCall, PhoneMissed, PhoneOutgoing, RefreshCw, Target, Users } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, ComposedChart, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { StatsKpiCard } from './StatsKpiCard';

type Props={startDate:string;endDate:string;onStartDateChange?:(v:string)=>void;onEndDateChange?:(v:string)=>void};
const colors=['#2563eb','#16a34a','#f59e0b','#ef4444','#8b5cf6','#64748b'];
const input='h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold dark:border-slate-700 dark:bg-slate-900';
function token(){try{return JSON.parse(localStorage.getItem('asterisk_cdr_session')||'{}').token||''}catch{return ''}}
function duration(v:any){if(v==null)return '—';const n=Math.round(Number(v)||0);return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
function dateValue(d:Date){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-slate-200/70 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 className="mb-3 text-sm font-black text-slate-800 dark:text-slate-100">{title}</h3>{children}</section>}
export function OutgoingDashboard({startDate,endDate,onStartDateChange,onEndDateChange}:Props){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [group,setGroup]=useState('day'),[extensions,setExtensions]=useState<string[]>([]),[trunk,setTrunk]=useState('all'),[result,setResult]=useState('all'),[search,setSearch]=useState(''),[page,setPage]=useState(1),[heatMetric,setHeatMetric]=useState('attempts');
 const params=useMemo(()=>{const p=new URLSearchParams({startDate,endDate,group,trunk,result,search,page:String(page),pageSize:'25'});if(extensions.length)p.set('extensions',extensions.join(','));return p},[startDate,endDate,group,extensions,trunk,result,search,page]);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/reports/outgoing?'+params,{headers:{Authorization:'Bearer '+token()}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Ошибка отчёта');setData(j)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[params.toString()]);
 const preset=(kind:string)=>{const now=new Date(),s=new Date(now),e=new Date(now);if(kind==='yesterday'){s.setDate(s.getDate()-1);e.setDate(e.getDate()-1)}else if(kind==='7d')s.setDate(s.getDate()-6);else if(kind==='30d')s.setDate(s.getDate()-29);else if(kind==='month')s.setDate(1);onStartDateChange?.(dateValue(s));onEndDateChange?.(dateValue(e));setPage(1)};
 const k=data?.kpis||{};const retry=data?.retries||{};const retryChart=['first','second','third','fourth','fifthPlus','never'].map((key,i)=>({name:['1-я','2-я','3-я','4-я','5+','Нет дозвона'][i],count:retry[key]?.numbers||0,rate:retry[key]?.attempts?100*(retry[key]?.answered||0)/retry[key].attempts:0}));
 const heat=Array.from({length:7},(_,day)=>({day:['Пн','Вт','Ср','Чт','Пт','Сб','Вс'][day],hours:Array.from({length:24},(_,hour)=>{const x=data?.heatmap?.find((r:any)=>Number(r.weekday)===day&&Number(r.hour)===hour)||{};return heatMetric==='answerRate'?(Number(x.attempts)?100*Number(x.answered)/Number(x.attempts):0):Number(x[heatMetric]||0)})}));
 return <div className="space-y-4">
  <div className="flex flex-wrap gap-2 rounded-2xl border border-slate-200/70 bg-white p-3 dark:border-slate-800 dark:bg-slate-900">
   {['today','yesterday','7d','30d','month'].map((x,i)=><button key={x} onClick={()=>preset(x)} className={input}>{['Сегодня','Вчера','7 дней','30 дней','Месяц'][i]}</button>)}
   <select className={input} value={group} onChange={e=>setGroup(e.target.value)}><option value="hour">Час</option><option value="day">День</option><option value="week">Неделя</option><option value="month">Месяц</option></select>
   <select multiple className={input+' min-w-40'} value={extensions} onChange={e=>{setExtensions([...e.target.selectedOptions].map(o=>o.value));setPage(1)}}>{data?.options?.extensions?.map((x:any)=><option value={x.extension} key={x.extension}>{x.name} — {x.extension}</option>)}</select>
   <select className={input} value={trunk} onChange={e=>setTrunk(e.target.value)}><option value="all">Все транки</option>{data?.options?.trunks?.map((x:string)=><option key={x}>{x}</option>)}</select>
   <select className={input} value={result} onChange={e=>setResult(e.target.value)}><option value="all">Все результаты</option><option value="answered">Отвечено</option><option value="no_answer">Нет ответа</option><option value="busy">Занято</option><option value="failed">Ошибка</option><option value="congestion">Перегрузка</option><option value="other">Другие</option></select>
   <input className={input} value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Поиск номера"/>
   <button className="ml-auto inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 text-xs font-black text-white" onClick={load}><RefreshCw className={'h-4 w-4 '+(loading?'animate-spin':'')}/>Обновить</button>
  </div>
  {error&&<div className="rounded-xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
  <div className="grid grid-cols-2 gap-3 xl:grid-cols-5">
   <StatsKpiCard label="Всего попыток" value={Number(k.totalAttempts||0).toLocaleString('ru')} hint="Уникальные linkedid" icon={PhoneOutgoing} tone="blue"/><StatsKpiCard label="Уникальные номера" value={Number(k.uniqueNumbers||0).toLocaleString('ru')} hint="Внешние назначения" icon={Users} tone="purple"/><StatsKpiCard label="Успешные дозвоны" value={Number(k.answered||0).toLocaleString('ru')} hint="ANSWERED и billsec > 0" icon={PhoneCall} tone="green"/><StatsKpiCard label="Недозвоны" value={Number(k.unanswered||0).toLocaleString('ru')} hint="Без разговора" icon={PhoneMissed} tone="red"/><StatsKpiCard label="Процент дозвона" value={Number(k.answerRate||0).toFixed(1)+'%'} hint="Успешные / попытки" icon={Target} tone="green"/>
   <StatsKpiCard label="Среднее ожидание" value={duration(k.averageWaitSeconds)} hint="Fallback duration − billsec" icon={Clock} tone="orange"/><StatsKpiCard label="Медиана ожидания" value={duration(k.medianWaitSeconds)} hint="Только отвеченные" icon={Clock} tone="orange"/><StatsKpiCard label="Средний разговор" value={duration(k.averageTalkSeconds)} hint="По billsec" icon={PhoneCall} tone="blue"/><StatsKpiCard label="Разговорное время" value={duration(k.totalTalkSeconds)} hint="Сумма billsec" icon={PhoneCall} tone="purple"/><StatsKpiCard label="С первой попытки" value={Number(k.firstAttemptRate||0).toFixed(1)+'%'} hint="В пределах периода" icon={Target} tone="green"/>
  </div>
  <Panel title="Динамика исходящих"><ResponsiveContainer width="100%" height={280}><ComposedChart data={data?.timeline||[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="bucket"/><YAxis/><Tooltip/><Legend/><Bar dataKey="attempts" name="Попытки" fill="#2563eb"/><Line dataKey="answered" name="Отвеченные" stroke="#16a34a"/><Line dataKey="unanswered" name="Неотвеченные" stroke="#ef4444"/></ComposedChart></ResponsiveContainer></Panel>
  <div className="grid gap-4 xl:grid-cols-2"><Panel title="Процент дозвона"><ResponsiveContainer width="100%" height={240}><ComposedChart data={data?.timeline||[]}><XAxis dataKey="bucket"/><YAxis/><Tooltip/><Line dataKey="answer_rate" stroke="#16a34a" name="Дозвон, %"/></ComposedChart></ResponsiveContainer></Panel><Panel title="Ожидание ответа"><ResponsiveContainer width="100%" height={240}><ComposedChart data={data?.timeline||[]}><XAxis dataKey="bucket"/><YAxis/><Tooltip/><Line dataKey="avg_wait" stroke="#2563eb" name="Среднее"/><Line dataKey="median_wait" stroke="#8b5cf6" name="Медиана"/></ComposedChart></ResponsiveContainer></Panel></div>
  <div className="grid gap-4 xl:grid-cols-2"><Panel title="Результаты звонков"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={data?.results||[]} dataKey="count" nameKey="result" outerRadius={90} label>{(data?.results||[]).map((_:any,i:number)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></Panel><Panel title="Тепловая карта"><select className={input+' mb-2'} value={heatMetric} onChange={e=>setHeatMetric(e.target.value)}><option value="attempts">Попытки</option><option value="answerRate">Дозвон, %</option><option value="avg_wait">Среднее ожидание</option><option value="avg_talk">Средний разговор</option></select><div className="overflow-x-auto"><div className="grid min-w-[720px] grid-cols-[40px_repeat(24,1fr)] gap-1 text-[10px]">{heat.map(row=><React.Fragment key={row.day}><b>{row.day}</b>{row.hours.map((v,i)=><div key={i} title={`${row.day} ${i}:00 — ${v.toFixed(1)}`} className="h-7 rounded" style={{backgroundColor:`rgba(37,99,235,${Math.min(.9,.08+v/Math.max(1,...row.hours))})`}}/>)}</React.Fragment>)}</div></div></Panel></div>
  <div className="grid gap-4 xl:grid-cols-2"><Panel title="Исходящие по внутренним номерам"><ResponsiveContainer width="100%" height={280}><BarChart layout="vertical" data={data?.extensions||[]}><XAxis type="number"/><YAxis type="category" dataKey="internal_extension"/><Tooltip/><Bar dataKey="attempts" fill="#2563eb"/><Bar dataKey="answered" fill="#16a34a"/></BarChart></ResponsiveContainer></Panel><Panel title="Статистика по транкам"><div className="overflow-auto"><table className="w-full text-xs"><thead><tr>{['Транк','Попытки','Дозвоны','Дозвон','Ожидание','Разговор','Ошибки'].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{data?.trunks?.map((x:any)=><tr key={x.trunk} className="border-t dark:border-slate-800"><td className="p-2">{x.trunk}</td><td>{x.attempts}</td><td>{x.answered}</td><td>{Number(x.answer_rate).toFixed(1)}%</td><td>{duration(x.avg_wait)}</td><td>{duration(x.avg_talk)}</td><td>{x.technical_errors}</td></tr>)}</tbody></table></div></Panel></div>
  <div className="grid gap-4 xl:grid-cols-2"><Panel title="Распределение ожидания"><ResponsiveContainer width="100%" height={220}><BarChart data={data?.waitBuckets||[]}><XAxis dataKey="bucket"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#f59e0b"/></BarChart></ResponsiveContainer></Panel><Panel title="Распределение разговоров"><ResponsiveContainer width="100%" height={220}><BarChart data={data?.durationBuckets||[]}><XAxis dataKey="bucket"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#8b5cf6"/></BarChart></ResponsiveContainer></Panel></div>
  <div className="grid gap-4 xl:grid-cols-2"><Panel title="Попытка первого дозвона (в пределах периода)"><ResponsiveContainer width="100%" height={220}><BarChart data={retryChart}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#2563eb"/></BarChart></ResponsiveContainer></Panel><Panel title="Эффективность повторных попыток"><ResponsiveContainer width="100%" height={220}><BarChart data={retryChart.filter(x=>x.name!=='Нет дозвона')}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="rate" fill="#16a34a"/></BarChart></ResponsiveContainer></Panel></div>
  <Panel title="Детализация исходящих звонков"><div className="mb-3 flex justify-end"><button className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white" onClick={()=>{const rows=data?.details?.rows||[];const csv=['Дата;Внутренний;Пользователь;Внешний;Транк;Результат;Ожидание;Разговор',...rows.map((r:any)=>[r.calldate,r.internalExtension,r.user||'',r.externalNumber,r.trunk,r.result,r.waitSeconds??'',r.billsec].join(';'))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='outgoing.csv';a.click();URL.revokeObjectURL(a.href)}}><Download className="h-4 w-4"/>CSV</button></div><div className="overflow-auto"><table className="w-full min-w-[980px] text-xs"><thead><tr>{['Дата','Внутренний','Пользователь','Внешний','Транк','Результат','Ожидание','Разговор','Попыток'].map(x=><th key={x} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{data?.details?.rows?.map((r:any)=><tr key={r.callId} className="border-t dark:border-slate-800" title={`ID: ${r.technicalId}`}><td className="p-2">{r.calldate}</td><td>{r.internalExtension}</td><td>{r.user||'—'}</td><td>{r.externalNumber}</td><td>{r.trunk}</td><td>{r.result}</td><td>{duration(r.waitSeconds)}</td><td>{duration(r.billsec)}</td><td>{r.attemptsForNumber}</td></tr>)}</tbody></table></div><div className="mt-3 flex items-center justify-between text-xs"><span>Всего: {data?.details?.total||0}</span><div className="flex gap-2"><button className={input} disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Назад</button><span className="p-2">{page}</span><button className={input} disabled={page*25>=Number(data?.details?.total||0)} onClick={()=>setPage(p=>p+1)}>Далее</button></div></div></Panel>
  <div className="text-xs text-slate-500">CDR этой АТС не содержит точных полей answer/end. Ожидание рассчитано как duration − billsec. Технический ANSWERED может означать автоответчик или голосовую почту.</div>
 </div>
}
