import https from 'node:https';
import { queryPBXPulsDb, withPBXPulsTransaction } from '../pbxpulsDb.js';
import { NotificationEventService } from '../notifications/eventService.js';
import { normalizeWebhookPayload } from './validation.js';
import { SiteFormPullCrypto } from './pullCrypto.js';

const sqlDate=(value:any)=>/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(String(value||''))?String(value):new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date(value||Date.now()));
const json=(value:any,fallback:any)=>{try{return JSON.parse(String(value||''))}catch{return fallback}};
const httpsJson=(target:URL,token:string)=>new Promise<any>((resolve,reject)=>{
  const request=https.get(target,{headers:{'X-PBXPuls-Token':token,Accept:'application/json'},timeout:15000},response=>{
    const chunks:Buffer[]=[];let size=0;
    response.on('data',(chunk:Buffer)=>{size+=chunk.length;if(size>2*1024*1024)request.destroy(new Error('pull_response_too_large'));else chunks.push(chunk)});
    response.on('end',()=>{try{const data=json(Buffer.concat(chunks).toString('utf8'),{}),status=Number(response.statusCode||0);if(status<200||status>=300)return reject(new Error(String(data?.code||`pull_http_${status}`)));resolve(data)}catch(error){reject(error)}});
  });
  request.on('timeout',()=>request.destroy(new Error('pull_timeout')));request.on('error',reject);
});

export class SiteFormPullService{
  private crypto:SiteFormPullCrypto;
  private running=new Set<string>();
  constructor(secret:string,private importClicks:(siteId:string,items:any[])=>Promise<number>){this.crypto=new SiteFormPullCrypto(secret)}
  encryptToken(token:string){return this.crypto.encrypt(token)}
  async request(source:any,action:string,params:Record<string,string>={}){const target=new URL(String(source.endpoint_url));target.searchParams.set('action',action);for(const[k,v]of Object.entries(params))target.searchParams.set(k,v);if(target.protocol!=='https:')throw new Error('pull_https_required');const token=this.crypto.decrypt(source.token_encrypted);if(!token)throw new Error('pull_token_unavailable');return httpsJson(target,token)}
  async forms(integrationId:string){const source=(await queryPBXPulsDb('SELECT * FROM site_form_pull_sources WHERE integration_id=?',[integrationId]))[0];if(!source)throw new Error('pull_source_not_found');return this.request(source,'forms')}
  async syncOne(integrationId:string){if(this.running.has(integrationId))return{leads:0,clicks:0,skipped:0,alreadyRunning:true};this.running.add(integrationId);try{const source=(await queryPBXPulsDb(`SELECT s.*,i.* FROM site_form_pull_sources s JOIN site_form_integrations i ON i.id=s.integration_id WHERE s.integration_id=? AND i.is_enabled=1`,[integrationId]))[0];if(!source)return{leads:0,clicks:0,skipped:0};await queryPBXPulsDb('UPDATE site_form_pull_sources SET last_attempt_at=NOW(),next_sync_at=DATE_ADD(NOW(),INTERVAL sync_interval_seconds SECOND) WHERE integration_id=?',[integrationId]);try{const forms=json(source.selected_form_ids_json,[]).map(String);let leads=0,clicks=0,skipped=0;if(forms.length){const data=await this.request(source,'leads',{after:String(source.leads_cursor||0),limit:'100',formIds:forms.join(',')});for(const item of Array.isArray(data.items)?data.items:[]){try{if(await this.ingestLead(source,item))leads++}catch(error:any){if(error?.code==='phone_required'){skipped++;continue}throw error}}await queryPBXpulsCursor(integrationId,'leads_cursor',Number(data.nextCursor)||Number(source.leads_cursor)||0)}if(source.calltracking_site_id){const data=await this.request(source,'clicks',{after:String(source.clicks_cursor||0),limit:'100'});clicks=await this.importClicks(String(source.calltracking_site_id),Array.isArray(data.items)?data.items:[]);await queryPBXpulsCursor(integrationId,'clicks_cursor',Number(data.nextCursor)||Number(source.clicks_cursor)||0)}await queryPBXPulsDb('UPDATE site_form_pull_sources SET last_success_at=NOW(),last_error=?,updated_at=NOW() WHERE integration_id=?',[skipped?`Пропущено записей с некорректным телефоном: ${skipped}`:null,integrationId]);return{leads,clicks,skipped}}catch(error:any){await queryPBXPulsDb('UPDATE site_form_pull_sources SET last_error=?,updated_at=NOW() WHERE integration_id=?',[String(error?.message||error).slice(0,500),integrationId]);throw error}}finally{this.running.delete(integrationId)}}
  async syncDue(){const rows=await queryPBXPulsDb("SELECT integration_id FROM site_form_pull_sources WHERE next_sync_at IS NULL OR next_sync_at<=NOW() LIMIT 20");for(const row of rows)await this.syncOne(String(row.integration_id)).catch(()=>undefined)}
  private async ingestLead(integration:any,input:any){const payload=normalizeWebhookPayload(input,'universal');const existing=(await queryPBXPulsDb('SELECT id FROM site_form_leads WHERE integration_id=? AND event_id=? LIMIT 1',[integration.integration_id,payload.eventId]))[0];if(existing)return false;let duplicateOf:number|null=null;if(Boolean(integration.duplicate_detection_enabled)){const row=(await queryPBXPulsDb('SELECT id FROM site_form_leads WHERE integration_id=? AND external_form_id=? AND phone_normalized=? AND created_at>=DATE_SUB(?,INTERVAL ? MINUTE) ORDER BY created_at DESC LIMIT 1',[integration.integration_id,payload.externalFormId,payload.phoneNormalized,payload.createdAt,Number(integration.duplicate_window_minutes)]))[0];duplicateOf=row?Number(row.id):null}const status=duplicateOf?'duplicate':'new',sla=duplicateOf?'not_applicable':'pending';let id=0;await withPBXPulsTransaction(async c=>{const[result]:any=await c.execute(`INSERT INTO site_form_leads(integration_id,event_id,external_result_id,external_form_id,form_code,form_name,site_id,site_url,page_url,page_title,referer,customer_name,phone_raw,phone_normalized,phone_extension,email,company,comment,preferred_time,utm_source,utm_medium,utm_campaign,utm_content,utm_term,visitor_client_id,visitor_session_id,visitor_ip,visitor_user_agent,status,assigned_user_id,assigned_department_id,is_duplicate,duplicate_of_lead_id,sla_deadline_at,sla_status,created_at,raw_payload_json)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,DATE_ADD(?,INTERVAL ? MINUTE),?,?,?)`,[integration.integration_id,payload.eventId,payload.externalResultId,payload.externalFormId,payload.formCode,payload.formName,payload.siteId,payload.siteUrl,payload.pageUrl,payload.pageTitle,payload.referer,payload.customerName,payload.phoneRaw,payload.phoneNormalized,payload.phoneExtension,payload.email,payload.company,payload.comment,payload.preferredTime,payload.utmSource,payload.utmMedium,payload.utmCampaign,payload.utmContent,payload.utmTerm,payload.visitorClientId,payload.visitorSessionId,payload.visitorIp,payload.visitorUserAgent,status,integration.default_user_id,integration.default_department_id,duplicateOf?1:0,duplicateOf,payload.createdAt,Number(integration.sla_minutes),sla,sqlDate(payload.createdAt),payload.rawPayload]);id=Number(result.insertId);await c.execute("INSERT INTO site_form_lead_history(lead_id,event_type,new_value,metadata_json)VALUES(?,'lead_received',?,?)",[id,status,JSON.stringify({source:'bitrix_pull',eventId:payload.eventId,duplicateOf})])});void new NotificationEventService().emit({eventType:'site_forms.lead_received',category:'marketing',severity:'info',title:'Новая заявка с сайта',message:`Получена заявка #${id}`,source:'site_forms',entityType:'site_form_lead',entityId:String(id),dedupeKey:`site-form-lead:${id}`,status:'active',occurredAt:new Date(),metadata:{integrationId:integration.integration_id,formId:payload.externalFormId}}).catch(()=>undefined);return true}
}

const queryPBXpulsCursor=(integrationId:string,column:'leads_cursor'|'clicks_cursor',cursor:number)=>queryPBXPulsDb(`UPDATE site_form_pull_sources SET ${column}=? WHERE integration_id=?`,[cursor,integrationId]);
