import https from 'node:https';
import net from 'node:net';
import { assertDnsSafe } from '../ai-platform/integrations/integrationSecurity.js';
import { SiteFormError } from './types.js';

type PairingResponse={success:boolean;platform?:string;connector?:string;pairingVersion?:number;token?:string;sites?:any[];forms?:any[];tracking?:any;code?:string;error?:string};

function pairingUrl(siteUrl:unknown){let base:URL;try{base=new URL(String(siteUrl||''))}catch{throw new SiteFormError(400,'invalid_site_url','Укажите корректный URL сайта')}if(base.protocol!=='https:')throw new SiteFormError(400,'https_required','Для подключения сайта требуется HTTPS');base.pathname='/local/api/pbxpuls/pair.php';base.search='';base.hash='';return base}

async function request(target:URL,method:'GET'|'POST',payload?:any):Promise<PairingResponse>{const addresses=await assertDnsSafe(target),address=addresses[0],body=payload?JSON.stringify(payload):'';return new Promise((resolve,reject)=>{const req=https.request(target,{method,timeout:15000,servername:target.hostname,lookup:(_hostname,_options,callback)=>callback(null,address,net.isIP(address)),headers:{Accept:'application/json',...(body?{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body)}:{})}},res=>{const chunks:Buffer[]=[];let size=0;res.on('data',(chunk:Buffer)=>{size+=chunk.length;if(size>512*1024)req.destroy(new Error('pairing_response_too_large'));else chunks.push(chunk)});res.on('end',()=>{let data:PairingResponse={success:false};try{data=JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{}const status=Number(res.statusCode||0);if(status<200||status>=300)return reject(new SiteFormError(status===401?401:502,String(data.code||'pairing_failed'),String(data.error||`HTTP ${status}`)));resolve(data)})});req.on('timeout',()=>req.destroy(new Error('pairing_timeout')));req.on('error',error=>reject(error instanceof SiteFormError?error:new SiteFormError(502,'pairing_unreachable','Коннектор PBXPuls недоступен')));if(body)req.write(body);req.end()})}

export async function previewBitrixPairing(siteUrl:unknown){const endpoint=pairingUrl(siteUrl),data=await request(endpoint,'GET');if(data.platform!=='bitrix'||data.connector!=='pbxpuls'||data.pairingVersion!==1)throw new SiteFormError(409,'connector_incompatible','На сайте не найден совместимый коннектор PBXPuls');return{siteUrl:new URL('/',endpoint).toString().replace(/\/$/,''),endpointUrl:new URL('/local/api/pbxpuls/leads.php',endpoint).toString(),pairingUrl:endpoint.toString(),platform:'bitrix',connectorVersion:1}}
export async function applyBitrixPairing(siteUrl:unknown,code:unknown){const preview=await previewBitrixPairing(siteUrl),value=String(code||'').trim();if(!/^\d{8}$/.test(value))throw new SiteFormError(400,'invalid_pairing_code','Введите восьмизначный код');const data=await request(new URL(preview.pairingUrl),'POST',{code:value});if(!data.token)throw new SiteFormError(502,'pairing_token_missing','Сайт не вернул токен интеграции');return{...preview,token:data.token,sites:Array.isArray(data.sites)?data.sites:[],forms:Array.isArray(data.forms)?data.forms:[],tracking:data.tracking&&typeof data.tracking==='object'?data.tracking:{}}}
