import React,{useState}from'react';

export default function AgentSandboxPanel({token,agentId}:{token:string;agentId:number}){
  const[versionId,setVersionId]=useState(''),[session,setSession]=useState<any>(null),[text,setText]=useState(''),[messages,setMessages]=useState<any[]>([]),[error,setError]=useState('');
  const call=async(path:string,body:unknown={})=>{const response=await fetch(path,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),value=await response.json();if(!response.ok)throw new Error(value.error||'Ошибка sandbox');return value.data};
  const start=async()=>{try{setSession(await call(`/api/ai-platform/agents/${agentId}/sandbox/start`,{versionId:Number(versionId),allowDraft:true}));setMessages([]);setError('')}catch(reason:any){setError(reason.message)}};
  const send=async()=>{if(!session||!text.trim())return;const user=text;setText('');setMessages(value=>[...value,{role:'user',message:user}]);try{const result=await call(`/api/ai-platform/sandbox/${session.sessionId}/message`,{message:user});setMessages(value=>[...value,{role:'assistant',...result}])}catch(reason:any){setError(reason.message)}};
  const finish=async(action:string)=>{if(session)await call(`/api/ai-platform/sandbox/${session.sessionId}/${action}`);setSession(null)};
  return <div className="mt-5 rounded-2xl border bg-white p-5"><h3 className="font-black">Тестирование</h3><p className="text-sm text-slate-500">Текстовый sandbox с безопасными read-only инструментами, без телефонии</p>{!session?<div className="mt-4 flex gap-2"><input value={versionId} onChange={event=>setVersionId(event.target.value)} placeholder="ID версии (draft/published)" className="rounded-xl border p-2"/><button onClick={start} className="rounded-xl bg-blue-600 px-4 text-white">Начать тест</button></div>:<><div className="my-4 max-h-96 space-y-2 overflow-auto">{messages.map((item,index)=><div key={index} className={`rounded-xl p-3 text-sm ${item.role==='user'?'ml-10 bg-blue-50':'mr-10 bg-slate-100'}`}><div>{item.message}</div>{item.role==='assistant'&&<div className="mt-2 text-xs text-slate-500"><div>Источник: {item.finalResponseSource||'—'} · tool steps: {item.toolLoopCount||0} · {item.provider||'deterministic'} {item.latencyMs??''}ms</div>{item.intent&&<div>intent: {item.intent} · transfer_required: {String(item.transferRequired)}</div>}{item.toolResultsSummary?.map((tool:any)=><div key={`${tool.toolKey}-${tool.executionId}`} className="mt-1 rounded border bg-white/70 p-2"><b>{tool.toolKey}</b> · {tool.status} · {tool.durationMs??0}ms<div>{tool.safeSummary}{tool.errorCode?` · ${tool.errorCode}`:''}</div><details className="mt-1"><summary className="cursor-pointer">Технические сведения</summary><div>execution ID: {tool.executionId||'—'} · context truncated: {String(item.contextTruncated)}</div><pre className="mt-1 max-h-32 overflow-auto whitespace-pre-wrap">{JSON.stringify({arguments:tool.safeArguments,result:tool.safeResult},null,2)}</pre></details></div>)}</div>}</div>)}</div><div className="flex gap-2"><input value={text} onChange={event=>setText(event.target.value)} onKeyDown={event=>event.key==='Enter'&&void send()} className="flex-1 rounded-xl border p-2"/><button onClick={send} className="rounded-xl bg-blue-600 px-4 text-white">Отправить</button><button onClick={()=>void finish('complete')} className="rounded-xl border px-3">Завершить</button><button onClick={()=>void finish('cancel')} className="rounded-xl border px-3">Очистить</button></div></>}{error&&<div className="mt-3 text-sm text-red-600">{error}</div>}</div>;
}
