import React,{useEffect,useMemo,useState}from'react';import{AlertTriangle,Archive,Power,X}from'lucide-react';
export default function AiAgentDeletionWizard({token,agent,onClose,onChanged}:{token:string;agent:any;onClose:()=>void;onChanged:()=>void}){
 const headers=useMemo(()=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'}),[token]),[mode,setMode]=useState<'disable'|'archive'|'delete'>('archive'),[report,setReport]=useState<any>(null),[preview,setPreview]=useState<any>(null),[confirmName,setConfirmName]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const call=async(path:string,method='GET',body?:any)=>{const r=await fetch(path,{method,headers,body:body?JSON.stringify(body):undefined}),v=await r.json();if(!r.ok)throw new Error(v.error||'Операция не выполнена');return v.data};
 useEffect(()=>{void call(`/api/ai-platform/agents/${agent.id}/dependencies`).then(setReport).catch(e=>setMessage(e.message))},[agent.id]);
 const makePreview=async()=>{setBusy(true);try{setPreview(await call(`/api/ai-platform/agents/${agent.id}/${mode}-preview`,'POST',{idempotencyKey:crypto.randomUUID()}));setMessage('Preview готов. Изменения ещё не применены.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const apply=async()=>{if(!preview||!confirm(`Применить действие «${label(mode)}»?`))return;setBusy(true);try{await call(`/api/ai-platform/agents/${mode}-apply`,'POST',{previewId:preview.previewId,confirm:true,confirmName});setMessage(`${label(mode)}: выполнено`);onChanged()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-4"><section className="mx-auto max-w-3xl rounded-2xl bg-white p-5 shadow-2xl"><header className="flex items-start justify-between"><div><h2 className="text-xl font-black">Управление AI-сотрудником</h2><p className="text-sm text-slate-500">{agent.name}</p></div><button onClick={onClose}><X className="h-5 w-5"/></button></header>
  <div className="mt-5 grid gap-3 sm:grid-cols-3">{([['disable',Power,'Отключить','Новые звонки не принимаются; объекты и история сохраняются.'],['archive',Archive,'Архивировать','Скрыть из основного списка с возможностью восстановления.'],['delete',AlertTriangle,'Удалить','Удалить конфигурацию только после проверки зависимостей.']]as const).map(([key,Icon,title,description])=><button key={key} onClick={()=>{setMode(key);setPreview(null)}} className={`rounded-xl border p-4 text-left ${mode===key?'border-blue-500 bg-blue-50':''}`}><Icon className={`h-5 w-5 ${key==='delete'?'text-red-600':'text-blue-600'}`}/><b className="mt-2 block">{title}</b><span className="text-xs text-slate-500">{description}</span></button>)}</div>
  <div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><h3 className="font-black">Зависимости</h3>{report?<div className="mt-2 grid gap-2 sm:grid-cols-2"><div>Номер: <b>{report.extension?.extension||'нет'}</b></div><div>Версии: <b>{Object.values(report.versions||{}).reduce((a:any,b:any)=>a+Number(b),0)}</b></div><div>Разговоры: <b>{report.counts?.conversations||0}</b></div><div>Записи: <b>{report.counts?.recordings||0}</b></div><div>Активные звонки: <b>{report.active?.calls||0}</b></div><div>Блокирующие зависимости: <b>{report.blockers?.length||0}</b></div></div>:<div>Проверяем…</div>}{report?.blockers?.length>0&&<ul className="mt-3 list-disc pl-5 text-red-700">{report.blockers.map((x:any,index:number)=><li key={index}>{x.name}</li>)}</ul>}</div>
  <div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border p-3"><b>Будет изменено</b><p className="mt-1 text-sm text-slate-500">{mode==='disable'?'Подключение и приём новых звонков':mode==='archive'?'Статус, подключение и видимость':'Черновики, назначения и управляемые FreePBX-объекты'}</p></div><div className="rounded-xl border p-3"><b>Будет сохранено</b><p className="mt-1 text-sm text-slate-500">CDR/CEL, разговоры, записи, audit и published snapshots.</p></div></div>
  <label className="mt-4 block text-sm font-bold">Введите имя для подтверждения<input value={confirmName} onChange={e=>setConfirmName(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 font-normal" placeholder={agent.name}/></label>
  <div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={makePreview} className="rounded-lg border px-4 py-2 font-bold">Создать preview</button>{preview&&<button disabled={busy||!preview.ready||confirmName!==agent.name} onClick={apply} className={`rounded-lg px-4 py-2 font-bold text-white disabled:opacity-40 ${mode==='delete'?'bg-red-700':'bg-blue-600'}`}>{label(mode)}</button>}</div>
  {preview&&<div className={`mt-3 rounded-lg p-3 text-sm ${preview.ready?'bg-emerald-50':'bg-red-50'}`}>Preview #{preview.previewId} · {preview.ready?'готов':'заблокирован'} · productionAffected={String(preview.productionAffected)}</div>}{message&&<p className="mt-3 text-sm">{message}</p>}
 </section></div>
}
const label=(mode:string)=>mode==='disable'?'Отключить':mode==='archive'?'Архивировать':'Удалить окончательно';
