import React,{useEffect,useMemo,useState}from'react';
import{ArrowLeft,ChevronLeft,ChevronRight,Plus,ShieldCheck,X}from'lucide-react';

const steps=['Имя и роль','Телефония','Голос','Навыки и знания','Передача сотруднику','Проверка','Создание'];
const empty={templateKey:'information_assistant',name:'',role:'Информационный помощник',description:'Помогает клиентам и отвечает на информационные вопросы.',language:'ru-RU',communicationStyle:'Спокойный и доброжелательный',greeting:'Здравствуйте. Чем могу помочь?',extension:'',freepbxDisplayName:'',fallbackType:'terminate_call',fallbackValue:'',provider:'openai_realtime',model:'gpt-realtime-2.1',voiceId:'marin',voice:{speakingRate:'normal',pauseStyle:'short_natural',testPhrase:'Здравствуйте. Чем могу помочь?'},skills:{toolIds:[]},knowledge:{sourceIds:[]},handoff:{enabled:false,destinationType:'extension',destinationId:'',timeout:20,onNoAnswer:'return_to_ai',announcement:'Хорошо, соединяю',directRequestRequiresConfirmation:false,aiOfferRequiresConfirmation:true}};

export default function AiAgentCreationWizard({token,onClose,onCreated}:{token:string;onClose:()=>void;onCreated:()=>void}){
 const headers=useMemo(()=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'}),[token]),[step,setStep]=useState(1),[draft,setDraft]=useState<any>(empty),[draftId,setDraftId]=useState<number|null>(null),[preview,setPreview]=useState<any>(null),[numberStatus,setNumberStatus]=useState('Требует проверки'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[templates,setTemplates]=useState<any[]>([]);
 const api=async(path:string,method='GET',body?:any)=>{const response=await fetch(path,{method,headers,body:body?JSON.stringify(body):undefined}),value=await response.json();if(!response.ok)throw new Error(value.error||'Операция не выполнена');return value.data??value.rows};
 useEffect(()=>{void api('/api/ai-platform/agent-creation/templates').then(setTemplates).catch(e=>setMessage(e.message))},[]);
 const createOrSave=async()=>{setBusy(true);try{if(!draftId){const value=await api('/api/ai-platform/agent-creation/drafts','POST',{...draft,idempotencyKey:crypto.randomUUID()});setDraftId(value.id);setMessage('Черновик сохранён');return value.id}await api(`/api/ai-platform/agent-creation/drafts/${draftId}`,'PUT',{...draft,step});setMessage('Черновик сохранён');return draftId}finally{setBusy(false)}};
 const next=async()=>{try{await createOrSave();setStep(x=>Math.min(7,x+1))}catch(e:any){setMessage(e.message)}};
 const suggest=async()=>{try{const value=await api('/api/ai-platform/agent-creation/suggest-extension');setDraft((x:any)=>({...x,extension:value.extension}));setNumberStatus('Свободен')}catch(e:any){setMessage(e.message)}};
 const validateNumber=async()=>{try{const value=await api('/api/ai-platform/agent-creation/validate-extension','POST',{extension:draft.extension,draftId});setNumberStatus(value.status==='free'?'Свободен':'Конфликт');if(value.conflicts?.length)setMessage(`Номер занят: ${value.conflicts.map((x:any)=>x.name).join(', ')}`)}catch(e:any){setNumberStatus('Конфликт');setMessage(e.message)}};
 const makePreview=async()=>{setBusy(true);try{const id=await createOrSave(),value=await api('/api/ai-platform/agent-creation/preview','POST',{draftId:id,idempotencyKey:crypto.randomUUID()});setPreview(value);setStep(7);setMessage('Проверка завершена. Live-изменения не выполнялись.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const apply=async()=>{if(!preview||!confirm('Создать AI-сотрудника и виртуальный номер? Будут выполнены live-операции FreePBX.'))return;setBusy(true);try{await api('/api/ai-platform/agent-creation/apply','POST',{previewId:preview.previewId,confirm:true});setMessage('AI-сотрудник создан');onCreated()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const set=(field:string,value:any)=>setDraft((x:any)=>({...x,[field]:value}));
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-3 md:p-6"><section className="mx-auto max-w-[1120px] rounded-2xl bg-slate-50 shadow-2xl">
  <header className="sticky top-0 z-10 flex items-center justify-between rounded-t-2xl border-b bg-white p-4"><div className="flex items-center gap-3"><button onClick={onClose} className="rounded-lg border p-2"><ArrowLeft className="h-4 w-4"/></button><div><h1 className="text-xl font-black">Добавить AI-сотрудника</h1><p className="text-sm text-slate-500">Безопасный мастер с обязательным preview</p></div></div><button onClick={onClose}><X className="h-5 w-5"/></button></header>
  <div className="p-4 md:p-6"><ol className="mb-5 grid grid-cols-2 gap-2 md:grid-cols-7">{steps.map((name,index)=><li key={name}><button onClick={()=>setStep(index+1)} className={`w-full rounded-xl px-2 py-2 text-xs font-bold ${step===index+1?'bg-blue-600 text-white':'border bg-white'}`}>{index+1}. {name}</button></li>)}</ol>
   <div className="min-h-[390px] rounded-2xl border bg-white p-5">
    {step===1&&<Step title="Имя и роль" text="Как новый AI-сотрудник представляется клиентам."><div className="grid gap-4 md:grid-cols-2"><Field label="Способ создания"><select value={draft.templateKey} onChange={e=>set('templateKey',e.target.value)} className="input">{templates.map(x=><option key={x.key} value={x.key}>{x.name}</option>)}</select></Field><Field label="Имя *"><input value={draft.name} onChange={e=>set('name',e.target.value)} maxLength={191} className="input"/></Field><Field label="Роль *"><input value={draft.role} onChange={e=>set('role',e.target.value)} className="input"/></Field><Field label="Язык"><select value={draft.language} onChange={e=>set('language',e.target.value)} className="input"><option value="ru-RU">Русский (ru-RU)</option></select></Field><Field label="Краткое описание *" wide><textarea rows={3} value={draft.description} onChange={e=>set('description',e.target.value)} className="input"/></Field><Field label="Стиль общения" wide><input value={draft.communicationStyle} onChange={e=>set('communicationStyle',e.target.value)} className="input"/></Field><Field label="Приветствие *" wide><input maxLength={500} value={draft.greeting} onChange={e=>set('greeting',e.target.value)} className="input"/></Field></div></Step>}
    {step===2&&<Step title="Телефония" text="Выберите свободный виртуальный внутренний номер."><div className="rounded-xl bg-blue-50 p-3 text-sm">Будет создан виртуальный внутренний номер. SIP-регистрация не требуется.</div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Внутренний номер"><div className="flex gap-2"><input value={draft.extension} onChange={e=>{set('extension',e.target.value.replace(/\D/g,''));setNumberStatus('Требует проверки')}} className="input"/><button onClick={suggest} className="rounded-lg border px-3 text-sm font-bold">Предложить</button></div><button onClick={validateNumber} className="mt-2 text-sm font-bold text-blue-700">Проверить конфликты</button><div className="mt-1 text-xs text-slate-500">Статус: {numberStatus}</div></Field><Field label="Имя объекта FreePBX"><input value={draft.freepbxDisplayName||draft.name} onChange={e=>set('freepbxDisplayName',e.target.value)} className="input"/></Field><Field label="При недоступности AI"><select value={draft.fallbackType} onChange={e=>set('fallbackType',e.target.value)} className="input"><option value="terminate_call">Завершить звонок с сообщением</option><option value="extension">Внутренний номер</option><option value="queue">Очередь</option><option value="ring_group">Группа вызова</option></select></Field>{draft.fallbackType!=='terminate_call'&&<Field label="Fallback-направление"><input value={draft.fallbackValue} onChange={e=>set('fallbackValue',e.target.value)} className="input"/></Field>}</div></Step>}
    {step===3&&<Step title="Голос" text="Выберите голос и настройки произношения."><div className="grid gap-4 md:grid-cols-2"><Field label="Голосовой сервис"><select value={draft.provider} className="input" onChange={e=>set('provider',e.target.value)}><option value="openai_realtime">OpenAI Realtime</option></select></Field><Field label="Модель"><input value={draft.model} onChange={e=>set('model',e.target.value)} className="input"/></Field><Field label="Голос"><select value={draft.voiceId} onChange={e=>set('voiceId',e.target.value)} className="input">{['marin','cedar','coral','sage'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Темп"><select value={draft.voice.speakingRate} onChange={e=>set('voice',{...draft.voice,speakingRate:e.target.value})} className="input"><option value="normal">Обычный</option><option value="slightly_fast">Немного быстрее</option></select></Field><Field label="Паузы"><select value={draft.voice.pauseStyle} onChange={e=>set('voice',{...draft.voice,pauseStyle:e.target.value})} className="input"><option value="short_natural">Короткие естественные</option><option value="natural">Естественные</option></select></Field><Field label="Тестовая фраза"><div className="flex gap-2"><input value={draft.voice.testPhrase} onChange={e=>set('voice',{...draft.voice,testPhrase:e.target.value})} className="input"/><button className="rounded-lg border px-3 font-bold">Прослушать</button></div></Field></div><div className="mt-4 rounded-lg bg-amber-50 p-3 text-sm">Качество произношения зависит от голосовой модели и языка.</div></Step>}
    {step===4&&<Step title="Навыки и знания" text="Этот шаг можно пропустить. AI-сотрудник может быть создан без навыков."><div className="grid gap-3 md:grid-cols-3">{['Пустой AI-сотрудник','На основе шаблона','Копия существующего AI-сотрудника'].map(x=><button key={x} className="rounded-xl border p-4 text-left font-bold">{x}<div className="mt-1 text-xs font-normal text-slate-500">Номера, подключения, история и секреты не копируются.</div></button>)}</div><div className="mt-4 flex gap-2"><button className="rounded-lg border px-3 py-2 text-sm font-bold">Добавить навык</button><button className="rounded-lg border px-3 py-2 text-sm font-bold">Подключить базу знаний</button></div></Step>}
    {step===5&&<Step title="Передача сотруднику" text="Необязательная настройка."><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={draft.handoff.enabled} onChange={e=>set('handoff',{...draft.handoff,enabled:e.target.checked})}/>Включить передачу сотруднику</label>{draft.handoff.enabled&&<div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Основное направление"><input value={draft.handoff.destinationId} onChange={e=>set('handoff',{...draft.handoff,destinationId:e.target.value})} className="input"/></Field><Field label="Время ожидания"><input type="number" min={5} max={120} value={draft.handoff.timeout} onChange={e=>set('handoff',{...draft.handoff,timeout:Number(e.target.value)})} className="input"/></Field><Field label="Если не ответили"><select className="input"><option>Вернуть к AI</option></select></Field><Field label="Фраза перед переводом"><input value={draft.handoff.announcement} onChange={e=>set('handoff',{...draft.handoff,announcement:e.target.value})} className="input"/></Field></div>}</Step>}
    {step===6&&<Step title="Проверка" text="Проверьте итог. Кнопка ниже создаст только preview."><Summary draft={draft}/><button disabled={busy} onClick={makePreview} className="mt-5 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-50"><ShieldCheck className="mr-2 inline h-5 w-5"/>Проверить создание</button></Step>}
    {step===7&&<Step title="Создание" text="Live apply начнётся только после отдельного подтверждения.">{preview?<><Summary draft={draft}/><div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm"><b>Preview ID: {preview.previewId}</b><div>Будут созданы: agent, version 1, виртуальный номер {preview.extension}, Misc Application и Custom Destination.</div><div>productionAffected=false · automaticCall=false · SIP endpoint не создаётся</div></div><button disabled={busy} onClick={apply} className="mt-5 rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white">Создать AI-сотрудника и виртуальный номер</button></>:<div className="rounded-xl bg-slate-50 p-5 text-sm">Сначала выполните шаг «Проверка».</div>}</Step>}
   </div>
   {message&&<div className="mt-3 rounded-lg bg-slate-100 p-3 text-sm">{message}</div>}
   <div className="mt-4 flex justify-between"><button disabled={step===1} onClick={()=>setStep(x=>x-1)} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-bold disabled:opacity-30"><ChevronLeft className="h-4 w-4"/>Назад</button>{step<6&&<button disabled={busy} onClick={next} className="flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-2 text-sm font-bold text-white">Далее<ChevronRight className="h-4 w-4"/></button>}</div>
  </div>
 </section></div>
}
function Step({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <section><h2 className="text-lg font-black">{title}</h2><p className="mb-5 text-sm text-slate-500">{text}</p>{children}</section>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={`text-sm font-bold ${wide?'md:col-span-2':''}`}>{label}<div className="mt-1 font-normal">{children}</div></label>}
function Summary({draft}:{draft:any}){return <div className="grid gap-3 sm:grid-cols-2"><Card title="AI-сотрудник" value={`${draft.name||'—'} · ${draft.role}`}/><Card title="Внутренний номер" value={draft.extension||'—'}/><Card title="Голос" value={`${draft.voiceId} · ${draft.language}`}/><Card title="Передача сотруднику" value={draft.handoff.enabled?draft.handoff.destinationId:'Выключена'}/><Card title="Fallback" value={draft.fallbackType}/><Card title="FreePBX" value={`AI: ${draft.name||'—'} (${draft.extension||'—'})`}/></div>}
function Card({title,value}:{title:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">{title}</div><b>{value}</b></div>}
