import React,{useEffect,useMemo,useState}from'react';

type Props={token:string;agentId:number;canView:boolean;canCreate:boolean;canUpdate:boolean;canApply:boolean};
const statusLabel:Record<string,string>={draft:'Черновик',preview_ready:'Готов к применению',applying:'Создаётся',verifying:'Проверяется',active:'Подключён',disabled:'Отключён',conflict:'Конфликт',sync_failed:'Ошибка синхронизации',archived:'Архив'};

export default function AiExtensionPanel({token,agentId,canView,canCreate,canUpdate,canApply}:Props){
  const headers=useMemo(()=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'}),[token]);
  const[rows,setRows]=useState<any[]>([]),[extension,setExtension]=useState(''),[fallbackType,setFallbackType]=useState('terminate_call'),[fallbackValue,setFallbackValue]=useState(''),[preview,setPreview]=useState<any>(null),[message,setMessage]=useState(''),[expert,setExpert]=useState(false),[busy,setBusy]=useState(false);
  const load=async()=>{if(!canView)return;const response=await fetch(`/api/ai-platform/ai-extensions?agentId=${agentId}`,{headers}),body=await response.json();if(!response.ok)throw new Error(body.error||'Не удалось загрузить телефонию');setRows(body.rows||[])};
  useEffect(()=>{void load().catch(error=>setMessage(error.message))},[agentId,headers,canView]);
  const suggest=async()=>{setBusy(true);try{const response=await fetch('/api/ai-platform/ai-extensions/suggest',{headers}),body=await response.json();if(!response.ok)throw new Error(body.error||'Свободный номер не найден');setExtension(body.data.extension);setMessage(`Предложен свободный номер ${body.data.extension}`)}catch(error:any){setMessage(error.message)}finally{setBusy(false)}};
  const createPreview=async()=>{setBusy(true);setPreview(null);try{const response=await fetch('/api/ai-platform/ai-extensions/preview',{method:'POST',headers,body:JSON.stringify({agentId,extension,displayName:'AI-сотрудник',fallbackType,fallbackValue,idempotencyKey:crypto.randomUUID()})}),body=await response.json();if(!response.ok)throw new Error(body.error||'Preview не создан');setPreview(body.data);setMessage(body.data.ready?'Preview готов. FreePBX пока не изменён.':'Номер нельзя применить: устраните конфликт.')}catch(error:any){setMessage(error.message)}finally{setBusy(false)}};
  const apply=async()=>{if(!preview?.ready||!window.confirm(`Создать виртуальный номер ${extension} в FreePBX? Будет выполнен fwconsole reload.`))return;setBusy(true);try{const response=await fetch('/api/ai-platform/ai-extensions/apply',{method:'POST',headers,body:JSON.stringify({previewId:preview.previewId,confirm:true})}),body=await response.json();if(!response.ok)throw new Error(body.error||'Не удалось применить');setPreview(null);setMessage(`Виртуальный номер ${extension} подключён`);await load()}catch(error:any){setMessage(error.message)}finally{setBusy(false)}};
  const disable=async(id:number)=>{if(!window.confirm('Отключить виртуальный номер? История и опубликованная версия сохранятся.'))return;setBusy(true);try{const response=await fetch(`/api/ai-platform/ai-extensions/${id}/disable`,{method:'POST',headers,body:JSON.stringify({confirm:true})}),body=await response.json();if(!response.ok)throw new Error(body.error||'Не удалось отключить');setMessage('Виртуальный номер отключён; история сохранена');await load()}catch(error:any){setMessage(error.message)}finally{setBusy(false)}};
  const readiness=async(id:number)=>{const response=await fetch(`/api/ai-platform/ai-extensions/${id}/test-readiness`,{headers}),body=await response.json();setMessage(body.data?.ready?'Номер готов к тестовому звонку. Автоматический звонок не выполнялся.':'Номер пока не готов к звонку.')};
  if(!canView)return null;
  return <section id="telephony" className="rounded-2xl border bg-white p-5">
    <div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-lg font-black">Телефония</h3><p className="text-sm text-slate-500">Виртуальный внутренний номер без SIP-регистрации</p></div><button className="rounded border px-3 py-2 text-sm" onClick={()=>setExpert(!expert)}>{expert?'Скрыть технические детали':'Экспертный режим'}</button></div>
    <div className="mt-4 space-y-3">{rows.map(row=><article key={row.id} className="rounded-xl border p-4">{row.status==='sync_failed'&&<div className="mb-3 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Создание не завершено: FreePBX-объект создан, но dialplan не активирован.</div>}<div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-black">{row.extension} · {row.displayName}</div><div className="text-sm text-slate-500">{statusLabel[row.status]||row.status} · опубликованная версия {row.publishedVersion}</div></div><div className="flex flex-wrap gap-2"><button className="rounded border px-3 py-2 text-sm" onClick={()=>void readiness(row.id)}>Проверить звонок</button>{canUpdate&&row.status!=='disabled'&&<button disabled={busy} className="rounded border px-3 py-2 text-sm text-red-700" onClick={()=>void disable(row.id)}>Отключить</button>}</div></div><div className="mt-2 text-sm">Fallback: {row.fallbackType==='terminate_call'?'завершить звонок':`${row.fallbackType} ${row.fallbackValueSafe||''}`}</div>{expert&&<pre className="mt-3 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify({objectType:row.freepbxObjectType,context:row.dialplanContext,destination:row.dialplanDestination,provider:row.provider,syncStatus:row.syncStatus,lastSyncedAt:row.lastSyncedAt,error:row.syncErrorCode},null,2)}</pre>}</article>)}</div>
    {!rows.length&&canCreate&&<div className="mt-4 rounded-xl bg-slate-50 p-4"><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-bold">Внутренний номер<div className="mt-1 flex gap-2"><input className="w-full rounded border p-2 font-normal" inputMode="numeric" value={extension} onChange={event=>setExtension(event.target.value.replace(/\D/g,'').slice(0,8))}/><button disabled={busy} className="rounded border px-3 text-sm" onClick={()=>void suggest()}>Предложить</button></div></label><label className="text-sm font-bold">Куда направлять звонок при недоступности AI<select className="mt-1 w-full rounded border p-2 font-normal" value={fallbackType} onChange={event=>setFallbackType(event.target.value)}><option value="terminate_call">Завершить звонок с сообщением</option><option value="extension">Внутренний номер</option><option value="ring_group">Ring Group</option><option value="queue">Queue</option><option value="external">Внешнее направление</option></select></label>{fallbackType!=='terminate_call'&&<label className="text-sm font-bold md:col-start-2">Номер назначения<input className="mt-1 w-full rounded border p-2 font-normal" inputMode="tel" value={fallbackValue} onChange={event=>setFallbackValue(event.target.value.replace(/\D/g,'').slice(0,20))}/></label>}</div><button disabled={busy||extension.length<2} className="mt-4 rounded bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-40" onClick={()=>void createPreview()}>Создать и подключить</button><p className="mt-2 text-xs text-slate-500">Сначала будет создан preview. FreePBX изменится только после отдельного подтверждения.</p></div>}
    {preview&&<div className={`mt-4 rounded-xl border p-4 ${preview.ready?'border-emerald-200 bg-emerald-50':'border-red-200 bg-red-50'}`}><h4 className="font-black">Preview виртуального номера {extension}</h4><div className="mt-2 text-sm">Объект: Misc Application + Custom Destination · SIP endpoint: не создаётся</div><div className="text-sm">Destination: {preview.freepbxObject?.miscApplication?.destination} · Production routes: не затрагиваются</div>{preview.errors?.length>0&&<div className="mt-2 text-sm text-red-700">{preview.errors.map((item:any)=>`${item.type}: ${item.name}`).join(', ')}</div>}{expert&&<pre className="mt-3 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(preview,null,2)}</pre>}{preview.ready&&canApply&&<button disabled={busy} className="mt-3 rounded bg-emerald-600 px-4 py-2 text-sm font-bold text-white" onClick={()=>void apply()}>Применить после подтверждения</button>}</div>}
    {message&&<div className="mt-4 rounded border bg-slate-50 p-3 text-sm">{message}</div>}
  </section>;
}
