import React,{useEffect,useState}from'react';
type Row={id:number;name:string;providerType:string;healthStatus:string;agentCount:number;credentialIdentifier?:string};
const headers=(token:string)=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'});
export default function IntegrationManagementPanel({token,canView,canCreate,canTest}:{token:string;canView:boolean;canCreate:boolean;canEdit:boolean;canTest:boolean}){
 const[rows,setRows]=useState<Row[]>([]),[actions,setActions]=useState<any[]>([]),[selected,setSelected]=useState(0),[action,setAction]=useState('customer.lookup_by_phone'),[input,setInput]=useState('{"phone":"200"}'),[result,setResult]=useState(''),[name,setName]=useState('');
 const load=async()=>{if(!canView)return;const[r,a]=await Promise.all([fetch('/api/ai-platform/integrations',{headers:headers(token)}),fetch('/api/ai-platform/integrations/actions',{headers:headers(token)})]);const rj=await r.json(),aj=await a.json();setRows(rj.rows||[]);setActions(aj.rows||[])};
 useEffect(()=>{void load()},[token,canView]);
 const create=async()=>{await fetch('/api/ai-platform/integrations',{method:'POST',headers:headers(token),body:JSON.stringify({name,providerType:'generic_rest',connectorType:'generic_rest',baseUrl:'https://crm.example.test',authType:'none',allowedHosts:['crm.example.test'],environment:'sandbox'})});setName('');await load()};
 const preview=async()=>{const id=selected||rows[0]?.id;if(!id)return;try{const response=await fetch(`/api/ai-platform/integrations/${id}/preview`,{method:'POST',headers:headers(token),body:JSON.stringify({actionId:action,input:JSON.parse(input),dryRun:true})}),json=await response.json();setResult(JSON.stringify(json.data||{error:json.error},null,2))}catch{setResult('Некорректные тестовые данные')}};
 if(!canView)return <div className="rounded-xl border bg-white p-5 text-sm text-slate-500">Недостаточно прав для просмотра интеграций.</div>;
 return <div className="space-y-4"><section className="rounded-2xl border bg-white p-5"><h2 className="font-black">CRM и бизнес-системы</h2><p className="text-sm text-slate-500">AI получает только разрешённые действия и безопасные поля. Секреты после сохранения не отображаются.</p>{canCreate&&<div className="mt-4 flex gap-2"><input className="min-w-0 flex-1 rounded-lg border px-3 py-2" placeholder="Название подключения" value={name} onChange={e=>setName(e.target.value)}/><button disabled={!name.trim()} onClick={()=>void create()} className="rounded-lg bg-blue-600 px-4 py-2 font-bold text-white">Добавить REST API</button></div>}<div className="mt-4 space-y-2">{rows.map(row=><article key={row.id} className="flex items-center justify-between rounded-xl border p-3"><div><b>{row.name}</b><div className="text-xs text-slate-500">{row.providerType} · AI-сотрудников: {row.agentCount} · ключ: {row.credentialIdentifier||'не требуется'}</div></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{row.healthStatus==='connected'?'Подключено':row.healthStatus||'Не проверено'}</span></article>)}</div></section>{canTest&&rows.length>0&&<section className="rounded-2xl border bg-white p-5"><h2 className="font-black">Безопасная тестовая консоль</h2><div className="mt-3 grid gap-2 md:grid-cols-2"><select className="rounded-lg border px-3 py-2" value={selected||rows[0]?.id} onChange={e=>setSelected(Number(e.target.value))}>{rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="rounded-lg border px-3 py-2" value={action} onChange={e=>setAction(e.target.value)}>{actions.map(x=><option key={x.actionId} value={x.actionId}>{x.title} · {x.sideEffectLevel}</option>)}</select></div><textarea className="mt-2 h-24 w-full rounded-lg border p-3 font-mono text-sm" value={input} onChange={e=>setInput(e.target.value)}/><button onClick={()=>void preview()} className="mt-2 rounded-lg bg-blue-600 px-4 py-2 font-bold text-white">Предпросмотр</button>{result&&<pre className="mt-3 overflow-auto rounded-xl bg-slate-950 p-3 text-xs text-slate-100">{result}</pre>}</section>}</div>
}
