import React, { useEffect, useState } from 'react';

export default function RealtimeVoicePanel({ token, canView, canTest }: { token: string; canView: boolean; canTest: boolean }) {
  const [status, setStatus] = useState<any>(null), [sessionId, setSessionId] = useState(''), [mediaSessionId, setMediaSessionId] = useState(''), [message, setMessage] = useState('');
  const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };
  const load = () => canView ? fetch('/api/ai-platform/voice/realtime/status', { headers }).then(response => response.json()).then(value => setStatus(value.data)).catch(() => setStatus(null)) : Promise.resolve();
  useEffect(() => { void load(); }, [canView]);
  const call = async (path: string, body: unknown) => { const response = await fetch(path, { method: 'POST', headers, body: JSON.stringify(body) }), value = await response.json(); setMessage(response.ok ? `Session ${value.data?.id}: ${value.data?.state}` : value.error || 'Ошибка'); if (value.data?.id) setSessionId(String(value.data.id)); void load(); };
  if (!canView) return null;
  return <section className="mt-5 rounded-2xl border bg-white p-5"><h3 className="font-black">Realtime Voice-to-Voice</h3><div className="mt-2 rounded border border-amber-200 bg-amber-50 p-3 text-sm">Тест работает через synthetic media и не подключён к Asterisk.</div><div className="mt-3 grid gap-2 text-sm md:grid-cols-3"><div>Feature: {String(status?.featureEnabled)}</div><div>Provider: {status?.provider || 'synthetic'}</div><div>Configured: {String(status?.configured)}</div><div>Active sessions: {status?.activeSessions || 0}</div><div>First audio: {status?.averageFirstResponseLatencyMs ?? '—'} ms</div><div>Asterisk: disconnected</div></div>{canTest && <div className="mt-4 flex flex-wrap gap-2"><input className="rounded border p-2" placeholder="Media session ID" value={mediaSessionId} onChange={event => setMediaSessionId(event.target.value)}/><button className="rounded bg-blue-600 px-3 text-white" onClick={() => void call('/api/ai-platform/voice/realtime/test/start', { mediaSessionId: Number(mediaSessionId) })}>Начать</button><button className="rounded border px-3" onClick={() => void call('/api/ai-platform/voice/realtime/test/audio', { sessionId: Number(sessionId), fixture: 'question' })}>Вопрос</button><button className="rounded border px-3" onClick={() => void call('/api/ai-platform/voice/realtime/test/audio', { sessionId: Number(sessionId), fixture: 'transfer_request' })}>Transfer</button><button className="rounded border px-3" onClick={() => void call('/api/ai-platform/voice/realtime/test/audio', { sessionId: Number(sessionId), fixture: 'callback_request' })}>Callback</button><button className="rounded border px-3" onClick={() => void call('/api/ai-platform/voice/realtime/test/commit', { sessionId: Number(sessionId) })}>Commit</button><button className="rounded border px-3" onClick={() => void call('/api/ai-platform/voice/realtime/test/barge-in', { sessionId: Number(sessionId) })}>Barge-in</button><button className="rounded border px-3" onClick={() => void call('/api/ai-platform/voice/realtime/test/stop', { sessionId: Number(sessionId) })}>Стоп</button></div>}{message && <p className="mt-2 text-sm">{message}</p>}</section>;
}
