import React,{useEffect,useMemo,useState}from"react";
import{Plus,Settings2}from"lucide-react";

type Props={token:string;agentId:number;enabled:boolean;canManage:boolean};
type SkillRow={id:number;skill_key:string;name:string;description:string;status:string;version_number:number};
type SkillDetail={
  id:number;skillKey:string;name:string;description:string;status:string;
  triggerPhrases:string[];negativeTriggerPhrases:string[];intentExamples:string[];
  activationThreshold:number;ambiguityPolicy:"clarify"|"none";
};
const lines=(value:string)=>value.split("\n").map(item=>item.trim()).filter(Boolean);

export default function SkillBuilderPanel({token,agentId,enabled,canManage}:Props){
  const headers=useMemo(()=>({Authorization:`Bearer ${token}`,"Content-Type":"application/json"}),[token]);
  const[rows,setRows]=useState<SkillRow[]>([]);
  const[name,setName]=useState(""),[key,setKey]=useState(""),[message,setMessage]=useState("");
  const[selected,setSelected]=useState<SkillDetail|null>(null);
  const[triggers,setTriggers]=useState(""),[negative,setNegative]=useState(""),[examples,setExamples]=useState("");
  const[threshold,setThreshold]=useState(.72),[ambiguity,setAmbiguity]=useState<"clarify"|"none">("clarify");
  const[testText,setTestText]=useState("Запишите меня ко врачу завтра на 12"),[preview,setPreview]=useState<any>(null);
  const load=()=>fetch("/api/ai-platform/skills",{headers}).then(r=>r.json()).then(body=>setRows(body.rows||[])).catch(()=>setRows([]));
  useEffect(()=>{if(enabled)void load()},[enabled,headers]);
  const open=async(id:number)=>{const response=await fetch(`/api/ai-platform/skills/${id}`,{headers}),body=await response.json(),skill=body.data as SkillDetail;setSelected(skill);setTriggers((skill.triggerPhrases||[]).join("\n"));setNegative((skill.negativeTriggerPhrases||[]).join("\n"));setExamples((skill.intentExamples||[]).join("\n"));setThreshold(skill.activationThreshold??.72);setAmbiguity(skill.ambiguityPolicy||"clarify");setPreview(null)};
  const create=async()=>{const response=await fetch("/api/ai-platform/skills",{method:"POST",headers,body:JSON.stringify({skillKey:key,name,description:"",triggerPhrases:[],negativeTriggerPhrases:[],intentExamples:[],activationThreshold:.72,ambiguityPolicy:"clarify",escalationPolicy:{enabled:true}})}),body=await response.json();setMessage(response.ok?"Draft навыка создан":body.error||"Не удалось создать навык");if(response.ok){setName("");setKey("");await load()}};
  const save=async()=>{if(!selected)return;const response=await fetch(`/api/ai-platform/skills/${selected.id}`,{method:"PUT",headers,body:JSON.stringify({triggerPhrases:lines(triggers),negativeTriggerPhrases:lines(negative),intentExamples:lines(examples),activationThreshold:threshold,ambiguityPolicy:ambiguity})});setMessage(response.ok?"Настройки распознавания сохранены":"Не удалось сохранить настройки");if(response.ok)await open(selected.id)};
  const recognize=async()=>{if(!selected)return;const response=await fetch(`/api/ai-platform/skills/${selected.id}/recognition-preview`,{method:"POST",headers,body:JSON.stringify({text:testText})}),body=await response.json();setPreview(body.data||null);setMessage(response.ok?"Проверка завершена":"Не удалось проверить распознавание")};
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800">
    <div className="flex items-center gap-2"><Settings2 className="h-5 w-5 text-blue-600"/><h3 className="font-black">Навыки AI-сотрудника</h3></div>
    <p className="mt-1 text-sm text-slate-500">Поля, каталоги, действия и фразы хранятся в immutable версиях навыков.</p>
    {canManage&&<div className="mt-4 grid gap-2 md:grid-cols-[1fr_1fr_auto]"><input className="rounded-xl border p-2" placeholder="Название навыка" value={name} onChange={e=>setName(e.target.value)}/><input className="rounded-xl border p-2" placeholder="skill_key" value={key} onChange={e=>setKey(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,""))}/><button disabled={!name||!key} onClick={()=>void create()} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-40"><Plus className="h-4 w-4"/>Создать навык</button></div>}
    {message&&<p className="mt-2 text-sm text-slate-600">{message}</p>}
    <div className="mt-4 space-y-2">{rows.map(row=><button type="button" onClick={()=>void open(row.id)} key={row.id} className="block w-full rounded-xl border p-3 text-left"><div className="flex justify-between gap-3"><div><b>{row.name}</b><div className="text-xs text-slate-500">{row.skill_key} · версия {row.version_number}</div></div><span className="text-xs font-bold uppercase text-slate-500">{row.status}</span></div><p className="mt-2 text-sm text-slate-500">{row.description||"Описание не задано"}</p></button>)}</div>
    {selected&&<div className="mt-5 rounded-xl border p-4"><h4 className="font-bold">Распознавание: {selected.name}</h4><div className="mt-3 grid gap-3 md:grid-cols-3"><label className="text-sm">Trigger phrases<textarea disabled={selected.status!=="draft"} className="mt-1 min-h-28 w-full rounded-xl border p-2" value={triggers} onChange={e=>setTriggers(e.target.value)}/></label><label className="text-sm">Negative triggers<textarea disabled={selected.status!=="draft"} className="mt-1 min-h-28 w-full rounded-xl border p-2" value={negative} onChange={e=>setNegative(e.target.value)}/></label><label className="text-sm">Intent examples<textarea disabled={selected.status!=="draft"} className="mt-1 min-h-28 w-full rounded-xl border p-2" value={examples} onChange={e=>setExamples(e.target.value)}/></label></div><div className="mt-3 flex flex-wrap items-end gap-3"><label className="text-sm">Activation threshold<input disabled={selected.status!=="draft"} type="number" min="0" max="1" step=".01" className="mt-1 block rounded-xl border p-2" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><label className="text-sm">Ambiguity policy<select disabled={selected.status!=="draft"} className="mt-1 block rounded-xl border p-2" value={ambiguity} onChange={e=>setAmbiguity(e.target.value as any)}><option value="clarify">Уточнить</option><option value="none">Не активировать</option></select></label>{canManage&&selected.status==="draft"&&<button onClick={()=>void save()} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Сохранить</button>}</div><div className="mt-4 grid gap-2 md:grid-cols-[1fr_auto]"><input className="rounded-xl border p-2" value={testText} onChange={e=>setTestText(e.target.value)} placeholder="Проверить распознавание навыка"/><button onClick={()=>void recognize()} className="rounded-xl border px-4 py-2 text-sm font-bold">Проверить распознавание навыка</button></div>{preview&&<div className="mt-3 rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-900"><div>Навык: <b>{preview.selectedSkill||"none"}</b> · confidence {preview.confidence}</div><div>Поля: {JSON.stringify(preview.extractedFields||{})}</div><div>Не хватает: {(preview.missingFields||[]).join(", ")||"—"}</div><div>Следующий intent: {preview.nextPlannerIntent}</div></div>}</div>}
    {!rows.length&&<p className="mt-4 text-sm text-slate-500">Навыки ещё не созданы.</p>}<p className="mt-3 text-xs text-slate-400">Agent #{agentId}: назначение выполняется для draft-версии после preview.</p>
  </section>;
}
