import React,{useEffect,useMemo,useState}from"react";
import{HelpCircle,Plus,Settings2,X}from"lucide-react";

type Props={token:string;agentId?:number;enabled:boolean;canManage:boolean;canPublish?:boolean};
type SkillRow={id:number;skill_key:string;name:string;description:string;status:string;version_number:number};
type SkillField={key:string;label:string;type:string;required:boolean};
type SkillDetail={id:number;skillKey:string;name:string;description:string;status:string;triggerPhrases:string[];negativeTriggerPhrases:string[];intentExamples:string[];activationThreshold:number;ambiguityPolicy:"clarify"|"none";fields:SkillField[];responseTemplates:Record<string,string>};
const lines=(value:string)=>value.split("\n").map(item=>item.trim()).filter(Boolean);

export default function SkillBuilderPanel({token,enabled,canManage,canPublish=false}:Props){
 const headers=useMemo(()=>({Authorization:`Bearer ${token}`,"Content-Type":"application/json"}),[token]);
 const[rows,setRows]=useState<SkillRow[]>([]),[selected,setSelected]=useState<SkillDetail|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const[helpOpen,setHelpOpen]=useState(false);
 const[name,setName]=useState(""),[key,setKey]=useState(""),[description,setDescription]=useState("");
 const[triggers,setTriggers]=useState(""),[negative,setNegative]=useState(""),[examples,setExamples]=useState(""),[threshold,setThreshold]=useState(.72),[ambiguity,setAmbiguity]=useState<"clarify"|"none">("clarify");
 const[field,setField]=useState({key:"",label:"",type:"text"});
 const[fallback,setFallback]=useState("Извините, я не смог выполнить эту задачу. Давайте уточним запрос."),[unavailable,setUnavailable]=useState("Сейчас это действие недоступно. Я могу соединить вас с сотрудником.");
 const[testText,setTestText]=useState("Хочу записаться на завтра"),[preview,setPreview]=useState<any>(null),[validation,setValidation]=useState<any>(null);
 const request=async(path:string,method="GET",data?:any)=>{const response=await fetch(path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)}),body=await response.json();if(!response.ok)throw new Error(String(body?.error||body?.message||"Операция не выполнена"));return body.data??body.rows};
 const load=async()=>setRows(await request("/api/ai-platform/skills")||[]);
 useEffect(()=>{if(enabled)void load().catch(e=>setMessage(e.message))},[enabled,headers]);
 const open=async(id:number)=>{try{const skill=await request(`/api/ai-platform/skills/${id}`) as SkillDetail;if(!skill)throw new Error("Навык не найден");setSelected(skill);setDescription(skill.description||"");setTriggers((skill.triggerPhrases||[]).join("\n"));setNegative((skill.negativeTriggerPhrases||[]).join("\n"));setExamples((skill.intentExamples||[]).join("\n"));setThreshold(skill.activationThreshold??.72);setAmbiguity(skill.ambiguityPolicy||"clarify");setFallback(skill.responseTemplates?.fallback||fallback);setUnavailable(skill.responseTemplates?.action_unavailable||unavailable);setPreview(null);setValidation(null)}catch(e:any){setMessage(e.message)}};
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setMessage("");try{await action()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 const create=()=>run(async()=>{const skill=await request("/api/ai-platform/skills","POST",{skillKey:key,name,description,triggerPhrases:[],negativeTriggerPhrases:[],intentExamples:[],activationThreshold:.72,ambiguityPolicy:"clarify",escalationPolicy:{enabled:true}});setName("");setKey("");setDescription("");await load();await open(skill.id);setMessage("Черновик навыка создан")});
 const save=()=>run(async()=>{if(!selected)return;await request(`/api/ai-platform/skills/${selected.id}`,"PUT",{name:selected.name,description,triggerPhrases:lines(triggers),negativeTriggerPhrases:lines(negative),intentExamples:lines(examples),activationThreshold:threshold,ambiguityPolicy:ambiguity,escalationPolicy:{enabled:true}});await request(`/api/ai-platform/skills/${selected.id}/templates/fallback`,"PUT",{text:fallback});await request(`/api/ai-platform/skills/${selected.id}/templates/action_unavailable`,"PUT",{text:unavailable});await open(selected.id);await load();setMessage("Навык сохранён")});
 const addField=()=>run(async()=>{if(!selected)return;await request(`/api/ai-platform/skills/${selected.id}/fields`,"POST",{...field,required:true,extractionHints:[],synonyms:[],validation:{},confirmationRequired:false,sensitive:false,displayOrder:selected.fields.length});setField({key:"",label:"",type:"text"});await open(selected.id);setMessage("Поле добавлено")});
 const validate=()=>run(async()=>{if(!selected)return;const result=await request(`/api/ai-platform/skills/${selected.id}/validate`,"POST",{});setValidation(result);setMessage(result.valid?"Навык готов к публикации":"Исправьте ошибки проверки")});
 const publish=()=>run(async()=>{if(!selected||!confirm("Опубликовать навык? Опубликованная версия станет неизменяемой."))return;await request(`/api/ai-platform/skills/${selected.id}/publish`,"POST",{});await open(selected.id);await load();setMessage("Навык опубликован и доступен для AI-сотрудников")});
 const recognize=()=>run(async()=>{if(!selected)return;setPreview(await request(`/api/ai-platform/skills/${selected.id}/recognition-preview`,"POST",{text:testText}));setMessage("Проверка распознавания завершена")});
 const draft=selected?.status==="draft";
 return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800">
  <div className="flex items-center gap-2"><Settings2 className="h-5 w-5 text-blue-600"/><h3 className="font-black">Навыки AI-сотрудников</h3><button type="button" onClick={()=>setHelpOpen(true)} aria-label="Как работать с навыками" title="Как работать с навыками" className="rounded-full p-1 text-slate-400 hover:bg-blue-50 hover:text-blue-600"><HelpCircle className="h-5 w-5"/></button></div><p className="mt-1 text-sm text-slate-500">Создайте сценарий, настройте распознавание и поля, проверьте и опубликуйте его.</p>
  {canManage&&<div className="mt-4 grid gap-2 md:grid-cols-[1fr_1fr_2fr_auto]"><input className="rounded-xl border p-2" placeholder="Название" value={name} onChange={e=>setName(e.target.value)}/><input className="rounded-xl border p-2" placeholder="skill_key" value={key} onChange={e=>setKey(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,""))}/><input className="rounded-xl border p-2" placeholder="Что делает навык" value={description} onChange={e=>setDescription(e.target.value)}/><button disabled={busy||!name||key.length<2} onClick={create} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-40"><Plus className="h-4 w-4"/>Создать</button></div>}
  {message&&<p className="mt-3 rounded-lg bg-slate-50 p-2 text-sm dark:bg-slate-900">{message}</p>}
  <div className="mt-4 grid gap-4 lg:grid-cols-[300px_1fr]"><div className="space-y-2">{rows.map(row=><button type="button" onClick={()=>void open(row.id)} key={row.id} className={`block w-full rounded-xl border p-3 text-left ${selected?.id===row.id?"border-blue-500 bg-blue-50 dark:bg-slate-900":""}`}><div className="flex justify-between gap-2"><b>{row.name}</b><span className="text-xs font-bold uppercase text-slate-500">{row.status}</span></div><div className="text-xs text-slate-500">{row.skill_key} · v{row.version_number}</div></button>)}{!rows.length&&<p className="text-sm text-slate-500">Навыки ещё не созданы.</p>}</div>
  {selected?<div className="space-y-5 rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h4 className="font-bold">{selected.name}</h4><p className="text-xs text-slate-500">{selected.skillKey} · {selected.status}</p></div><div className="flex gap-2"><button disabled={busy} onClick={validate} className="rounded-lg border px-3 py-2 text-sm font-bold">Проверить</button>{canPublish&&draft&&<button disabled={busy} onClick={publish} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-bold text-white">Опубликовать</button>}</div></div>
   <label className="block text-sm font-bold">Описание<input disabled={!draft} className="mt-1 w-full rounded-xl border p-2 font-normal" value={description} onChange={e=>setDescription(e.target.value)}/></label>
   <div className="grid gap-3 md:grid-cols-3"><Area label="Фразы активации" value={triggers} set={setTriggers} disabled={!draft}/><Area label="Когда не активировать" value={negative} set={setNegative} disabled={!draft}/><Area label="Примеры запросов" value={examples} set={setExamples} disabled={!draft}/></div>
   <div className="flex flex-wrap gap-3"><label className="text-sm font-bold">Порог<input disabled={!draft} type="number" min="0" max="1" step=".01" className="ml-2 rounded-lg border p-2 font-normal" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><label className="text-sm font-bold">Неуверенность<select disabled={!draft} className="ml-2 rounded-lg border p-2 font-normal" value={ambiguity} onChange={e=>setAmbiguity(e.target.value as any)}><option value="clarify">Задать вопрос</option><option value="none">Не запускать</option></select></label></div>
   <div><h5 className="font-bold">Данные, которые нужно получить</h5><div className="mt-2 space-y-2">{selected.fields.map(item=><div key={item.key} className="rounded-lg bg-slate-50 p-2 text-sm dark:bg-slate-900"><b>{item.label}</b> · {item.key} · {item.type}{item.required?" · обязательное":""}</div>)}</div>{canManage&&draft&&<div className="mt-3 grid gap-2 md:grid-cols-4"><input className="rounded-lg border p-2" placeholder="field_key" value={field.key} onChange={e=>setField({...field,key:e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,"")})}/><input className="rounded-lg border p-2" placeholder="Название поля" value={field.label} onChange={e=>setField({...field,label:e.target.value})}/><select className="rounded-lg border p-2" value={field.type} onChange={e=>setField({...field,type:e.target.value})}><option value="text">Текст</option><option value="phone">Телефон</option><option value="number">Число</option><option value="date">Дата</option><option value="time">Время</option><option value="boolean">Да/нет</option></select><button disabled={!field.key||!field.label} onClick={addField} className="rounded-lg border px-3 font-bold disabled:opacity-40">Добавить поле</button></div>}</div>
   <div className="grid gap-3 md:grid-cols-2"><Area label="Ответ при ошибке" value={fallback} set={setFallback} disabled={!draft}/><Area label="Действие недоступно" value={unavailable} set={setUnavailable} disabled={!draft}/></div>
   {canManage&&draft&&<button disabled={busy} onClick={save} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Сохранить черновик</button>}
   <div className="grid gap-2 md:grid-cols-[1fr_auto]"><input className="rounded-xl border p-2" value={testText} onChange={e=>setTestText(e.target.value)} placeholder="Фраза клиента"/><button disabled={busy} onClick={recognize} className="rounded-xl border px-4 py-2 text-sm font-bold">Проверить фразу</button></div>
   {validation&&!validation.valid&&<div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Ошибки: {(validation.errors||[]).join(", ")}</div>}{preview&&<div className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-900">Навык: <b>{preview.selectedSkill||"не определён"}</b> · уверенность {preview.confidence}<br/>Получено: {JSON.stringify(preview.extractedFields||{})}<br/>Не хватает: {(preview.missingFields||[]).join(", ")||"—"}</div>}
  </div>:<div className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500 dark:bg-slate-900">Выберите навык слева.</div>}</div>
  {helpOpen&&<div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true" aria-labelledby="skills-help-title" onMouseDown={e=>{if(e.target===e.currentTarget)setHelpOpen(false)}}><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-800"><div className="flex items-start justify-between gap-3"><div><h3 id="skills-help-title" className="text-lg font-black">Как работать с навыками</h3><p className="mt-1 text-sm text-slate-500">Навык — отдельный сценарий разговора: запись клиента, проверка заказа или ответы на вопросы.</p></div><button type="button" onClick={()=>setHelpOpen(false)} aria-label="Закрыть инструкцию" className="rounded-lg border p-2"><X className="h-4 w-4"/></button></div><ol className="mt-5 list-decimal space-y-3 pl-5 text-sm"><li><b>Создайте черновик:</b> укажите название, технический ключ латиницей и описание.</li><li><b>Добавьте фразы активации</b> и реальные примеры запросов — по одной фразе на строку.</li><li><b>Укажите исключения:</b> фразы, при которых этот навык запускать не нужно.</li><li><b>Добавьте данные клиента:</b> имя, телефон, дату, время и другие обязательные поля.</li><li><b>Сохраните</b> черновик и проверьте его на тестовой фразе.</li><li>Нажмите <b>«Проверить»</b>, исправьте найденные ошибки и затем <b>«Опубликовать»</b>.</li><li>При создании AI-сотрудника выберите опубликованный навык на шаге <b>«Навыки и знания»</b>.</li></ol><div className="mt-5 rounded-xl bg-blue-50 p-4 text-sm text-blue-950"><b>Пример:</b> «Запись на приём», ключ <code>appointment_booking</code>. Фразы: «Хочу записаться», «Запишите меня на завтра». Поля: имя, телефон, дата и время.</div><div className="mt-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><b>Важно:</b> опубликованная версия неизменяема. Реальные действия в CRM или Bitrix24 подключаются через интеграции.</div></div></div>}
 </section>;
}
function Area({label,value,set,disabled}:{label:string;value:string;set:(value:string)=>void;disabled:boolean}){return <label className="text-sm font-bold">{label}<textarea disabled={disabled} className="mt-1 min-h-24 w-full rounded-xl border p-2 font-normal" value={value} onChange={e=>set(e.target.value)}/></label>}
