import React,{useEffect,useMemo,useState}from"react";
import{Plus,Settings2}from"lucide-react";
type Props={token:string;agentId:number;enabled:boolean;canManage:boolean};
type Skill={id:number;skill_key:string;name:string;description:string;status:string;version_number:number};
export default function SkillBuilderPanel({token,agentId,enabled,canManage}:Props){
  const headers=useMemo(()=>({Authorization:`Bearer ${token}`,"Content-Type":"application/json"}),[token]);
  const[rows,setRows]=useState<Skill[]>([]),[name,setName]=useState(""),[key,setKey]=useState(""),[message,setMessage]=useState("");
  const load=()=>fetch("/api/ai-platform/skills",{headers}).then(r=>r.json()).then(body=>setRows(body.rows||[])).catch(()=>setRows([]));
  useEffect(()=>{if(enabled)void load()},[enabled,headers]);
  const create=async()=>{const response=await fetch("/api/ai-platform/skills",{method:"POST",headers,body:JSON.stringify({skillKey:key,name,description:"",intentExamples:[],escalationPolicy:{enabled:true}})}),body=await response.json();setMessage(response.ok?"Draft навыка создан":body.error||"Не удалось создать навык");if(response.ok){setName("");setKey("");await load()}};
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800"><div className="flex items-center gap-2"><Settings2 className="h-5 w-5 text-blue-600"/><h3 className="font-black">Навыки AI-сотрудника</h3></div><p className="mt-1 text-sm text-slate-500">Поля, каталоги, действия и фразы хранятся в immutable версиях навыков.</p>{canManage&&<div className="mt-4 grid gap-2 md:grid-cols-[1fr_1fr_auto]"><input className="rounded-xl border p-2" placeholder="Название навыка" value={name} onChange={e=>setName(e.target.value)}/><input className="rounded-xl border p-2" placeholder="skill_key" value={key} onChange={e=>setKey(e.target.value.toLowerCase().replace(/[^a-z0-9_]/g,""))}/><button disabled={!name||!key} onClick={()=>void create()} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-40"><Plus className="h-4 w-4"/>Создать навык</button></div>}{message&&<p className="mt-2 text-sm text-slate-600">{message}</p>}<div className="mt-4 space-y-2">{rows.map(row=><article key={row.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><div><b>{row.name}</b><div className="text-xs text-slate-500">{row.skill_key} · версия {row.version_number}</div></div><span className="text-xs font-bold uppercase text-slate-500">{row.status}</span></div><p className="mt-2 text-sm text-slate-500">{row.description||"Описание не задано"}</p></article>)}</div>{!rows.length&&<p className="mt-4 text-sm text-slate-500">Навыки ещё не созданы.</p>}<p className="mt-3 text-xs text-slate-400">Agent #{agentId}: назначение выполняется для draft-версии после preview.</p></section>
}
