import React,{useEffect,useMemo,useState}from'react';

const blindLabels=['A','B','C'];
export default function VoiceSettingsPanel({token,agentId,canManage,expertMode=false}:{token:string;agentId:number;canManage:boolean;expertMode?:boolean}){
 const headers=useMemo(()=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'}),[token]);
 const[catalog,setCatalog]=useState<any[]>([]),[texts,setTexts]=useState<any>({primary:'',additional:''}),[profile,setProfile]=useState<any>({provider:'',voiceId:'',language:'ru',locale:'ru-RU',pronunciationStyle:'native_neutral',speakingRate:'slightly_fast',pauseStyle:'short_natural',expressiveness:'warm_moderate',pitchStyle:'neutral'}),[vad,setVad]=useState(350),[entries,setEntries]=useState<any[]>([]),[testText,setTestText]=useState(''),[audio,setAudio]=useState<Record<string,string>>({}),[generating,setGenerating]=useState(''),[comparison,setComparison]=useState<string[]>([]),[blind,setBlind]=useState(false),[blindVoices,setBlindVoices]=useState<string[]>([]),[blindChoice,setBlindChoice]=useState<number|null>(null),[providerFilter,setProviderFilter]=useState('all'),[availability,setAvailability]=useState('active'),[newOnly,setNewOnly]=useState(false),[genderFilter,setGenderFilter]=useState('all'),[lastVerifiedAt,setLastVerifiedAt]=useState<string|null>(null),[preview,setPreview]=useState<any>(null),[draft,setDraft]=useState<any>(null),[published,setPublished]=useState<any>(null),[bindingId,setBindingId]=useState<number|null>(null),[controlledPreview,setControlledPreview]=useState<any>(null),[message,setMessage]=useState('');
 useEffect(()=>{void Promise.all([
  fetch('/api/ai-platform/voice-profiles/options',{headers}).then(r=>r.json()),
  fetch('/api/ai-platform/voice-catalog',{headers}).then(r=>r.json()),
  fetch(`/api/ai-platform/agents/${agentId}/voice-settings`,{headers}).then(r=>r.json()),
  fetch('/api/ai-platform/voice-agent-bindings',{headers}).then(r=>r.json()),
 ]).then(([o,c,s,b])=>{const rows=c.rows||[];setCatalog(rows);setLastVerifiedAt(c.lastVerifiedAt||null);setTexts(o.data.comparisonTexts);setTestText(o.data.comparisonTexts.primary);if(s.data?.voiceProfile)setProfile(s.data.voiceProfile);setVad(Number(s.data?.endOfTurnSilenceMs||350));setEntries(s.data?.pronunciationEntries||[]);setBlindVoices(rows.filter((x:any)=>x.active&&x.supported).map((x:any)=>x.voiceId).sort(()=>Math.random()-.5).slice(0,3));const binding=(b.rows||[]).find((x:any)=>x.bindingKey==='controlled_test_205');setBindingId(binding?Number(binding.id):null)}).catch(()=>setMessage('Не удалось загрузить Voice Catalog'))},[agentId,headers]);
 const post=async(path:string,body:any)=>{const r=await fetch(path,{method:'POST',headers,body:JSON.stringify(body)}),v=await r.json();if(!r.ok)throw new Error(v.error||'Ошибка');return v.data};
 const body={voiceProfile:profile,endOfTurnSilenceMs:vad,pronunciationEntries:entries};
 const listen=async(voiceId:string,force=false)=>{try{setGenerating(voiceId);const r=await fetch('/api/ai-platform/voice-profiles/preview-audio',{method:'POST',headers,body:JSON.stringify({voiceProfile:{...profile,voiceId},text:testText,force})});if(!r.ok)throw new Error((await r.json()).error||'Голос недоступен');if(audio[voiceId])URL.revokeObjectURL(audio[voiceId]);const url=URL.createObjectURL(await r.blob());setAudio(v=>({...v,[voiceId]:url}));await new Audio(url).play();setMessage(`Preview ${blind?'варианта':voiceId}: cache ${r.headers.get('X-Voice-Preview-Cache')||'—'}`)}catch(e:any){setMessage(e.message)}finally{setGenerating('')}};
 const compare=async()=>{for(const voiceId of comparison)await listen(voiceId)};
 const refreshCatalog=async()=>{try{const result=await post('/api/ai-platform/voice-catalog/refresh',{provider:profile.provider||'openai_realtime'});const response=await fetch('/api/ai-platform/voice-catalog',{headers}).then(r=>r.json());setCatalog(response.rows||[]);setLastVerifiedAt(response.lastVerifiedAt||result.lastVerifiedAt);setMessage(`Каталог проверен: новых ${result.added.length}, недоступных ${result.unavailable.length}. Agent versions и bindings не изменены.`)}catch(e:any){setMessage(e.message)}};
 const select=(item:any)=>{setProfile({...profile,provider:item.provider,voiceId:item.voiceId});setDraft(null);setPreview(null);setMessage(`Выбран ${item.voiceId}; изменение ещё не сохранено`)};
 const createDraft=async()=>{try{const value=await post(`/api/ai-platform/agents/${agentId}/voice-settings/draft`,body);setDraft(value);setPublished(null);setMessage(`Voice Profile сохранён в draft version ${value.version}`)}catch(e:any){setMessage(e.message)}};
 const publish=async()=>{if(!draft||!window.confirm(`Опубликовать immutable version ${draft.version}?`))return;try{const value=await post(`/api/ai-platform/agents/${agentId}/versions/${draft.id}/publish`,{});setPublished({...value,version:draft.version});setMessage(`Version ${draft.version} опубликована; binding 205 не изменён`)}catch(e:any){setMessage(e.message)}};
 const previewBinding=async()=>{try{if(!published||!bindingId)return;const value=await post(`/api/ai-platform/voice-agent-bindings/${bindingId}/version-preview`,{agentVersionId:published.id});setControlledPreview(value);setMessage('Preview controlled binding готов')}catch(e:any){setMessage(e.message)}};
 const applyBinding=async()=>{if(!controlledPreview?.ready||!window.confirm('Переключить только controlled binding 205?'))return;try{const value=await post(`/api/ai-platform/voice-agent-bindings/${bindingId}/version-apply`,{agentVersionId:published.id,confirm:true});setMessage(`205 переключён; productionAffected=${String(value.productionAffected)}`)}catch(e:any){setMessage(e.message)}};
 const providers=[...new Set(catalog.map(x=>x.provider))],genders=[...new Set(catalog.map(x=>String(x.metadata?.gender||'')).filter(Boolean))];
 const visible=catalog.filter(x=>(providerFilter==='all'||x.provider===providerFilter)&&(availability==='all'||(availability==='active'?x.active&&x.supported:!x.active||!x.supported))&&(!newOnly||x.isNew)&&(genderFilter==='all'||x.metadata?.gender===genderFilter));
 const renderCard=(item:any,label=item.displayName,hidden=false)=><article key={label} className={`rounded-xl border p-3 ${profile.voiceId===item.voiceId?'border-blue-500 bg-blue-50':''} ${!item.supported?'opacity-60':''}`}><div className="flex justify-between gap-2"><b>{label} {item.isNew&&<span className="rounded bg-emerald-100 px-2 py-0.5 text-[10px] text-emerald-800">Новый</span>}</b>{!hidden&&<code className="text-xs">{item.voiceId}</code>}</div>{!hidden&&<>{expertMode&&<p className="text-xs text-slate-500">Голосовой сервис: {item.provider}</p>}<p className="mt-1 text-xs">{item.description||'Описание не задано'}</p>{!item.supported&&<p className="mt-1 text-xs text-amber-700">Недоступен для новых настроек; сохранён для опубликованных версий.</p>}</>}<div className="mt-2 flex flex-wrap gap-2"><button disabled={!item.previewAvailable||!item.supported||generating===item.voiceId} onClick={()=>void listen(item.voiceId)} className="rounded border px-2 py-1 text-xs">{generating===item.voiceId?'Генерация…':'Прослушать'}</button><button disabled={!audio[item.voiceId]} onClick={()=>void new Audio(audio[item.voiceId]).play()} className="rounded border px-2 py-1 text-xs">Повторить</button><button disabled={!item.previewAvailable||!item.supported} onClick={()=>void listen(item.voiceId,true)} className="rounded border px-2 py-1 text-xs">Обновить пример</button></div>{audio[item.voiceId]&&<audio controls className="mt-2 w-full" src={audio[item.voiceId]}/>}<div className="mt-2 flex gap-2"><button disabled={!canManage||!item.supported} onClick={()=>{if(hidden){const i=blindVoices.indexOf(item.voiceId);setBlindChoice(i)}select(item)}} className="rounded bg-slate-900 px-2 py-1 text-xs text-white">Выбрать</button>{!hidden&&<label className="text-xs"><input type="checkbox" checked={comparison.includes(item.voiceId)} disabled={!comparison.includes(item.voiceId)&&comparison.length>=5} onChange={e=>setComparison(v=>e.target.checked?[...v,item.voiceId]:v.filter(x=>x!==item.voiceId))}/> Сравнить</label>}{profile.voiceId===item.voiceId&&<span className="text-xs font-bold text-blue-700">Текущий выбор</span>}</div></article>;
 if(!catalog.length)return <section className="mt-5 rounded-2xl border bg-white p-5">Voice Catalog загружается… {message}</section>;
 return <section className="mt-5 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-black">Голос и произношение</h3><button disabled={!canManage} onClick={()=>void refreshCatalog()} className="rounded border px-3 py-2 text-sm disabled:opacity-40">Обновить каталог голосов</button></div><p className="text-sm text-slate-500">Preview изолирован от voice sessions и published version. Качество произношения зависит от языка и определяется пользователем на слух.</p><p className="mt-1 text-xs text-slate-500">Последняя проверка каталога: {lastVerifiedAt?new Date(lastVerifiedAt).toLocaleString('ru-RU'):'не выполнялась'}</p>
  <div className="mt-3 rounded-xl bg-slate-50 p-3"><textarea maxLength={300} className="w-full rounded border p-2 text-sm" value={testText} onChange={e=>setTestText(e.target.value)}/><div className="mt-2 flex gap-2"><button className="rounded border px-2 py-1 text-xs" onClick={()=>setTestText(texts.primary)}>Текст по умолчанию</button><button className="rounded border px-2 py-1 text-xs" onClick={()=>setTestText(texts.additional)}>Дополнительный текст</button></div></div>
  <div className="mt-3 flex flex-wrap gap-2"><button className="rounded border px-3 py-2 text-sm" onClick={()=>setBlind(false)}>Каталог</button><button className="rounded border px-3 py-2 text-sm" onClick={()=>{setBlind(true);setBlindChoice(null)}}>Сравнение голосов</button>{!blind&&<>{expertMode&&<select className="rounded border p-2 text-sm" value={providerFilter} onChange={e=>setProviderFilter(e.target.value)}><option value="all">Все голосовые сервисы</option>{providers.map(v=><option key={v}>{v}</option>)}</select>}<select className="rounded border p-2 text-sm" value={availability} onChange={e=>setAvailability(e.target.value)}><option value="active">Доступные</option><option value="unavailable">Недоступные</option><option value="all">Все</option></select><label className="rounded border p-2 text-sm"><input type="checkbox" checked={newOnly} onChange={e=>setNewOnly(e.target.checked)}/> Новые</label>{expertMode&&genders.length>0&&<select className="rounded border p-2 text-sm" value={genderFilter} onChange={e=>setGenderFilter(e.target.value)}><option value="all">Любой тип голоса</option>{genders.map(v=><option key={v}>{v}</option>)}</select>}<span className="rounded border p-2 text-sm">Язык: {profile.locale}</span><button disabled={comparison.length<2} onClick={()=>void compare()} className="rounded bg-blue-600 px-3 py-2 text-sm text-white disabled:opacity-40">Сравнить ({comparison.length})</button></>}</div>
  <div className="mt-4 grid gap-3 md:grid-cols-3">{blind?blindVoices.map((id,i)=>renderCard(catalog.find(x=>x.voiceId===id),`Вариант ${blindLabels[i]}`,true)):visible.map(item=>renderCard(item))}</div>{blindChoice!==null&&<p className="mt-2 rounded bg-emerald-50 p-2 text-sm">Выбран вариант {blindLabels[blindChoice]}: <code>{blindVoices[blindChoice]}</code></p>}
  <div className="mt-5 grid gap-3 md:grid-cols-3"><label className="text-sm">Voice ID<input readOnly className="mt-1 w-full rounded border p-2" value={profile.voiceId}/></label><label className="text-sm">Язык<input className="mt-1 w-full rounded border p-2" value={profile.language} onChange={e=>setProfile({...profile,language:e.target.value})}/></label><label className="text-sm">Locale<input className="mt-1 w-full rounded border p-2" value={profile.locale} onChange={e=>setProfile({...profile,locale:e.target.value})}/></label><label className="text-sm">Темп<select className="mt-1 w-full rounded border p-2" value={profile.speakingRate} onChange={e=>setProfile({...profile,speakingRate:e.target.value})}><option value="slightly_fast">Немного быстрее</option><option value="normal">Обычный</option></select></label><label className="text-sm">Паузы<select className="mt-1 w-full rounded border p-2" value={profile.pauseStyle} onChange={e=>setProfile({...profile,pauseStyle:e.target.value})}><option value="short_natural">Короткие естественные</option><option value="natural">Естественные</option></select></label><label className="text-sm md:col-span-3">Инструкции произношения<textarea maxLength={1000} className="mt-1 w-full rounded border p-2" value={profile.pronunciationInstructions||''} onChange={e=>setProfile({...profile,pronunciationInstructions:e.target.value})}/></label></div>
  <div className="mt-4"><div className="flex justify-between"><b className="text-sm">Словарь произношения</b><button disabled={!canManage} onClick={()=>setEntries([...entries,{source:'',pronunciation:'',stress:'',aliases:[]}])} className="rounded border px-2 py-1 text-xs">Добавить</button></div>{entries.map((x,i)=><div key={i} className="mt-2 grid gap-2 md:grid-cols-3"><input className="rounded border p-2" placeholder="Написание" value={x.source} onChange={e=>setEntries(entries.map((v,j)=>j===i?{...v,source:e.target.value}:v))}/><input className="rounded border p-2" placeholder="Произношение" value={x.pronunciation} onChange={e=>setEntries(entries.map((v,j)=>j===i?{...v,pronunciation:e.target.value}:v))}/><input className="rounded border p-2" placeholder="Ударение" value={x.stress||''} onChange={e=>setEntries(entries.map((v,j)=>j===i?{...v,stress:e.target.value}:v))}/></div>)}</div>
  <div className="mt-4 flex flex-wrap gap-2"><button disabled={!canManage} onClick={()=>void createDraft()} className="rounded bg-blue-600 px-3 py-2 text-sm text-white disabled:opacity-40">Сохранить черновик</button>{expertMode&&<><button onClick={()=>void post(`/api/ai-platform/agents/${agentId}/voice-settings/preview`,body).then(setPreview).then(()=>setMessage('Проверка готова; опубликованная версия не изменена')).catch(e=>setMessage(e.message))} className="rounded border px-3 py-2 text-sm">Проверить настройки</button><button disabled={!draft} onClick={()=>void publish()} className="rounded border border-amber-500 px-3 py-2 text-sm">Опубликовать с подтверждением</button><button disabled={!published||!bindingId} onClick={()=>void previewBinding()} className="rounded border px-3 py-2 text-sm">Проверить подключение 205</button><button disabled={!controlledPreview?.ready} onClick={()=>void applyBinding()} className="rounded border border-red-500 px-3 py-2 text-sm">Применить к 205</button></>}</div>{message&&<p className="mt-2 text-sm">{message}</p>}
 </section>
}
