import React,{useEffect,useState}from'react';

export default function VoiceSettingsPanel({token,agentId,canManage}:{token:string;agentId:number;canManage:boolean}){
  const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
  const[options,setOptions]=useState<any>(null),[profile,setProfile]=useState<any>({voiceId:'marin',language:'ru',locale:'ru-RU',pronunciationStyle:'native_neutral',speakingRate:'slightly_fast',pauseStyle:'short_natural',expressiveness:'warm_moderate',pitchStyle:'neutral'}),[vad,setVad]=useState(350),[entries,setEntries]=useState<any[]>([]),[preview,setPreview]=useState<any>(null),[message,setMessage]=useState(''),[audioUrl,setAudioUrl]=useState('');
  useEffect(()=>{void Promise.all([
    fetch('/api/ai-platform/voice-profiles/options',{headers}).then(r=>r.json()),
    fetch(`/api/ai-platform/agents/${agentId}/voice-settings`,{headers}).then(r=>r.json()),
  ]).then(([o,s])=>{setOptions(o.data);if(s.data?.voiceProfile)setProfile(s.data.voiceProfile);setVad(Number(s.data?.endOfTurnSilenceMs||350));setEntries(s.data?.pronunciationEntries||[])}).catch(()=>setMessage('Не удалось загрузить настройки голоса'))},[agentId,token]);
  const post=async(path:string)=>{const r=await fetch(path,{method:'POST',headers,body:JSON.stringify({voiceProfile:profile,endOfTurnSilenceMs:vad,pronunciationEntries:entries})}),v=await r.json();if(!r.ok)throw new Error(v.error||'Ошибка');return v.data};
  const doPreview=async()=>{try{setPreview(await post(`/api/ai-platform/agents/${agentId}/voice-settings/preview`));setMessage('Preview готов; published version не изменена')}catch(e:any){setMessage(e.message)}};
  const draft=async()=>{try{const v=await post(`/api/ai-platform/agents/${agentId}/voice-settings/draft`);setMessage(`Создан immutable draft version ${v.versionNumber||v.version_number||v.id}`)}catch(e:any){setMessage(e.message)}};
  const listen=async()=>{try{setMessage('Готовится voice preview…');const r=await fetch('/api/ai-platform/voice-profiles/preview-audio',{method:'POST',headers,body:JSON.stringify({voiceProfile:profile})});if(!r.ok)throw new Error((await r.json()).error||'Voice preview unavailable');if(audioUrl)URL.revokeObjectURL(audioUrl);const url=URL.createObjectURL(await r.blob());setAudioUrl(url);new Audio(url).play();setMessage(`Прослушивается ${profile.voiceId}`)}catch(e:any){setMessage(e.message)}};
  const addEntry=()=>setEntries([...entries,{source:'',pronunciation:'',stress:'',aliases:[]}]);
  if(!options)return null;
  return <section className="mt-5 rounded-2xl border bg-white p-5"><h3 className="font-black">Голос и произношение</h3><p className="text-sm text-slate-500">Versioned Voice Profile · draft → preview → test → publish</p>
    <div className="mt-4 grid gap-3 md:grid-cols-3">
      <label className="text-sm">Голос<select className="mt-1 w-full rounded border p-2" value={profile.voiceId} onChange={e=>setProfile({...profile,voiceId:e.target.value})}>{options.voices.map((v:string)=><option key={v}>{v}</option>)}</select></label>
      <label className="text-sm">Язык<input className="mt-1 w-full rounded border p-2" value={profile.locale} onChange={e=>setProfile({...profile,locale:e.target.value})}/></label>
      <label className="text-sm">Произношение<select className="mt-1 w-full rounded border p-2" value={profile.pronunciationStyle} onChange={e=>setProfile({...profile,pronunciationStyle:e.target.value})}><option value="native_neutral">Нейтральное русское</option><option value="neutral">Нейтральное</option><option value="custom">По словарю</option></select></label>
      <label className="text-sm">Скорость<select className="mt-1 w-full rounded border p-2" value={profile.speakingRate} onChange={e=>setProfile({...profile,speakingRate:e.target.value})}><option value="slightly_fast">Немного быстрее</option><option value="normal">Обычная</option></select></label>
      <label className="text-sm">Паузы<select className="mt-1 w-full rounded border p-2" value={profile.pauseStyle} onChange={e=>setProfile({...profile,pauseStyle:e.target.value})}><option value="short_natural">Короткие естественные</option><option value="natural">Естественные</option></select></label>
      <label className="text-sm">Выразительность<select className="mt-1 w-full rounded border p-2" value={profile.expressiveness} onChange={e=>setProfile({...profile,expressiveness:e.target.value})}><option value="warm_moderate">Тёплая умеренная</option><option value="neutral">Нейтральная</option></select></label>
      <label className="text-sm">End-of-turn sensitivity<select className="mt-1 w-full rounded border p-2" value={vad} onChange={e=>setVad(Number(e.target.value))}><option value={300}>300 ms</option><option value={350}>350 ms</option><option value={400}>400 ms</option></select></label>
    </div>
    <div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm"><b>Тестовая фраза:</b> {options.testPhrase}<div className="mt-2 text-xs text-slate-500">Сравните голоса в controlled preview на одной фразе. Технические метрики не оценивают акцент автоматически.</div></div>
    <div className="mt-4"><div className="flex items-center justify-between"><b className="text-sm">Словарь произношения</b><button disabled={!canManage} className="rounded border px-2 py-1 text-xs" onClick={addEntry}>Добавить</button></div>{entries.map((item,i)=><div key={i} className="mt-2 grid gap-2 md:grid-cols-4"><input className="rounded border p-2 text-sm" placeholder="Написание" value={item.source} onChange={e=>setEntries(entries.map((x,j)=>j===i?{...x,source:e.target.value}:x))}/><input className="rounded border p-2 text-sm" placeholder="Произношение" value={item.pronunciation} onChange={e=>setEntries(entries.map((x,j)=>j===i?{...x,pronunciation:e.target.value}:x))}/><input className="rounded border p-2 text-sm" placeholder="Ударение" value={item.stress||''} onChange={e=>setEntries(entries.map((x,j)=>j===i?{...x,stress:e.target.value}:x))}/><input className="rounded border p-2 text-sm" placeholder="Aliases через запятую" value={(item.aliases||[]).join(', ')} onChange={e=>setEntries(entries.map((x,j)=>j===i?{...x,aliases:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)}:x))}/></div>)}</div>
    <div className="mt-4 flex gap-2"><button disabled={!canManage} onClick={()=>void listen()} className="rounded border px-3 py-2 text-sm">Прослушать</button><button disabled={!canManage} onClick={()=>void doPreview()} className="rounded border px-3 py-2 text-sm">Preview и оценка latency</button><button disabled={!canManage||!preview} onClick={()=>void draft()} className="rounded bg-blue-600 px-3 py-2 text-sm text-white">Сохранить в draft</button></div>
    {preview&&<p className="mt-2 text-xs">VAD {preview.latencyEstimate.vadMs} ms · startup {preview.latencyEstimate.startupBufferMs} ms · provider-dependent</p>}{message&&<p className="mt-2 text-sm">{message}</p>}
  </section>
}
