import type { Express, Request, Response } from 'express';
import { GsmGatewayService } from './service.js';

export function registerGsmGatewayRoutes(app:Express,deps:{requireAuth:any;checkPermission:(req:Request,p:string)=>Promise<boolean>;hashSecret:string}){
 const service=new GsmGatewayService(deps.hashSecret),guard=(p:string)=>(handler:(req:Request,res:Response)=>Promise<any>)=>async(req:Request,res:Response)=>{if(!(await deps.checkPermission(req,p)))return res.status(403).json({error:`Access denied: ${p} permission required`});try{return await handler(req,res)}catch(error:any){const code=String(error?.message||'gsm_gateway_failed').slice(0,64),bad=/invalid|required|not_found|expired/.test(code);return res.status(bad?400:503).json({success:false,safeErrorCode:code})}};
 app.get('/api/gsm-gateways',deps.requireAuth(),guard('view_gsm_gateways')(async(_req,res)=>res.json({success:true,gateways:await service.settings()})));
 app.put('/api/gsm-gateways/settings',deps.requireAuth(),guard('manage_gsm_gateways')(async(req,res)=>res.json({success:true,id:await service.save(req.body||{})})));
 app.post('/api/gsm-gateways/:id/ami/test',deps.requireAuth(),guard('manage_gsm_gateways')(async(req,res)=>res.json(await service.testAmi(Number(req.params.id)))));
 app.get('/api/gsm-gateways/:id/status',deps.requireAuth(),guard('view_gsm_gateways')(async(req,res)=>{const id=Number(req.params.id),status=await service.status(id);await service.recordStatusMetrics(id,status);return res.json({success:true,...status})}));
 app.get('/api/gsm-gateways/:id/metrics/:port',deps.requireAuth(),guard('view_gsm_gateways')(async(req,res)=>res.json({success:true,...await service.metricsHistory(Number(req.params.id),String(req.params.port))})));
 app.get('/api/gsm-gateways/:id/history',deps.requireAuth(),guard('view_gsm_gateways')(async(req,res)=>res.json({success:true,items:await service.history(Number(req.params.id))})));
 app.get('/api/gsm-gateways/:id/sms/:box',deps.requireAuth(),guard('view_gsm_sms')(async(req,res)=>{const box=req.params.box==='outbox'?'outbox':'inbox';return res.json({success:true,...await service.smsHistory(Number(req.params.id),box,req.query)})}));
 app.post('/api/gsm-gateways/:id/sms/preview',deps.requireAuth(),guard('send_gsm_sms')(async(req,res)=>res.json({success:true,preview:await service.preview(Number(req.params.id),'sms',req.body||{},String((req as any).user?.username||'unknown'))})));
 app.get('/api/gsm-gateways/:id/ussd/presets',deps.requireAuth(),guard('manage_gsm_services')(async(req,res)=>res.json({success:true,items:await service.ussdPresets(Number(req.params.id))})));
 app.put('/api/gsm-gateways/:id/ussd/presets',deps.requireAuth(),guard('manage_gsm_services')(async(req,res)=>res.json({success:true,id:await service.saveUssdPreset(Number(req.params.id),req.body||{}),items:await service.ussdPresets(Number(req.params.id))})));
 app.get('/api/gsm-gateways/:id/ussd/history',deps.requireAuth(),guard('manage_gsm_services')(async(req,res)=>res.json({success:true,items:await service.ussdHistory(Number(req.params.id))})));
 app.post('/api/gsm-gateways/:id/ussd/preview',deps.requireAuth(),guard('manage_gsm_services')(async(req,res)=>res.json({success:true,preview:await service.preview(Number(req.params.id),'ussd',req.body||{},String((req as any).user?.username||'unknown'))})));
 app.post('/api/gsm-gateways/operations/:id/apply',deps.requireAuth(),async(req,res)=>{try{const id=Number(req.params.id),type=await service.operationType(id),permission=type==='sms'?'send_gsm_sms':'manage_gsm_services';if(!await deps.checkPermission(req,permission))return res.status(403).json({error:`Access denied: ${permission} permission required`});return res.json(await service.apply(id,String((req as any).user?.username||'unknown')))}catch(error:any){const code=String(error?.message||'gsm_gateway_failed').slice(0,64);return res.status(/invalid|required|not_found|expired/.test(code)?400:503).json({success:false,safeErrorCode:code})}});
 app.get('/api/gsm-gateways/:id/balances',deps.requireAuth(),guard('view_gsm_balances')(async(req,res)=>res.json({success:true,...await service.balances(Number(req.params.id),req.query.days)})));
 app.put('/api/gsm-gateways/:id/balance-settings',deps.requireAuth(),guard('manage_gsm_balances')(async(req,res)=>res.json({success:true,settings:await service.saveBalanceSettings(Number(req.params.id),req.body||{})})));
 app.post('/api/gsm-gateways/:id/balances/:port/refresh',deps.requireAuth(),guard('manage_gsm_balances')(async(req,res)=>res.json({success:true,item:await service.refreshBalance(Number(req.params.id),String(req.params.port),req.body?.code)})));
 return{start:()=>service.start(),stop:()=>service.stop(),notificationSnapshot:()=>service.notificationSnapshot()};
}
