import { AiPlatformError } from '../../core/errors.js';
import { parseJsonObject, redactAiPlatformValue } from '../../core/redaction.js';
import type { AiAuditService } from '../../audit/aiAuditService.js';
import type { LifecycleActor } from '../../agents/agentLifecycleService.js';
import type { AiPlatformStore } from '../../storage/aiPlatformStore.js';
import { insertId } from '../../storage/aiPlatformStore.js';
import { knowledgeChecksum, validateKnowledgeContent, validateKnowledgeType } from '../validation/knowledgeValidation.js';

const safeKey=(value:unknown)=>{const key=String(value||'').trim();if(!/^[a-z][a-z0-9_-]{2,99}$/.test(key))throw new AiPlatformError('invalid_request',400,'Invalid knowledge source key');return key};
const safeText=(value:unknown,field:string,max:number)=>{const text=String(value||'').trim();if(!text||text.length>max)throw new AiPlatformError('invalid_request',400,`Invalid ${field}`);return text};
export class KnowledgeService {
  constructor(private readonly store:AiPlatformStore,private readonly audit:AiAuditService){}
  async createSource(tenantId:number,input:{agentId?:number|null;sourceKey:unknown;name:unknown;type:unknown;description?:unknown;metadata?:unknown},actor:LifecycleActor){if(input.agentId){const agent=await this.store.query('SELECT id FROM ai_agents WHERE id=? AND tenant_id=? LIMIT 1',[input.agentId,tenantId]);if(!agent.length)throw new AiPlatformError('not_found',404,'Agent not found')}const metadata=parseJsonObject(input.metadata||{},'metadata');if(redactAiPlatformValue(metadata).stats.secrets>0)throw new AiPlatformError('invalid_request',400,'Secrets are not allowed in knowledge metadata');const result:any=await this.store.query(`INSERT INTO ai_knowledge_sources (tenant_id,agent_id,source_key,name,type,description,status,metadata_json,created_by) VALUES (?,?,?,?,?,?,?,?,?)`,[tenantId,input.agentId||null,safeKey(input.sourceKey),safeText(input.name,'name',191),validateKnowledgeType(input.type),String(input.description||'').slice(0,1000),'draft',JSON.stringify(metadata),actor.actorId]);const id=insertId(result);if(input.agentId)await this.store.query("INSERT INTO ai_agent_knowledge (tenant_id,agent_id,knowledge_source_id,access_mode) VALUES (?,?,?,'read')",[tenantId,input.agentId,id]);await this.audit.append({tenantId,...actor,eventType:'knowledge_source_created',entityType:'knowledge_source',entityId:String(id),decision:'created',details:{sourceKey:input.sourceKey,agentId:input.agentId||null}});return{id,status:'draft'}}
  async createVersion(tenantId:number,sourceId:number,input:{content:unknown},actor:LifecycleActor){const sources=await this.store.query('SELECT id,status FROM ai_knowledge_sources WHERE id=? AND tenant_id=? LIMIT 1',[sourceId,tenantId]);if(!sources.length)throw new AiPlatformError('not_found',404,'Knowledge source not found');if(sources[0].status==='archived')throw new AiPlatformError('conflict',409,'Knowledge source is archived');const content=validateKnowledgeContent(input.content);const rows=await this.store.query('SELECT COALESCE(MAX(version_number),0)+1 next_version FROM ai_knowledge_versions WHERE source_id=?',[sourceId]);const version=Number(rows[0]?.next_version||1),checksum=knowledgeChecksum(content);const result:any=await this.store.query(`INSERT INTO ai_knowledge_versions (tenant_id,source_id,version_number,content,checksum,status,created_by) VALUES (?,?,?,?,?,'draft',?)`,[tenantId,sourceId,version,content,checksum,actor.actorId]);const id=insertId(result);await this.audit.append({tenantId,...actor,eventType:'knowledge_version_created',entityType:'knowledge_version',entityId:String(id),decision:'created',details:{sourceId,version}});return{id,version,status:'draft',checksum}}
  async publishVersion(tenantId:number,sourceId:number,versionId:number|undefined,actor:LifecycleActor){const rows=await this.store.query(`SELECT id,content,checksum,status FROM ai_knowledge_versions WHERE source_id=? AND tenant_id=? ${versionId?'AND id=?':'ORDER BY version_number DESC'} LIMIT 1`,versionId?[sourceId,tenantId,versionId]:[sourceId,tenantId]);const row=rows[0];if(!row)throw new AiPlatformError('not_found',404,'Knowledge version not found');if(row.status!=='draft')throw new AiPlatformError('conflict',409,'Published knowledge versions are immutable');const validation=this.validateKnowledge(row.content,row.checksum);if(!validation.valid){await this.audit.append({tenantId,...actor,eventType:'validation_failed',entityType:'knowledge_version',entityId:String(row.id),decision:'denied',details:{errors:validation.errors}});throw new AiPlatformError('invalid_request',400,`Invalid knowledge: ${validation.errors.join(', ')}`)}await this.store.query("UPDATE ai_knowledge_versions SET status='published',published_at=NOW() WHERE id=? AND tenant_id=? AND status='draft'",[row.id,tenantId]);await this.store.query("UPDATE ai_knowledge_sources SET status='published',updated_at=NOW() WHERE id=? AND tenant_id=?",[sourceId,tenantId]);await this.audit.append({tenantId,...actor,eventType:'knowledge_version_published',entityType:'knowledge_version',entityId:String(row.id),decision:'published',details:{sourceId}});return{id:Number(row.id),status:'published'}}
  async archiveVersion(tenantId:number,sourceId:number,actor:LifecycleActor){const result:any=await this.store.query("UPDATE ai_knowledge_sources SET status='archived',updated_at=NOW() WHERE id=? AND tenant_id=? AND status<>'archived'",[sourceId,tenantId]);if(!Number(result?.affectedRows||0))throw new AiPlatformError('not_found',404,'Knowledge source not found');await this.audit.append({tenantId,...actor,eventType:'knowledge_archived',entityType:'knowledge_source',entityId:String(sourceId),decision:'archived'});return{status:'archived'}}
  validateKnowledge(content:unknown,checksum:unknown){const errors:string[]=[];let normalized='';try{normalized=validateKnowledgeContent(content)}catch(error:any){errors.push(error?.message||'invalid_content')}if(normalized&&knowledgeChecksum(normalized)!==String(checksum||''))errors.push('checksum_mismatch');return{valid:errors.length===0,errors}}
}
