import crypto from 'crypto';
import { AiPlatformError } from '../../core/errors.js';
import { parseJsonObject } from '../../core/redaction.js';
import type { AiAuditService } from '../../audit/aiAuditService.js';
import type { LifecycleActor } from '../../agents/agentLifecycleService.js';
import type { AiPlatformStore } from '../../storage/aiPlatformStore.js';
import { insertId } from '../../storage/aiPlatformStore.js';
import { validateTrainingItem } from '../validation/trainingValidation.js';
export class TrainingService {
  constructor(private readonly store:AiPlatformStore,private readonly audit:AiAuditService){}
  async createTrainingItem(tenantId:number,input:{agentId:number;type:unknown;title:unknown;inputText:unknown;expectedOutput:unknown;rule?:unknown},actor:LifecycleActor){const agent=await this.store.query('SELECT id FROM ai_agents WHERE id=? AND tenant_id=? LIMIT 1',[input.agentId,tenantId]);if(!agent.length)throw new AiPlatformError('not_found',404,'Agent not found');const valid=validateTrainingItem(input),rule=parseJsonObject(input.rule||{},'rule');const title=String(input.title||'').trim();if(!title||title.length>191)throw new AiPlatformError('invalid_request',400,'Invalid training title');const result:any=await this.store.query(`INSERT INTO ai_training_items (tenant_id,agent_id,type,title,input_text,expected_output,rule_json,status,created_by) VALUES (?,?,?,?,?,?,?,'draft',?)`,[tenantId,input.agentId,valid.type,title,valid.inputText,valid.expectedOutput,JSON.stringify(rule),actor.actorId]);const id=insertId(result);await this.audit.append({tenantId,...actor,eventType:'training_item_created',entityType:'training_item',entityId:String(id),decision:'created',details:{agentId:input.agentId,type:valid.type}});return{id,status:'draft'}}
  async createTrainingVersion(tenantId:number,agentId:number,actor:LifecycleActor){const agent=await this.store.query('SELECT id FROM ai_agents WHERE id=? AND tenant_id=? LIMIT 1',[agentId,tenantId]);if(!agent.length)throw new AiPlatformError('not_found',404,'Agent not found');const items=await this.store.query("SELECT id,type,title,input_text,expected_output,rule_json FROM ai_training_items WHERE tenant_id=? AND agent_id=? AND status<>'archived' ORDER BY id",[tenantId,agentId]);if(!items.length)throw new AiPlatformError('invalid_request',400,'Training items are required');const snapshot=items.map(row=>({...row,rule:parseJsonObject(row.rule_json,'rule_json'),rule_json:undefined}));const json=JSON.stringify(snapshot),checksum=crypto.createHash('sha256').update(json).digest('hex');const versions=await this.store.query('SELECT COALESCE(MAX(version_number),0)+1 next_version FROM ai_training_versions WHERE agent_id=?',[agentId]);const version=Number(versions[0]?.next_version||1);const result:any=await this.store.query(`INSERT INTO ai_training_versions (tenant_id,agent_id,version_number,training_snapshot_json,checksum,status) VALUES (?,?,?,?,?,'draft')`,[tenantId,agentId,version,json,checksum]);const id=insertId(result);await this.audit.append({tenantId,...actor,eventType:'training_version_created',entityType:'training_version',entityId:String(id),decision:'created',details:{agentId,version,itemCount:items.length}});return{id,version,status:'draft',checksum}}
  async publishTraining(tenantId:number,agentId:number,versionId:number|undefined,actor:LifecycleActor){const rows=await this.store.query(`SELECT id,training_snapshot_json,checksum,status FROM ai_training_versions WHERE tenant_id=? AND agent_id=? ${versionId?'AND id=?':'ORDER BY version_number DESC'} LIMIT 1`,versionId?[tenantId,agentId,versionId]:[tenantId,agentId]);const row=rows[0];if(!row)throw new AiPlatformError('not_found',404,'Training version not found');if(row.status!=='draft')throw new AiPlatformError('conflict',409,'Published training versions are immutable');const validation=this.validateTraining(row.training_snapshot_json,row.checksum);if(!validation.valid){await this.audit.append({tenantId,...actor,eventType:'validation_failed',entityType:'training_version',entityId:String(row.id),decision:'denied',details:{errors:validation.errors}});throw new AiPlatformError('invalid_request',400,'Invalid training snapshot')}await this.store.query("UPDATE ai_training_versions SET status='published',published_at=NOW() WHERE id=? AND tenant_id=? AND status='draft'",[row.id,tenantId]);await this.store.query("UPDATE ai_training_items SET status='published' WHERE tenant_id=? AND agent_id=? AND status='draft'",[tenantId,agentId]);await this.audit.append({tenantId,...actor,eventType:'training_version_published',entityType:'training_version',entityId:String(row.id),decision:'published',details:{agentId}});return{id:Number(row.id),status:'published'}}
  validateTraining(snapshot:unknown,checksum:unknown){const errors:string[]=[];let json='';try{const value=typeof snapshot==='string'?JSON.parse(snapshot):snapshot;if(!Array.isArray(value)||!value.length)errors.push('empty_snapshot');json=JSON.stringify(value)}catch{errors.push('invalid_snapshot')}if(json&&crypto.createHash('sha256').update(json).digest('hex')!==String(checksum||''))errors.push('checksum_mismatch');return{valid:errors.length===0,errors}}
}
