import crypto from"node:crypto";import{execFile}from"node:child_process";import{promisify}from"node:util";import path from"node:path";import type{AiPlatformStore}from"../storage/aiPlatformStore.js";import type{AiAuditService}from"../audit/aiAuditService.js";import{AiPlatformError}from"../core/errors.js";
const run=promisify(execFile),helper=path.join(process.cwd(),"scripts","freepbx-ai-handoff.php"),types=new Set(["extension","queue","ring_group","ivr","custom_destination","external_allowed","ai_extension"]);
const cleanText=(v:unknown,n=500)=>String(v||"").replace(/[<>]/g,"").trim().slice(0,n);
export class HandoffConfigService{
 constructor(private store:AiPlatformStore,private audit:AiAuditService){}
 private async command(args:string[]){try{const{stdout}=await run("php",[helper,...args],{timeout:15000,maxBuffer:512*1024});return JSON.parse(String(stdout||"{}"))}catch(e:any){let code="handoff_adapter_failed";try{code=JSON.parse(String(e?.stdout||"{}")).code||code}catch{}throw new AiPlatformError("conflict",409,code)}}
 async destinations(){const result=await this.command(["list"]);return result.rows||[]}
 async inspect(type:string,ref:string){if(!types.has(type)||!/^[A-Za-z0-9_.:+-]{1,100}$/.test(ref))throw new AiPlatformError("invalid_request",400,"Invalid handoff destination");return this.command(["inspect",type,ref])}
 async activeForAgent(tenantId:number,agentId:number,versionId:number){return(await this.store.query("SELECT * FROM ai_handoff_configs WHERE tenant_id=? AND agent_id=? AND agent_version_id=? AND status='active' AND enabled=1 LIMIT 1",[tenantId,agentId,versionId]))[0]||null}
 async preview(tenantId:number,input:any,actor:any){
  const key=String(input.idempotencyKey||"");if(!/^[A-Za-z0-9_.:-]{8,100}$/.test(key))throw new AiPlatformError("invalid_request",400,"Valid idempotencyKey required");
  const old=(await this.store.query("SELECT id,preview_json,status FROM ai_handoff_previews WHERE tenant_id=? AND idempotency_key=? LIMIT 1",[tenantId,key]))[0];if(old)return{previewId:Number(old.id),...JSON.parse(old.preview_json),idempotent:true};
  const aiExtensionId=Number(input.aiExtensionId),ext=(await this.store.query("SELECT e.*,v.version_number FROM ai_extensions e JOIN ai_agent_versions v ON v.id=e.published_agent_version_id WHERE e.tenant_id=? AND e.id=? AND e.status='active' AND e.enabled=1 LIMIT 1",[tenantId,aiExtensionId]))[0];if(!ext)throw new AiPlatformError("conflict",409,"Active AI Extension required");
  const type=String(input.primaryDestinationType||""),ref=String(input.primaryDestinationId||"");if(!types.has(type))throw new AiPlatformError("invalid_request",400,"Invalid destination type");
  const callerTestExtension=String(input.callerTestExtension||"");if(!/^[0-9]{2,8}$/.test(callerTestExtension))throw new AiPlatformError("invalid_request",400,"Controlled caller extension required");
  const checkedCaller=await this.inspect("extension",callerTestExtension);if(!checkedCaller.available)throw new AiPlatformError("conflict",409,"Controlled caller extension unavailable");
  if(type==="ai_extension"){const other=(await this.store.query("SELECT id,extension FROM ai_extensions WHERE tenant_id=? AND id=? AND status='active' AND enabled=1",[tenantId,Number(ref)]))[0];if(!other||Number(other.id)===aiExtensionId)throw new AiPlatformError("conflict",409,"AI Extension cycle detected")}
  const checked=type==="ai_extension"?{available:true,destination:{type,ref,name:"AI Extension",target:null}}:await this.inspect(type,ref);if(!checked.available)throw new AiPlatformError("conflict",409,"Handoff destination unavailable");
  if(String(checked.destination?.target||"")===`pbxpuls-ai,${ext.extension},1`)throw new AiPlatformError("conflict",409,"Handoff destination points back to the same AI Extension");
  const timeout=Math.max(5,Math.min(Number(input.answerTimeoutSeconds)||20,120)),token=`handoff-${crypto.createHash("sha256").update(`${tenantId}:${aiExtensionId}`).digest("hex").slice(0,12)}`,existing=(await this.store.query("SELECT id FROM ai_handoff_configs WHERE tenant_id=? AND ai_extension_id=? LIMIT 1",[tenantId,aiExtensionId]))[0];
  const policy=(value:unknown)=>["return_to_ai","backup","callback","announce_hangup"].includes(String(value))?String(value):"return_to_ai";
  const noAnswer=policy(input.onNoAnswer),onBusy=policy(input.onBusy),onCongestion=policy(input.onCongestion),destinationSafe=cleanText(input.primaryDestinationDisplayName||(type==="extension"?`Extension ${ref}`:checked.destination.name||checked.destination.safeLabel||ref),191);
  const values=[type,ref,destinationSafe,timeout,noAnswer,onBusy,onCongestion,input.offerBeforeTransfer!==false,input.confirmationRequired!==false,cleanText(input.announcementTemplate||"Хорошо, соединяю вас с сотрудником."),cleanText(input.unavailableTemplate||"Сотрудник сейчас не ответил. Чем ещё могу помочь?"),JSON.stringify(Array.isArray(input.intentPhrases)?input.intentPhrases.slice(0,50):["соедините с оператором","переведите на сотрудника","позовите человека","хочу поговорить с живым человеком"])];
  let configId:number;if(existing){configId=Number(existing.id);await this.store.query("UPDATE ai_handoff_configs SET primary_destination_type=?,primary_destination_ref=?,primary_destination_safe=?,answer_timeout_seconds=?,on_no_answer=?,on_busy=?,on_congestion=?,offer_before_transfer=?,confirmation_required=?,announcement_template=?,unavailable_template=?,intent_phrases_json=?,status='preview_ready',enabled=0,sync_status='previewed',sync_error_code=NULL,updated_at=NOW() WHERE tenant_id=? AND id=?",[...values,tenantId,configId])}else{const r:any=await this.store.query("INSERT INTO ai_handoff_configs(tenant_id,ai_extension_id,agent_id,agent_version_id,primary_destination_type,primary_destination_ref,primary_destination_safe,answer_timeout_seconds,on_no_answer,on_busy,on_congestion,offer_before_transfer,confirmation_required,announcement_template,unavailable_template,intent_phrases_json,dialplan_token,status,created_by,sync_status)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'preview_ready',?,'previewed')",[tenantId,aiExtensionId,ext.agent_id,ext.published_agent_version_id,...values,token,actor.actorId]);configId=Number(r.insertId)}
  const preview={ready:true,applied:false,productionAffected:false,dialplanAffected:true,automaticCall:false,aiExtension:{id:aiExtensionId,extension:ext.extension},callerTest:{extension:callerTestExtension,name:`Extension ${callerTestExtension}`,exists:true,active:true,role:"caller_only",changed:false},agent:{id:Number(ext.agent_id),versionId:Number(ext.published_agent_version_id),versionNumber:Number(ext.version_number),voice:"marin"},destination:{type,ref,name:destinationSafe,target:checked.destination.target,exists:true,active:true,cycleDetected:false},timeoutSeconds:timeout,confirmationRequired:Boolean(input.confirmationRequired!==false),announcement:values[9],policies:{noAnswer,onBusy,onCongestion,channelUnavailable:onCongestion,backupDestination:null},ariPlan:{operation:"continueInDialplan",callerChannelPreserved:true,callerIndependentOfDestination:true,context:"pbxpuls-ai-handoff",extension:token},cleanupPlan:{providerSession:"close_before_continue",mediaSession:"close_before_continue",providerAudioAfterAnswer:false},coordinatorPlan:{closingCoordinatorMutualExclusion:true,transferRequestsMax:1},privacy:{afterAnswer:"AI detached; no provider audio or transcript"},dialplan:{context:"pbxpuls-ai-handoff",targetContext:"pbxpuls-ai-handoff-target",token,atomicWrite:true,preserveOtherContexts:true,diff:[`[pbxpuls-ai-handoff] ${token} -> Dial(Local/${token}@pbxpuls-ai-handoff-target/n,${timeout})`,`[pbxpuls-ai-handoff-target] ${token} -> Goto(${checked.destination.target})`]},verification:["Extension 299 exists and is active","Extension 200 exists and remains caller-only","destination differs from AI Extension 205","no cycle to AI Extension","caller channel preserved by ARI continueInDialplan","provider/media closed before continue","return statuses reuse caller without greeting","binding unchanged"],rollback:{dialplanFile:"restore atomic pre-apply content",config:"sync_failed",aiExtension:"unchanged",binding:"unchanged",productionRoutes:"unchanged"}};
  const r:any=await this.store.query("INSERT INTO ai_handoff_previews(tenant_id,config_id,idempotency_key,preview_json,status,created_by,expires_at)VALUES(?,?,?,?, 'ready',?,DATE_ADD(NOW(),INTERVAL 30 MINUTE))",[tenantId,configId,key,JSON.stringify(preview),actor.actorId]);await this.audit.append({tenantId,...actor,eventType:"human_transfer_ready",entityType:"ai_handoff_config",entityId:String(configId),decision:"preview_ready",details:{destinationType:type,productionAffected:false}});return{previewId:Number(r.insertId),configId,...preview}
 }
 async apply(tenantId:number,previewId:number,confirm:boolean,actor:any){
  if(!confirm)throw new AiPlatformError("invalid_request",400,"Explicit confirmation required");const p=(await this.store.query("SELECT * FROM ai_handoff_previews WHERE tenant_id=? AND id=? LIMIT 1",[tenantId,previewId]))[0];if(!p)throw new AiPlatformError("not_found",404,"Preview not found");if(p.status==="applied")return{...JSON.parse(p.preview_json),applied:true,idempotent:true};if(p.status!=="ready"||new Date(p.expires_at).getTime()<=Date.now())throw new AiPlatformError("conflict",409,"Preview expired");
  const c=(await this.store.query("SELECT * FROM ai_handoff_configs WHERE tenant_id=? AND id=?",[tenantId,p.config_id]))[0],preview=JSON.parse(p.preview_json);try{await this.store.query("UPDATE ai_handoff_configs SET status='applying',sync_status='applying' WHERE id=?",[c.id]);await this.command(["apply",c.dialplan_token,c.primary_destination_type,c.primary_destination_ref,String(c.answer_timeout_seconds)]);await this.store.query("UPDATE ai_handoff_configs SET status='verifying',sync_status='verifying' WHERE id=?",[c.id]);await run("fwconsole",["reload"],{timeout:120000});const{stdout}=await run("asterisk",["-rx",`dialplan show ${c.dialplan_token}@pbxpuls-ai-handoff`],{timeout:10000});if(!String(stdout).includes("Dial(Local/")||!String(stdout).includes("Stasis(pbxpuls-ai-control,handoff_return:"))throw new Error("HANDOFF_DIALPLAN_NOT_LOADED");await this.store.query("UPDATE ai_handoff_configs SET status='active',enabled=1,sync_status='synced',sync_error_code=NULL,last_synced_at=NOW() WHERE id=?",[c.id]);await this.store.query("UPDATE ai_handoff_previews SET status='applied',applied_at=NOW() WHERE id=?",[previewId]);return{...preview,applied:true,verified:true}}catch(e:any){await this.store.query("UPDATE ai_handoff_configs SET status='sync_failed',enabled=0,sync_status='failed',sync_error_code=?,last_synced_at=NULL WHERE id=?",[cleanText(e?.message||"HANDOFF_APPLY_FAILED",64).replace(/[^A-Za-z0-9_.-]/g,"_"),c.id]);throw new AiPlatformError("conflict",409,"Handoff apply failed")}
 }
 async history(tenantId:number){return this.store.query("SELECT id,voice_session_id voiceSessionId,state,destination_type destinationType,destination_ref_safe destination,requested_at requestedAt,announcement_finished_at announcementFinishedAt,dialing_at dialingAt,answered_at answeredAt,ended_at endedAt,dial_status dialStatus,failure_cause failureCause,outcome FROM ai_handoff_events WHERE tenant_id=? ORDER BY id DESC LIMIT 100",[tenantId])}
}
