import type{AiPlatformStore}from'../../storage/aiPlatformStore.js';import type{AiAuditService}from'../../audit/aiAuditService.js';import{AiPlatformError}from'../../core/errors.js';import{voiceHash}from'../voiceEncryption.js';import type{AriConnectionManager}from'../ari/ariConnectionManager.js';import{VoiceEncryptionService}from'../voiceEncryption.js';import{readAudioSocketServerConfig}from'../media/transports/audioSocketAdapter.js';import{readOpenAIRealtimeConfig}from'../providers/adapters/openaiRealtimeAdapter.js';import{readAriConfig}from'../ari/ariTypes.js';import{buildVoiceRouteDialplanPreview}from'./voiceRouteDialplan.js';
const sourceTypes=new Set(['extension','did','inbound_route','queue_overflow','after_hours']),fallbackTypes=new Set(['extension','queue','ring_group','receptionist','terminate_call']);
const safeLabel=(value:string)=>value?`${'*'.repeat(Math.max(2,value.length-2))}${value.slice(-2)}`:'—';
export class VoiceAgentRouteService{constructor(private store:AiPlatformStore,private audit:AiAuditService,private manager:AriConnectionManager){}
 async readiness(tenantId:number){const ari=readAriConfig(),audio=readAudioSocketServerConfig(),provider=readOpenAIRealtimeConfig(),applications=this.manager.status().state==='connected'?await (async()=>true)():false;const items=[['ari',this.manager.status().state==='connected','ari_unavailable'],['stasis',ari.configured&&applications,'stasis_unavailable'],['audioSocket',audio.port>0,'live_media_not_configured'],['providerConfigured',provider.configured,'provider_not_configured'],['providerHealth',provider.configured,'provider_not_ready'],['encryption',new VoiceEncryptionService().ready(),'encryption_not_configured']]as const;return{ready:items.every(x=>x[1]),items:items.map(([key,ready,code])=>({key,ready,code:ready?null:code}))}}
 async agents(tenantId:number){const readiness=await this.readiness(tenantId),rows=await this.store.query(`SELECT a.id,a.name,a.agent_type,a.status,av.id version_id,av.version_number,av.lifecycle_status,av.config_json published_config_json,av.published_at,
   dv.id draft_version_id,dv.version_number draft_version_number,dv.config_json draft_config_json,
   COUNT(DISTINCT b.id) binding_count,SUM(v.state NOT IN('completed','failed','cancelled')) active_calls,MAX(v.failure_code) last_error,
   (SELECT GROUP_CONCAT(CONCAT(e.extension,':',e.status) ORDER BY e.extension SEPARATOR ',') FROM ai_extensions e WHERE e.tenant_id=a.tenant_id AND e.agent_id=a.id AND e.status<>'archived') telephony,
   (SELECT COUNT(*) FROM ai_agent_skills aks WHERE aks.tenant_id=a.tenant_id AND aks.agent_version_id=av.id AND aks.enabled=1) skill_count,
   EXISTS(SELECT 1 FROM ai_agent_knowledge ak WHERE ak.tenant_id=a.tenant_id AND ak.agent_id=a.id AND ak.access_mode='read') knowledge_connected,
   (SELECT hc.primary_destination_safe FROM ai_extensions ae JOIN ai_handoff_configs hc ON hc.ai_extension_id=ae.id AND hc.tenant_id=ae.tenant_id AND hc.status='active' AND hc.enabled=1 WHERE ae.tenant_id=a.tenant_id AND ae.agent_id=a.id AND ae.status='active' AND ae.enabled=1 LIMIT 1) handoff_destination
   FROM ai_agents a
   LEFT JOIN ai_agent_versions av ON av.id=a.current_version_id AND av.tenant_id=a.tenant_id
   LEFT JOIN ai_agent_versions dv ON dv.id=(SELECT d.id FROM ai_agent_versions d WHERE d.tenant_id=a.tenant_id AND d.agent_id=a.id AND d.lifecycle_status='draft' ORDER BY d.version_number DESC LIMIT 1)
   LEFT JOIN ai_voice_route_bindings b ON b.agent_id=a.id AND b.tenant_id=a.tenant_id
   LEFT JOIN ai_voice_sessions v ON v.route_binding_id=b.id AND v.tenant_id=a.tenant_id
   WHERE a.tenant_id=? GROUP BY a.id,a.name,a.agent_type,a.status,av.id,av.version_number,av.lifecycle_status,av.config_json,av.published_at,dv.id,dv.version_number,dv.config_json ORDER BY a.name`,[tenantId]);
   return rows.map((row:any)=>{const parse=(value:any)=>{try{return JSON.parse(String(value||'{}'))}catch{return{}}},published=parse(row.published_config_json),draft=parse(row.draft_config_json),publishedVoice=String(published.voiceProfile?.voiceId||published.voice?.voiceId||'marin'),draftVoice=row.draft_version_id?String(draft.voiceProfile?.voiceId||draft.voice?.voiceId||publishedVoice):null;return{...row,published_config_json:undefined,draft_config_json:undefined,provider:String(published.voiceProfile?.provider||'openai_realtime'),voice:publishedVoice,publishedVoice,draftVoice,hasVoiceDraftChange:Boolean(row.draft_version_id&&draftVoice!==publishedVoice),language:String(published.voiceProfile?.language||'ru'),ready:readiness.ready,readiness}})}
 private validate(input:any){const sourceType=String(input.sourceType||''),fallbackType=String(input.fallbackType||''),routeValue=String(input.routeValue||'').trim(),mode=input.mode==='production'?'production':'test';if(!sourceTypes.has(sourceType))throw new AiPlatformError('invalid_request',400,'Invalid route source');if(!routeValue||routeValue.length>64)throw new AiPlatformError('invalid_request',400,'Invalid route value');if(!fallbackTypes.has(fallbackType))throw new AiPlatformError('invalid_request',400,'Fallback is required');const fallbackValue=String(input.fallbackValue||'').trim();if(fallbackType!=='terminate_call'&&!fallbackValue)throw new AiPlatformError('invalid_request',400,'Fallback destination is required');if(fallbackValue&&fallbackValue===routeValue)throw new AiPlatformError('conflict',409,'Fallback cannot point to the same AI route');return{sourceType,routeValue,mode,fallbackType,fallbackValue}}
 async preview(tenantId:number,input:any){const v=this.validate(input),agentId=Number(input.agentId),versionId=Number(input.agentVersionId),version=(await this.store.query('SELECT lifecycle_status FROM ai_agent_versions WHERE tenant_id=? AND agent_id=? AND id=?',[tenantId,agentId,versionId]))[0];if(version?.lifecycle_status!=='published')throw new AiPlatformError('conflict',409,'Published agent version is required');const hash=voiceHash(tenantId,v.routeValue),conflict=(await this.store.query("SELECT id,name FROM ai_voice_route_bindings WHERE tenant_id=? AND match_value_hash=? AND status='active' LIMIT 1",[tenantId,hash]))[0],fallbackHash=v.fallbackValue?voiceHash(tenantId,v.fallbackValue):null,cycle=fallbackHash?(await this.store.query('SELECT id FROM ai_voice_route_bindings WHERE tenant_id=? AND match_value_hash=? AND fallback_value_hash=? LIMIT 1',[tenantId,fallbackHash,hash]))[0]:null,readiness=await this.readiness(tenantId),dialplan=buildVoiceRouteDialplanPreview({bindingKey:String(input.bindingKey||`voice_${Date.now()}`),sourceType:v.sourceType,routeValue:v.routeValue,fallbackType:v.fallbackType,fallbackValue:v.fallbackValue,stasisApplication:readAriConfig().application,recordingEnabled:input.recordingEnabled!==false});const errors=[conflict?'route_conflict':null,cycle?'cyclic_fallback':null,!readiness.ready?'provider_not_ready':null,!dialplan.ready?dialplan.code:null].filter(Boolean);if(v.mode==='production'&&v.sourceType==='did')errors.push('freepbx_inbound_route_review_required');return{ready:errors.length===0,errors,changes:{mode:v.mode,sourceType:v.sourceType,routeLabel:safeLabel(v.routeValue),fallbackType:v.fallbackType,fallbackLabel:safeLabel(v.fallbackValue),agentId,agentVersionId:versionId,recordingEnabled:input.recordingEnabled!==false},readiness,dialplan,requiresConfirm:v.mode==='production',applied:false}}
 async create(tenantId:number,input:any,actor:any){const v=this.validate(input),preview=await this.preview(tenantId,input),key=String(input.bindingKey||'');if(!/^[a-z][a-z0-9_.-]{2,99}$/.test(key))throw new AiPlatformError('invalid_request',400,'Invalid binding key');const expires=v.mode==='test'?new Date(Date.now()+Math.max(5,Math.min(Number(input.ttlMinutes)||30,1440))*60000):null,allowed=Array.isArray(input.allowedCallers)?input.allowedCallers.map((x:any)=>String(x).replace(/\D/g,'')).filter(Boolean).map((x:string)=>({hash:voiceHash(tenantId,x),masked:safeLabel(x)})):[],result:any=await this.store.query(`INSERT INTO ai_voice_route_bindings(tenant_id,binding_key,name,status,match_type,match_value_hash,safe_match_label,agent_id,agent_version_id,language,priority,dry_run_only,created_by,route_mode,provider_key,voice_key,allowed_callers_json,fallback_type,fallback_value_safe,fallback_value_hash,maximum_concurrent_calls,effective_schedule_json,expires_at,activation_state)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[tenantId,key,String(input.name||key).slice(0,191),'disabled',v.sourceType,voiceHash(tenantId,v.routeValue),safeLabel(v.routeValue),Number(input.agentId),Number(input.agentVersionId),String(input.language||'ru').slice(0,20),Number(input.priority)||100,v.mode==='test'?1:0,actor.actorId,v.mode,'openai_realtime',String(input.voice||'marin').slice(0,100),JSON.stringify(allowed),v.fallbackType,v.fallbackValue?safeLabel(v.fallbackValue):null,v.fallbackValue?voiceHash(tenantId,v.fallbackValue):null,Math.max(1,Math.min(Number(input.maximumConcurrentCalls)||1,100)),JSON.stringify(input.effectiveSchedule||{}),expires,'draft']);await this.audit.append({tenantId,...actor,eventType:'voice_route_binding_created' as any,entityType:'voice_route_binding',entityId:String(result.insertId),decision:'created',details:{mode:v.mode,sourceType:v.sourceType,fallbackType:v.fallbackType,previewReady:preview.ready,recordingEnabled:input.recordingEnabled!==false}});return{id:Number(result.insertId),status:'disabled',activationState:'draft',preview}}
 async activate(tenantId:number,id:number,confirm:boolean,actor:any){const row=(await this.store.query('SELECT * FROM ai_voice_route_bindings WHERE tenant_id=? AND id=?',[tenantId,id]))[0];if(!row)throw new AiPlatformError('not_found',404,'Voice binding not found');if(row.route_mode==='production'&&confirm!==true)throw new AiPlatformError('invalid_request',400,'Production activation requires confirm=true');if(row.route_mode==='production')throw new AiPlatformError('conflict',409,'Production dialplan apply requires a reviewed FreePBX apply step');await this.store.query("UPDATE ai_voice_route_bindings SET status='active',activation_state='active',updated_at=NOW() WHERE tenant_id=? AND id=?",[tenantId,id]);await this.audit.append({tenantId,...actor,eventType:'voice_route_binding_updated' as any,entityType:'voice_route_binding',entityId:String(id),decision:'test_activation',details:{mode:row.route_mode,expiresAt:row.expires_at}});return{id,status:'active',mode:row.route_mode}}
 async expire(tenantId:number){const rows=await this.store.query("SELECT id FROM ai_voice_route_bindings WHERE tenant_id=? AND route_mode='test' AND status='active' AND expires_at IS NOT NULL AND expires_at<=NOW()",[tenantId]);for(const row of rows)await this.store.query("UPDATE ai_voice_route_bindings SET status='disabled',activation_state='expired',updated_at=NOW() WHERE tenant_id=? AND id=?",[tenantId,row.id]);return{expired:rows.length}}
 async previewControlledVersionSwitch(tenantId:number,id:number,versionId:number){const binding=(await this.store.query("SELECT id,agent_id,agent_version_id,route_mode,match_type,safe_match_label FROM ai_voice_route_bindings WHERE tenant_id=? AND id=? LIMIT 1",[tenantId,id]))[0];if(!binding)throw new AiPlatformError('not_found',404,'Voice binding not found');if(binding.route_mode!=='test'||binding.match_type!=='controlled_test_extension')throw new AiPlatformError('permission_denied',403,'Only controlled test binding can switch version here');const version=(await this.store.query("SELECT id,agent_id,version_number,lifecycle_status FROM ai_agent_versions WHERE tenant_id=? AND id=? LIMIT 1",[tenantId,versionId]))[0];const active=(await this.store.query("SELECT COUNT(*) total FROM ai_voice_sessions WHERE tenant_id=? AND route_binding_id=? AND state NOT IN('completed','failed','cancelled')",[tenantId,id]))[0];const errors=[!version?'version_not_found':null,version&&Number(version.agent_id)!==Number(binding.agent_id)?'agent_mismatch':null,version?.lifecycle_status!=='published'?'unpublished_agent':null,Number(active?.total||0)>0?'active_call_conflict':null].filter(Boolean);return{ready:errors.length===0,errors,applied:false,bindingId:id,routeLabel:binding.safe_match_label,fromVersionId:Number(binding.agent_version_id),toVersionId:versionId,toVersionNumber:version?Number(version.version_number):null,productionAffected:false,dialplanAffected:false}}
 async switchControlledVersion(tenantId:number,id:number,versionId:number,confirm:boolean,actor:any){if(confirm!==true)throw new AiPlatformError('invalid_request',400,'Explicit confirmation is required');const preview=await this.previewControlledVersionSwitch(tenantId,id,versionId);if(!preview.ready)throw new AiPlatformError('conflict',409,String(preview.errors[0]||'version_switch_not_ready'));await this.store.query("UPDATE ai_voice_route_bindings SET agent_version_id=?,updated_at=NOW() WHERE tenant_id=? AND id=? AND route_mode='test' AND match_type='controlled_test_extension'",[versionId,tenantId,id]);await this.audit.append({tenantId,...actor,eventType:'voice_route_binding_updated' as any,entityType:'voice_route_binding',entityId:String(id),decision:'controlled_version_switch',details:{fromVersionId:preview.fromVersionId,toVersionId:versionId,productionAffected:false,dialplanAffected:false}});return{...preview,applied:true}}
}
