import type { Express, Request, Response } from 'express';
import { AiPlatformError } from '../../core/errors.js';
import { parseJsonObject, redactAiPlatformValue } from '../../core/redaction.js';
import type { AiPlatformStore } from '../../storage/aiPlatformStore.js';
import type { AiAuditService } from '../../audit/aiAuditService.js';
import type { LifecycleActor } from '../../agents/agentLifecycleService.js';
import { KnowledgeService } from '../core/knowledgeService.js';
type Handler=(req:Request,res:Response)=>Promise<any>;
export interface KnowledgeRouteRuntime { authenticated:any[];permit:(permission:string)=>any;enabled:any;wrap:(handler:Handler)=>any;getTenantId:()=>Promise<number>;actor:(req:Request)=>LifecycleActor;store:AiPlatformStore;audit:AiAuditService;positiveInt:(value:unknown,name:string)=>number;page:(req:Request)=>{limit:number;offset:number} }
export function registerKnowledgeRoutes(app:Express,r:KnowledgeRouteRuntime){const service=new KnowledgeService(r.store,r.audit);
  app.get('/api/ai-platform/knowledge',...r.authenticated,r.permit('view_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),p=r.page(req);const rows=await r.store.query(`SELECT s.id,s.agent_id,s.source_key,s.name,s.type,s.description,s.status,s.metadata_json,s.created_by,s.created_at,s.updated_at,(SELECT MAX(version_number) FROM ai_knowledge_versions v WHERE v.source_id=s.id) latest_version,(SELECT GROUP_CONCAT(ak.agent_id ORDER BY ak.agent_id) FROM ai_agent_knowledge ak WHERE ak.tenant_id=s.tenant_id AND ak.knowledge_source_id=s.id AND ak.access_mode='read') assigned_agent_ids FROM ai_knowledge_sources s WHERE s.tenant_id=? AND s.status<>'archived' ORDER BY s.id DESC LIMIT ? OFFSET ?`,[tenantId,p.limit,p.offset]);res.json({success:true,rows:rows.map(row=>({...row,assignedAgentIds:String(row.assigned_agent_ids||'').split(',').filter(Boolean).map(Number),metadata:redactAiPlatformValue(parseJsonObject(row.metadata_json,'metadata_json')).value,metadata_json:undefined,assigned_agent_ids:undefined})),page:Math.floor(p.offset/p.limit)+1,limit:p.limit})}));
  app.post('/api/ai-platform/knowledge',...r.authenticated,r.permit('manage_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId();res.status(201).json({success:true,data:await service.createSource(tenantId,{agentId:req.body?.agentId?r.positiveInt(req.body.agentId,'agent id'):null,sourceKey:req.body?.sourceKey,name:req.body?.name,type:req.body?.type,description:req.body?.description,metadata:req.body?.metadata},r.actor(req))})}));
  app.put('/api/ai-platform/knowledge/:id',...r.authenticated,r.permit('manage_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),id=r.positiveInt(req.params.id,'knowledge id'),name=String(req.body?.name||'').replace(/[<>]/g,'').trim().slice(0,191),description=String(req.body?.description||'').replace(/[<>]/g,'').trim().slice(0,1000);if(!name)throw new AiPlatformError('invalid_request',400,'Knowledge name is required');const result:any=await r.store.query('UPDATE ai_knowledge_sources SET name=?,description=?,updated_at=NOW() WHERE tenant_id=? AND id=?',[name,description,tenantId,id]);if(!Number(result?.affectedRows||0))throw new AiPlatformError('not_found',404,'Knowledge source not found');await r.audit.append({tenantId,...r.actor(req),eventType:'knowledge_source_updated' as any,entityType:'knowledge_source',entityId:String(id),decision:'updated',details:{name}});res.json({success:true,data:{id,name,description}})}));
  app.post('/api/ai-platform/knowledge/:id/assignment',...r.authenticated,r.permit('manage_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),sourceId=r.positiveInt(req.params.id,'knowledge id'),agentId=r.positiveInt(req.body?.agentId,'agent id'),enabled=req.body?.enabled!==false;const rows=await r.store.query('SELECT s.id source_id,a.id agent_id FROM ai_knowledge_sources s JOIN ai_agents a ON a.tenant_id=s.tenant_id WHERE s.tenant_id=? AND s.id=? AND a.id=? AND a.status<>\'archived\' LIMIT 1',[tenantId,sourceId,agentId]);if(!rows[0])throw new AiPlatformError('not_found',404,'Knowledge source or agent not found');if(enabled)await r.store.query("INSERT INTO ai_agent_knowledge(tenant_id,agent_id,knowledge_source_id,access_mode) VALUES (?,?,?,'read') ON DUPLICATE KEY UPDATE access_mode='read'",[tenantId,agentId,sourceId]);else await r.store.query('DELETE FROM ai_agent_knowledge WHERE tenant_id=? AND agent_id=? AND knowledge_source_id=?',[tenantId,agentId,sourceId]);await r.audit.append({tenantId,...r.actor(req),eventType:'knowledge_source_assignment_changed' as any,entityType:'knowledge_source',entityId:String(sourceId),decision:enabled?'assigned':'unassigned',details:{agentId}});res.json({success:true,data:{sourceId,agentId,enabled}})}));
  app.get('/api/ai-platform/knowledge/:id',...r.authenticated,r.permit('view_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),id=r.positiveInt(req.params.id,'knowledge id');const sources=await r.store.query('SELECT id,agent_id,source_key,name,type,description,status,metadata_json,created_by,created_at,updated_at FROM ai_knowledge_sources WHERE id=? AND tenant_id=? LIMIT 1',[id,tenantId]);if(!sources.length)throw new AiPlatformError('not_found',404,'Knowledge source not found');const versions=await r.store.query('SELECT id,version_number,checksum,status,created_by,created_at,published_at FROM ai_knowledge_versions WHERE source_id=? AND tenant_id=? ORDER BY version_number DESC',[id,tenantId]);const source=sources[0];res.json({success:true,data:{...source,metadata:redactAiPlatformValue(parseJsonObject(source.metadata_json,'metadata_json')).value,metadata_json:undefined,versions}})}));
  app.get('/api/ai-platform/knowledge/:id/content',...r.authenticated,r.permit('view_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),id=r.positiveInt(req.params.id,'knowledge id');const rows=await r.store.query(`SELECT v.id version_id,v.version_number,v.status,v.content FROM ai_knowledge_versions v JOIN ai_knowledge_sources s ON s.id=v.source_id AND s.tenant_id=v.tenant_id WHERE v.tenant_id=? AND v.source_id=? ORDER BY v.status='draft' DESC,v.version_number DESC LIMIT 1`,[tenantId,id]);if(!rows[0])throw new AiPlatformError('not_found',404,'Knowledge content not found');res.setHeader('Cache-Control','no-store');res.json({success:true,data:{versionId:Number(rows[0].version_id),versionNumber:Number(rows[0].version_number),status:rows[0].status,content:String(rows[0].content||'')}})}));
  app.post('/api/ai-platform/knowledge/:id/versions',...r.authenticated,r.permit('manage_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId();res.status(201).json({success:true,data:await service.createVersion(tenantId,r.positiveInt(req.params.id,'knowledge id'),{content:req.body?.content},r.actor(req))})}));
  app.post('/api/ai-platform/knowledge/:id/publish',...r.authenticated,r.permit('publish_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId();res.json({success:true,data:await service.publishVersion(tenantId,r.positiveInt(req.params.id,'knowledge id'),req.body?.versionId?r.positiveInt(req.body.versionId,'version id'):undefined,r.actor(req))})}));
  app.post('/api/ai-platform/knowledge/:id/archive',...r.authenticated,r.permit('manage_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),sourceId=r.positiveInt(req.params.id,'knowledge id');if(req.body?.confirm!==true)throw new AiPlatformError('invalid_request',400,'Explicit confirmation is required');const data=await service.archiveVersion(tenantId,sourceId,r.actor(req));await r.store.query('DELETE FROM ai_agent_knowledge WHERE tenant_id=? AND knowledge_source_id=?',[tenantId,sourceId]);res.json({success:true,data})}));
}
