import type { Express, Request, Response } from 'express';
import { AiPlatformError } from '../../core/errors.js';
import { parseJsonObject, redactAiPlatformValue } from '../../core/redaction.js';
import type { AiPlatformStore } from '../../storage/aiPlatformStore.js';
import type { AiAuditService } from '../../audit/aiAuditService.js';
import type { LifecycleActor } from '../../agents/agentLifecycleService.js';
import { KnowledgeService } from '../core/knowledgeService.js';
type Handler=(req:Request,res:Response)=>Promise<any>;
export interface KnowledgeRouteRuntime { authenticated:any[];permit:(permission:string)=>any;enabled:any;wrap:(handler:Handler)=>any;getTenantId:()=>Promise<number>;actor:(req:Request)=>LifecycleActor;store:AiPlatformStore;audit:AiAuditService;positiveInt:(value:unknown,name:string)=>number;page:(req:Request)=>{limit:number;offset:number} }
export function registerKnowledgeRoutes(app:Express,r:KnowledgeRouteRuntime){const service=new KnowledgeService(r.store,r.audit);
  app.get('/api/ai-platform/knowledge',...r.authenticated,r.permit('view_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),p=r.page(req),agentId=req.query.agentId?r.positiveInt(req.query.agentId,'agent id'):null;const rows=await r.store.query(`SELECT s.id,s.agent_id,s.source_key,s.name,s.type,s.description,s.status,s.metadata_json,s.created_by,s.created_at,s.updated_at,(SELECT MAX(version_number) FROM ai_knowledge_versions v WHERE v.source_id=s.id) latest_version FROM ai_knowledge_sources s WHERE s.tenant_id=? ${agentId?'AND (s.agent_id=? OR s.agent_id IS NULL)':''} ORDER BY s.id DESC LIMIT ? OFFSET ?`,agentId?[tenantId,agentId,p.limit,p.offset]:[tenantId,p.limit,p.offset]);res.json({success:true,rows:rows.map(row=>({...row,metadata:redactAiPlatformValue(parseJsonObject(row.metadata_json,'metadata_json')).value,metadata_json:undefined})),page:Math.floor(p.offset/p.limit)+1,limit:p.limit})}));
  app.post('/api/ai-platform/knowledge',...r.authenticated,r.permit('manage_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId();res.status(201).json({success:true,data:await service.createSource(tenantId,{agentId:req.body?.agentId?r.positiveInt(req.body.agentId,'agent id'):null,sourceKey:req.body?.sourceKey,name:req.body?.name,type:req.body?.type,description:req.body?.description,metadata:req.body?.metadata},r.actor(req))})}));
  app.get('/api/ai-platform/knowledge/:id',...r.authenticated,r.permit('view_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId(),id=r.positiveInt(req.params.id,'knowledge id');const sources=await r.store.query('SELECT id,agent_id,source_key,name,type,description,status,metadata_json,created_by,created_at,updated_at FROM ai_knowledge_sources WHERE id=? AND tenant_id=? LIMIT 1',[id,tenantId]);if(!sources.length)throw new AiPlatformError('not_found',404,'Knowledge source not found');const versions=await r.store.query('SELECT id,version_number,checksum,status,created_by,created_at,published_at FROM ai_knowledge_versions WHERE source_id=? AND tenant_id=? ORDER BY version_number DESC',[id,tenantId]);const source=sources[0];res.json({success:true,data:{...source,metadata:redactAiPlatformValue(parseJsonObject(source.metadata_json,'metadata_json')).value,metadata_json:undefined,versions}})}));
  app.post('/api/ai-platform/knowledge/:id/versions',...r.authenticated,r.permit('manage_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId();res.status(201).json({success:true,data:await service.createVersion(tenantId,r.positiveInt(req.params.id,'knowledge id'),{content:req.body?.content},r.actor(req))})}));
  app.post('/api/ai-platform/knowledge/:id/publish',...r.authenticated,r.permit('publish_ai_knowledge'),r.enabled,r.wrap(async(req,res)=>{const tenantId=await r.getTenantId();res.json({success:true,data:await service.publishVersion(tenantId,r.positiveInt(req.params.id,'knowledge id'),req.body?.versionId?r.positiveInt(req.body.versionId,'version id'):undefined,r.actor(req))})}));
}
