import crypto from 'node:crypto';
import type { AiPlatformStore } from '../storage/aiPlatformStore.js';
import type { AiAuditService } from '../audit/aiAuditService.js';
import { IntegrationCredentialStore } from './credentialStore.js';
import { IntegrationActionRegistry, PROVIDER_CAPABILITIES } from './integrationActionRegistry.js';
import { assertSafeUrl } from './integrationSecurity.js';
import { createConnector } from './integrationConnectors.js';
import { ApplicationEncryptionService } from '../actions/applicationEncryption.js';
import { redactAiPlatformValue } from '../core/redaction.js';

export class IntegrationService {
  readonly actions=new IntegrationActionRegistry();readonly credentials:IntegrationCredentialStore;
  constructor(private store:AiPlatformStore,private audit:AiAuditService){this.credentials=new IntegrationCredentialStore(store)}
  async list(tenantId:number){return this.store.query(`SELECT i.id,i.name,i.provider_type providerType,i.connector_type connectorType,i.auth_type authType,i.status,i.enabled,i.environment,i.last_checked_at lastCheckedAt,i.health_status healthStatus,i.health_error_code healthErrorCode,c.masked_identifier credentialIdentifier,c.updated_at credentialUpdatedAt,(SELECT COUNT(*) FROM ai_agent_integration_policies p WHERE p.integration_id=i.id AND p.tenant_id=i.tenant_id AND p.enabled=1) agentCount FROM ai_integrations i LEFT JOIN ai_integration_credentials c ON c.integration_id=i.id AND c.tenant_id=i.tenant_id WHERE i.tenant_id=? AND i.status<>'deleted' ORDER BY i.name`,[tenantId])}
  async create(tenantId:number,input:any,actor:any){
    const provider=String(input.providerType||'');if(!['generic_rest','generic_webhook','mock_crm'].includes(provider))throw new Error('VALIDATION_FAILED');
    const allowedHosts=Array.isArray(input.allowedHosts)?input.allowedHosts.map(String):[];if(provider!=='mock_crm')assertSafeUrl(String(input.baseUrl||''),allowedHosts,Boolean(input.allowPrivate));
    const result:any=await this.store.query(`INSERT INTO ai_integrations(tenant_id,name,provider_type,connector_type,base_url,auth_type,status,enabled,environment,timeout_ms,retry_policy_json,rate_limit_policy_json,allowed_hosts_json,allow_private,created_by)VALUES(?,?,?,?,?,?,'active',1,?,?,?,?,?,?,?)`,[tenantId,String(input.name||'').trim().slice(0,191),provider,String(input.connectorType||provider),provider==='mock_crm'?null:String(input.baseUrl),String(input.authType||'none'),String(input.environment||'sandbox'),Math.max(500,Math.min(Number(input.timeoutMs||8000),30000)),JSON.stringify(input.retryPolicy||{}),JSON.stringify(input.rateLimitPolicy||{}),JSON.stringify(allowedHosts),Boolean(input.allowPrivate)?1:0,actor.actorId]);
    await this.audit.append({tenantId,...actor,eventType:'integration_created' as any,entityType:'integration',entityId:String(result.insertId),decision:'created',details:{providerType:provider,authType:String(input.authType||'none'),allowedHosts}});
    return{id:Number(result.insertId)}
  }
  async setMapping(tenantId:number,id:number,input:any){if(!this.actions.get(String(input.actionId)))throw new Error('ACTION_NOT_ALLOWED');if(!/^(GET|POST|PUT|PATCH|DELETE)$/.test(String(input.method||'GET')))throw new Error('VALIDATION_FAILED');if(!/^\/[A-Za-z0-9/_{}.-]*$/.test(String(input.path||'/')))throw new Error('VALIDATION_FAILED');await this.store.query(`INSERT INTO ai_integration_mappings(tenant_id,integration_id,action_id,http_method,path_template,request_mapping_json,response_mapping_json,timeout_ms,enabled)VALUES(?,?,?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE http_method=VALUES(http_method),path_template=VALUES(path_template),request_mapping_json=VALUES(request_mapping_json),response_mapping_json=VALUES(response_mapping_json),timeout_ms=VALUES(timeout_ms),enabled=1`,[tenantId,id,String(input.actionId),String(input.method||'GET'),String(input.path||'/'),JSON.stringify(input.requestMapping||{}),JSON.stringify(input.responseMapping||{}),Math.max(500,Math.min(Number(input.timeoutMs||8000),30000))])}
  async assign(tenantId:number,id:number,agentId:number,input:any){const actions=(input.allowedActions||[]).map(String);if(actions.some((x:string)=>!this.actions.get(x)))throw new Error('ACTION_NOT_ALLOWED');await this.store.query(`INSERT INTO ai_agent_integration_policies(tenant_id,agent_id,integration_id,enabled,allowed_actions_json,allowed_fields_json,confirmation_policy_json,max_calls_per_conversation,rate_limit_json,allowed_stages_json,fallback_policy,can_read_personal_data,can_write_data)VALUES(?,?,?,1,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE enabled=1,allowed_actions_json=VALUES(allowed_actions_json),allowed_fields_json=VALUES(allowed_fields_json),confirmation_policy_json=VALUES(confirmation_policy_json),max_calls_per_conversation=VALUES(max_calls_per_conversation),rate_limit_json=VALUES(rate_limit_json),allowed_stages_json=VALUES(allowed_stages_json),fallback_policy=VALUES(fallback_policy),can_read_personal_data=VALUES(can_read_personal_data),can_write_data=VALUES(can_write_data)`,[tenantId,agentId,id,JSON.stringify(actions),JSON.stringify(input.allowedFields||[]),JSON.stringify(input.confirmationPolicy||{}),Math.max(1,Math.min(Number(input.maxCallsPerConversation||10),100)),JSON.stringify(input.rateLimit||{}),JSON.stringify(input.allowedStages||['during_call']),String(input.fallbackPolicy||'safe_message'),input.canReadPersonalData?1:0,input.canWriteData?1:0])}
  async health(tenantId:number,id:number){const integration=(await this.store.query('SELECT * FROM ai_integrations WHERE tenant_id=? AND id=?',[tenantId,id]))[0];if(!integration)throw new Error('REMOTE_NOT_FOUND');const started=Date.now();try{const result=await createConnector(integration.provider_type).health(integration,await this.credentials.get(tenantId,id));await this.store.query("UPDATE ai_integrations SET health_status='connected',health_error_code=NULL,last_checked_at=NOW() WHERE id=? AND tenant_id=?",[id,tenantId]);return result}catch{await this.store.query("UPDATE ai_integrations SET health_status='unavailable',health_error_code='REMOTE_UNAVAILABLE',last_checked_at=NOW() WHERE id=? AND tenant_id=?",[id,tenantId]);return{status:'unavailable',latencyMs:Date.now()-started,errorCode:'REMOTE_UNAVAILABLE'}}}
  manifests(){return PROVIDER_CAPABILITIES}
  async queuePostCall(tenantId:number,integrationId:number,conversationId:string,actionId:string,input:any){const key=`post:${conversationId}:${actionId}:${crypto.createHash('sha256').update(JSON.stringify(input)).digest('hex').slice(0,20)}`,encrypted=new ApplicationEncryptionService().encrypt(JSON.stringify(input));await this.store.query("INSERT IGNORE INTO ai_integration_post_call_jobs(tenant_id,integration_id,conversation_id,action_id,idempotency_key,input_masked_json,input_encrypted,status,next_attempt_at)VALUES(?,?,?,?,?,?,?,'pending',NOW())",[tenantId,integrationId,conversationId,actionId,key,JSON.stringify(redactAiPlatformValue(input).value),encrypted.ciphertext]);return{queued:true,idempotencyKey:key}}
}
