import type{IntegrationActionDefinition,SideEffectLevel}from'./integrationTypes.js';
const read=['customer.lookup_by_phone','customer.get','customer.list_recent_interactions','order.get_status','ticket.get','appointment.get_available_slots','appointment.get','manager.get_on_duty','account.get_balance','custom.read'];
const writes:[string,SideEffectLevel][]=[['lead.create','consequential_write'],['customer.add_note','reversible_write'],['ticket.create','consequential_write'],['ticket.update_status','consequential_write'],['task.create','consequential_write'],['callback.create','consequential_write'],['appointment.create','consequential_write'],['appointment.reschedule','consequential_write'],['appointment.cancel','consequential_write'],['call_result.save','reversible_write'],['custom.write','consequential_write']];
const title=(id:string)=>id.split('.').join(' · ');
const fields=(actionId:string)=>actionId==='customer.lookup_by_phone'?{phone:{type:'string',minLength:3,maxLength:20}}:actionId.includes('appointment')?{appointmentId:{type:'string',maxLength:100},date:{type:'string',format:'date-time'}}:actionId.startsWith('ticket.')?{ticketId:{type:'string',maxLength:100},subject:{type:'string',maxLength:500}}:actionId==='order.get_status'?{orderId:{type:'string',maxLength:100}}:{businessKey:{type:'string',maxLength:100}};
const make=(actionId:string,sideEffectLevel:SideEffectLevel):IntegrationActionDefinition=>({actionId,title:title(actionId),description:`Нормализованное действие ${actionId}`,inputSchema:{type:'object',properties:fields(actionId),additionalProperties:false},outputSchema:{type:'object',additionalProperties:true},sideEffectLevel,confirmationPolicy:sideEffectLevel==='read_only'?'none':sideEffectLevel==='reversible_write'?'policy':'required',idempotencyPolicy:sideEffectLevel==='read_only'?'none':'conversation_action_business_key',timeoutMs:8000,allowedRoles:['su','admin','ai_agent'],dataClassification:actionId.startsWith('customer.')?'personal':'internal',auditPolicy:'metadata_only'});
export const INTEGRATION_ACTIONS=[...read.map(id=>make(id,'read_only' as const)),...writes.map(([id,level])=>make(id,level))];
export class IntegrationActionRegistry{list(){return INTEGRATION_ACTIONS}get(id:string){return INTEGRATION_ACTIONS.find(x=>x.actionId===id)||null}}
export const PROVIDER_CAPABILITIES=[
 {providerType:'generic_rest',implemented:true,capabilities:['read','write','mapping','health']},{providerType:'generic_webhook',implemented:true,capabilities:['signed_write','async_response']},
 {providerType:'bitrix24',implemented:false,capabilities:['manifest']},{providerType:'amocrm',implemented:false,capabilities:['manifest']},{providerType:'1c',implemented:false,capabilities:['manifest']},{providerType:'retailcrm',implemented:false,capabilities:['manifest']},{providerType:'custom_crm',implemented:false,capabilities:['manifest']},
];
