import { isPBXPulsDbAvailable, queryPBXPulsDb } from '../pbxpulsDb.js';
import { mergeNotificationToken, NotificationConfigCrypto } from './configCrypto.js';
import { NotificationDispatcher } from './dispatcher.js';
import { NotificationEventService } from './eventService.js';
import { NOTIFICATION_EVENT_CATALOG } from './catalog.js';
import { TelegramTransport, validTelegramChat, validTelegramToken } from './telegramTransport.js';
import { safeNotificationError } from './errors.js';

export interface NotificationRuntimeDeps { missedCalls: (delayMinutes:number)=>Promise<any[]>; missedCallSlaMinutes:()=>Promise<number>; trunksStatus:()=>Promise<any[]>; }
export { safeNotificationError } from './errors.js';

export class NotificationService {
  readonly events=new NotificationEventService(); private readonly crypto:NotificationConfigCrypto; private readonly dispatcher:NotificationDispatcher;
  private timer:ReturnType<typeof setInterval>|null=null;private polling=false;private dbOutageAt:Date|null=null;private systemCursor=0;private systemCursorInitialized=false;
  constructor(secret:string,private readonly deps:NotificationRuntimeDeps,private readonly telegram=new TelegramTransport()){this.crypto=new NotificationConfigCrypto(secret);this.dispatcher=new NotificationDispatcher(this.crypto,telegram)}
  private async channel(){const row=(await queryPBXPulsDb("SELECT * FROM notification_channels WHERE channel='telegram' LIMIT 1"))[0]||{},config=this.crypto.decrypt(row.encrypted_config);return{enabled:row.enabled===1||row.enabled===true,hasToken:Boolean(config.botToken),token:String(config.botToken||''),chatId:String(row.destination||''),lastSuccessAt:row.last_success_at||null,lastError:row.last_error||null}}
  async settings(){const [global,rules,channel,missedCallSlaMinutes]=await Promise.all([this.events.globalSettings(),this.events.rules(),this.channel(),this.deps.missedCallSlaMinutes()]);return{global,rules,channel:{enabled:channel.enabled,hasToken:channel.hasToken,chatId:channel.chatId,lastSuccessAt:channel.lastSuccessAt,lastError:channel.lastError},catalog:NOTIFICATION_EVENT_CATALOG,callQuality:{missedCallSlaMinutes}}}
  async save(input:any){const old=await this.channel(),tokenInput=String(input?.channel?.botToken||'').trim(),replace=input?.channel?.replaceToken===true;if(tokenInput&&!validTelegramToken(tokenInput))throw new Error('invalid_bot_token');const token=mergeNotificationToken(old.token,tokenInput,replace||!old.hasToken),chatId=String(input?.channel?.chatId??old.chatId).trim();if(chatId&&!validTelegramChat(chatId))throw new Error('invalid_chat_id');const global=await this.events.saveGlobal(input?.global||{}),rules=await this.events.saveRules(input?.rules||[]);await queryPBXPulsDb(`UPDATE notification_channels SET type='telegram',enabled=?,encrypted_config=?,destination=?,updated_at=UTC_TIMESTAMP() WHERE channel='telegram'`,[input?.channel?.enabled===true?1:0,this.crypto.encrypt({botToken:token}),chatId||null]);return{global,rules,channel:{enabled:input?.channel?.enabled===true,hasToken:Boolean(token),chatId,lastSuccessAt:old.lastSuccessAt,lastError:old.lastError},catalog:NOTIFICATION_EVENT_CATALOG,callQuality:{missedCallSlaMinutes:await this.deps.missedCallSlaMinutes()}}}
  async clearToken(){const old=await this.channel();await queryPBXPulsDb("UPDATE notification_channels SET encrypted_config=?,enabled=0,last_error=NULL,updated_at=UTC_TIMESTAMP() WHERE channel='telegram'",[this.crypto.encrypt({})]);return{enabled:false,hasToken:false,chatId:old.chatId,lastSuccessAt:old.lastSuccessAt,lastError:null}}
  async test(){const channel=await this.channel();if(!channel.token||!channel.chatId)throw new Error('telegram_not_configured');await this.telegram.send(channel.token,channel.chatId,'PBXPuls: тестовое сообщение Центра уведомлений успешно доставлено.');await queryPBXPulsDb("UPDATE notification_channels SET last_success_at=UTC_TIMESTAMP(),last_error=NULL,updated_at=UTC_TIMESTAMP() WHERE channel='telegram'");return{delivered:true}}
  async telegramIdentity(){const channel=await this.channel();if(!channel.token)throw new Error('telegram_not_configured');return this.telegram.identity(channel.token)}
  async discoverTelegramChats(){const channel=await this.channel();if(!channel.token)throw new Error('telegram_not_configured');return this.telegram.discoverChats(channel.token)}
  async preview(){const data=await this.settings(),balanceRule=data.rules.find(x=>x.eventType==='balance.low'),slaMinutes=data.callQuality.missedCallSlaMinutes;const balances=await this.balanceRows(Number(balanceRule?.parameters.threshold||1500));return{settings:data,candidates:{balance:balances.filter((r:any)=>Number(r.balance_amount)<=Number(balanceRule?.parameters.threshold||1500)),missedCalls:await this.deps.missedCalls(slaMinutes),trunks:(await this.deps.trunksStatus()).filter((r:any)=>r.reachable===false),monitoring:[],system:await this.criticalSystemRows()}}}
  private balanceRows(_threshold:number){return queryPBXPulsDb(`SELECT s.id,s.display_name,p.balance_amount,p.currency,p.id snapshot_id FROM balance_sources s JOIN balance_snapshots p ON p.id=(SELECT x.id FROM balance_snapshots x WHERE x.source_id=s.id ORDER BY x.measured_at DESC,x.id DESC LIMIT 1) WHERE s.enabled=1 AND p.balance_amount IS NOT NULL`)}
  private criticalSystemRows(){return queryPBXPulsDb(`SELECT id,event_type,severity,source,message,created_at FROM system_events WHERE severity='critical' AND id>? ORDER BY id LIMIT 50`,[this.systemCursor])}
  private async missedWindow(delayMinutes:number){const now=new Date(),rows=await queryPBXPulsDb("SELECT cursor_at FROM notification_producer_cursors WHERE producer_key='missed_calls' LIMIT 1"),previous=rows[0]?.cursor_at?new Date(rows[0].cursor_at):now;await queryPBXPulsDb("INSERT INTO notification_producer_cursors(producer_key,cursor_at,updated_at)VALUES('missed_calls',UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE cursor_at=VALUES(cursor_at),updated_at=UTC_TIMESTAMP()");if(!rows.length)return[];const from=previous.getTime()-delayMinutes*60000,to=now.getTime()-delayMinutes*60000;return(await this.deps.missedCalls(delayMinutes)).filter(row=>{const value=new Date(row.occurredAt).getTime();return Number.isFinite(value)&&value>from&&value<=to})}
  async poll(){if(this.polling)return;this.polling=true;try{const available=await isPBXPulsDbAvailable();if(!available){if(!this.dbOutageAt)this.dbOutageAt=new Date();return}if(this.dbOutageAt){const started=this.dbOutageAt;this.dbOutageAt=null;await this.events.observe({eventType:'database.unavailable',category:'system',severity:'critical',title:'База PBXPuls была недоступна',message:`Недоступность зафиксирована ${started.toISOString()}`,source:'pbxpuls_db',entityType:'database',entityId:'main',dedupeKey:'database.unavailable:main',status:'active',occurredAt:started},{problem:true});await this.events.observe({eventType:'database.unavailable',category:'system',severity:'info',title:'База PBXPuls восстановлена',message:'Соединение с базой PBXPuls восстановлено',source:'pbxpuls_db',entityType:'database',entityId:'main',dedupeKey:'database.unavailable:main',status:'resolved',occurredAt:new Date()},{problem:false})}
    const rules=await this.events.rules(),balanceRule=rules.find(x=>x.eventType==='balance.low');if(balanceRule){const threshold=Number(balanceRule.parameters.threshold||1500);for(const row of await this.balanceRows(threshold)){const problem=Number(row.balance_amount)<=threshold;await this.events.observe({eventType:'balance.low',category:'balance',severity:'warning',title:problem?'Низкий баланс':'Баланс восстановлен',message:`${row.display_name}: ${Number(row.balance_amount).toLocaleString('ru-RU')} ${row.currency||''}`,source:'balance',entityType:'provider',entityId:String(row.id),dedupeKey:`balance.low:${row.id}`,status:problem?'active':'resolved',occurredAt:new Date(),metadata:{snapshotId:row.snapshot_id,balance:Number(row.balance_amount),threshold}},{problem})}}
    const missedRule=rules.find(x=>x.eventType==='calls.missed_unreturned');if(missedRule?.enabled){const slaMinutes=await this.deps.missedCallSlaMinutes();for(const row of await this.missedWindow(slaMinutes)){await this.events.emit({eventType:'calls.missed_unreturned',category:'calls',severity:'warning',title:'Нет перезвона по пропущенному в рамках SLA',message:`От: ${row.callerNumber||'неизвестно'} · Кому: ${row.calledExtension||'—'} · UID: ${row.linkedid||'—'} · SLA: ${slaMinutes} мин. · ${row.occurredAt}`,source:'cdr',entityType:'call',entityId:row.linkedidHash,dedupeKey:`missed.unreturned:${row.linkedidHash}`,status:'active',occurredAt:new Date(row.occurredAt),metadata:{linkedidHash:row.linkedidHash,uid:row.linkedid||null,slaMinutes}})}}
    const trunkRule=rules.find(x=>x.eventType==='trunk.down'),required=Math.max(1,Number(trunkRule?.parameters.consecutiveFailures||2));if(trunkRule?.enabled)for(const row of await this.deps.trunksStatus()){if(typeof row.reachable!=='boolean')continue;const problem=row.reachable===false,key=String(row.trunkKey||row.displayName||'');if(!key)continue;await this.events.observe({eventType:'trunk.down',category:'telephony',severity:problem?'critical':'info',title:problem?'Транк недоступен':'Транк восстановлен',message:String(row.displayName||key),source:'asterisk_cli',entityType:'trunk',entityId:key,dedupeKey:`trunk.down:${key}`,status:problem?'active':'resolved',occurredAt:new Date(),metadata:{registrationState:row.registrationState||null}},{problem,consecutiveFailures:required})}
    if(!this.systemCursorInitialized){const cursor=(await queryPBXPulsDb("SELECT cursor_value FROM notification_producer_cursors WHERE producer_key='critical_system_events' LIMIT 1"))[0];if(cursor){this.systemCursor=Number(cursor.cursor_value||0)}else{const row=(await queryPBXPulsDb("SELECT COALESCE(MAX(id),0) id FROM system_events WHERE severity='critical'"))[0];this.systemCursor=Number(row?.id||0);await queryPBXPulsDb("INSERT INTO notification_producer_cursors(producer_key,cursor_at,cursor_value,updated_at)VALUES('critical_system_events',UTC_TIMESTAMP(),?,UTC_TIMESTAMP())",[String(this.systemCursor)])}this.systemCursorInitialized=true}else for(const row of await this.criticalSystemRows()){this.systemCursor=Math.max(this.systemCursor,Number(row.id));await this.events.emit({eventType:'pbxpuls.critical_error',category:'system',severity:'critical',title:String(row.event_type||'Критическая ошибка PBXPuls'),message:String(row.message||''),source:String(row.source||'pbxpuls'),entityType:'system_event',entityId:String(row.id),dedupeKey:`pbxpuls.critical:${row.id}`,status:'active',occurredAt:new Date(row.created_at),metadata:{systemEventId:row.id}});await queryPBXPulsDb("UPDATE notification_producer_cursors SET cursor_at=UTC_TIMESTAMP(),cursor_value=?,updated_at=UTC_TIMESTAMP() WHERE producer_key='critical_system_events'",[String(this.systemCursor)])}}
    catch(error){if(!(await isPBXPulsDbAvailable())){if(!this.dbOutageAt)this.dbOutageAt=new Date()}else console.warn('[NOTIFICATIONS] producer failed:',safeNotificationError(error).safeErrorCode)}finally{this.polling=false}}
  start(){if(this.timer)return;this.dispatcher.start();setTimeout(()=>void this.poll(),5000).unref?.();this.timer=setInterval(()=>void this.poll(),60000);this.timer.unref?.()}
  stop(){if(this.timer)clearInterval(this.timer);this.timer=null;this.dispatcher.stop()}
}
