import type { Express, Request, Response } from 'express';
import { queryPBXPulsDb } from '../pbxpulsDb.js';
import { NotificationService, safeNotificationError, type NotificationRuntimeDeps } from './notificationService.js';

export function registerNotificationRoutes(app:Express,deps:{requireAuth:any;checkPermission:(req:Request,p:string)=>Promise<boolean>;hashSecret:string;runtime:NotificationRuntimeDeps}){
  const service=new NotificationService(deps.hashSecret,deps.runtime);
  const allowed=async(req:Request,res:Response,permission:string)=>{if(await deps.checkPermission(req,permission))return true;res.status(403).json({error:`Access denied: ${permission} permission required`});return false};
  app.get('/api/notifications/settings',deps.requireAuth(),async(req,res)=>{if(!await allowed(req,res,'view_notification_center'))return;try{return res.json({success:true,...await service.settings()})}catch{return res.status(503).json({success:false,safeErrorCode:'notification_storage_unavailable'})}});
  app.put('/api/notifications/settings',deps.requireAuth(),async(req,res)=>{if(!await allowed(req,res,'manage_notification_center'))return;try{return res.json({success:true,...await service.save(req.body||{})})}catch(error){return res.status(400).json({success:false,...safeNotificationError(error)})}});
  app.delete('/api/notifications/telegram/token',deps.requireAuth(),async(req,res)=>{if(!await allowed(req,res,'manage_notification_center'))return;try{return res.json({success:true,channel:await service.clearToken()})}catch(error){return res.status(400).json({success:false,...safeNotificationError(error)})}});
  app.get('/api/notifications/preview',deps.requireAuth(),async(req,res)=>{if(!await allowed(req,res,'view_notification_center'))return;try{return res.json({success:true,...await service.preview()})}catch{return res.status(503).json({success:false,safeErrorCode:'notification_preview_unavailable'})}});
  app.post('/api/notifications/test',deps.requireAuth(),async(req,res)=>{if(!await allowed(req,res,'manage_notification_center'))return;try{return res.json({success:true,...await service.test()})}catch(error){return res.status(503).json({success:false,...safeNotificationError(error)})}});
  app.post('/api/notifications/telegram/check',deps.requireAuth(),async(req,res)=>{if(!await allowed(req,res,'manage_notification_center'))return;try{return res.json({success:true,bot:await service.telegramIdentity()})}catch(error){return res.status(503).json({success:false,...safeNotificationError(error)})}});
  app.post('/api/notifications/telegram/discover-chats',deps.requireAuth(),async(req,res)=>{if(!await allowed(req,res,'manage_notification_center'))return;try{return res.json({success:true,chats:await service.discoverTelegramChats()})}catch(error){return res.status(503).json({success:false,...safeNotificationError(error)})}});
  app.get('/api/notifications/deliveries',deps.requireAuth(),async(req,res)=>{if(!await allowed(req,res,'view_notification_delivery_log'))return;const limit=Math.max(1,Math.min(200,Number(req.query.limit)||50)),conditions=['1=1'],params:any[]=[];for(const[key,column]of[['status','d.status'],['category','e.category'],['eventType','e.event_type']]as const){const value=String(req.query[key]||'').trim();if(value){conditions.push(`${column}=?`);params.push(value)}}const from=String(req.query.from||'').trim(),to=String(req.query.to||'').trim();if(from){conditions.push('d.created_at>=?');params.push(from)}if(to){conditions.push('d.created_at<=?');params.push(to)}const rows=await queryPBXPulsDb(`SELECT d.id,d.created_at,d.status,d.attempt_count,d.last_error,d.channel_id,e.event_type,e.category,e.severity,e.title,e.entity_type,e.entity_id FROM notification_deliveries d LEFT JOIN notification_events e ON e.id=d.event_id WHERE ${conditions.join(' AND ')} ORDER BY d.id DESC LIMIT ${limit}`,params);return res.json({success:true,rows})});
  return{start:()=>service.start(),stop:()=>service.stop()};
}
