import type { Express } from 'express';
import type { IntegrationService } from '../integrationService.js';
import type { ConnectorExecutor } from '../connectorExecutor.js';
export function registerIntegrationRoutes(app:Express,r:any,service:IntegrationService,executor:ConnectorExecutor){
 const{authenticated,permit,wrap,getTenantId,actor,positiveInt}=r;
 app.get('/api/ai-platform/integrations',...authenticated,permit('view_integrations'),wrap(async(_req:any,res:any)=>res.json({success:true,rows:await service.list(await getTenantId())})));
 app.get('/api/ai-platform/integrations/actions',...authenticated,permit('view_integrations'),wrap(async(_req:any,res:any)=>res.json({success:true,rows:service.actions.list(),providers:service.manifests()})));
 app.get('/api/ai-platform/agents/:agentId/integrations',...authenticated,permit('view_integrations'),wrap(async(req:any,res:any)=>{const tenantId=await getTenantId(),agentId=positiveInt(req.params.agentId,'agent id'),integrations=await service.list(tenantId),policies=await r.store.query('SELECT integration_id integrationId,enabled,allowed_actions_json allowedActions,allowed_fields_json allowedFields,max_calls_per_conversation maxCallsPerConversation FROM ai_agent_integration_policies WHERE tenant_id=? AND agent_id=?',[tenantId,agentId]);res.json({success:true,data:{integrations,actions:service.actions.list(),policies:policies.map((x:any)=>({...x,allowedActions:JSON.parse(x.allowedActions||'[]'),allowedFields:JSON.parse(x.allowedFields||'[]')}))}})}));
 app.post('/api/ai-platform/integrations',...authenticated,permit('create_integrations'),wrap(async(req:any,res:any)=>res.status(201).json({success:true,data:await service.create(await getTenantId(),req.body,actor(req))})));
 app.put('/api/ai-platform/integrations/:id/credentials',...authenticated,permit('manage_integration_credentials'),wrap(async(req:any,res:any)=>{const tenantId=await getTenantId(),id=positiveInt(req.params.id,'integration id');res.json({success:true,data:await service.credentials.set(tenantId,id,String(req.body?.authType||''),req.body?.credential||{},actor(req).actorId)})}));
 app.put('/api/ai-platform/integrations/:id/mappings/:actionId',...authenticated,permit('edit_integrations'),wrap(async(req:any,res:any)=>{await service.setMapping(await getTenantId(),positiveInt(req.params.id,'integration id'),{...req.body,actionId:req.params.actionId});res.json({success:true,data:{saved:true}})}));
 app.put('/api/ai-platform/integrations/:id/agents/:agentId/policy',...authenticated,permit('assign_integrations_to_agents'),wrap(async(req:any,res:any)=>{await service.assign(await getTenantId(),positiveInt(req.params.id,'integration id'),positiveInt(req.params.agentId,'agent id'),req.body);res.json({success:true,data:{saved:true}})}));
 app.post('/api/ai-platform/integrations/:id/health',...authenticated,permit('test_integrations'),wrap(async(req:any,res:any)=>res.json({success:true,data:await service.health(await getTenantId(),positiveInt(req.params.id,'integration id'))})));
 app.post('/api/ai-platform/integrations/:id/preview',...authenticated,permit('test_integrations'),wrap(async(req:any,res:any)=>{const action=service.actions.get(String(req.body?.actionId||''));if(!action)throw new Error('ACTION_NOT_ALLOWED');if(action.sideEffectLevel!=='read_only'&&req.body?.dryRun!==true)throw new Error('CONFIRMATION_REQUIRED');const a=actor(req),data=await executor.execute({tenantId:await getTenantId(),agentId:req.body?.agentId?positiveInt(req.body.agentId,'agent id'):null,agentVersionId:null,conversationId:String(req.body?.conversationId||'controlled-preview'),actorId:a.actorId,role:String(req.user?.role||'admin'),confirmed:false,dryRun:true},positiveInt(req.params.id,'integration id'),action.actionId,req.body?.input||{});res.json({success:true,data})}));
 app.post('/api/ai-platform/integrations/:id/test',...authenticated,permit('test_integrations'),wrap(async(req:any,res:any)=>{const action=service.actions.get(String(req.body?.actionId||''));if(!action)throw new Error('ACTION_NOT_ALLOWED');if(action.sideEffectLevel!=='read_only'){const allowed=await r.checkPermission?.(req,'execute_write_integration_tests');if(!allowed||req.body?.confirm!==true)throw new Error('CONFIRMATION_REQUIRED')}const a=actor(req),data=await executor.execute({tenantId:await getTenantId(),agentId:req.body?.agentId?positiveInt(req.body.agentId,'agent id'):null,agentVersionId:null,conversationId:String(req.body?.conversationId||'controlled-test'),actorId:a.actorId,role:String(req.user?.role||'admin'),confirmed:req.body?.confirm===true,dryRun:req.body?.dryRun!==false},positiveInt(req.params.id,'integration id'),action.actionId,req.body?.input||{});res.json({success:true,data})}));
 app.get('/api/ai-platform/integrations/:id/executions',...authenticated,permit('view_integrations'),wrap(async(req:any,res:any)=>{const rows=await r.store.query('SELECT id,request_id requestId,action_id actionId,status,external_object_id externalObjectId,latency_ms latencyMs,error_code errorCode,started_at startedAt,completed_at completedAt FROM ai_integration_executions WHERE tenant_id=? AND integration_id=? ORDER BY id DESC LIMIT 100',[await getTenantId(),positiveInt(req.params.id,'integration id')]);res.json({success:true,rows})}));
 app.post('/api/ai-platform/integrations/post-call/:id/retry',...authenticated,permit('test_integrations'),wrap(async(req:any,res:any)=>{await r.store.query("UPDATE ai_integration_post_call_jobs SET status='pending',next_attempt_at=NOW(),error_code=NULL WHERE tenant_id=? AND id=? AND status IN('failed','dead_letter')",[await getTenantId(),positiveInt(req.params.id,'job id')]);res.json({success:true,data:{queued:true}})}));
 app.post('/api/ai-platform/integrations/:id/disable',...authenticated,permit('delete_integrations'),wrap(async(req:any,res:any)=>{await r.store.query("UPDATE ai_integrations SET enabled=0,status='disabled' WHERE tenant_id=? AND id=?",[await getTenantId(),positiveInt(req.params.id,'integration id')]);res.json({success:true,data:{status:'disabled'}})}));
}
