import crypto from'crypto';import{isAiPlatformCoreEnabled}from'../core/featureFlag.js';import{redactAiPlatformValue}from'../core/redaction.js';import type{AiAuditService}from'../audit/aiAuditService.js';import type{AiPlatformStore}from'../storage/aiPlatformStore.js';import{TransferDestinationResolver}from'./transferDestinationResolver.js';import type{TransferExecutionAdapter}from'./transferExecutionAdapter.js';import{TransferError}from'./transferErrors.js';import{enforceTransferPolicy,parseHumanTransferConfig}from'./humanTransferPolicyEngine.js';import{TransferRepository}from'./transferRepository.js';import type{TransferHooks,TransferProjection,TransferRequestInput}from'./transferTypes.js';

const ACTIVE=new Set(['requested','resolving','ready','executing','completed','failed','unavailable','dry_run_completed']);
const timeout=<T>(task:(signal:AbortSignal)=>Promise<T>,ms:number,external?:AbortSignal)=>new Promise<T>((resolve,reject)=>{const controller=new AbortController();let settled=false;const finish=(action:()=>void)=>{if(settled)return;settled=true;clearTimeout(timer);external?.removeEventListener('abort',cancel);action()},cancel=()=>{controller.abort();finish(()=>reject(new TransferError('transfer_timeout',409,'Transfer cancelled')))},timer=setTimeout(()=>{controller.abort();finish(()=>reject(new TransferError('transfer_timeout',504,'Transfer timed out')))},ms);if(external?.aborted)cancel();else external?.addEventListener('abort',cancel,{once:true});if(!settled)task(controller.signal).then(value=>finish(()=>resolve(value)),error=>finish(()=>reject(error)))});
export class HumanTransferService{
  private readonly repository:TransferRepository;private readonly inFlight=new Map<string,Promise<TransferProjection>>();
  constructor(private readonly store:AiPlatformStore,private readonly audit:AiAuditService,private readonly resolver:TransferDestinationResolver,private readonly adapter:TransferExecutionAdapter|null,private readonly options:{isEnabled?:()=>Promise<boolean>;hooks?:TransferHooks}={}){this.repository=new TransferRepository(store)}
  private async emit(input:TransferRequestInput,id:number,eventType:any,decision:string,details:Record<string,unknown>={}){await this.audit.append({tenantId:input.tenantId,traceId:input.traceId,actorType:input.requestedByType,actorId:input.requestedById,eventType,entityType:'transfer_request',entityId:String(id),decision,details:redactAiPlatformValue(details).value})}
  private projection(row:any,mode:'dry_run'|'live_test'):TransferProjection{return{id:Number(row.id),status:row.status,triggerType:row.trigger_type,destinationType:row.destination_type||null,destinationSafeLabel:row.destination_value_safe||null,fallbackAction:row.fallback_action||null,fallbackAvailable:Boolean(row.fallback_action),failureCode:row.failure_code||null,requestedAt:row.requested_at||null,startedAt:row.started_at||null,completedAt:row.completed_at||null,failedAt:row.failed_at||null,callbackRequired:row.fallback_action==='callback_request'||row.destination_type==='callback_request',transferMode:mode}}
  async get(tenantId:number,id:number,mode:'dry_run'|'live_test'='dry_run'){const rows=await this.repository.get(tenantId,id);if(!rows[0])throw new TransferError('transfer_not_allowed',404,'Transfer request not found');return this.projection(rows[0],mode)}
  request(input:TransferRequestInput,signal?:AbortSignal):Promise<TransferProjection>{const identity=input.liveCallId?crypto.createHash('sha256').update(input.liveCallId).digest('hex'):String(input.conversationId||'none'),key=`${input.tenantId}:${input.agentId}:${input.agentVersionId}:${identity}`,active=this.inFlight.get(key);if(active)return active.then(async result=>{await this.emit(input,result.id,'human_transfer_duplicate_suppressed','suppressed',{status:result.status});return result});const operation=this.run(input,signal).finally(()=>this.inFlight.delete(key));this.inFlight.set(key,operation);return operation}
  private async run(input:TransferRequestInput,signal?:AbortSignal):Promise<TransferProjection>{
    const enabled=await(this.options.isEnabled||isAiPlatformCoreEnabled)();if(!enabled)throw new TransferError('feature_disabled',503,'AI Platform Core is disabled');
    await this.options.hooks?.onTransferRequested({conversationId:input.conversationId,traceId:input.traceId});
    const liveHash=input.liveCallId?crypto.createHash('sha256').update(input.liveCallId).digest('hex'):null,existing=(await this.repository.findActive(input.tenantId,input.agentId,input.agentVersionId,liveHash,input.conversationId))[0];
    if(existing&&ACTIVE.has(existing.status)){await this.emit(input,Number(existing.id),'human_transfer_duplicate_suppressed','suppressed',{status:existing.status});return this.projection(existing,input.dryRun?'dry_run':'live_test')}
    const id=await this.repository.create(input);await this.emit(input,id,'human_transfer_requested','requested',{triggerType:input.triggerType,mode:input.dryRun?'dry_run':'live_test'});
    try{
      await this.repository.update(id,'resolving');await this.emit(input,id,'human_transfer_resolving','resolving');
      const versions=await this.store.query('SELECT config_json FROM ai_agent_versions WHERE id=? AND agent_id=? AND tenant_id=? LIMIT 1',[input.agentVersionId,input.agentId,input.tenantId]);if(!versions[0])throw new TransferError('transfer_not_allowed',404,'Agent version not found');let configJson:any;try{configJson=JSON.parse(String(versions[0].config_json||'{}'))}catch{throw new TransferError('destination_not_configured')};const config=parseHumanTransferConfig(configJson.humanTransfer),policies=await this.store.query('SELECT rules_json FROM ai_transfer_policies WHERE policy_key=? AND (tenant_id=? OR tenant_id IS NULL) ORDER BY tenant_id IS NULL LIMIT 1',[config.policyKey,input.tenantId]);if(policies[0]){let rules:any={};try{rules=JSON.parse(String(policies[0].rules_json||'{}'))}catch{}enforceTransferPolicy(config,rules)}
      const resolved=await timeout(inner=>this.resolver.resolve(config,inner),config.maxResolveMs,signal),destination=resolved.destination,fallbackAction=destination.type==='callback_request'?'callback_request':destination.fallback?destination.type:null;
      if(destination.fallback)await this.emit(input,id,'human_transfer_fallback_selected','selected',{destinationType:destination.type});
      await this.repository.update(id,'ready',{destinationType:destination.type,destinationSafeLabel:destination.safeLabel,destinationRef:destination.ref,fallbackAction});await this.emit(input,id,'human_transfer_ready','ready',{destinationType:destination.type,fallback:Boolean(destination.fallback)});
      if(input.dryRun){await this.repository.update(id,'dry_run_completed',{destinationType:destination.type,destinationSafeLabel:destination.safeLabel,destinationRef:destination.ref,fallbackAction});await this.emit(input,id,'human_transfer_dry_run_completed','completed',{destinationType:destination.type});return this.get(input.tenantId,id,'dry_run')}
      if(!input.liveCallId||!this.adapter)throw new TransferError('live_context_required');if(destination.type==='callback_request')throw new TransferError('destination_unavailable');
      const live=await this.adapter.validateLiveContext(input.liveCallId,signal);if(!live)throw new TransferError('live_call_not_found');if(!live.active)throw new TransferError('live_call_ended');
      await this.repository.update(id,'executing');await this.emit(input,id,'human_transfer_started','executing',{destinationType:destination.type});const result=await timeout(inner=>this.adapter!.executeBlindTransfer(live,destination,inner),config.maxExecutionMs,signal);if(!result.ok)throw new TransferError('transfer_failed',502,'Transfer failed');
      await this.repository.update(id,'completed',{pbxActionRef:result.actionRef});await this.emit(input,id,'human_transfer_completed','completed',{destinationType:destination.type});return this.get(input.tenantId,id,'live_test');
    }catch(error){if(signal?.aborted){await this.repository.update(id,'cancelled');await this.emit(input,id,'human_transfer_cancelled','cancelled');return this.get(input.tenantId,id,input.dryRun?'dry_run':'live_test')}const failure=error instanceof TransferError?error.failureCode:'transfer_failed',callbackRequired=['destination_not_configured','destination_not_found','destination_unavailable','outside_business_hours'].includes(failure);await this.repository.update(id,'failed',{failureCode:failure,fallbackAction:callbackRequired?'callback_request':'safe_apology'});await this.emit(input,id,'human_transfer_failed','failed',{failureCode:failure});return this.get(input.tenantId,id,input.dryRun?'dry_run':'live_test')}
  }
}
