import type { Express } from "express";
import { AiPlatformError } from "../../../core/errors.js";
import type { VoiceTranscriptService } from "../voiceTranscriptService.js";

const bool=(value:unknown)=>value===true||value==='true';
export function registerVoiceTranscriptRoutes(app:Express,r:any,service:VoiceTranscriptService){const{authenticated,permit,wrap,getTenantId,positiveInt,page,store}=r;
 app.get('/api/ai-platform/voice/history',...authenticated,permit('view_ai_voice_agents'),wrap(async(req:any,res:any)=>{const tenantId=await getTenantId(),p=page(req),rows=await store.query(`SELECT v.id,v.started_at,v.ended_at,v.state,v.caller_masked,v.failure_code,v.transfer_state,v.media_state,v.provider_state,v.route_binding_id,b.name binding_name,a.name agent_name,r.provider_key,r.first_response_latency_ms,r.input_audio_ms,r.output_audio_ms,r.interruption_count,r.tool_call_count,i.summary_safe,i.topic_safe,i.outcome_safe,i.next_action_safe,i.transferred,i.callback_requested,i.callback_confirmed,i.unresolved_issue,i.analysis_status,i.failure_code analysis_failure_code,i.usage_json FROM ai_voice_sessions v LEFT JOIN ai_voice_route_bindings b ON b.id=v.route_binding_id AND b.tenant_id=v.tenant_id JOIN ai_agents a ON a.id=v.agent_id AND a.tenant_id=v.tenant_id LEFT JOIN ai_realtime_voice_sessions r ON r.voice_session_id=v.id AND r.tenant_id=v.tenant_id LEFT JOIN ai_voice_call_insights i ON i.voice_session_id=v.id AND i.tenant_id=v.tenant_id WHERE v.tenant_id=? ORDER BY v.id DESC LIMIT ? OFFSET ?`,[tenantId,p.limit,p.offset]);res.json({success:true,rows:rows.map((row:any)=>({...row,usage:JSON.parse(row.usage_json||'{}'),usage_json:undefined}))})}));
 app.get('/api/ai-platform/voice/history/:id/transcript',...authenticated,permit('view_ai_voice_transcripts'),wrap(async(req:any,res:any)=>{const tenantId=await getTenantId(),voiceSessionId=positiveInt(req.params.id,'voice session id'),voice=(await store.query('SELECT id FROM ai_voice_sessions WHERE tenant_id=? AND id=?',[tenantId,voiceSessionId]))[0];if(!voice)throw new AiPlatformError('not_found',404,'Voice session not found');const rows=await service.list(tenantId,voiceSessionId),insight=(await store.query('SELECT summary_safe summary,topic_safe topic,outcome_safe outcome,customer_request_safe customerRequest,promised_actions_safe promisedActions,next_action_safe nextAction,transferred,callback_requested callbackRequested,callback_confirmed callbackConfirmed,unresolved_issue unresolvedIssue,analysis_status analysisStatus,failure_code analysisFailureCode,usage_json FROM ai_voice_call_insights WHERE tenant_id=? AND voice_session_id=?',[tenantId,voiceSessionId]))[0];res.json({success:true,data:{voiceSessionId,status:rows.length?'available':'transcript_unavailable',utterances:rows,insight:insight?{...insight,usage:JSON.parse(insight.usage_json||'{}'),usage_json:undefined}:null}})}));
 app.get('/api/ai-platform/voice/history/:id/transcript/export',...authenticated,permit('export_ai_voice_transcripts'),wrap(async(req:any,res:any)=>{const tenantId=await getTenantId(),voiceSessionId=positiveInt(req.params.id,'voice session id'),settings=(await store.query("SELECT setting_value FROM settings WHERE setting_key='ai.voice_transcripts_export'"))[0];if(settings?.setting_value!=='true')throw new AiPlatformError('feature_disabled',503,'Transcript export is disabled');const rows=await service.list(tenantId,voiceSessionId),format=String(req.query.format||'txt');if(format==='json'){res.type('application/json').attachment(`voice-${voiceSessionId}-transcript.json`).send(JSON.stringify({voiceSessionId,utterances:rows},null,2));return}if(format!=='txt')throw new AiPlatformError('invalid_request',400,'Invalid export format');res.type('text/plain').attachment(`voice-${voiceSessionId}-transcript.txt`).send(rows.map((row:any)=>`${row.speaker}: ${row.spokenText||row.text||''}${row.interrupted?' [interrupted]':''}${row.incomplete?' [incomplete]':''}`).join('\n'))}));
 app.get('/api/ai-platform/voice/live/:id/transcript-stream',...authenticated,permit('view_ai_voice_transcripts'),wrap(async(req:any,res:any)=>{const tenantId=await getTenantId(),voiceSessionId=positiveInt(req.params.id,'voice session id'),voice=(await store.query('SELECT id FROM ai_voice_sessions WHERE tenant_id=? AND id=?',[tenantId,voiceSessionId]))[0];if(!voice)throw new AiPlatformError('not_found',404,'Voice session not found');res.status(200).set({'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders?.();const send=(event:unknown)=>res.write(`data: ${JSON.stringify(event)}\n\n`),unsubscribe=service.subscribe(voiceSessionId,send),keepalive=setInterval(()=>res.write(': keepalive\n\n'),15000);keepalive.unref?.();req.on('close',()=>{clearInterval(keepalive);unsubscribe()});send({type:'connected',voiceSessionId})}));
 app.get('/api/ai-platform/voice/transcript-settings',...authenticated,permit('view_ai_voice_agents'),wrap(async(_req:any,res:any)=>{const rows=await store.query("SELECT setting_key,setting_value FROM settings WHERE setting_key LIKE 'ai.voice_transcripts_%' ORDER BY setting_key");res.json({success:true,data:Object.fromEntries(rows.map((row:any)=>[row.setting_key,row.setting_value]))})}));
 app.put('/api/ai-platform/voice/transcript-settings',...authenticated,permit('manage_ai_voice_agents'),wrap(async(req:any,res:any)=>{const allowed=new Set(['ai.voice_transcripts_save','ai.voice_transcripts_live','ai.voice_transcripts_save_ai','ai.voice_transcripts_save_partial','ai.voice_transcripts_post_call_summary','ai.voice_transcripts_pii_redaction','ai.voice_transcripts_export','ai.voice_transcripts_store_generated']),retention=[0,7,30,90,180,-1].includes(Number(req.body?.retentionDays))?Number(req.body.retentionDays):null;if(retention===null)throw new AiPlatformError('invalid_request',400,'Invalid transcript retention');for(const key of allowed)if(req.body?.[key]!==undefined)await store.query('UPDATE settings SET setting_value=? WHERE setting_key=?',[bool(req.body[key])?'true':'false',key]);await store.query("UPDATE settings SET setting_value=? WHERE setting_key='ai.voice_transcripts_retention_days'",[String(retention)]);res.json({success:true,data:{updated:true}})}));
 app.post('/api/ai-platform/voice/transcripts/retention-cleanup',...authenticated,permit('manage_ai_voice_agents'),wrap(async(_req:any,res:any)=>res.json({success:true,data:await service.cleanup(await getTenantId())})));
}
