import net from 'node:net';
import crypto from 'node:crypto';
import type { MediaTransportAdapter } from '../mediaTransportAdapter.js';
import type { AudioFrame, MediaTransportContext } from '../mediaTypes.js';
import { MediaError } from '../mediaErrors.js';
import { AudioResampler } from '../audioResampler.js';

const TYPE_TERMINATE=0x00,TYPE_UUID=0x01,TYPE_SLIN8=0x10,TYPE_SLIN16_16K=0x12,TYPE_ERROR=0xff;
export interface AudioSocketServerConfig { host:'127.0.0.1'|'::1';port:number;connectionTimeoutMs:number;transportFormat:'ast18_slin8'|'slin16' }
export function readAudioSocketServerConfig():AudioSocketServerConfig{const host=process.env.PBXPULS_AI_AUDIOSOCKET_HOST==='::1'?'::1':'127.0.0.1',port=Number(process.env.PBXPULS_AI_AUDIOSOCKET_PORT||0),transportFormat=process.env.PBXPULS_AI_AUDIOSOCKET_PACKET_MODE==='slin16'?'slin16':'ast18_slin8';return{host,port:Number.isInteger(port)&&port>=1024&&port<=65535?port:0,connectionTimeoutMs:5000,transportFormat}}
const packet = (type:number,payload:Uint8Array) => { const result=Buffer.allocUnsafe(3+payload.byteLength);result[0]=type;result.writeUInt16BE(payload.byteLength,1);Buffer.from(payload).copy(result,3);return result; };

export class AudioSocketAdapter implements MediaTransportAdapter {
  private server:net.Server|null=null;private socket:net.Socket|null=null;private context:MediaTransportContext|null=null;private handlers=new Set<(frame:AudioFrame)=>void|Promise<void>>();private buffer=Buffer.alloc(0);private sequence=0;private connectionId=crypto.randomUUID();private authenticated=false;private readyResolve:(()=>void)|null=null;private readyReject:((error:Error)=>void)|null=null;private readonly resampler=new AudioResampler();private metrics={audiosocketIngressPackets:0,audiosocketEgressPackets:0,ingressPacketType:null as string|null,egressPacketType:null as string|null,ingressSourceSampleRate:null as number|null,egressTargetSampleRate:null as number|null,ingressResampledFrames:0,egressResampledFrames:0,unknownPacketTypes:0,malformedPackets:0,unsupportedAudioPackets:0,protocolErrors:0,firstIngressAudioAt:null as string|null,firstEgressAudioAt:null as string|null};
  getCapabilities(){const config=readAudioSocketServerConfig(),ast18=config.transportFormat==='ast18_slin8';return{mode:'audiosocket' as const,available:true,live:true,network:true,codecs:['slin16']as const,audioSocketProtocol:{supportedInboundPacketTypes:[TYPE_SLIN8,TYPE_SLIN16_16K],supportedOutboundPacketTypes:ast18?[TYPE_SLIN8]:[TYPE_SLIN16_16K],preferredAsteriskPacketType:ast18?TYPE_SLIN8:TYPE_SLIN16_16K,preferredAsteriskSampleRate:ast18?8000:16000,internalSampleRate:16000,resamplingRequired:ast18,transportFormat:config.transportFormat}}}
  async validateConfig(){const config=readAudioSocketServerConfig();return{valid:config.port>0,errorCode:config.port>0?undefined:'live_media_not_configured'}}
  async createTransport(context:MediaTransportContext){if(this.server)throw new MediaError('conflict',409,'AudioSocket transport already exists');const config=readAudioSocketServerConfig();if(!config.port)throw new MediaError('feature_disabled',503,'AudioSocket port is not configured');this.context=context;this.server=net.createServer(socket=>this.accept(socket));this.server.maxConnections=1;await new Promise<void>((resolve,reject)=>{this.server!.once('error',reject);this.server!.listen(config.port,config.host,()=>{this.server!.off('error',reject);resolve()})})}
  async start(){const config=readAudioSocketServerConfig();if(this.authenticated)return;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{this.readyResolve=null;this.readyReject=null;reject(new MediaError('provider_not_configured',504,'AudioSocket connection timed out'))},config.connectionTimeoutMs);this.readyResolve=()=>{clearTimeout(timer);resolve()};this.readyReject=error=>{clearTimeout(timer);reject(error)}})}
  private accept(socket:net.Socket){if(this.socket){socket.destroy();return}socket.setNoDelay(true);socket.setTimeout(65000,()=>socket.destroy());this.socket=socket;socket.on('data',chunk=>this.parse(chunk));socket.on('error',()=>this.readyReject?.(new MediaError('internal_error',502,'AudioSocket connection failed')));socket.on('close',()=>{this.socket=null;this.authenticated=false})}
  private parse(chunk:Buffer){this.buffer=Buffer.concat([this.buffer,chunk]);while(this.buffer.length>=3){const type=this.buffer[0],length=this.buffer.readUInt16BE(1);if(length>4096){this.metrics.malformedPackets++;this.metrics.protocolErrors++;this.socket?.destroy();return}if(this.buffer.length<3+length)return;const payload=this.buffer.subarray(3,3+length);this.buffer=this.buffer.subarray(3+length);if(type===TYPE_TERMINATE){this.socket?.end();return}if(type===TYPE_ERROR){this.metrics.protocolErrors++;continue}if(type===TYPE_UUID){const expected=this.connectionId.replace(/-/g,'').toLowerCase(),received=payload.toString('hex').toLowerCase();if(length!==16||received!==expected){this.metrics.protocolErrors++;this.readyReject?.(new MediaError('permission_denied',403,'AudioSocket identity rejected'));this.socket?.destroy();return}this.authenticated=true;this.readyResolve?.();this.readyResolve=null;this.readyReject=null;continue}if(!this.authenticated||!this.context){this.metrics.protocolErrors++;continue}if(type!==TYPE_SLIN8&&type!==TYPE_SLIN16_16K){this.metrics.unknownPacketTypes++;if(type>=0x10&&type<=0x18)this.metrics.unsupportedAudioPackets++;continue}if(length===0||length%2!==0){this.metrics.malformedPackets++;continue}const sourceRate=type===TYPE_SLIN8?8000:16000,source=new Int16Array(payload.buffer.slice(payload.byteOffset,payload.byteOffset+payload.byteLength)),normalized=sourceRate===16000?source:this.resampler.resamplePcm16(source,sourceRate,16000),now=new Date().toISOString();this.metrics.audiosocketIngressPackets++;this.metrics.ingressPacketType=this.packetLabel(type);this.metrics.ingressSourceSampleRate=sourceRate;this.metrics.firstIngressAudioAt??=now;if(sourceRate!==16000)this.metrics.ingressResampledFrames++;const frame:AudioFrame={sequence:this.sequence++,timestampMs:Date.now(),direction:'ingress',codec:'slin16',sampleRate:16000,channels:1,durationMs:Math.max(1,Math.round(source.length/sourceRate*1000)),payload:new Uint8Array(normalized.buffer),source:type===TYPE_SLIN8?'audiosocket_ast18_slin8':'audiosocket_slin16',traceId:this.context.traceId,voiceSessionId:this.context.voiceSessionId,mediaSessionId:this.context.mediaSessionId};for(const handler of this.handlers)void handler(frame)}}
  async sendFrame(frame:AudioFrame){if(!this.socket||this.socket.destroyed||!this.authenticated)throw new MediaError('provider_not_configured',503,'AudioSocket is not connected');if(frame.codec!=='slin16'||frame.sampleRate!==16000||frame.payload.byteLength>4096||frame.payload.byteLength%2!==0)throw new MediaError('invalid_request',400,'Invalid AudioSocket output frame');const config=readAudioSocketServerConfig(),type=config.transportFormat==='ast18_slin8'?TYPE_SLIN8:TYPE_SLIN16_16K,source=new Int16Array(frame.payload.buffer.slice(frame.payload.byteOffset,frame.payload.byteOffset+frame.payload.byteLength)),targetRate=type===TYPE_SLIN8?8000:16000,converted=targetRate===16000?source:this.resampler.resamplePcm16(source,16000,targetRate),payload=new Uint8Array(converted.buffer);if(payload.byteLength>4096)throw new MediaError('invalid_request',400,'Invalid AudioSocket output frame');if(!this.socket.write(packet(type,payload)))await new Promise<void>(resolve=>this.socket!.once('drain',resolve));this.metrics.audiosocketEgressPackets++;this.metrics.egressPacketType=this.packetLabel(type);this.metrics.egressTargetSampleRate=targetRate;this.metrics.firstEgressAudioAt??=new Date().toISOString();if(targetRate!==16000)this.metrics.egressResampledFrames++}
  subscribeFrames(handler:(frame:AudioFrame)=>void|Promise<void>){this.handlers.add(handler);return()=>this.handlers.delete(handler)}
  getHealth(){return{state:this.socket?'connected':this.server?'listening':'disabled',failureCode:null}}
  getProtocolMetrics(){return{...this.metrics}}
  private packetLabel(type:number){return type===TYPE_SLIN8?'0x10_slin8':type===TYPE_SLIN16_16K?'0x12_slin16':`0x${type.toString(16).padStart(2,'0')}_unsupported`}
  getEndpoint(){const config=readAudioSocketServerConfig();return{externalHost:`${config.host}:${config.port}`,connectionId:this.connectionId}}
  async stop(){if(this.socket&&!this.socket.destroyed){this.socket.write(packet(TYPE_TERMINATE,new Uint8Array()));this.socket.destroy()}await new Promise<void>(resolve=>this.server?this.server.close(()=>resolve()):resolve());this.server=null;this.socket=null;this.context=null;this.buffer=Buffer.alloc(0);this.authenticated=false;this.handlers.clear()}
}
