import net from 'node:net';
import crypto from 'node:crypto';
import type { MediaTransportAdapter } from '../mediaTransportAdapter.js';
import type { AudioFrame, MediaTransportContext } from '../mediaTypes.js';
import { MediaError } from '../mediaErrors.js';

const TYPE_UUID = 0x01, TYPE_SLIN16_16K = 0x12, TYPE_TERMINATE = 0x00;
export interface AudioSocketServerConfig { host: '127.0.0.1'|'::1'; port: number; connectionTimeoutMs: number }
export function readAudioSocketServerConfig(): AudioSocketServerConfig { const host = process.env.PBXPULS_AI_AUDIOSOCKET_HOST === '::1' ? '::1' : '127.0.0.1', port = Number(process.env.PBXPULS_AI_AUDIOSOCKET_PORT || 0); return { host, port: Number.isInteger(port) && port >= 1024 && port <= 65535 ? port : 0, connectionTimeoutMs: 5000 }; }
const packet = (type:number,payload:Uint8Array) => { const result=Buffer.allocUnsafe(3+payload.byteLength);result[0]=type;result.writeUInt16BE(payload.byteLength,1);Buffer.from(payload).copy(result,3);return result; };

export class AudioSocketAdapter implements MediaTransportAdapter {
  private server:net.Server|null=null;private socket:net.Socket|null=null;private context:MediaTransportContext|null=null;private handlers=new Set<(frame:AudioFrame)=>void|Promise<void>>();private buffer=Buffer.alloc(0);private sequence=0;private connectionId=crypto.randomUUID();private authenticated=false;private readyResolve:(()=>void)|null=null;private readyReject:((error:Error)=>void)|null=null;
  getCapabilities(){return{mode:'audiosocket' as const,available:true,live:true,network:true,codecs:['slin16']as const}}
  async validateConfig(){const config=readAudioSocketServerConfig();return{valid:config.port>0,errorCode:config.port>0?undefined:'live_media_not_configured'}}
  async createTransport(context:MediaTransportContext){if(this.server)throw new MediaError('conflict',409,'AudioSocket transport already exists');const config=readAudioSocketServerConfig();if(!config.port)throw new MediaError('feature_disabled',503,'AudioSocket port is not configured');this.context=context;this.server=net.createServer(socket=>this.accept(socket));this.server.maxConnections=1;await new Promise<void>((resolve,reject)=>{this.server!.once('error',reject);this.server!.listen(config.port,config.host,()=>{this.server!.off('error',reject);resolve()})})}
  async start(){const config=readAudioSocketServerConfig();if(this.authenticated)return;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{this.readyResolve=null;this.readyReject=null;reject(new MediaError('provider_not_configured',504,'AudioSocket connection timed out'))},config.connectionTimeoutMs);this.readyResolve=()=>{clearTimeout(timer);resolve()};this.readyReject=error=>{clearTimeout(timer);reject(error)}})}
  private accept(socket:net.Socket){if(this.socket){socket.destroy();return}socket.setNoDelay(true);socket.setTimeout(65000,()=>socket.destroy());this.socket=socket;socket.on('data',chunk=>this.parse(chunk));socket.on('error',()=>this.readyReject?.(new MediaError('internal_error',502,'AudioSocket connection failed')));socket.on('close',()=>{this.socket=null;this.authenticated=false})}
  private parse(chunk:Buffer){this.buffer=Buffer.concat([this.buffer,chunk]);while(this.buffer.length>=3){const type=this.buffer[0],length=this.buffer.readUInt16BE(1);if(length>4096){this.socket?.destroy();return}if(this.buffer.length<3+length)return;const payload=this.buffer.subarray(3,3+length);this.buffer=this.buffer.subarray(3+length);if(type===TYPE_TERMINATE){this.socket?.end();return}if(type===TYPE_UUID){const expected=this.connectionId.replace(/-/g,'').toLowerCase(),received=payload.toString('hex').toLowerCase();if(length!==16||received!==expected){this.readyReject?.(new MediaError('permission_denied',403,'AudioSocket identity rejected'));this.socket?.destroy();return}this.authenticated=true;this.readyResolve?.();this.readyResolve=null;this.readyReject=null;continue}if(!this.authenticated||type!==TYPE_SLIN16_16K||!this.context)continue;const frame:AudioFrame={sequence:this.sequence++,timestampMs:Date.now(),direction:'ingress',codec:'slin16',sampleRate:16000,channels:1,durationMs:Math.max(1,Math.round(length/32)),payload:new Uint8Array(payload),source:'audiosocket',traceId:this.context.traceId,voiceSessionId:this.context.voiceSessionId,mediaSessionId:this.context.mediaSessionId};for(const handler of this.handlers)void handler(frame)}}
  async sendFrame(frame:AudioFrame){if(!this.socket||this.socket.destroyed||!this.authenticated)throw new MediaError('provider_not_configured',503,'AudioSocket is not connected');if(frame.codec!=='slin16'||frame.sampleRate!==16000||frame.payload.byteLength>4096)throw new MediaError('invalid_request',400,'Invalid AudioSocket output frame');if(!this.socket.write(packet(TYPE_SLIN16_16K,frame.payload)))await new Promise<void>(resolve=>this.socket!.once('drain',resolve))}
  subscribeFrames(handler:(frame:AudioFrame)=>void|Promise<void>){this.handlers.add(handler);return()=>this.handlers.delete(handler)}
  getHealth(){return{state:this.socket?'connected':this.server?'listening':'disabled',failureCode:null}}
  getEndpoint(){const config=readAudioSocketServerConfig();return{externalHost:`${config.host}:${config.port}`,connectionId:this.connectionId}}
  async stop(){if(this.socket&&!this.socket.destroyed){this.socket.write(packet(TYPE_TERMINATE,new Uint8Array()));this.socket.destroy()}await new Promise<void>(resolve=>this.server?this.server.close(()=>resolve()):resolve());this.server=null;this.socket=null;this.context=null;this.buffer=Buffer.alloc(0);this.authenticated=false;this.handlers.clear()}
}
