import type { Express } from 'express';import { AiPlatformError } from '../../../core/errors.js';import type { ControlledLiveVoiceService } from '../controlledLiveVoiceService.js';
export function registerLiveVoiceRoutes(app:Express,r:any,service:ControlledLiveVoiceService){const{authenticated,permit,wrap,getTenantId,actor}=r;
 app.get('/api/ai-platform/voice/live-test/status',...authenticated,permit('view_ai_voice_live_test'),wrap(async(_req:any,res:any)=>res.json({success:true,data:await service.status(await getTenantId())})));
 app.post('/api/ai-platform/voice/live-test/validate',...authenticated,permit('configure_ai_voice_live_test'),wrap(async(req:any,res:any)=>{const tenantId=await getTenantId(),a=actor(req);await r.audit.append({tenantId,...a,eventType:'live_voice_test_validation_started',entityType:'voice_live_test',decision:'started',details:{}});const data=await service.status(tenantId);if(!data.ready)await r.audit.append({tenantId,...a,eventType:'live_voice_test_validation_failed',entityType:'voice_live_test',decision:'not_ready',details:{failed:data.readiness.items.filter((item:any)=>!item.ready).map((item:any)=>item.key)}});res.json({success:true,data})}));
 app.post('/api/ai-platform/voice/live-test/run-checklist',...authenticated,permit('execute_ai_voice_live_test_checks'),wrap(async(_req:any,res:any)=>res.json({success:true,data:await service.status(await getTenantId())})));
 app.post('/api/ai-platform/voice/live-test/dialplan-preview',...authenticated,permit('configure_ai_voice_live_test'),wrap(async(req:any,res:any)=>{if(req.body&&Object.keys(req.body).some(key=>!['confirm'].includes(key)))throw new AiPlatformError('invalid_request',400,'Dialplan values are server configured');res.json({success:true,data:await service.dialplanPreview()})}));
 app.post('/api/ai-platform/voice/live-test/enable',...authenticated,permit('enable_ai_voice_live_test'),wrap(async(req:any,res:any)=>{if(req.body?.confirm!==true)throw new AiPlatformError('invalid_request',400,'Explicit confirmation is required');const a=actor(req);res.json({success:true,data:await service.setEnabled(await getTenantId(),true,a.traceId)})}));
 app.post('/api/ai-platform/voice/live-test/disable',...authenticated,permit('enable_ai_voice_live_test'),wrap(async(req:any,res:any)=>{if(req.body?.confirm!==true)throw new AiPlatformError('invalid_request',400,'Explicit confirmation is required');const a=actor(req);res.json({success:true,data:await service.setEnabled(await getTenantId(),false,a.traceId)})}));
}
