/** Shared sidebar labels, permission editor and server visibility policy. */
export const SYSTEM_SECTIONS = [
  {"defaultVisible": true, "key": "calls", "label": "Реестр звонков"},
  {"defaultVisible": true, "key": "dialer", "label": "Телефон"},
  {"defaultVisible": true, "key": "directory", "label": "Справочник"},
  {"defaultVisible": true, "key": "reports", "label": "Отчеты и аналитика"},
  {"defaultVisible": true, "key": "marketing", "label": "Маркетинг"},
  {"defaultVisible": true, "key": "monitoring", "label": "Мониторинг"},
  {"defaultVisible": true, "key": "management", "label": "Управление"},
  {"defaultVisible": true, "key": "balance", "label": "Баланс"},
  {"defaultVisible": true, "key": "gsm_gateways", "label": "GSM-шлюзы"},
  {"defaultVisible": true, "key": "ai_platform", "label": "AI Platform"},
  {"defaultVisible": true, "key": "settings", "label": "Настройки"},
  {"defaultVisible": true, "key": "about", "label": "О системе"},
  {"defaultVisible": false, "key": "scripts", "label": "AI Platform / AI-скрипты"},
  {"defaultVisible": false, "key": "ai_assistant", "label": "AI Platform / AI-автоответчик"},
  {"defaultVisible": false, "key": "ai_pbx_admin", "label": "Мониторинг / AI администратор"},
 ] as const;
export type SystemSectionKey = typeof SYSTEM_SECTIONS[number]['key'];
export type ModuleVisibility = Record<SystemSectionKey, boolean>;
export type PermissionKind = 'tab' | 'feature' | 'su';
interface PermissionDefinition { key:string; label:string; kind:PermissionKind; hint:string; bulk?:boolean; moduleKey?:SystemSectionKey }
interface GroupDefinition { id:SystemSectionKey; title:string; description:string; color:'blue'; moduleKey:SystemSectionKey; rows:readonly PermissionDefinition[] }
export const PERMISSION_GROUPS = [
  { id: "calls", title: "Реестр звонков", description: "Права раздела «Реестр звонков».", color: "blue", moduleKey: "calls", rows: [
    {"kind": "tab", "hint": "Показывает раздел Реестр звонков", "key": "view_calls", "label": "Открыть вкладку звонков"},
    {"bulk": false, "kind": "feature", "hint": "Ограничивает журнал и отчеты добавочным номером пользователя", "key": "own_calls_only", "label": "Только мои звонки"},
    {"bulk": false, "kind": "feature", "hint": "Ограничивает звонки отделами, назначенными руководителю в настройках пользователя", "key": "department_calls_only", "label": "Только звонки подчинённых отделов"},
    {"kind": "feature", "hint": "Показывает DTMF-цифры, введённые сотрудником после ответа на исходящий звонок", "key": "view_call_dtmf", "label": "Введённые добавочные номера"},
    {"kind": "feature", "hint": "Разрешает менять статус/обработку звонка", "key": "process_calls", "label": "Обработка звонков"},
    {"kind": "feature", "hint": "Разрешает слушать записи разговоров", "key": "listen_recordings", "label": "Прослушивание записей"},
    {"kind": "feature", "hint": "Удаление записей звонков", "key": "delete_records", "label": "Удаление записей звонков"},
  ] },
  { id: "dialer", title: "Телефон", description: "Права раздела «Телефон».", color: "blue", moduleKey: "dialer", rows: [
    {"kind": "feature", "hint": "Разрешает звонить из интерфейса", "key": "make_calls", "label": "Click2Call"},
    {"kind": "feature", "hint": "Показывает модальное окно с логом инициации звонка", "key": "show_call_modal", "label": "Окно Click2Call"},
  ] },
  { id: "directory", title: "Справочник", description: "Права раздела «Справочник».", color: "blue", moduleKey: "directory", rows: [
    {"kind": "tab", "hint": "Показывает телефонный справочник", "key": "view_directory", "label": "Открыть вкладку справочника"},
    {"kind": "feature", "hint": "Создание, изменение и удаление контактов", "key": "edit_directory", "label": "Редактирование справочника"},
    {"bulk": false, "kind": "feature", "hint": "Создание личных и изменение/удаление только собственных личных контактов", "key": "edit_own_directory_contacts", "label": "Только свои контакты"},
    {"kind": "feature", "hint": "Google/CSV/vCard импорт только в личный справочник пользователя", "key": "directory_import_contacts", "label": "Личный импорт контактов"},
    {"kind": "feature", "hint": "Глобальные переключатели источников личного импорта", "key": "directory_manage_import_settings", "label": "Настройки импорта контактов"},
    {"kind": "feature", "hint": "Админский импорт CSV/JSON, экспорт, нормализация и sync-url", "key": "manage_directory_import", "label": "Импорт и синхронизация"},
    {"kind": "feature", "hint": "Разрешает добавлять и удалять номера из ЧС", "key": "manage_blacklist", "label": "Черный список"},
    {"kind": "feature", "hint": "Профили справочника SIP-телефонов", "key": "manage_phonebook_gateway", "label": "Профили справочника SIP-телефонов"},
    {"kind": "feature", "hint": "Источники импорта справочника", "key": "import_directory", "label": "Источники импорта справочника"},
  ] },
  { id: "reports", title: "Отчеты и аналитика", description: "Права раздела «Отчеты и аналитика».", color: "blue", moduleKey: "reports", rows: [
    {"kind": "tab", "hint": "Показывает отчеты и аналитику", "key": "view_reports", "label": "Открыть вкладку отчетов"},
    {"kind": "feature", "hint": "Разрешает выгрузку таблиц и отчетов", "key": "export_excel", "label": "Экспорт Excel"},
  ] },
  { id: "marketing", title: "Маркетинг", description: "Права раздела «Маркетинг».", color: "blue", moduleKey: "marketing", rows: [
    {"kind": "tab", "hint": "Показывает раздел Маркетинг", "key": "view_marketing", "label": "Открыть вкладку маркетинга"},
    {"kind": "feature", "hint": "Разрешает изменять маркетинговые настройки", "key": "manage_marketing", "label": "Управление маркетингом"},
    {"kind": "feature", "hint": "Разрешает управлять сайтами, номерами и правилами подмены", "key": "manage_calltracking", "label": "CallTracking"},
    {"kind": "feature", "hint": "Разрешает подключать счетчики, цели и интеграции Метрики", "key": "manage_yandex_metrika", "label": "Яндекс Метрика"},
    {"kind": "feature", "hint": "Разрешает управлять настройками расходов и отчетами Директа", "key": "manage_yandex_direct", "label": "Яндекс Директ"},
    {"kind": "tab", "hint": "Просмотр доступных заявок с форм сайта", "key": "view_site_form_leads", "label": "Заявки с сайта"},
    {"kind": "feature", "hint": "Статусы, комментарии и завершение заявок", "key": "manage_site_form_leads", "label": "Обработка заявок"},
    {"kind": "feature", "hint": "Click-to-call из заявки", "key": "call_site_form_leads", "label": "Звонки по заявкам"},
    {"kind": "feature", "hint": "Назначение ответственного и подразделения", "key": "assign_site_form_leads", "label": "Назначение заявок"},
    {"kind": "feature", "hint": "CSV/XLSX-выгрузка заявок", "key": "export_site_form_leads", "label": "Экспорт заявок"},
    {"kind": "feature", "hint": "KPI, SLA и конверсии заявок", "key": "view_site_form_reports", "label": "Отчёты по заявкам"},
    {"kind": "feature", "hint": "Webhook, токены и настройки сайтов", "key": "manage_site_form_integrations", "label": "Интеграции форм"},
    {"kind": "feature", "hint": "Безопасный журнал приёма заявок", "key": "view_site_form_webhook_logs", "label": "Журнал webhook"},
  ] },
  { id: "monitoring", title: "Мониторинг", description: "Права раздела «Мониторинг».", color: "blue", moduleKey: "monitoring", rows: [
    {"kind": "tab", "hint": "Показывает общий раздел мониторинга", "key": "view_monitoring", "label": "Открыть раздел мониторинга"},
    {"kind": "tab", "hint": "Показывает live-сессии Asterisk", "key": "view_active_calls", "label": "Активные звонки"},
    {"kind": "tab", "hint": "Показывает IP/RTP-телеметрию, MOS, джиттер, RTT и потери пакетов", "key": "view_quality", "label": "Качество связи"},
    {"kind": "tab", "hint": "Показывает tcpdump и SIP/RTP диагностику", "key": "view_tcpdump", "label": "TCPDUMP / SIP-RTP"},
    {"kind": "tab", "hint": "Реальный SIP flow из ограниченного PCAP; ключ сохранён для совместимости", "key": "view_sngrep", "label": "SIP-диалоги"},
    {"kind": "tab", "hint": "Диагностика, Asterisk CLI и справочная информация", "key": "view_cli", "label": "Командный центр"},
    {"kind": "tab", "hint": "Показывает read-only просмотр CDR/CEL и таблиц", "key": "view_db_explorer", "label": "DB Explorer"},
    {"kind": "tab", "hint": "Показывает Health Report сервера и служб", "key": "view_health", "label": "Состояние АТС"},
    {"kind": "tab", "hint": "Показывает SIP/PJSIP регистрации, IP-адреса, User-Agent и конфликтующие устройства", "key": "view_sip_devices_map", "label": "Карта IP / SIP устройств"},
    {"kind": "tab", "hint": "Открывает централизованный анализ журналов и трассировку звонка", "key": "view_log_analysis", "label": "Анализ логов"},
    {"kind": "tab", "hint": "Объединяет CDR, CEL, SIP, RTCP, логи, записи и события безопасности", "key": "view_call_intelligence", "label": "Карточка звонка"},
    {"kind": "tab", "hint": "Открывает центр мониторинга безопасности", "key": "view_security", "label": "Безопасность"},
    {"kind": "feature", "hint": "Просмотр событий и внешних IP", "key": "view_security_events", "label": "События безопасности"},
    {"kind": "feature", "hint": "Просмотр Firewall и сетевых сервисов", "key": "view_firewall", "label": "Firewall и порты"},
    {"kind": "feature", "hint": "Просмотр jail и блокировок", "key": "view_fail2ban", "label": "Fail2Ban"},
    {"kind": "su", "hint": "Ручные действия только при включенном feature flag", "key": "manage_fail2ban", "label": "Управление Fail2Ban"},
    {"kind": "su", "hint": "Управление доверенными IP PBXPuls", "key": "manage_security_whitelist", "label": "Белый список безопасности"},
    {"kind": "feature", "hint": "Просмотр проверок и изменений файлов", "key": "view_security_config_audit", "label": "Аудит конфигурации"},
    {"kind": "su", "hint": "Управление мониторингом и уведомлениями", "key": "manage_security_settings", "label": "Настройки безопасности"},
    {"kind": "feature", "hint": "Экспорт отчетов безопасности", "key": "export_security_report", "label": "Экспорт security-отчетов"},
    {"kind": "tab", "hint": "Разрешает доступ к разделу \"AI администратор АТС\"", "moduleKey": "ai_pbx_admin", "key": "view_ai_pbx_admin", "label": "AI администратор: Открыть AI-администратор"},
    {"kind": "feature", "hint": "Разрешает изменять системные настройки и промпты AI-администратора АТС", "moduleKey": "ai_pbx_admin", "key": "manage_ai_pbx_admin", "label": "AI администратор: Управление AI-администратором"},
  ] },
  { id: "management", title: "Управление", description: "Права раздела «Управление».", color: "blue", moduleKey: "management", rows: [
    {"kind": "tab", "hint": "Показывает раздел Управление АТС", "key": "view_management", "label": "Открыть вкладку управления"},
    {"kind": "su", "hint": "Массовые операции с внутренними номерами", "key": "bulk_extensions", "label": "Массовые EXT"},
    {"kind": "su", "hint": "Управление SIP-транками", "key": "manage_trunks", "label": "Транки"},
    {"kind": "su", "hint": "Управление исходящими маршрутами", "key": "manage_outbound_routes", "label": "Исходящие правила"},
    {"kind": "su", "hint": "Управление номерной емкостью", "key": "manage_numbering_capacity", "label": "Номерная емкость"},
    {"kind": "su", "hint": "Разрешает потенциально опасные изменения FreePBX/Asterisk", "key": "dangerous_pbx_write", "label": "Опасные изменения АТС"},
  ] },
  { id: "balance", title: "Баланс", description: "Права раздела «Баланс».", color: "blue", moduleKey: "balance", rows: [
    {"kind": "tab", "hint": "Показывает раздел Баланс операторов", "key": "view_balance", "label": "Открыть вкладку баланса"},
    {"kind": "su", "hint": "Управление провайдерами проверки баланса", "key": "manage_balance_providers", "label": "Провайдеры баланса"},
    {"kind": "feature", "hint": "Аналитика баланса и расходов", "key": "view_balance_analytics", "label": "Аналитика баланса и расходов"},
    {"kind": "feature", "hint": "Источники баланса и пакеты минут", "key": "manage_balance_sources", "label": "Источники баланса и пакеты минут"},
    {"kind": "feature", "hint": "Предупреждения о балансе", "key": "view_balance_alerts", "label": "Предупреждения о балансе"},
  ] },
  { id: "gsm_gateways", title: "GSM-шлюзы", description: "Права раздела «GSM-шлюзы».", color: "blue", moduleKey: "gsm_gateways", rows: [
    {"kind": "tab", "hint": "Состояние GSM-портов и SIP endpoints", "key": "view_gsm_gateways", "label": "GSM-шлюзы"},
    {"kind": "feature", "hint": "Просмотр входящих и исходящих SMS", "key": "view_gsm_sms", "label": "История GSM SMS"},
    {"kind": "su", "hint": "Preview и отправка SMS", "key": "send_gsm_sms", "label": "Отправка GSM SMS"},
    {"kind": "feature", "hint": "Текущий баланс, история и графики расходов", "key": "view_gsm_balances", "label": "Балансы GSM SIM"},
    {"kind": "su", "hint": "USSD-проверка и расписание автообновления", "key": "manage_gsm_balances", "label": "Управление балансами GSM"},
    {"kind": "su", "hint": "Шаблоны, Preview и выполнение USSD-команд", "key": "manage_gsm_services", "label": "USSD и услуги GSM"},
    {"kind": "su", "hint": "Подключение OpenVox и AMI", "key": "manage_gsm_gateways", "label": "Настройки GSM-шлюзов"},
  ] },
  { id: "ai_platform", title: "AI Platform", description: "Права раздела «AI Platform».", color: "blue", moduleKey: "ai_platform", rows: [
    {"kind": "tab", "hint": "Открыть AI Platform", "key": "view_ai_platform", "label": "Открыть AI Platform"},
    {"kind": "feature", "hint": "Управление AI-сотрудниками", "key": "manage_ai_agents", "label": "Управление AI-сотрудниками"},
    {"kind": "feature", "hint": "Провайдеры AI и подключения", "key": "manage_ai_providers", "label": "Провайдеры AI и подключения"},
    {"kind": "feature", "hint": "Просмотр инструментов", "key": "view_ai_tools", "label": "Просмотр инструментов"},
    {"kind": "feature", "hint": "Управление инструментами", "key": "manage_ai_tools", "label": "Управление инструментами"},
    {"kind": "feature", "hint": "Журнал действий AI", "key": "view_ai_audit", "label": "Журнал действий AI"},
    {"kind": "feature", "hint": "Выполнение инструментов чтения", "key": "execute_ai_read_tools", "label": "Выполнение инструментов чтения"},
    {"kind": "feature", "hint": "Подтверждение действий AI", "key": "approve_ai_actions", "label": "Подтверждение действий AI"},
    {"kind": "feature", "hint": "Настройки платформы", "key": "manage_ai_platform", "label": "Настройки платформы"},
    {"kind": "feature", "hint": "Создание AI-сотрудников", "key": "create_ai_agents", "label": "Создание AI-сотрудников"},
    {"kind": "feature", "hint": "Клонирование AI-сотрудников", "key": "clone_ai_agents", "label": "Клонирование AI-сотрудников"},
    {"kind": "feature", "hint": "Публикация AI-сотрудников", "key": "publish_ai_agents", "label": "Публикация AI-сотрудников"},
    {"kind": "feature", "hint": "Просмотр AI-сотрудников", "key": "view_ai_agents", "label": "Просмотр AI-сотрудников"},
    {"kind": "feature", "hint": "Редактирование AI-сотрудников", "key": "edit_ai_agents", "label": "Редактирование AI-сотрудников"},
    {"kind": "feature", "hint": "Просмотр телефонии AI", "key": "view_ai_telephony", "label": "Просмотр телефонии AI"},
    {"kind": "feature", "hint": "Настройка телефонии AI", "key": "configure_ai_telephony", "label": "Настройка телефонии AI"},
    {"kind": "feature", "hint": "Экспертный режим", "key": "ai_platform_expert_mode", "label": "Экспертный режим"},
    {"kind": "feature", "hint": "Шаблоны AI-сотрудников", "key": "manage_ai_templates", "label": "Шаблоны AI-сотрудников"},
    {"kind": "feature", "hint": "Профили поведения", "key": "manage_ai_behavior_profiles", "label": "Профили поведения"},
    {"kind": "feature", "hint": "Политики AI", "key": "manage_ai_policies", "label": "Политики AI"},
    {"kind": "feature", "hint": "Тестовые сессии AI", "key": "run_ai_test_sessions", "label": "Тестовые сессии AI"},
    {"kind": "feature", "hint": "Редактирование баз знаний", "key": "manage_ai_knowledge", "label": "Редактирование баз знаний"},
    {"kind": "feature", "hint": "Просмотр баз знаний", "key": "view_ai_knowledge", "label": "Просмотр баз знаний"},
    {"kind": "feature", "hint": "Публикация баз знаний", "key": "publish_ai_knowledge", "label": "Публикация баз знаний"},
    {"kind": "feature", "hint": "Редактирование обучения", "key": "manage_ai_training", "label": "Редактирование обучения"},
    {"kind": "feature", "hint": "Просмотр обучения", "key": "view_ai_training", "label": "Просмотр обучения"},
    {"kind": "feature", "hint": "Публикация обучения", "key": "publish_ai_training", "label": "Публикация обучения"},
    {"kind": "feature", "hint": "Предпросмотр контекста", "key": "view_ai_context_preview", "label": "Предпросмотр контекста"},
    {"kind": "feature", "hint": "Запуск песочницы", "key": "execute_ai_sandbox", "label": "Запуск песочницы"},
    {"kind": "feature", "hint": "Журнал выполнения инструментов", "key": "view_ai_tool_executions", "label": "Журнал выполнения инструментов"},
    {"kind": "feature", "hint": "Тестирование инструментов", "key": "test_ai_tools", "label": "Тестирование инструментов"},
    {"kind": "feature", "hint": "Запросы перевода на сотрудника", "key": "view_ai_transfer_requests", "label": "Запросы перевода на сотрудника"},
    {"kind": "feature", "hint": "Политики перевода", "key": "manage_ai_transfer_policies", "label": "Политики перевода"},
    {"kind": "feature", "hint": "Тестирование перевода на сотрудника", "key": "test_ai_human_transfer", "label": "Тестирование перевода на сотрудника"},
    {"kind": "feature", "hint": "Просмотр действий AI", "key": "view_ai_actions", "label": "Просмотр действий AI"},
    {"kind": "feature", "hint": "Управление действиями AI", "key": "manage_ai_actions", "label": "Управление действиями AI"},
    {"kind": "feature", "hint": "Выполнение действий низкого риска", "key": "execute_ai_low_risk_actions", "label": "Выполнение действий низкого риска"},
    {"kind": "feature", "hint": "Просмотр запросов обратного звонка", "key": "view_ai_callback_requests", "label": "Просмотр запросов обратного звонка"},
    {"kind": "feature", "hint": "Обработка обратных звонков", "key": "manage_ai_callback_requests", "label": "Обработка обратных звонков"},
    {"kind": "feature", "hint": "Назначение действий AI-сотрудникам", "key": "assign_ai_actions", "label": "Назначение действий AI-сотрудникам"},
    {"kind": "feature", "hint": "Голосовой шлюз: состояние", "key": "view_ai_voice_status", "label": "Голосовой шлюз: состояние"},
    {"kind": "feature", "hint": "Голосовой шлюз: сессии", "key": "view_ai_voice_sessions", "label": "Голосовой шлюз: сессии"},
    {"kind": "feature", "hint": "Голосовой шлюз: привязки маршрутов", "key": "manage_ai_voice_bindings", "label": "Голосовой шлюз: привязки маршрутов"},
    {"kind": "feature", "hint": "Управление голосовым шлюзом", "key": "control_ai_voice_gateway", "label": "Управление голосовым шлюзом"},
    {"kind": "feature", "hint": "Тестирование голосового шлюза", "key": "test_ai_voice_gateway", "label": "Тестирование голосового шлюза"},
    {"kind": "feature", "hint": "Медиатранспорт: состояние", "key": "view_ai_voice_media_status", "label": "Медиатранспорт: состояние"},
    {"kind": "feature", "hint": "Медиатранспорт: сессии", "key": "view_ai_voice_media_sessions", "label": "Медиатранспорт: сессии"},
    {"kind": "feature", "hint": "Тестирование медиатранспорта", "key": "test_ai_voice_media", "label": "Тестирование медиатранспорта"},
    {"kind": "feature", "hint": "Управление медиатранспортом", "key": "manage_ai_voice_media", "label": "Управление медиатранспортом"},
    {"kind": "feature", "hint": "Realtime: состояние", "key": "view_ai_realtime_voice_status", "label": "Realtime: состояние"},
    {"kind": "feature", "hint": "Realtime: голосовые сессии", "key": "view_ai_realtime_voice_sessions", "label": "Realtime: голосовые сессии"},
    {"kind": "feature", "hint": "Тестирование Realtime", "key": "test_ai_realtime_voice", "label": "Тестирование Realtime"},
    {"kind": "feature", "hint": "Управление Realtime", "key": "manage_ai_realtime_voice", "label": "Управление Realtime"},
    {"kind": "feature", "hint": "Просмотр живого голосового теста", "key": "view_ai_voice_live_test", "label": "Просмотр живого голосового теста"},
    {"kind": "feature", "hint": "Настройка живого голосового теста", "key": "configure_ai_voice_live_test", "label": "Настройка живого голосового теста"},
    {"kind": "feature", "hint": "Включение живого голосового теста", "key": "enable_ai_voice_live_test", "label": "Включение живого голосового теста"},
    {"kind": "feature", "hint": "Проверки живого голосового теста", "key": "execute_ai_voice_live_test_checks", "label": "Проверки живого голосового теста"},
    {"kind": "feature", "hint": "Просмотр голосовых AI-сотрудников", "key": "view_ai_voice_agents", "label": "Просмотр голосовых AI-сотрудников"},
    {"kind": "feature", "hint": "Управление голосовыми AI-сотрудниками", "key": "manage_ai_voice_agents", "label": "Управление голосовыми AI-сотрудниками"},
    {"kind": "feature", "hint": "Тестирование голосовых AI-сотрудников", "key": "test_ai_voice_agents", "label": "Тестирование голосовых AI-сотрудников"},
    {"kind": "feature", "hint": "Голосовые маршруты AI", "key": "manage_ai_voice_routes", "label": "Голосовые маршруты AI"},
    {"kind": "feature", "hint": "Просмотр расшифровок разговоров", "key": "view_ai_voice_transcripts", "label": "Просмотр расшифровок разговоров"},
    {"kind": "feature", "hint": "Экспорт расшифровок разговоров", "key": "export_ai_voice_transcripts", "label": "Экспорт расшифровок разговоров"},
    {"kind": "feature", "hint": "Просмотр голосовых профилей", "key": "view_ai_voice_profiles", "label": "Просмотр голосовых профилей"},
    {"kind": "feature", "hint": "Управление голосовыми профилями", "key": "manage_ai_voice_profiles", "label": "Управление голосовыми профилями"},
    {"kind": "feature", "hint": "Просмотр каталога голосов", "key": "view_ai_voice_catalog", "label": "Просмотр каталога голосов"},
    {"kind": "feature", "hint": "Управление каталогом голосов", "key": "manage_ai_voice_catalog", "label": "Управление каталогом голосов"},
    {"kind": "feature", "hint": "Предпрослушивание голоса", "key": "generate_ai_voice_preview", "label": "Предпрослушивание голоса"},
    {"kind": "feature", "hint": "Просмотр внутренних номеров AI", "key": "view_ai_extensions", "label": "Просмотр внутренних номеров AI"},
    {"kind": "feature", "hint": "Создание внутренних номеров AI", "key": "create_ai_extensions", "label": "Создание внутренних номеров AI"},
    {"kind": "feature", "hint": "Изменение внутренних номеров AI", "key": "update_ai_extensions", "label": "Изменение внутренних номеров AI"},
    {"kind": "feature", "hint": "Публикация внутренних номеров AI", "key": "publish_ai_extensions", "label": "Публикация внутренних номеров AI"},
    {"kind": "feature", "hint": "Удаление внутренних номеров AI", "key": "delete_ai_extensions", "label": "Удаление внутренних номеров AI"},
    {"kind": "feature", "hint": "Просмотр передачи звонка", "key": "view_ai_handoff", "label": "Просмотр передачи звонка"},
    {"kind": "feature", "hint": "Настройка передачи звонка", "key": "configure_ai_handoff", "label": "Настройка передачи звонка"},
    {"kind": "feature", "hint": "Тестирование передачи звонка", "key": "test_ai_handoff", "label": "Тестирование передачи звонка"},
    {"kind": "feature", "hint": "Публикация передачи звонка", "key": "publish_ai_handoff", "label": "Публикация передачи звонка"},
    {"kind": "feature", "hint": "Предпросмотр создания AI-сотрудника", "key": "preview_ai_agents", "label": "Предпросмотр создания AI-сотрудника"},
    {"kind": "feature", "hint": "Применение создания AI-сотрудника", "key": "apply_ai_agents", "label": "Применение создания AI-сотрудника"},
    {"kind": "feature", "hint": "Отключение AI-сотрудников", "key": "disable_ai_agents", "label": "Отключение AI-сотрудников"},
    {"kind": "feature", "hint": "Архивирование AI-сотрудников", "key": "archive_ai_agents", "label": "Архивирование AI-сотрудников"},
    {"kind": "feature", "hint": "Удаление AI-сотрудников", "key": "delete_ai_agents", "label": "Удаление AI-сотрудников"},
    {"kind": "feature", "hint": "Принудительное удаление AI-сотрудников", "key": "force_delete_ai_agents", "label": "Принудительное удаление AI-сотрудников"},
    {"kind": "feature", "hint": "Просмотр навыков", "key": "view_ai_skills", "label": "Просмотр навыков"},
    {"kind": "feature", "hint": "Редактирование навыков", "key": "manage_ai_skills", "label": "Редактирование навыков"},
    {"kind": "feature", "hint": "Публикация навыков", "key": "publish_ai_skills", "label": "Публикация навыков"},
    {"kind": "feature", "hint": "Просмотр интеграций AI", "key": "view_integrations", "label": "Просмотр интеграций AI"},
    {"kind": "feature", "hint": "Создание интеграций AI", "key": "create_integrations", "label": "Создание интеграций AI"},
    {"kind": "feature", "hint": "Редактирование интеграций AI", "key": "edit_integrations", "label": "Редактирование интеграций AI"},
    {"kind": "feature", "hint": "Удаление интеграций AI", "key": "delete_integrations", "label": "Удаление интеграций AI"},
    {"kind": "feature", "hint": "Тестирование интеграций AI", "key": "test_integrations", "label": "Тестирование интеграций AI"},
    {"kind": "feature", "hint": "Учётные данные интеграций AI", "key": "manage_integration_credentials", "label": "Учётные данные интеграций AI"},
    {"kind": "feature", "hint": "Назначение интеграций AI-сотрудникам", "key": "assign_integrations_to_agents", "label": "Назначение интеграций AI-сотрудникам"},
    {"kind": "tab", "hint": "Разрешает доступ к разделу \"Скрипты разговоров\"", "moduleKey": "scripts", "key": "view_scripts", "label": "AI-скрипты: Открыть Скрипты"},
    {"kind": "feature", "hint": "Разрешает создавать, редактировать и удалять скрипты разговоров", "moduleKey": "scripts", "key": "manage_scripts", "label": "AI-скрипты: Управление скриптами"},
    {"kind": "tab", "hint": "Разрешает доступ к разделу \"AI-автоответчик\"", "moduleKey": "ai_assistant", "key": "view_ai_assistant", "label": "AI-автоответчик: Открыть AI-автоответчик"},
    {"kind": "feature", "hint": "Разрешает редактировать промпты и правила AI-автоответчика", "moduleKey": "ai_assistant", "key": "manage_ai_assistant", "label": "AI-автоответчик: Управление автоответчиком"},
  ] },
  { id: "settings", title: "Настройки", description: "Права раздела «Настройки».", color: "blue", moduleKey: "settings", rows: [
    {"kind": "tab", "hint": "Показывает страницу Настройки системы", "key": "view_settings", "label": "Открыть настройки"},
    {"kind": "su", "hint": "Создание, редактирование и отключение пользователей", "key": "manage_users", "label": "Пользователи"},
    {"kind": "su", "hint": "Редактирование матрицы прав доступа", "key": "manage_roles", "label": "Роли"},
    {"kind": "feature", "hint": "Центр уведомлений: просмотр", "key": "view_notification_center", "label": "Центр уведомлений: просмотр"},
    {"kind": "feature", "hint": "Центр уведомлений: каналы и правила", "key": "manage_notification_center", "label": "Центр уведомлений: каналы и правила"},
    {"kind": "feature", "hint": "Журнал доставки уведомлений", "key": "view_notification_delivery_log", "label": "Журнал доставки уведомлений"},
  ] },
 ] as const satisfies readonly GroupDefinition[];
export type PermissionKey = typeof PERMISSION_GROUPS[number]['rows'][number]['key'];
export interface PermissionRow extends PermissionDefinition { key:PermissionKey }
export interface PermissionGroup extends Omit<GroupDefinition,'rows'> { rows:PermissionRow[] }
export const SECTION_LABELS = Object.fromEntries(SYSTEM_SECTIONS.map(s=>[s.key,s.label])) as Record<SystemSectionKey,string>;
export const DEFAULT_MODULE_VISIBILITY = Object.fromEntries(SYSTEM_SECTIONS.map(s=>[s.key,s.defaultVisible])) as ModuleVisibility;
export const PERMISSION_MODULE_MAP: Record<string,SystemSectionKey> = Object.fromEntries(PERMISSION_GROUPS.flatMap(group=>group.rows.map(row=>[row.key,('moduleKey' in row ? row.moduleKey : group.moduleKey)])));
export const SU_PERMISSION_KEYS: string[] = PERMISSION_GROUPS.flatMap(group=>group.rows.filter(row=>row.kind==='su').map(row=>row.key));
export function normalizeModuleVisibilitySettings(value:unknown):ModuleVisibility {
  const source=value && typeof value==='object' ? value as Record<string,unknown> : {};
  const next={...DEFAULT_MODULE_VISIBILITY};
  for(const section of SYSTEM_SECTIONS)if(typeof source[section.key]==='boolean')next[section.key]=source[section.key] as boolean;
  // GSM previously inherited Management visibility. Preserve that choice on older installations.
  if(typeof source.gsm_gateways!=='boolean' && source.management===false)next.gsm_gateways=false;
  return next;
}
export function isSystemSectionVisible(role:string|undefined,visibility:unknown,section:SystemSectionKey):boolean {
  if(role==='su')return true;
  const normalized=normalizeModuleVisibilitySettings(visibility);
  if(['scripts','ai_assistant'].includes(section) && !normalized.ai_platform)return false;
  if(section==='ai_pbx_admin' && !normalized.monitoring)return false;
  return normalized[section];
}
export function isPermissionModuleVisible(role:string|undefined,visibility:unknown,key:string):boolean {
  const section=PERMISSION_MODULE_MAP[key];
  return !section || isSystemSectionVisible(role,visibility,section);
}
