import fs from'node:fs';import path from'node:path';
import{diagnoseDirectoryExtension,diagnoseDirectoryPhone,normalizeDirectoryPhoneInput,parseDirectoryCsv,validateDirectoryPhone,type DirectoryImportDiagnostic}from'../shared/directoryImportValidation.js';
const file=path.resolve(process.argv[2]||'');if(!file||!fs.existsSync(file))throw new Error('CSV file not found');
const text=fs.readFileSync(file,'utf8'),csv=parseDirectoryCsv(text),header=(csv.rows[0]?.values||[]).map(value=>value.replace(/^\uFEFF/,'').trim().toLowerCase()),data=csv.rows.slice(1);
const names:Record<string,string[]>={phone:['phone','phone1','телефон1','номер1','телефон','номер'],phone2:['phone2','телефон2','номер2'],phone3:['phone3','телефон3','номер3'],internalExtension:['internalextension','внутренний номер','extension'],linkedExternalNumber:['linkedexternalnumber','связанный внешний номер','externalnumber'],name:['fullname','name','имя','фио'],company:['organization','company','компания','организация'],type:['type','тип'],visibility:['visibility','видимость'],isSpam:['isspam','is_spam','spam','спам']};
const get=(values:string[],field:string)=>{for(const name of names[field]||[]){const index=header.indexOf(name);if(index>=0)return values[index]||''}return''};
const diagnostics:Array<DirectoryImportDiagnostic&{name:string;columnCount:number;expectedColumns:number}>=[];
for(const row of data){const values=row.values,name=get(values,'name')||get(values,'company'),items=[diagnoseDirectoryPhone(get(values,'phone'),'phone',row.rowNumber),diagnoseDirectoryPhone(get(values,'phone2'),'phone2',row.rowNumber),diagnoseDirectoryPhone(get(values,'phone3'),'phone3',row.rowNumber),diagnoseDirectoryPhone(get(values,'linkedExternalNumber'),'linkedExternalNumber',row.rowNumber),diagnoseDirectoryExtension(get(values,'internalExtension'),row.rowNumber)].filter(Boolean)as DirectoryImportDiagnostic[];if(values.length!==header.length)items.push({rowNumber:row.rowNumber,field:'row',raw:values.join(csv.delimiter),trimmed:'',normalized:'',digitLength:0,codePoints:[],reason:'parser_column_mismatch',duplicateInFile:false,suggestedValue:null});for(const item of items)diagnostics.push({...item,name,columnCount:values.length,expectedColumns:header.length})}
const seen=new Map<string,number>();for(const row of data){const raw=get(row.values,'phone'),digits=normalizeDirectoryPhoneInput(raw).digits;if(!digits)continue;const first=seen.get(digits);if(first)diagnostics.push({rowNumber:row.rowNumber,field:'phone',raw,trimmed:raw.trim(),normalized:digits,digitLength:digits.length,codePoints:normalizeDirectoryPhoneInput(raw).codePoints,reason:'duplicate_in_file',duplicateInFile:true,suggestedValue:null,name:get(row.values,'name')||get(row.values,'company'),columnCount:row.values.length,expectedColumns:header.length});else seen.set(digits,row.rowNumber)}
const summary=Object.fromEntries(Array.from(new Set(diagnostics.map(item=>item.reason))).sort().map(reason=>[reason,diagnostics.filter(item=>item.reason===reason).length])),ranges=Array.from({length:10},(_,index)=>({range:`${index*10000+1}-${(index+1)*10000}`,count:new Set(diagnostics.filter(item=>item.rowNumber-1>=index*10000&&item.rowNumber-1<(index+1)*10000).map(item=>item.rowNumber)).size}));
const oldParse=(line:string)=>{const result:string[]=[];let current='',quoted=false;for(let index=0;index<line.length;index++){const char=line[index],next=line[index+1];if(char==='"'&&quoted&&next==='"'){current+='"';index++}else if(char==='"')quoted=!quoted;else if([',',';','\t'].includes(char)&&!quoted){result.push(current.trim());current=''}else current+=char}result.push(current.trim());return result.map(value=>value.replace(/^"|"$/g,'').trim())};
const oldLines=text.split(/\r?\n/).filter(line=>line.trim()),oldHeader=oldParse(oldLines[0]).map(value=>value.toLowerCase()),oldGet=(values:string[],...fields:string[])=>{for(const field of fields){const index=oldHeader.indexOf(field.toLowerCase());if(index>=0)return values[index]||''}return''},oldErrors:any[]=[];
for(let index=1;index<oldLines.length;index++){const values=oldParse(oldLines[index]),rowNumber=index+1,name=oldGet(values,'fullName','name','имя','фио')||oldGet(values,'organization','company'),type=oldGet(values,'type','тип').toLowerCase(),visibility=oldGet(values,'visibility','видимость').toLowerCase(),spam=oldGet(values,'isSpam','is_spam','spam','спам').toLowerCase(),fields=[['phone',oldGet(values,'phone','phone1','телефон')],['phone2',oldGet(values,'phone2','телефон2')],['phone3',oldGet(values,'phone3','телефон3')],['linkedExternalNumber',oldGet(values,'linkedExternalNumber','связанный внешний номер','externalNumber')]]as const;const reasons:any[]=[];if(type&&!['client','клиент','supplier','поставщик','government','госорган','internal','внутренний'].includes(type))reasons.push({field:'type',raw:type,reason:'invalid_type'});if(visibility&&!['shared','private','общий','личный'].includes(visibility))reasons.push({field:'visibility',raw:visibility,reason:'invalid_visibility'});if(spam&&!['true','false','1','0','yes','no','да','нет'].includes(spam))reasons.push({field:'isSpam',raw:spam,reason:'invalid_boolean'});for(const[field,raw]of fields){const validation=validateDirectoryPhone(raw);if(raw&&!validation.valid)reasons.push({field,raw,normalized:validation.digits,digitLength:validation.digits.length,reason:validation.reason})}if(reasons.length)oldErrors.push({rowNumber,name,columnCount:values.length,expectedColumns:oldHeader.length,reasons})}
const oldSummary:Record<string,number>={},shiftedValues:Record<string,number>={};for(const row of oldErrors)for(const item of row.reasons){oldSummary[item.reason]=(oldSummary[item.reason]||0)+1;shiftedValues[item.raw]=(shiftedValues[item.raw]||0)+1}
const oldRanges=[];for(let index=0;index<10;index++){const firstDataRow=index*10000+1,lastDataRow=(index+1)*10000;oldRanges.push({range:`${firstDataRow}-${lastDataRow}`,count:oldErrors.reduce((count,item)=>{const dataRow=item.rowNumber-1;return count+(dataRow>=firstDataRow&&dataRow<=lastDataRow?1:0)},0)})}
const rowNumbers=oldErrors.map(item=>item.rowNumber),steps=rowNumbers.slice(1).map((value,index)=>value-rowNumbers[index]),stepSummary=Object.fromEntries(Array.from(new Set(steps)).sort((a,b)=>a-b).map(step=>[step,steps.filter(value=>value===step).length]));
const report={file:path.basename(file),bytes:Buffer.byteLength(text),delimiter:csv.delimiter,headers:header,rowCount:data.length,newParser:{diagnosticCount:diagnostics.length,invalidRowCount:new Set(diagnostics.filter(item=>item.reason!=='duplicate_in_file').map(item=>item.rowNumber)).size,summary,ranges,first50:diagnostics.slice(0,50)},oldParser:{invalidRowCount:oldErrors.length,summary:oldSummary,shiftedValues,ranges:oldRanges,stepSummary,first50:oldErrors.slice(0,50),allErrors:oldErrors}};
const output=path.resolve(process.argv[3]||'directory-import-diagnostic.json');fs.writeFileSync(output,JSON.stringify(report,null,2));console.log(JSON.stringify({...report,newParser:{...report.newParser,first50:report.newParser.first50.slice(0,10)},oldParser:{...report.oldParser,first50:report.oldParser.first50.slice(0,10),allErrors:undefined},reportPath:output},null,2));
