import assert from'node:assert/strict';import fs from'node:fs';import http from'node:http';import express from'express';import{AiAuditService}from'../server/ai-platform/audit/aiAuditService.js';import{registerAiPlatformRoutes}from'../server/ai-platform/api/router.js';import{ConversationRuntime}from'../server/ai-platform/conversations/conversationRuntime.js';import type{AiPlatformStore}from'../server/ai-platform/storage/aiPlatformStore.js';import{HumanTransferService}from'../server/ai-platform/transfer/humanTransferService.js';import{parseHumanTransferConfig}from'../server/ai-platform/transfer/humanTransferPolicyEngine.js';import{TransferDestinationResolver}from'../server/ai-platform/transfer/transferDestinationResolver.js';import{PBXTransferExecutionAdapter}from'../server/ai-platform/transfer/transferExecutionAdapter.js';import type{PBXTransferService}from'../server/services/pbxTransferService.js';

const baseConfig={enabled:true,primaryDestination:{type:'queue',ref:'600'},fallbacks:[{type:'extension',ref:'101'},{type:'callback_request'}],outsideBusinessHoursAction:'callback_request',announceBeforeTransfer:true,maxResolveMs:1500,maxExecutionMs:5000};
class Store implements AiPlatformStore{rows:any[]=[];audits:any[][]=[];config:any={humanTransfer:baseConfig};async query(sql:string,p:any[]=[]):Promise<any>{if(sql.includes('FROM ai_tenants'))return[{id:1,tenant_key:'installation',name:'PBXPuls',mode:'installation',status:'active'}];if(sql.startsWith('INSERT INTO ai_transfer_requests')){const row={id:this.rows.length+1,tenant_id:p[0],trace_id:p[1],conversation_id:p[2],voice_session_id:p[3],agent_id:p[4],agent_version_id:p[5],requested_by_type:p[6],requested_by_id:p[7],trigger_type:p[8],trigger_text_hash:p[9],status:p[10],metadata_json:p[11],destination_type:null,destination_value_safe:null,destination_ref:null,failure_code:null,fallback_action:null,pbx_action_ref:null,requested_at:'now',started_at:null,completed_at:null,failed_at:null};this.rows.push(row);return{insertId:row.id}}if(sql.startsWith('UPDATE ai_transfer_requests')){const row=this.rows.find(x=>x.id===p[11]);if(row){row.status=p[0];if(p[1]!=null)row.destination_type=p[1];if(p[2]!=null)row.destination_value_safe=p[2];if(p[3]!=null)row.destination_ref=p[3];row.failure_code=p[4];if(p[5]!=null)row.fallback_action=p[5];if(p[6]!=null)row.pbx_action_ref=p[6];if(p[7]!=null)row.metadata_json=p[7];if(['completed','dry_run_completed'].includes(p[0]))row.completed_at='now';if(['failed','unavailable'].includes(p[0]))row.failed_at='now'}return{affectedRows:row?1:0}}if(sql.includes('FROM ai_transfer_requests WHERE tenant_id=? AND agent_id=')){const conversationId=p[5],hash=p[3];return this.rows.filter(x=>x.tenant_id===p[0]&&x.agent_id===p[1]&&x.agent_version_id===p[2]&&(x.conversation_id===conversationId||(hash&&JSON.parse(x.metadata_json).liveCallHash===hash))).slice(-1)}if(sql.includes('FROM ai_transfer_requests WHERE id='))return this.rows.filter(x=>x.id===p[0]&&x.tenant_id===p[1]);if(sql.includes('SELECT config_json FROM ai_agent_versions'))return p[0]===3&&p[1]===2&&p[2]===1?[{config_json:JSON.stringify(this.config)}]:[];if(sql.startsWith('INSERT INTO ai_audit_log')){this.audits.push(p);return{insertId:this.audits.length}}return[]}}
const pbx=(overrides:Partial<PBXTransferService>={}):PBXTransferService=>({resolveDestination:async(type,ref)=>({type,ref,safeLabel:`${type} safe`,available:true}),resolveLiveCall:async id=>({liveCallId:id,active:true,channelRef:'PJSIP/hidden-channel'}),executeBlindTransfer:async()=>({ok:true,actionRef:'safe-action',safeMessage:'accepted'}),getTransferStatus:async()=> 'completed',...overrides});
const input=(overrides:any={})=>({tenantId:1,traceId:'trace',conversationId:9,agentId:2,agentVersionId:3,requestedByType:'user' as const,requestedById:'su',triggerType:'explicit_human_request' as const,triggerText:'соедините меня +79991234567',dryRun:true,...overrides});
const make=(store=new Store(),service=pbx(),open?:()=>Promise<boolean>)=>({store,service:new HumanTransferService(store,new AiAuditService(store),new TransferDestinationResolver(service,undefined,open),new PBXTransferExecutionAdapter(service),{isEnabled:async()=>true})});

assert.equal(parseHumanTransferConfig(baseConfig).primaryDestination.type,'queue');assert.throws(()=>parseHumanTransferConfig({...baseConfig,primaryDestination:{type:'extension',ref:'PJSIP/101-raw'}}));assert.throws(()=>parseHumanTransferConfig({enabled:false}));
for(const[type,ref]of[['extension','101'],['queue','600'],['ring_group','700']]as const){const store=new Store();store.config={humanTransfer:{...baseConfig,primaryDestination:{type,ref},fallbacks:[]}};const h=make(store),result=await h.service.request(input());assert.equal(result.status,'dry_run_completed');assert.equal(result.destinationType,type);assert.equal(result.transferMode,'dry_run');assert.equal(h.store.rows[0].trigger_text_hash.length,64);assert.doesNotMatch(JSON.stringify(h.store.rows),/79991234567|соедините меня/)}
{
 const service=pbx({resolveDestination:async(type,ref)=>type==='queue'?null:{type:type as any,ref,safeLabel:'Fallback extension',available:true}}),h=make(new Store(),service),result=await h.service.request(input());assert.equal(result.destinationType,'extension');assert.equal(result.fallbackAvailable,true);assert.ok(h.store.audits.some(row=>row[4]==='human_transfer_fallback_selected'));
}
{
 const store=new Store();store.config={humanTransfer:{...baseConfig,primaryDestination:{type:'queue',ref:'600'},fallbacks:[{type:'callback_request'}]}};const h=make(store,pbx({resolveDestination:async()=>null})),result=await h.service.request(input());assert.equal(result.destinationType,'callback_request');assert.equal(result.callbackRequired,true);assert.equal(result.status,'dry_run_completed');
}
{
 const store=new Store();store.config={};const h=make(store),result=await h.service.request(input());assert.equal(result.status,'failed');assert.equal(result.failureCode,'destination_not_configured');assert.equal(result.fallbackAction,'callback_request');
}
{
 const h=make(new Store(),pbx(),async()=>false),result=await h.service.request(input());assert.equal(result.destinationType,'callback_request');assert.equal(result.callbackRequired,true);
}
{
 let executions=0;const service=pbx({executeBlindTransfer:async()=>{executions++;return{ok:true,actionRef:'action',safeMessage:'ok'}}}),h=make(new Store(),service),first=await h.service.request(input({conversationId:null,liveCallId:'trusted.call.1',dryRun:false,triggerType:'admin_test'})),second=await h.service.request(input({conversationId:null,liveCallId:'trusted.call.1',dryRun:false,triggerType:'admin_test'}));assert.equal(first.status,'completed');assert.equal(second.id,first.id);assert.equal(executions,1);assert.ok(h.store.audits.some(row=>row[4]==='human_transfer_duplicate_suppressed'));assert.doesNotMatch(JSON.stringify(first),/PJSIP|hidden-channel/);
}
{
 let executions=0;const h=make(new Store(),pbx({executeBlindTransfer:async()=>{executions++;await new Promise(resolve=>setTimeout(resolve,10));return{ok:true,actionRef:'one',safeMessage:'ok'}}})),request=input({conversationId:null,liveCallId:'concurrent.call',dryRun:false,triggerType:'admin_test'}),[a,b]=await Promise.all([h.service.request(request),h.service.request(request)]);assert.equal(a.id,b.id);assert.equal(executions,1);assert.equal(h.store.rows.length,1);
}
for(const[override,code]of[[{resolveLiveCall:async()=>null},'live_call_not_found'],[{resolveLiveCall:async(id:string)=>({liveCallId:id,active:false,channelRef:'hidden'})},'live_call_ended'],[{executeBlindTransfer:async()=>({ok:false,actionRef:null,safeMessage:'AMI secret response'})},'transfer_failed']]as const){const h=make(new Store(),pbx(override as any)),result=await h.service.request(input({conversationId:null,liveCallId:`call-${code}`,dryRun:false,triggerType:'admin_test'}));assert.equal(result.status,'failed');assert.equal(result.failureCode,code);assert.doesNotMatch(JSON.stringify(result),/hidden|AMI secret response/)}
{
 const h=make(new Store(),pbx()),result=await h.service.request(input({conversationId:null,dryRun:false,triggerType:'admin_test'}));assert.equal(result.failureCode,'live_context_required');
}
{
 const store=new Store();store.config={humanTransfer:{...baseConfig,maxResolveMs:100}};const never=new Promise<any>(()=>{}),h=make(store,pbx({resolveDestination:async()=>never})),result=await h.service.request(input({conversationId:77}));assert.equal(result.failureCode,'transfer_timeout');
}
{
 const store=new Store(),service=pbx(),h=new HumanTransferService(store,new AiAuditService(store),new TransferDestinationResolver(service),new PBXTransferExecutionAdapter(service),{isEnabled:async()=>false});await assert.rejects(()=>h.request(input()),(error:any)=>error.failureCode==='feature_disabled');
}
{
 const never=new Promise<any>(()=>{}),h=make(new Store(),pbx({resolveDestination:async()=>never})),controller=new AbortController(),pending=h.service.request(input({conversationId:88}),controller.signal);setTimeout(()=>controller.abort(),5);const result=await pending;assert.equal(result.status,'cancelled');assert.ok(h.store.audits.some(row=>row[4]==='human_transfer_cancelled'));
}
{
 class SandboxStore extends Store{messages:any[][]=[];override async query(sql:string,p:any[]=[]):Promise<any>{if(sql.includes('FROM ai_agent_test_sessions s JOIN'))return[{id:1,agent_id:2,agent_version_id:3,conversation_id:9,started_by:'su',status:'active',lifecycle_status:'draft',system_prompt:''}];if(sql.includes('MAX(sequence_no)'))return[{next_no:this.messages.length+1}];if(sql.startsWith('INSERT INTO ai_conversation_messages')){this.messages.push(p);return{insertId:this.messages.length}}return super.query(sql,p)}}
 const store=new SandboxStore(),service=pbx(),transfer=new HumanTransferService(store,new AiAuditService(store),new TransferDestinationResolver(service),new PBXTransferExecutionAdapter(service),{isEnabled:async()=>true});let providerCalls=0;const runtime=new ConversationRuntime(store,new AiAuditService(store),async()=>{providerCalls++;throw new Error('provider must not run')},null,transfer),result=await runtime.message(1,1,'Соедините меня с человеком',{traceId:'sandbox-transfer',actorId:'su'});assert.equal(result.transferRequired,true);assert.equal(result.transferMode,'dry_run');assert.equal(result.transferStatus,'dry_run_completed');assert.ok(result.transferRequestId);assert.equal(providerCalls,0);assert.ok(store.messages.some(row=>row[3]==='system'));assert.doesNotMatch(JSON.stringify(store.messages),/PJSIP|channelRef/);
}
const migration=fs.readFileSync(new URL('../server/pbxpulsMigrations.ts',import.meta.url),'utf8'),router=fs.readFileSync(new URL('../server/ai-platform/api/router.ts',import.meta.url),'utf8'),runtime=fs.readFileSync(new URL('../server/ai-platform/conversations/conversationRuntime.ts',import.meta.url),'utf8');for(const permission of['view_ai_transfer_requests','manage_ai_transfer_policies','test_ai_human_transfer'])assert.match(migration,new RegExp(permission));assert.match(migration,/ai_transfer_requests/);assert.match(migration,/WHERE r\.role_key IN\('su','admin'\)/);assert.match(router,/confirm!==true/);assert.match(router,/Arbitrary transfer destination is forbidden/);assert.doesNotMatch(router,/req\.body\?\.channel[^\n]*executeBlindTransfer/);assert.ok(runtime.indexOf('if(detectHumanTransfer(text))')<runtime.indexOf('new AgentContextBuilder'));assert.match(runtime,/addSystemAction/);
{
 const store=new Store(),app=express();app.use(express.json());registerAiPlatformRoutes(app,{requireAuth:()=>((req:any,_res:any,next:any)=>{req.user={username:'su'};next()}),checkPermission:async(req:any,permission:string)=>String(req.header('x-test-permissions')||'').split(',').includes(permission),readLegacyDb:async()=>({}),store,isEnabled:async()=>true,pbxTransferService:pbx()});const server=await new Promise<http.Server>(resolve=>{const value=app.listen(0,'127.0.0.1',()=>resolve(value))}),post=(body:any,permissions:string)=>new Promise<{status:number;body:any}>((resolve,reject)=>{const address=server.address()as any,request=http.request({host:'127.0.0.1',port:address.port,path:'/api/ai-platform/transfer/test',method:'POST',headers:{'content-type':'application/json','x-test-permissions':permissions}},response=>{let text='';response.on('data',chunk=>text+=chunk);response.on('end',()=>resolve({status:response.statusCode||0,body:JSON.parse(text)}))});request.on('error',reject);request.end(JSON.stringify(body))});const valid={agentId:2,agentVersionId:3,liveCallId:'trusted.call',confirm:true};assert.equal((await post(valid,'execute_ai_sandbox')).status,403);assert.equal((await post({...valid,confirm:false},'execute_ai_sandbox,test_ai_human_transfer')).status,400);assert.equal((await post({...valid,channel:'PJSIP/raw'},'execute_ai_sandbox,test_ai_human_transfer')).status,400);const ok=await post(valid,'execute_ai_sandbox,test_ai_human_transfer');assert.equal(ok.status,200);assert.doesNotMatch(JSON.stringify(ok.body),/PJSIP|channelRef|destination_ref/);server.close();
}
console.log('AI Platform Human Transfer tests: OK');
