import assert from'node:assert/strict';import{getActionDefinitionRegistry}from'../server/ai-platform/actions/actionDefinitionRegistry.js';import{ActionExecutorRegistry}from'../server/ai-platform/actions/actionExecutorRegistry.js';import{BusinessActionService}from'../server/ai-platform/actions/businessActionService.js';import{CreateCallbackRequestExecutor}from'../server/ai-platform/actions/executors/createCallbackRequestExecutor.js';import{ApplicationEncryptionService,maskCallbackPhone,normalizePhone}from'../server/ai-platform/actions/applicationEncryption.js';import{classifyCallbackConsent,extractCallbackPhone}from'../server/ai-platform/actions/callbackConsent.js';import{validateResponse}from'../server/ai-platform/conversations/responseValidator.js';
process.env.PBXPULS_AI_ACTION_ENCRYPTION_KEY='11'.repeat(32);process.env.PBXPULS_AI_ACTION_HASH_KEY='test-only-hmac-key';
class Store{actions:any[]=[];callbacks:any[]=[];audits:any[]=[];next=1;assigned=true;async query(sql:string,p:any[]=[]):Promise<any>{if(sql.includes('JOIN ai_agent_actions'))return this.assigned?[{id:9,config_json:'{"autonomyLevel":"SAFE"}'}]:[];if(sql.includes('FROM ai_actions WHERE tenant_id=? AND idempotency_key'))return this.actions.filter(x=>x.tenant_id===p[0]&&x.idempotency_key===p[1]).slice(-1);if(sql.startsWith('INSERT INTO ai_actions')){const row={id:this.next++,tenant_id:p[0],trace_id:p[1],conversation_id:p[2],agent_id:p[4],agent_version_id:p[5],action_key:p[6],status:'requested',input_json:p[9],input_hash:p[10],idempotency_key:p[11]};this.actions.push(row);return{insertId:row.id}}if(sql.startsWith('UPDATE ai_actions')){const row=this.actions.find(x=>x.id===p[p.length-1]);if(row){row.status=p[0];if(p[1])row.output_json=p[1];if(p[2])row.safe_summary=p[2];row.error_code=p[3]}return{affectedRows:row?1:0}}if(sql.includes('FROM ai_callback_requests')&&sql.includes("status IN('new'"))return this.callbacks.filter(x=>x.tenant_id===p[0]&&(x.conversation_id===p[1]||x.phone_hash===p[3]));if(sql.startsWith('INSERT INTO ai_callback_requests')){const row={id:this.next++,tenant_id:p[0],conversation_id:p[1],phone_encrypted:p[7],phone_key_version:p[8],phone_hash:p[9],phone_masked:p[10],reason:p[13],status:'new'};this.callbacks.push(row);return{insertId:row.id}}if(sql.startsWith('INSERT INTO ai_audit_log')){this.audits.push(p);return{insertId:this.next++}}return[]}}
const context=(overrides:any={})=>({traceId:'trace',tenantId:1,installationId:'installation',conversationId:10,voiceSessionId:null,transferRequestId:null,agentId:2,agentVersionId:3,actorType:'user'as const,actorId:'admin',permissions:['execute_ai_low_risk_actions'],consentStatus:'granted'as const,sourceChannel:'sandbox'as const,requestStartedAt:new Date().toISOString(),idempotencyKey:'callback:test:0001',...overrides});
assert.equal(getActionDefinitionRegistry().list().length,1);assert.equal(getActionDefinitionRegistry().get('business.create_callback_request').riskLevel,'low');assert.throws(()=>getActionDefinitionRegistry().get('unknown'));
const executors=new ActionExecutorRegistry(),store=new Store();executors.register('create_callback_request',new CreateCallbackRequestExecutor(store as any));const audit={append:async(e:any)=>{store.audits.push(e)}}as any,service=new BusinessActionService(store as any,audit,getActionDefinitionRegistry(),executors,async()=>true);
assert.equal(normalizePhone('+7 (999) 123-45-67'),'+79991234567');assert.equal(maskCallbackPhone('+79991234567'),'+*******4567');assert.throws(()=>normalizePhone('123'));const encryption=new ApplicationEncryptionService(),secret=encryption.encrypt('+79991234567');assert.notEqual(secret.ciphertext.includes('79991234567'),true);assert.equal(encryption.decrypt(secret.ciphertext),'+79991234567');
assert.equal(classifyCallbackConsent('да',true),'granted');assert.equal(classifyCallbackConsent('да',false),'unknown');assert.equal(classifyCallbackConsent('да, погода хорошая',true),'unknown');assert.equal(classifyCallbackConsent('нет',true),'denied');assert.equal(extractCallbackPhone('мой номер +7 999 123-45-67'),'+79991234567');
await assert.rejects(()=>service.executeCallback(context({consentStatus:'unknown'}),{phone:'+79991234567',reason:'Перезвонить'}),(e:any)=>e.code==='consent_required');store.assigned=false;await assert.rejects(()=>service.executeCallback(context(),{phone:'+79991234567',reason:'Перезвонить'}),(e:any)=>e.code==='permission_denied');store.assigned=true;
const created=await service.executeCallback(context(),{phone:'+79991234567',reason:'Перезвонить'});assert.equal(created.ok,true);assert.equal(store.callbacks.length,1);assert.equal(store.callbacks[0].phone_encrypted.includes('79991234567'),false);assert.equal(store.callbacks[0].phone_masked.includes('79991234567'),false);assert.equal(JSON.stringify(store.audits).includes('79991234567'),false);const replay=await service.executeCallback(context(),{phone:'+79991234567',reason:'Перезвонить'});assert.equal(replay.duplicate,true);assert.equal(store.callbacks.length,1);await assert.rejects(()=>service.executeCallback(context({idempotencyKey:'callback:test:0001'}),{phone:'+79990000000',reason:'Другая причина'}),(e:any)=>e.code==='conflict');
assert.equal(validateResponse('Заявка создана').errors.includes('unsafe_claim'),true);assert.equal(validateResponse('Могу зафиксировать просьбу о звонке').errors.length,0);
const noKey=process.env.PBXPULS_AI_ACTION_ENCRYPTION_KEY;delete process.env.PBXPULS_AI_ACTION_ENCRYPTION_KEY;delete process.env.PBXPULS_AI_ACTION_HASH_KEY;assert.equal(new ApplicationEncryptionService().ready(),false);process.env.PBXPULS_AI_ACTION_ENCRYPTION_KEY=noKey;process.env.PBXPULS_AI_ACTION_HASH_KEY='test-only-hmac-key';
console.log('AI Platform Business Actions tests: OK');
