import assert from 'node:assert/strict';
import fs from 'node:fs';

const app=fs.readFileSync(new URL('../src/App.tsx',import.meta.url),'utf8');
const builder=fs.readFileSync(new URL('../src/modules/aiPlatform/AiAgentBuilderPage.tsx',import.meta.url),'utf8');
const editor=fs.readFileSync(new URL('../src/modules/aiPlatform/AiAgentEditor.tsx',import.meta.url),'utf8');
const agents=fs.readFileSync(new URL('../src/modules/aiPlatform/VoiceAgentsManagementPage.tsx',import.meta.url),'utf8');
const settings=fs.readFileSync(new URL('../src/modules/aiPlatform/VoiceSettingsPanel.tsx',import.meta.url),'utf8');
const diagnostics=fs.readFileSync(new URL('../src/modules/aiPlatform/VoiceDiagnosticsPanel.tsx',import.meta.url),'utf8');
const service=fs.readFileSync(new URL('../server/ai-platform/voice/management/voiceAgentRouteService.ts',import.meta.url),'utf8');

assert.ok(app.includes('/(?:knowledge|voice|diagnostics)'));
assert.match(app,/view_ai_voice_catalog/);
assert.match(app,/generate_ai_voice_preview/);
assert.match(app,/manage_ai_voice_profiles/);
assert.match(editor,/VoiceSettingsPanel/);
assert.match(editor,/"Голос"/);
assert.match(editor,/Основное/);
assert.match(editor,/Навыки и знания/);
assert.match(editor,/Публикация/);
assert.match(editor,/Тестирование/);
assert.match(agents,/Настроить телефонию/);
assert.match(agents,/publishedVoice/);
assert.match(agents,/draftVoice/);
assert.match(agents,/есть несохранённые изменения/);
assert.match(service,/publishedVoice/);
assert.match(service,/hasVoiceDraftChange/);
assert.match(settings,/\/api\/ai-platform\/voice-catalog/);
assert.match(settings,/Прослушать/);
assert.match(settings,/Выбрать/);
assert.match(settings,/Сравнить \(\{comparison\.length\}\)/);
assert.match(settings,/Сравнение голосов/);
assert.match(settings,/Обновить каталог голосов/);
assert.match(settings,/Новый/);
assert.match(settings,/Последняя проверка каталога/);
assert.match(settings,/Ответ на возражение о цене/);
assert.match(settings,/Следующий шаг, если город известен/);
assert.match(settings,/\{\{city\}\}/);
assert.doesNotMatch(settings,/VAD end-of-turn|AudioSocket|Frame conservation/);
assert.match(diagnostics,/AudioSocket/);
assert.match(diagnostics,/Frame conservation/);
assert.match(diagnostics,/Качество произношения зависит от голосовой модели/);
assert.match(settings,/disabled=\{!canManage\}/);
assert.doesNotMatch(settings,/disabled=\{!preview\}/);
assert.doesNotMatch(settings,/\[['"]alloy['"],['"]ash['"]/);

console.log('AI Platform voice settings navigation UI checks passed');
