import assert from"node:assert/strict";import fs from"node:fs";import{HumanHandoffCoordinator}from"../server/ai-platform/handoff/humanHandoffCoordinator.js";import{SyntheticAriClientAdapter}from"../server/ai-platform/voice/ari/ariClientAdapter.js";import{LiveBridgeService}from"../server/ai-platform/voice/live/liveBridgeService.js";
const request=new HumanHandoffCoordinator("offer-yes");assert.deepEqual(request.request(true),{accepted:true,needsConfirmation:true});assert.equal(request.state,"awaiting_confirmation");assert.equal(request.confirmation("да, соединяйте"),"confirmed");assert.equal(request.announcementRequested(),true);assert.equal(request.bindAnnouncement("response-1"),true);assert.equal(request.playoutStarted("response-1"),true);assert.equal(request.playoutCompleted("response-1"),true);assert.equal(request.transferRequested(),true);assert.equal(request.transferRequested(),false);assert.equal(request.ringing(),true);assert.equal(request.answered(),true);assert.equal(request.complete(),true);assert.equal(request.state,"completed");
const declined=new HumanHandoffCoordinator("offer-no");declined.request(true);assert.equal(declined.confirmation("нет, не надо"),"declined");assert.equal(declined.blocksNormalResponse(),false);
const ambiguous=new HumanHandoffCoordinator("ambiguous");ambiguous.request(true);assert.equal(ambiguous.confirmation("может быть"),"ambiguous");assert.equal(ambiguous.state,"awaiting_confirmation");assert.equal(ambiguous.clarificationCount,1);
const duplicate=new HumanHandoffCoordinator("duplicate");duplicate.request(true);duplicate.confirmation("да");assert.equal(duplicate.confirmation("да"),"ignored");assert.equal(duplicate.duplicateConfirmationCount,1);assert.equal(duplicate.transferRequestCount,0);
const direct=new HumanHandoffCoordinator("direct");assert.equal(direct.request(false).needsConfirmation,false);assert.equal(direct.state,"confirmed");
for(const kind of["no_answer","busy","failed"]as const){const c=new HumanHandoffCoordinator(kind);c.request(false);c.announcementRequested();c.bindAnnouncement("a");c.playoutStarted("a");c.playoutCompleted("a");c.transferRequested();c.ringing();assert.equal(c.fail(kind),true);assert.equal(c.state,"fallback_or_return")}
const closingExclusion=new HumanHandoffCoordinator("closing");closingExclusion.request(false);assert.equal(closingExclusion.blocksClosing(),true);
const ari=new SyntheticAriClientAdapter();await ari.connect();const bridge=new LiveBridgeService(ari);await bridge.create(10,"caller-safe","127.0.0.1:9092","00000000-0000-0000-0000-000000000001","pbxpuls-ai-control");await bridge.continueCaller(10,"caller-safe","handoff-123456789abc");assert.deepEqual(ari.operations,["bridge:create","audiosocket:create","bridge:add","bridge:add","hangup","bridge:destroy","continue"]);assert.equal(ari.operations.includes("hangup"),true);assert.equal(ari.operations.at(-1),"continue");
const helper=fs.readFileSync("scripts/freepbx-ai-handoff.php","utf8"),realtime=fs.readFileSync("server/ai-platform/voice/providers/realtimeVoiceSessionService.ts","utf8"),live=fs.readFileSync("server/ai-platform/voice/live/controlledLiveVoiceService.ts","utf8");
assert.match(helper,/\[pbxpuls-ai-handoff\]/);assert.match(helper,/Dial\(Local\//);assert.match(helper,/handoff_return/);assert.match(helper,/handoff_complete/);assert.doesNotMatch(helper,/req\.|payload|system\(|exec\(/);assert.match(realtime,/playoutCompleted/);assert.match(realtime,/setHandoffHandlers/);assert.match(realtime,/closing\.state!==\"active\"/);assert.match(live,/realtime\.stop/);assert.match(live,/media\.stop/);assert.match(live,/continueCaller/);assert.match(live,/restoreTaskState/);assert.match(live,/providerAudioAfterAnswer:false/);assert.ok(live.indexOf("realtime.stop")<live.indexOf("continueCaller"));assert.ok(live.indexOf("media.stop")<live.indexOf("continueCaller"));
console.log("AI Platform Human Handoff runtime tests: OK");
