import assert from 'node:assert/strict';
import {buildCallTrace,buildCoreCallTrace,buildLogEnrichment,detectTraceQueryType,findCallTraceCandidates,maskTraceForReport,selectRotatedPathsForWindow,validateTraceInput,type CallTraceDeps} from '../server/logAnalysis/callTrace.js';

const base={calldate:'2026-07-20 10:00:00',clid:'"Caller" <79990001122>',src:'79990001122',dst:'600',dcontext:'from-trunk',channel:'PJSIP/trunk-000001',dstchannel:'Local/600@from-queue-000002;1',lastapp:'Queue',lastdata:'600,t,,,',duration:40,billsec:20,disposition:'ANSWERED',amaflags:3,accountcode:'',uniqueid:'trace.1',userfield:'',did:'74950001122',recordingfile:'trace.wav',cnum:'79990001122',cnam:'Caller',outbound_cnum:'',outbound_cnam:'',dst_cnam:'',linkedid:'trace.1',peeraccount:'',sequence:1};
const branch={...base,calldate:'2026-07-20 10:00:05',src:'600',dst:'200',dcontext:'from-queue',channel:'Local/600@from-queue-000002;2',dstchannel:'PJSIP/200-000003',lastapp:'Dial',lastdata:'PJSIP/200',uniqueid:'trace.2',sequence:2};
const cel=[{id:1,eventtype:'CHAN_START',eventtime:'2026-07-20 10:00:00.100',cid_name:'Caller',cid_num:'79990001122',cid_ani:'',cid_rdnis:'',cid_dnid:'74950001122',exten:'600',context:'from-trunk',channame:base.channel,appname:'',appdata:'',amaflags:3,accountcode:'',uniqueid:'trace.1',linkedid:'trace.1',peer:'',userdeftype:'',extra:''},{id:2,eventtype:'BRIDGE_ENTER',eventtime:'2026-07-20 10:00:12.500',cid_name:'',cid_num:'200',cid_ani:'',cid_rdnis:'',cid_dnid:'',exten:'200',context:'from-queue',channame:branch.dstchannel,appname:'Dial',appdata:'',amaflags:3,accountcode:'',uniqueid:'trace.2',linkedid:'trace.1',peer:base.channel,userdeftype:'',extra:''}];
function deps(rows:any[]=[base,branch],celRows:any[]=cel,events:any[]=[]):CallTraceDeps{return{queryCdr:async(sql)=>sql.includes('FROM cel')?celRows:rows,searchLogs:async()=>({events,bytesRead:10,from:'2026-07-20T09:58:00.000Z',to:'2026-07-20T10:03:00.000Z'})}}
const input={query:'trace.1',queryType:'linkedid' as const,from:'2026-07-19T00:00:00Z',to:'2026-07-21T00:00:00Z'};

assert.equal(detectTraceQueryType('+79990001122'),'phone');assert.equal(detectTraceQueryType('200'),'extension');assert.equal(detectTraceQueryType('PJSIP/200-000003'),'channel');assert.equal(detectTraceQueryType('abc@pbx.local'),'call_id');assert.equal(detectTraceQueryType('192.0.2.1'),'ip');assert.equal(detectTraceQueryType('1711111111.42'),'uniqueid');
assert.throws(()=>validateTraceInput({...input,query:'bad\nquery'}),/идентификатор/);assert.throws(()=>validateTraceInput({...input,from:'2020-01-01',to:'2026-01-01'}),/период/);
const found=await findCallTraceCandidates(deps(),{query:'79990001122',queryType:'phone',from:input.from,to:input.to});assert.equal(found.candidates.length,1);assert.equal(found.candidates[0].cdrCount,2,'несколько CDR объединяются по linkedid');assert.equal(found.candidates[0].direction,'incoming');
const trace=await buildCallTrace(deps(),input);assert.equal(trace.cdrCount,2);assert.equal(trace.celCount,2);assert.equal(trace.direction,'incoming');assert.ok(trace.timeline.some((e:any)=>e.type==='cel_bridge_enter'));assert.ok(trace.graph.edges.some((e:any)=>e.type==='Queue'));assert.ok(trace.graph.nodes.some((n:any)=>n.type==='local'),'Local channel присутствует в графе');assert.ok(trace.timeline.every((e:any)=>e.correlation?.explanation),'у каждой записи указано основание корреляции');
const outbound=await buildCallTrace(deps([{...base,linkedid:'out.1',uniqueid:'out.1',src:'200',dst:'79995554433',did:'',dcontext:'from-internal',channel:'PJSIP/200-a',dstchannel:'PJSIP/trunk-b',lastapp:'Dial'}],[],[]),{...input,query:'out.1'});assert.equal(outbound.direction,'outgoing');
const internalCall=await buildCallTrace(deps([{...base,linkedid:'int.1',uniqueid:'int.1',src:'200',dst:'201',did:'',dcontext:'from-internal',channel:'PJSIP/200-a',dstchannel:'PJSIP/201-b'}],[],[]),{...input,query:'int.1'});assert.equal(internalCall.direction,'internal');
const follow=await buildCallTrace(deps([{...base,linkedid:'fm.1',uniqueid:'fm.1'},{...branch,linkedid:'fm.1',uniqueid:'fm.2',dst:'79995554433',dcontext:'ext-local',lastdata:'Local/79995554433@followme',dstchannel:'PJSIP/trunk-fm'}],[],[]),{...input,query:'fm.1'});assert.equal(follow.direction,'incoming_with_external_branch','исходная входящая классификация сохраняется');assert.ok(follow.graph.edges.some((e:any)=>e.type==='Follow Me'));
const lowEvent={sourceKey:'asterisk-full',sourceName:'Asterisk',source:'Asterisk',occurredAt:'2026-07-20T10:00:10Z',eventType:'unknown',type:'unknown',title:'Возможное событие',message:'рядом по времени',rawMessage:'рядом по времени',severity:'info',fingerprint:'low',confidence:'low',correlation:{confidence:'low',type:'time_window',explanation:'Только близкое время'}};const low=await buildCallTrace(deps([{...base,linkedid:'low.1',uniqueid:'low.1'}],[],[lowEvent]),{...input,query:'low.1',includeLowConfidence:true});assert.equal(low.possibleRelations.length,1);assert.ok(!low.timeline.some((e:any)=>e.confidence==='low'),'низкая уверенность не смешивается с основной шкалой');
const sipError={...lowEvent,linkedid:'sip.1',eventType:'sip_error',message:'SIP 503 Service Unavailable',rawMessage:'SIP 503 Service Unavailable',fingerprint:'sip',confidence:'exact',correlation:{confidence:'exact',type:'linkedid',explanation:'Точный Linkedid'}};const failed=await buildCallTrace(deps([{...base,linkedid:'sip.1',uniqueid:'sip.1',disposition:'FAILED',billsec:0}],[],[sipError]),{...input,query:'sip.1'});assert.match(failed.summary.title,/ошибку SIP/);
const noCel=await buildCallTrace(deps([{...base,linkedid:'nocel.1',uniqueid:'nocel.1'}],[],[]),{...input,query:'nocel.1'});assert.equal(noCel.celCount,0);
const controller=new AbortController();controller.abort();await assert.rejects(()=>buildCallTrace(deps(),{...input,query:'abort.1',signal:controller.signal}),{name:'AbortError'});
assert.throws(()=>validateTraceInput({...input,limit:999,query:''}),/Некорректный идентификатор/);assert.equal(validateTraceInput({...input,limit:999}).limit,100);
const masked=maskTraceForReport({raw:'password=123456 Authorization: Bearer abc.def.ghi mysql://user:pass@host/db'});assert.doesNotMatch(masked.raw,/123456|abc\.def|user:pass/);assert.match(masked.raw,/password=\*\*\*/);
let logCalls=0,sqlCalls=0;const progressive:CallTraceDeps={queryCdr:async(sql)=>{sqlCalls++;return sql.includes('FROM cel')?cel:[{...base,linkedid:'progress.1',uniqueid:'progress.1'}]},searchLogs:async()=>{logCalls++;await new Promise(resolve=>setTimeout(resolve,30));return{events:[],bytesRead:0,from:'2026-07-20T09:59:00Z',to:'2026-07-20T10:02:00Z',searchedSources:[],rotatedFilesConsidered:0}}};const core=await buildCoreCallTrace(progressive,{...input,query:'progress.1',mode:'core'});assert.equal(logCalls,0,'core trace не ждёт журналы');assert.equal(core.mode,'core');assert.ok(!JSON.stringify(core.timeline).includes('rawMessage'),'core DTO не содержит raw log text');const firstLogs=await buildLogEnrichment(progressive,{...input,query:'progress.1',mode:'logs'});assert.equal(firstLogs.cache.hit,false);const cachedLogs=await buildLogEnrichment(progressive,{...input,query:'progress.1',mode:'logs'});assert.equal(cachedLogs.cache.hit,true);assert.equal(logCalls,1,'повторный logs использует cache');
let parallelCalls=0;const parallelDeps=deps([{...base,linkedid:'parallel.1',uniqueid:'parallel.1'}],[],[]);parallelDeps.queryCdr=async(sql)=>{parallelCalls++;await new Promise(resolve=>setTimeout(resolve,20));return sql.includes('FROM cel')?[]:[{...base,linkedid:'parallel.1',uniqueid:'parallel.1'}]};await Promise.all([buildCoreCallTrace(parallelDeps,{...input,query:'parallel.1',mode:'core'}),buildCoreCallTrace(parallelDeps,{...input,query:'parallel.1',mode:'core'})]);assert.equal(parallelCalls,2,'одинаковые параллельные core-запросы дедуплицированы');
const rotated=selectRotatedPathsForWindow({rotatedPaths:['/var/log/asterisk/full-20260715','/var/log/asterisk/full-20260716','/var/log/asterisk/full-20260717','/var/log/asterisk/full-20260718','/var/log/asterisk/full-20260719']},Date.parse('2026-07-17T23:59:30+03:00'),Date.parse('2026-07-18T00:01:00+03:00'));assert.ok(rotated.length<=2);assert.ok(rotated.every((x:string)=>/2026071[89]$/.test(x)),'для перехода через полночь выбраны только соседние rotated');
console.log('call trace tests: OK');
