import assert from 'node:assert/strict';
import { workingDeadline, workingElapsed, isWorkingTime, type WorkingSchedule } from '../server/calls/freepbxWorkingSchedule.js';
import { enrichMissedRouteResponsibility } from '../server/calls/missedRouteResponsibility.js';
import { classifyMissedCallResolution } from '../server/missedCallResolution.js';
import { parseTimeConditionOverrides } from '../server/calls/timeConditionOverrides.js';
assert.deepEqual([...parseTimeConditionOverrides('/TC/1 : true_sticky\n/TC/2 : \n/TC/2/INUSESTATE : INUSE')], ['1']);
assert.equal(classifyMissedCallResolution({ missedMs: 0, nowMs: 100000, callbackWindowMs: 10, deadlineMs: Infinity, processedAtMs: 50000 }).isProcessedInSla, false);
const ms = (s: string) => Date.parse(s + '+03:00');
const schedule: WorkingSchedule = [[{ times: ['09:00-11:59|mon-fri|*|*', '13:00-17:59|mon-fri|*|*'], timezone: 'Europe/Moscow', match: true }]];
assert.equal(workingDeadline(schedule, ms('2026-10-08T08:00:00'), 300000), ms('2026-10-08T09:05:00'));
assert.equal(workingDeadline(schedule, ms('2026-10-09T17:58:00'), 300000), ms('2026-10-12T09:03:00'));
assert.equal(workingDeadline(schedule, ms('2026-10-08T11:58:30'), 300000), ms('2026-10-08T13:03:30'));
assert.equal(workingElapsed(schedule, ms('2026-10-08T11:58:30'), ms('2026-10-08T13:03:30')), 300000);
const holiday: WorkingSchedule = [[...schedule[0], { times: ['*|*|9|oct'], timezone: 'Europe/Moscow', match: false }]];
assert.equal(workingDeadline(holiday, ms('2026-10-08T17:58:00'), 300000), ms('2026-10-12T09:03:00'));
const overnight: WorkingSchedule = [[{ times: ['22:00-05:59|*|*|*'], timezone: 'Europe/Moscow', match: true }]];
assert.equal(isWorkingTime(overnight, ms('2026-10-08T02:00:00')), true);
assert.equal(isWorkingTime(overnight, ms('2026-10-08T12:00:00')), false);
const dst: WorkingSchedule = [[{ times: ['01:00-03:59|sun|*|*'], timezone: 'America/New_York', match: true }]];
assert.equal(workingElapsed(dst, Date.parse('2026-11-01T05:00:00Z'), Date.parse('2026-11-01T09:00:00Z')), 14400000);
const missed = ms('2026-10-08T19:00:00');
const deadline = workingDeadline(schedule, missed, 300000);
assert.equal(classifyMissedCallResolution({ missedMs: missed, nowMs: ms('2026-10-09T08:00:00'), callbackWindowMs: 300000, deadlineMs: deadline }).isPending, true);
assert.equal(classifyMissedCallResolution({ missedMs: missed, nowMs: deadline + 1, callbackWindowMs: 300000, deadlineMs: deadline }).isLost, true);
assert.equal(classifyMissedCallResolution({ missedMs: missed, nowMs: deadline + 1, callbackWindowMs: 300000, deadlineMs: deadline, processedAtMs: deadline }).isProcessedInSla, true);

let times = '09:00-17:59|mon-fri|*|*';
const query = async (sql: string, params: any[]) => {
  if (sql.includes('asterisk.incoming')) return [{ cidnum: '', destination: 'timeconditions,3,1' }];
  if (sql.includes('asterisk.timeconditions')) return [{ time: 2, truegoto: 'app-announcement-5,s,1', falsegoto: 'app-announcement-6,s,1', timezone: 'Europe/Moscow', mode: 'time-group' }];
  if (sql.includes('asterisk.timegroups_details')) return [{ time: times }];
  if (sql.includes('asterisk.announcement')) return [{ post_dest: params[0] === '5' ? 'from-did-direct,692,1' : 'app-blackhole,hangup,1', return_ivr: 0 }];
  if (sql.includes('asterisk.users')) return [{ extension: '692', name: 'Operator' }];
  throw Error('Unexpected query ' + sql);
};
const make = () => ({ did: '79184103852', src: '79215693128', dcontext: 'app-announcement-6', dst: 's', disposition: 'ANSWERED', billsec: 4, uniqueid: 'night' } as any);
let call = make();
await enrichMissedRouteResponsibility([call], query);
assert.deepEqual(call.routeResponsibleExts, ['692']);
assert.equal(workingDeadline(call.callbackWorkingSchedule, missed, 300000), ms('2026-10-09T09:05:00'));
times = '10:00-17:59|mon-fri|*|*';
call = make(); await enrichMissedRouteResponsibility([call], query);
assert.equal(workingDeadline(call.callbackWorkingSchedule, missed, 300000), ms('2026-10-09T10:05:00'), 'FreePBX edit must apply without restart');
const badQuery = async (sql: string, params: any[]) => sql.includes('asterisk.timeconditions') ? [{ mode: 'calendar' }] : query(sql, params);
call = make(); await enrichMissedRouteResponsibility([call], badQuery);
assert.equal(call.callbackScheduleUnknown, true);
assert.equal(call.routeResponsibleExts, undefined);
console.log('FreePBX SLA: nights, weekends, breaks, holidays, timezone/DST, callback statuses, night responsibility and live schedule edits passed');
