import assert from"node:assert/strict";import fs from"node:fs";import{HumanHandoffCoordinator}from"../server/ai-platform/handoff/humanHandoffCoordinator.js";import{SyntheticAriClientAdapter}from"../server/ai-platform/voice/ari/ariClientAdapter.js";import{LiveBridgeService}from"../server/ai-platform/voice/live/liveBridgeService.js";
const request=new HumanHandoffCoordinator("offer-yes");assert.deepEqual(request.request({trigger:"ai_offer",confirmationRequired:true}),{accepted:true,needsConfirmation:true});assert.equal(request.trigger,"ai_offer");assert.equal(request.state,"awaiting_confirmation");assert.equal(request.confirmation("да, соединяйте"),"confirmed");assert.equal(request.announcementRequested(),true);assert.equal(request.bindAnnouncement("response-1"),true);assert.equal(request.playoutStarted("response-1"),true);assert.equal(request.playoutCompleted("response-1"),true);assert.equal(request.transferRequested(),true);assert.equal(request.transferRequested(),false);assert.equal(request.ringing(),true);assert.equal(request.answered(),true);assert.equal(request.complete(),true);assert.equal(request.state,"completed");
const declined=new HumanHandoffCoordinator("offer-no");declined.request({trigger:"ai_offer",confirmationRequired:true});assert.equal(declined.confirmation("нет, не надо"),"declined");assert.equal(declined.blocksNormalResponse(),false);
const ambiguous=new HumanHandoffCoordinator("ambiguous");ambiguous.request({trigger:"ai_offer",confirmationRequired:true});assert.equal(ambiguous.confirmation("может быть"),"ambiguous");assert.equal(ambiguous.state,"awaiting_confirmation");assert.equal(ambiguous.clarificationCount,1);
const duplicate=new HumanHandoffCoordinator("duplicate");duplicate.request({trigger:"ai_offer",confirmationRequired:true});duplicate.confirmation("да");assert.equal(duplicate.confirmation("да"),"ignored");assert.equal(duplicate.duplicateConfirmationCount,1);assert.equal(duplicate.transferRequestCount,0);
const direct=new HumanHandoffCoordinator("direct");assert.equal(direct.request({trigger:"direct_request",confirmationRequired:false}).needsConfirmation,false);assert.equal(direct.trigger,"direct_request");assert.equal(direct.state,"confirmed");assert.notEqual(direct.state as string,"awaiting_confirmation");assert.equal(direct.confirmation("да"),"ignored");
const standaloneYes=new HumanHandoffCoordinator("standalone-yes");assert.equal(standaloneYes.confirmation("да"),"ignored");assert.equal(standaloneYes.state,"idle");assert.equal(standaloneYes.transferRequestCount,0);
const repeatedDirect=new HumanHandoffCoordinator("repeated-direct");assert.equal(repeatedDirect.request({trigger:"direct_request",confirmationRequired:false}).accepted,true);assert.equal(repeatedDirect.request({trigger:"direct_request",confirmationRequired:false}).accepted,false);assert.equal(repeatedDirect.announcementRequested(),true);assert.equal(repeatedDirect.bindAnnouncement("direct-announcement"),true);assert.equal(repeatedDirect.playoutCompleted("direct-announcement"),true);assert.equal(repeatedDirect.transferRequested(),true);assert.equal(repeatedDirect.transferRequested(),false);assert.equal(repeatedDirect.transferRequestCount,1);
const reorderedLifecycle=new HumanHandoffCoordinator("reordered-lifecycle");reorderedLifecycle.request({trigger:"direct_request",confirmationRequired:false});assert.equal(reorderedLifecycle.announcementRequested(),true);assert.equal(reorderedLifecycle.bindAnnouncement("response-reordered"),true);assert.equal(reorderedLifecycle.playoutCompleted("response-reordered"),true);assert.equal(reorderedLifecycle.state,"transfer_requested");assert.equal(reorderedLifecycle.transferRequested(),true);
for(const kind of["no_answer","busy","failed"]as const){const c=new HumanHandoffCoordinator(kind);c.request({trigger:"direct_request",confirmationRequired:false});c.announcementRequested();c.bindAnnouncement("a");c.playoutStarted("a");c.playoutCompleted("a");c.transferRequested();c.ringing();assert.equal(c.fail(kind),true);assert.equal(c.state,"fallback_or_return")}
const closingExclusion=new HumanHandoffCoordinator("closing");closingExclusion.request({trigger:"direct_request",confirmationRequired:false});assert.equal(closingExclusion.blocksClosing(),true);
const ari=new SyntheticAriClientAdapter();await ari.connect();const bridge=new LiveBridgeService(ari);await bridge.create(10,"caller-safe","127.0.0.1:9092","00000000-0000-0000-0000-000000000001","pbxpuls-ai-control");await bridge.continueCaller(10,"caller-safe","handoff-123456789abc");assert.deepEqual(ari.operations,["bridge:create","audiosocket:create","bridge:add","bridge:add","hangup","bridge:destroy","continue"]);assert.equal(ari.operations.includes("hangup"),true);assert.equal(ari.operations.at(-1),"continue");
const helper=fs.readFileSync("scripts/freepbx-ai-handoff.php","utf8"),realtime=fs.readFileSync("server/ai-platform/voice/providers/realtimeVoiceSessionService.ts","utf8"),live=fs.readFileSync("server/ai-platform/voice/live/controlledLiveVoiceService.ts","utf8");
assert.match(helper,/\[pbxpuls-ai-handoff\]/);assert.match(helper,/Dial\(Local\//);assert.match(helper,/handoff_return/);assert.match(helper,/handoff_complete/);assert.doesNotMatch(helper,/req\.|payload|system\(|exec\(/);assert.match(realtime,/const lifecycleResponseId=event\.responseId\|\|runtime\.activeResponseId\|\|undefined/);assert.match(realtime,/event\.frame\.responseId\s*\|\|\s*runtime\.activeResponseId/);assert.match(realtime,/pushResponseFrame\(stream,\{[\s\S]{0,120}responseId,/);assert.match(realtime,/const handoffResponseId=[\s\S]{0,300}boundAnnouncementResponseId[\s\S]{0,120}: lifecycleResponseId/);assert.match(realtime,/handoff\.playoutCompleted\(handoffResponseId\)/);assert.match(realtime,/human_handoff_playout_completed/);assert.match(realtime,/if\(this\.controlledHandoff&&runtime\.handoffConfig\)await this\.controlledHandoff/);assert.doesNotMatch(realtime,/runtime\.controlledHandoff/);assert.match(realtime,/setHandoffHandlers/);assert.match(realtime,/closing\.state!==\"active\"/);assert.match(realtime,/detectRealtimeTransfer\(responseText,this\.handoffIntentPhrases\(runtime\)\)\)\{[\s\S]{0,220}runtime\.flusher\.markDirty\(\);\s*return;/);assert.match(live,/realtime\.stop/);assert.match(live,/media\.stop/);assert.match(live,/executeBlindTransfer/);assert.match(live,/transferAnchor/);assert.match(live,/scheduleHandoffAnchorCleanup/);assert.match(live,/completeTransferredCaller/);assert.match(live,/hangupCaller\(active\.callerChannel\)/);assert.match(live,/restoreTaskState/);assert.match(live,/providerAudioAfterAnswer:false/);const handoffMethod=live.slice(live.indexOf("async humanHandoff"),live.indexOf("async resumeHandoff"));assert.ok(handoffMethod.indexOf("realtime.stop")<handoffMethod.indexOf("executeBlindTransfer"));assert.doesNotMatch(handoffMethod,/await this\.media\.stop/);assert.doesNotMatch(handoffMethod,/await this\.bridges\.cleanup/);
assert.match(realtime,/transfer\(runtime,id,traceId,row,extractionText,\"direct_request\"\)/);assert.match(realtime,/transfer\(runtime,\s*id,\s*traceId,\s*row,\s*responseText,\"ai_offer\"\)/);assert.match(realtime,/direct_request_requires_confirmation/);assert.match(realtime,/ai_offer_requires_confirmation/);
const priorityStart=realtime.indexOf("if(detectRealtimeTransfer(extractionText,this.handoffIntentPhrases(runtime)))"),skillStart=realtime.indexOf("if(!runtime.taskState.activeSkillId)",priorityStart);assert.ok(priorityStart>0&&skillStart>priorityStart,"handoff intent must run before SkillRouter");
console.log("AI Platform Human Handoff runtime tests: OK");
