import type { Express } from 'express';
import { AiPlatformError } from '../../../core/errors.js';
import type { RealtimeVoiceProviderRegistry } from '../realtimeVoiceProviderRegistry.js';
import type { RealtimeVoiceSessionService } from '../realtimeVoiceSessionService.js';
import { readRealtimeVoiceSettings } from '../realtimeVoiceControl.js';
import { readOpenAIRealtimeConfig } from '../adapters/openaiRealtimeAdapter.js';

export function registerRealtimeVoiceRoutes(app: Express, runtime: any, service: RealtimeVoiceSessionService, registry: RealtimeVoiceProviderRegistry) {
  const { authenticated, permit, wrap, getTenantId, actor, store, positiveInt, page } = runtime;
  const hits = new Map<string, number[]>();
  const consume = (key: string) => { const now = Date.now(); for (const [entry, values] of hits) if (!values.some(value => now - value < 60_000)) hits.delete(entry); const values = (hits.get(key) || []).filter(value => now - value < 60_000); if (values.length >= 60) throw new AiPlatformError('rate_limited', 429, 'Realtime test rate limit exceeded'); values.push(now); hits.set(key, values); };
  app.get('/api/ai-platform/voice/realtime/status', ...authenticated, permit('view_ai_realtime_voice_status'), wrap(async (_req: any, res: any) => {
    const tenantId = await getTenantId(), settings = await readRealtimeVoiceSettings(store), external = readOpenAIRealtimeConfig();
    const rows = await store.query("SELECT COUNT(*) total,SUM(state NOT IN('completed','failed','cancelled')) active,AVG(first_response_latency_ms) latency FROM ai_realtime_voice_sessions WHERE tenant_id=?", [tenantId]);
    res.json({ success: true, data: { featureEnabled: settings.enabled, provider: settings.provider, configured: settings.provider === 'synthetic' || external.configured, connectionState: settings.enabled ? 'available' : 'disabled', activeSessions: Number(rows[0]?.active || 0), totalSessions: Number(rows[0]?.total || 0), averageFirstResponseLatencyMs: rows[0]?.latency === null ? null : Number(rows[0]?.latency), capabilities: registry.list(), syntheticOnly: true, asteriskConnected: false, externalMediaCreated: false } });
  }));
  app.get('/api/ai-platform/voice/realtime/sessions', ...authenticated, permit('view_ai_realtime_voice_sessions'), wrap(async (req: any, res: any) => { const tenantId = await getTenantId(), paging = page(req), rows = await service.list(tenantId, paging.limit, paging.offset), count = await store.query('SELECT COUNT(*) total FROM ai_realtime_voice_sessions WHERE tenant_id=?', [tenantId]); res.json({ success: true, rows, pagination: { page: Math.floor(paging.offset / paging.limit) + 1, limit: paging.limit, total: Number(count[0]?.total || 0) } }); }));
  app.get('/api/ai-platform/voice/realtime/sessions/:id', ...authenticated, permit('view_ai_realtime_voice_sessions'), wrap(async (req: any, res: any) => res.json({ success: true, data: await service.get(await getTenantId(), positiveInt(req.params.id, 'realtime session id')) })));
  app.post('/api/ai-platform/voice/realtime/test/start', ...authenticated, permit('test_ai_realtime_voice'), wrap(async (req: any, res: any) => { const tenantId = await getTenantId(), current = actor(req); consume(`${tenantId}:${current.actorId}`); if (req.body?.providerKey && req.body.providerKey !== 'synthetic') throw new AiPlatformError('feature_disabled', 503, 'External realtime tests are disabled'); res.status(201).json({ success: true, data: await service.start({ tenantId, mediaSessionId: positiveInt(req.body?.mediaSessionId, 'media session id'), providerKey: 'synthetic', traceId: current.traceId, actorId: current.actorId }) }); }));
  app.post('/api/ai-platform/voice/realtime/test/audio', ...authenticated, permit('test_ai_realtime_voice'), wrap(async (req: any, res: any) => { const tenantId = await getTenantId(), current = actor(req); consume(`${tenantId}:${current.actorId}`); if (req.body?.payload || req.body?.audio || req.body?.base64) throw new AiPlatformError('invalid_request', 400, 'Raw audio payload is forbidden'); const fixture = String(req.body?.fixture || ''); if (!['silence','speech','question','transfer_request','callback_request','tool_query'].includes(fixture)) throw new AiPlatformError('invalid_request', 400, 'Invalid realtime fixture'); res.json({ success: true, data: await service.fixture(tenantId, positiveInt(req.body?.sessionId, 'realtime session id'), fixture as any, current.traceId) }); }));
  app.post('/api/ai-platform/voice/realtime/test/commit', ...authenticated, permit('test_ai_realtime_voice'), wrap(async (req: any, res: any) => { const current = actor(req); res.json({ success: true, data: await service.commit(await getTenantId(), positiveInt(req.body?.sessionId, 'realtime session id'), current.traceId) }); }));
  app.post('/api/ai-platform/voice/realtime/test/barge-in', ...authenticated, permit('test_ai_realtime_voice'), wrap(async (req: any, res: any) => { const current = actor(req); res.json({ success: true, data: await service.bargeIn(await getTenantId(), positiveInt(req.body?.sessionId, 'realtime session id'), current.traceId) }); }));
  app.post('/api/ai-platform/voice/realtime/test/stop', ...authenticated, permit('test_ai_realtime_voice'), wrap(async (req: any, res: any) => { const current = actor(req); res.json({ success: true, data: await service.stop(await getTenantId(), positiveInt(req.body?.sessionId, 'realtime session id'), current.traceId) }); }));
}
