import { queryPBXPulsDb } from '../pbxpulsDb.js';
import { sanitizeLogText } from './redaction.js';
import { detectLogSources } from './registry.js';
import { searchAllowedLogSource } from './reader.js';

export type TraceQueryType='auto'|'phone'|'extension'|'endpoint'|'ip'|'uniqueid'|'linkedid'|'call_id'|'channel'|'text';
export type TraceConfidence='exact'|'high'|'medium'|'low';
export interface CallTraceDeps { queryCdr:(sql:string,params:any[])=>Promise<any[]>; searchLogs?:(input:any,cdr:any[],linkedid:string)=>Promise<{events:any[];bytesRead:number;from:string;to:string;searchedSources?:string[];rotatedFilesConsidered?:number}> }
export interface TraceSearchInput { query:string;queryType?:TraceQueryType;from?:string;to?:string;limit?:number;includeRaw?:boolean;includeLowConfidence?:boolean;signal?:AbortSignal }
const CDR_FIELDS='calldate,clid,src,dst,dcontext,channel,dstchannel,lastapp,lastdata,duration,billsec,disposition,amaflags,accountcode,uniqueid,userfield,did,recordingfile,cnum,cnam,outbound_cnum,outbound_cnam,dst_cnam,linkedid,peeraccount,sequence';
const CEL_FIELDS='id,eventtype,eventtime,cid_name,cid_num,cid_ani,cid_rdnis,cid_dnid,exten,context,channame,appname,appdata,amaflags,accountcode,uniqueid,linkedid,peer,userdeftype,extra';
const CACHE_TTL=30000,MAX_RANGE=31*86400000,MAX_CDR=500,MAX_CEL=3000,MAX_LOG=600;
const cache=new Map<string,{expires:number,value:any}>();
const digits=(v:unknown)=>String(v||'').replace(/\D/g,'');
const internal=(v:unknown)=>/^\d{2,6}$/.test(digits(v));
const external=(v:unknown)=>/^\d{7,16}$/.test(digits(v));
const dateSql=(d:Date)=>d.toISOString().slice(0,19).replace('T',' ');
const abort=(signal?:AbortSignal)=>{if(signal?.aborted)throw Object.assign(new Error('Запрос отменён'),{name:'AbortError'})};
export function detectTraceQueryType(value:string):TraceQueryType{const q=value.trim();if(/^\[?(?:[\da-f]{0,4}:){2,}[\da-f:.]+\]?$/i.test(q)||/^(?:\d{1,3}\.){3}\d{1,3}$/.test(q))return'ip';if(/^(?:PJSIP|SIP|Local|IAX2|DAHDI)\//i.test(q))return'channel';if(/^[^\s@]+@[^\s@]+$/.test(q)||/^<[^>]+>$/.test(q))return'call_id';if(/^\d{9,12}\.\d+$/.test(q))return'uniqueid';if(/^\+?\d{7,16}$/.test(q))return'phone';if(/^\d{2,6}$/.test(q))return'extension';if(/^[A-Za-z][A-Za-z0-9_.@-]{1,63}$/.test(q))return'endpoint';return'text';}
export function validateTraceInput(input:TraceSearchInput){const query=String(input.query||'').trim();if(!query||query.length>255||/[\0\r\n]/.test(query))throw new Error('Некорректный идентификатор');const to=input.to?new Date(input.to):new Date(),from=input.from?new Date(input.from):new Date(to.getTime()-7*86400000);if(!Number.isFinite(from.getTime())||!Number.isFinite(to.getTime())||from>to||to.getTime()-from.getTime()>MAX_RANGE)throw new Error('Некорректный период');const allowed:TraceQueryType[]=['auto','phone','extension','endpoint','ip','uniqueid','linkedid','call_id','channel','text'];const requested=(input.queryType||'auto') as TraceQueryType;if(!allowed.includes(requested))throw new Error('Некорректный queryType');return{query,queryType:requested==='auto'?detectTraceQueryType(query):requested,from,to,limit:Math.max(1,Math.min(Number(input.limit)||50,100)),includeRaw:input.includeRaw===true,includeLowConfidence:input.includeLowConfidence===true,signal:input.signal};}

function cdrCondition(type:TraceQueryType,q:string){if(type==='uniqueid'||type==='linkedid')return{sql:'(uniqueid=? OR linkedid=?)',params:[q,q]};if(type==='channel')return{sql:'(channel=? OR dstchannel=? OR channel LIKE ? OR dstchannel LIKE ?)',params:[q,q,`%${q}%`,`%${q}%`]};if(type==='phone'||type==='extension'||type==='endpoint')return{sql:'(src=? OR dst=? OR cnum=? OR did=? OR outbound_cnum=? OR channel LIKE ? OR dstchannel LIKE ? OR lastdata LIKE ?)',params:[q,q,q,q,q,`%${q}%`,`%${q}%`,`%${q}%`]};return{sql:'(uniqueid=? OR linkedid=? OR src=? OR dst=? OR cnum=? OR did=? OR channel LIKE ? OR dstchannel LIKE ?)',params:[q,q,q,q,q,q,`%${q}%`,`%${q}%`]};}
function logicalId(row:any){return String(row.linkedid||row.uniqueid||'').trim();}
function direction(rows:any[]){const incoming=rows.some(r=>/from-(?:trunk|pstn)|ext-did/i.test(String(r.dcontext))||Boolean(String(r.did||''))&&!internal(r.did));const outgoing=rows.some(r=>/from-internal/i.test(String(r.dcontext))&&external(r.dst));const internalCall=!incoming&&rows.some(r=>internal(r.src)&&internal(r.dst));const externalBranch=rows.some(r=>external(r.dst)&&(/outbound|from-internal|macro-dialout|followme|fmgrps/i.test(`${r.dcontext} ${r.channel} ${r.dstchannel} ${r.lastdata}`)));if(incoming&&externalBranch)return'incoming_with_external_branch';if(internalCall&&externalBranch)return'internal_with_external_branch';if(incoming&&outgoing)return'mixed';if(incoming)return'incoming';if(outgoing)return'outgoing';if(internalCall)return'internal';return'unknown';}
const directionLabel=(v:string)=>({incoming:'входящий',outgoing:'исходящий',internal:'внутренний',incoming_with_external_branch:'входящий с внешней веткой Follow Me',internal_with_external_branch:'внутренний с внешней веткой',mixed:'смешанный',unknown:'неизвестно'} as any)[v]||v;
function summarizeCandidate(rows:any[]){const sorted=[...rows].sort((a,b)=>Date.parse(a.calldate)-Date.parse(b.calldate)),first=sorted[0],answered=rows.find(r=>String(r.disposition).toUpperCase()==='ANSWERED'&&Number(r.billsec)>0),dir=direction(rows);return{candidateId:logicalId(first),linkedid:logicalId(first),startedAt:first.calldate,endedAt:new Date(Date.parse(first.calldate)+Math.max(...rows.map(r=>Number(r.duration)||0))*1000).toISOString(),direction:dir,directionLabel:directionLabel(dir),src:first.src,incomingNumber:first.cnum||first.src,dst:first.dst,did:rows.find(r=>r.did)?.did||'',extension:rows.find(r=>internal(r.dst))?.dst||'',queue:rows.find(r=>/queue/i.test(`${r.lastapp} ${r.dcontext}`))?.dst||'',operator:answered&&internal(answered.dst)?answered.dst:'',disposition:answered?'ANSWERED':String(rows[rows.length-1].disposition||''),duration:Math.max(...rows.map(r=>Number(r.duration)||0)),billsec:Math.max(...rows.map(r=>Number(r.billsec)||0)),cdrCount:rows.length,logEventCount:0};}

export async function findCallTraceCandidates(deps:CallTraceDeps,input:TraceSearchInput){const v=validateTraceInput(input);abort(v.signal);let rows:any[]=[];if(v.queryType!=='call_id'&&v.queryType!=='ip'){const condition=cdrCondition(v.queryType,v.query);rows=await deps.queryCdr(`SELECT ${CDR_FIELDS} FROM cdr WHERE calldate BETWEEN ? AND ? AND ${condition.sql} ORDER BY calldate DESC LIMIT ${MAX_CDR}`,[dateSql(v.from),dateSql(v.to),...condition.params]);}const grouped=new Map<string,any[]>();for(const row of rows){const key=logicalId(row);if(!key)continue;if(!grouped.has(key))grouped.set(key,[]);grouped.get(key)!.push(row)}const candidates=[...grouped.values()].map(summarizeCandidate).sort((a,b)=>Date.parse(b.startedAt)-Date.parse(a.startedAt)).slice(0,v.limit);if(candidates.length){const ids=candidates.map(x=>x.linkedid);try{const placeholders=ids.map(()=>'?').join(',');const counts=await queryPBXPulsDb(`SELECT linkedid,COUNT(*) count FROM log_events WHERE linkedid IN (${placeholders}) GROUP BY linkedid`,ids);const byId=new Map(counts.map((r:any)=>[String(r.linkedid),Number(r.count)]));candidates.forEach(c=>c.logEventCount=byId.get(c.linkedid)||0)}catch{}}
 return{query:v.query,detectedQueryType:detectTraceQueryType(v.query),queryType:v.queryType,ambiguous:v.queryType==='text'||(v.queryType==='extension'&&candidates.length>1),candidates,total:candidates.length,period:{from:v.from.toISOString(),to:v.to.toISOString()}};}

async function loadCel(deps:CallTraceDeps,linkedid:string){try{return await deps.queryCdr(`SELECT ${CEL_FIELDS} FROM cel WHERE linkedid=? OR uniqueid=? ORDER BY eventtime ASC,id ASC LIMIT ${MAX_CEL}`,[linkedid,linkedid])}catch{return[]}}
function relation(confidence:TraceConfidence,type:string,value:string,source:string,explanation:string){return{confidence,type,value,source,explanation};}
function cdrTimeline(rows:any[]){const events:any[]=[];for(const r of rows){const rel=relation(r.linkedid?'exact':'high',r.linkedid?'linkedid':'uniqueid',r.linkedid||r.uniqueid,'CDR',r.linkedid?'CDR имеет точный Linkedid трассировки':'CDR найден по Uniqueid');events.push({id:`cdr:${r.uniqueid}:start`,occurredAt:r.calldate,source:'CDR',type:'cdr_start',title:`Ветка CDR: ${r.lastapp||r.dcontext||'маршрутизация'}`,description:`${r.src||'—'} → ${r.dst||'—'}; ${r.disposition||'—'}`,severity:['FAILED','BUSY'].includes(String(r.disposition).toUpperCase())?'warning':'info',channel:r.channel,relatedChannel:r.dstchannel,number:r.dst,uniqueid:r.uniqueid,linkedid:r.linkedid,confidence:rel.confidence,correlation:rel,raw:r});const end=new Date(Date.parse(r.calldate)+(Number(r.duration)||0)*1000).toISOString();events.push({id:`cdr:${r.uniqueid}:end`,occurredAt:end,source:'CDR',type:'cdr_end',title:String(r.disposition).toUpperCase()==='ANSWERED'?'Разговор завершён':'Ветка завершена без ответа',description:`Длительность ${r.duration||0} сек, разговор ${r.billsec||0} сек`,severity:String(r.disposition).toUpperCase()==='FAILED'?'error':'info',channel:r.channel,relatedChannel:r.dstchannel,number:r.dst,uniqueid:r.uniqueid,linkedid:r.linkedid,confidence:rel.confidence,correlation:rel,raw:r})}return events;}
function celTimeline(rows:any[],linkedid:string){return rows.map(r=>{const type=String(r.eventtype||'CEL').toLowerCase();const rel=relation(String(r.linkedid)===linkedid?'exact':'high',String(r.linkedid)===linkedid?'linkedid':'uniqueid',r.linkedid||r.uniqueid,'CEL',String(r.linkedid)===linkedid?'CEL имеет точный Linkedid':'CEL связан по Uniqueid');return{id:`cel:${r.id}`,occurredAt:r.eventtime,source:'CEL',type:`cel_${type}`,title:({chan_start:'Создан канал',answer:'Канал ответил',bridge_enter:'Канал вошёл в Bridge',bridge_exit:'Канал вышел из Bridge',hangup:'Канал закрыт',blindtransfer:'Blind transfer',attendedtransfer:'Attended transfer',app_start:`Запущено ${r.appname||'приложение'}`} as any)[type]||`CEL: ${r.eventtype}`,description:[r.cid_num&&`номер ${r.cid_num}`,r.exten&&`exten ${r.exten}`,r.appname&&`${r.appname}(${r.appdata||''})`].filter(Boolean).join('; '),severity:'info',channel:r.channame,relatedChannel:r.peer,number:r.exten||r.cid_num,uniqueid:r.uniqueid,linkedid:r.linkedid,confidence:rel.confidence,correlation:rel,raw:r}})}
function logRelation(event:any,ids:Set<string>,channels:Set<string>,numbers:Set<string>,windowStart:number,windowEnd:number){if(event.linkedid&&ids.has(event.linkedid))return relation('exact','linkedid',event.linkedid,event.sourceName,'Строка содержит точный Linkedid');if(event.uniqueid&&ids.has(event.uniqueid))return relation('exact','uniqueid',event.uniqueid,event.sourceName,'Строка содержит точный Uniqueid');if(event.callId)return relation('high','call_id',event.callId,event.sourceName,'Связано по SIP Call-ID в окне звонка');if(event.channel&&[...channels].some(c=>c&&baseChannel(c)===baseChannel(event.channel)))return relation('high','channel',event.channel,event.sourceName,'Совпадает базовое имя канала');const time=Date.parse(event.occurredAt);if(time>=windowStart&&time<=windowEnd&&[...numbers].some(n=>n&&event.rawMessage.includes(n)))return relation('medium','number_time',[...numbers].find(n=>event.rawMessage.includes(n))||'',event.sourceName,'Совпали номер и ограниченное временное окно');return relation('low','time_window','',event.sourceName,'Запись найдена только в близком временном окне');}
const baseChannel=(value:string)=>String(value||'').replace(/;[12]$/,'').replace(/-[0-9a-f]+$/i,'');
async function loadLogs(input:any,cdr:any[],linkedid:string){const detected=await detectLogSources(),wanted=detected.filter(s=>s.readable&&s.active&&['file','pm2'].includes(s.sourceType)&&(/asterisk\/full|queue_log|security|freepbx/i.test(`${s.canonicalPath} ${s.parserKey}`))).slice(0,8);const ids=new Set<string>([linkedid,input.query,...cdr.flatMap(r=>[r.uniqueid,r.linkedid]).filter(Boolean)].filter(Boolean)),channels=new Set<string>(cdr.flatMap(r=>[r.channel,r.dstchannel]).filter(Boolean)),numbers=new Set<string>(cdr.flatMap(r=>[r.src,r.dst,r.cnum,r.did,r.outbound_cnum]).map(digits).filter(n=>n.length>=2));const cdrStarts=cdr.map(r=>Date.parse(r.calldate)).filter(Number.isFinite),start=cdrStarts.length?Math.min(...cdrStarts):input.from.getTime(),end=cdr.length?Math.max(...cdr.map(r=>Date.parse(r.calldate)+(Number(r.duration)||0)*1000).filter(Number.isFinite),start):input.to.getTime();const from=new Date(start-120000).toISOString(),to=new Date(end+120000).toISOString(),events:any[]=[];let bytesRead=0;for(const source of wanted){abort(input.signal);const searches=[...ids].slice(0,10);let sourceRows:any[]=[];for(const id of searches){const part=await searchAllowedLogSource(source.sourceKey,{from,to,uniqueid:id,limit:80,maxBytes:256*1024,includeRotated:true,signal:input.signal});bytesRead+=part.bytesRead;sourceRows.push(...part.rows);if(sourceRows.length>=120)break}if(!sourceRows.length&&numbers.size){const number=[...numbers].sort((a,b)=>b.length-a.length)[0];const part=await searchAllowedLogSource(source.sourceKey,{from,to,phone:number,limit:80,maxBytes:128*1024,includeRotated:true,signal:input.signal});bytesRead+=part.bytesRead;sourceRows.push(...part.rows)}for(const event of sourceRows){const rel=logRelation(event,ids,channels,numbers,start-120000,end+120000);events.push({...event,id:`log:${event.sourceKey}:${event.occurredAt}:${event.fingerprint}`,source:event.sourceName,type:event.eventType,description:event.message,confidence:rel.confidence,correlation:rel,originPath:event.originPath})}}const unique=new Map<string,any>();events.forEach(e=>unique.set(`${e.sourceKey}|${e.occurredAt}|${e.rawMessage}`,e));return{events:[...unique.values()].slice(0,MAX_LOG),bytesRead,from,to,searchedSources:wanted.map(s=>s.sourceKey),rotatedFilesConsidered:wanted.reduce((sum,s)=>sum+(s.rotatedPaths?.length||0),0)};}
function graph(cdr:any[],cel:any[]){const nodes=new Map<string,any>(),edges:any[]=[];const add=(id:string,type:string,label:string,row:any)=>{if(!id)return;if(!nodes.has(id))nodes.set(id,{id,type,label,number:digits(label),startedAt:row.calldate||row.eventtime,answeredAt:null,endedAt:null,disposition:row.disposition||''})};for(const r of cdr){const a=baseChannel(r.channel)||`src:${r.src}`,b=baseChannel(r.dstchannel)||`dst:${r.dst}`;add(a,/Local\//i.test(a)?'local':/PJSIP|SIP/i.test(a)?'endpoint':'channel',a,r);add(b,/Local\//i.test(b)?'local':external(r.dst)?'trunk':'endpoint',b,r);if(a&&b)edges.push({id:`${a}->${b}:${r.uniqueid}`,from:a,to:b,type:/queue/i.test(`${r.lastapp} ${r.dcontext}`)?'Queue':/followme|fmgrps/i.test(`${r.dcontext} ${r.lastdata}`)?'Follow Me':'Dial',confidence:r.linkedid?'exact':'high',reason:r.linkedid?'Связь CDR по linkedid':'Связь channel/dstchannel'})}for(const r of cel){if(!/bridge_enter/i.test(r.eventtype))continue;const a=baseChannel(r.channame),b=baseChannel(r.peer);add(a,'channel',a,r);add(b,'channel',b,r);if(a&&b)edges.push({id:`bridge:${r.id}`,from:a,to:b,type:'Bridge',confidence:'exact',reason:'CEL BRIDGE_ENTER'})}return{nodes:[...nodes.values()].slice(0,100),edges:edges.slice(0,200)};}
function diagnostic(cdr:any[],cel:any[],logs:any[],dir:string){const answered=cdr.find(r=>String(r.disposition).toUpperCase()==='ANSWERED'&&Number(r.billsec)>0),failedSip=logs.find(r=>/sip.*(?:4\d\d|5\d\d)|503|forbidden|timeout/i.test(r.rawMessage||'')),queue=cdr.find(r=>/queue/i.test(`${r.lastapp} ${r.dcontext}`));if(failedSip)return{certainty:'confirmed',title:'Транк или endpoint вернул ошибку SIP',details:failedSip.message};if(answered)return{certainty:'confirmed',title:`Звонок успешно отвечен${internal(answered.dst)?` внутренним номером ${answered.dst}`:''}`,details:`Разговор ${answered.billsec} сек; направление: ${directionLabel(dir)}.`};if(queue)return{certainty:'probable',title:`Вероятно, звонок потерян в очереди ${queue.dst||''}`,details:`Ожидание ${queue.duration||0} сек, disposition ${queue.disposition||'неизвестен'}.`};if(cdr.length)return{certainty:'probable',title:'Звонок завершён без подтверждённого ответа',details:`Последний disposition: ${cdr[cdr.length-1].disposition||'неизвестен'}.`};return{certainty:'insufficient',title:'Причина не определена однозначно',details:'Недостаточно CDR/CEL для подтверждённого вывода.'};}

export async function buildCallTrace(deps:CallTraceDeps,input:TraceSearchInput){const v=validateTraceInput(input),key=JSON.stringify({q:v.query,t:v.queryType,f:v.from.toISOString(),to:v.to.toISOString(),raw:v.includeRaw,low:v.includeLowConfidence}),cached=cache.get(key);if(cached&&cached.expires>Date.now())return{...cached.value,cached:true};abort(v.signal);let cdr:any[]=[];if(v.queryType==='linkedid'||v.queryType==='uniqueid'){cdr=await deps.queryCdr(`SELECT ${CDR_FIELDS} FROM cdr WHERE linkedid=? OR uniqueid=? ORDER BY calldate ASC LIMIT ${MAX_CDR}`,[v.query,v.query])}else{const candidates=await findCallTraceCandidates(deps,v);const selected=candidates.candidates[0];if(selected)cdr=await deps.queryCdr(`SELECT ${CDR_FIELDS} FROM cdr WHERE linkedid=? OR uniqueid=? ORDER BY calldate ASC LIMIT ${MAX_CDR}`,[selected.linkedid,selected.linkedid])}abort(v.signal);const linkedid=cdr.length?logicalId(cdr[0]):v.query,cel=cdr.length?await loadCel(deps,linkedid):[],logs=await (deps.searchLogs||loadLogs)(v,cdr,linkedid),dir=direction(cdr),all=[...cdrTimeline(cdr),...celTimeline(cel,linkedid),...logs.events].sort((a,b)=>Date.parse(a.occurredAt)-Date.parse(b.occurredAt)),main=all.filter(e=>e.confidence!=='low'),low=all.filter(e=>e.confidence==='low');const raw=v.includeRaw?{cdr,cel,logs:logs.events}:undefined;const result={query:v.query,queryType:v.queryType,linkedid,cdrCount:cdr.length,celCount:cel.length,logEventCount:logs.events.length,direction:dir,directionLabel:directionLabel(dir),summary:diagnostic(cdr,cel,logs.events,dir),timeline:main.slice(0,1000),possibleRelations:v.includeLowConfidence?low.slice(0,200):[],graph:graph(cdr,cel),cdr,cel,sipEvents:logs.events.filter(e=>/sip|pjsip|invite|bye|rtp/i.test(`${e.eventType} ${e.rawMessage}`)).slice(0,200),logEvents:logs.events.slice(0,MAX_LOG),raw,window:{from:logs.from,to:logs.to},collector:{bytesRead:logs.bytesRead,searchedSources:logs.searchedSources||[],rotatedFilesConsidered:logs.rotatedFilesConsidered||0},limits:{cdr:MAX_CDR,cel:MAX_CEL,logs:MAX_LOG},cached:false};cache.set(key,{expires:Date.now()+CACHE_TTL,value:result});if(cache.size>100)for(const [k,x]of cache)if(x.expires<Date.now())cache.delete(k);return result;}

export function maskTraceForReport(value:any){return JSON.parse(JSON.stringify(value,(_key,item)=>typeof item==='string'?sanitizeLogText(item,4000):item));}
