import { queryPBXPulsDb } from '../pbxpulsDb.js';
import { getPBXPulsSettingsByCategory, upsertPBXPulsSetting } from '../pbxpulsSettings.js';
import { sanitizeLogText } from './redaction.js';
import type { DetectedLogSource, LogCursor, NormalizedLogEvent } from './types.js';

export const LOG_ANALYSIS_DEFAULTS: Record<string,boolean|number> = {
  'log_analysis.enabled':true,'log_analysis.poll_interval_seconds':5,'log_analysis.retention_days':30,
  'log_analysis.group_retention_days':90,'log_analysis.message_max_length':4000,'log_analysis.context_lines':5,
  'log_analysis.correlation_enabled':true,'log_analysis.grouping_enabled':true,'log_analysis.max_history_days':7,
  'log_analysis.max_export_rows':5000,'log_analysis.debug_visible':false
};
export async function getLogAnalysisSettings(){return {...LOG_ANALYSIS_DEFAULTS,...await getPBXPulsSettingsByCategory('log_analysis')};}
export async function updateLogAnalysisSettings(input:Record<string,unknown>){const saved:Record<string,unknown>={};const ranges:Record<string,[number,number]>={
  'log_analysis.poll_interval_seconds':[5,300],'log_analysis.retention_days':[1,365],'log_analysis.group_retention_days':[1,730],
  'log_analysis.message_max_length':[500,10000],'log_analysis.context_lines':[0,20],'log_analysis.max_history_days':[1,31],'log_analysis.max_export_rows':[100,10000]};
  for(const [key,def] of Object.entries(LOG_ANALYSIS_DEFAULTS)){if(!(key in input))continue;const value=typeof def==='boolean'?input[key]===true:Math.max(ranges[key]?.[0]||1,Math.min(Number(input[key])||Number(def),ranges[key]?.[1]||10000));await upsertPBXPulsSetting(key,value,{category:'log_analysis',valueType:typeof def==='boolean'?'boolean':'number'});saved[key]=value;}return saved;}

const sqlDate=(value?:string|null)=>value?new Date(value).toISOString().slice(0,19).replace('T',' '):null;
const json=(value:unknown)=>JSON.stringify(value??null);
const parseJson=(value:any,fallback:any)=>{try{return JSON.parse(String(value||''))}catch{return fallback}};

export async function saveDetectedSources(sources:DetectedLogSource[]){for(const s of sources)await queryPBXPulsDb(`INSERT INTO log_sources
  (source_key,display_name,category,source_type,canonical_path,journal_unit,detected,readable,active,status,file_size,inode_value,modified_at,read_error,parser_key,platform,collector_version)
  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name),category=VALUES(category),detected=VALUES(detected),
  readable=VALUES(readable),active=VALUES(active),status=VALUES(status),file_size=VALUES(file_size),inode_value=VALUES(inode_value),modified_at=VALUES(modified_at),read_error=VALUES(read_error),
  parser_key=VALUES(parser_key),platform=VALUES(platform),collector_version=VALUES(collector_version)`,[s.sourceKey,s.displayName,s.category,s.sourceType,s.canonicalPath||null,s.journalUnit||null,s.detected?1:0,s.readable?1:0,s.active?1:0,s.active?'online':s.detected?s.readError?'read_error':'unavailable':'missing',s.fileSize||null,s.inode||null,sqlDate(s.modifiedAt),s.readError||null,s.parserKey,s.platform,s.collectorVersion]);}
export async function listLogSources(){const rows=await queryPBXPulsDb(`SELECT *,canonical_path AS canonicalPath,journal_unit AS journalUnit,source_key AS sourceKey,display_name AS displayName,
  source_type AS sourceType,file_size AS fileSize,inode_value AS inode,modified_at AS modifiedAt,last_read_at AS lastReadAt,last_event_at AS lastEventAt,
  read_error AS readError,parser_key AS parserKey,collector_version AS collectorVersion FROM log_sources ORDER BY category,display_name`);return rows.map((r:any)=>({...r,detected:Boolean(r.detected),readable:Boolean(r.readable),active:Boolean(r.active)}));}
export async function loadLogCursors(){const rows=await queryPBXPulsDb('SELECT * FROM log_cursors');return new Map(rows.map((r:any)=>[String(r.source_key),{sourceKey:r.source_key,inode:r.inode_value||undefined,offset:Number(r.byte_offset||0),fileSize:Number(r.file_size||0),modifiedAt:r.modified_at?new Date(r.modified_at).toISOString():undefined,journalCursor:r.journal_cursor||undefined,lastLineHash:r.last_line_hash||undefined,lastReadAt:r.last_read_at?new Date(r.last_read_at).toISOString():undefined}]));}
export async function saveLogCursor(cursor:LogCursor){await queryPBXPulsDb(`INSERT INTO log_cursors (source_key,inode_value,byte_offset,file_size,modified_at,journal_cursor,last_line_hash,last_read_at,collector_version)
  VALUES (?,?,?,?,?,?,?,?, '1') ON DUPLICATE KEY UPDATE inode_value=VALUES(inode_value),byte_offset=VALUES(byte_offset),file_size=VALUES(file_size),modified_at=VALUES(modified_at),journal_cursor=VALUES(journal_cursor),last_line_hash=VALUES(last_line_hash),last_read_at=VALUES(last_read_at),collector_version='1'`,[cursor.sourceKey,cursor.inode||null,cursor.offset,cursor.fileSize,sqlDate(cursor.modifiedAt),cursor.journalCursor||null,cursor.lastLineHash||null,sqlDate(cursor.lastReadAt)]);}
export async function markLogSourceRead(sourceKey:string,input:{lastEventAt?:string;error?:string;status?:string;fileSize?:number;inode?:string;modifiedAt?:string}){await queryPBXPulsDb(`UPDATE log_sources SET status=?,last_read_at=NOW(),last_event_at=COALESCE(?,last_event_at),read_error=?,file_size=COALESCE(?,file_size),inode_value=COALESCE(?,inode_value),modified_at=COALESCE(?,modified_at) WHERE source_key=?`,[input.status||(input.error?'read_error':'waiting'),sqlDate(input.lastEventAt),input.error?sanitizeLogText(input.error,500):null,input.fileSize??null,input.inode||null,sqlDate(input.modifiedAt),sourceKey]);}

export async function storeLogEvent(event:NormalizedLogEvent):Promise<'created'|'duplicate'>{const result:any=await queryPBXPulsDb(`INSERT IGNORE INTO log_events
  (dedup_key,occurred_at,received_at,source_key,source_name,category,severity,event_type,title,message,raw_message,host,process_name,pid,module_name,ip_address,port,protocol,username,extension_number,sip_peer,trunk,channel,call_id,uniqueid,linkedid,http_method,http_path,http_status,service,jail,fingerprint,parser_confidence,tags_json,recommendations_json,context_before_json,context_after_json)
  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[event.dedupKey,sqlDate(event.occurredAt),sqlDate(event.receivedAt),event.sourceKey,event.sourceName,event.category,event.severity,event.eventType,event.title.slice(0,255),sanitizeLogText(event.message,2000),sanitizeLogText(event.rawMessage,4000),event.host||null,event.process||null,event.pid||null,event.module||null,event.ip||null,event.port||null,event.protocol||null,event.username||null,event.extension||null,event.sipPeer||null,event.trunk||null,event.channel||null,event.callId||null,event.uniqueid||null,event.linkedid||null,event.httpMethod||null,event.httpPath||null,event.httpStatus||null,event.service||null,event.jail||null,event.fingerprint,event.parserConfidence,json(event.tags),json(event.recommendedActions),json(event.contextBefore||[]),json(event.contextAfter||[])]);
  if(!Number(result?.affectedRows))return'duplicate';await queryPBXPulsDb(`INSERT INTO log_event_groups (fingerprint,source_key,category,severity,event_type,title,last_message,occurrence_count,first_seen_at,last_seen_at,affected_ips_json,affected_extensions_json,affected_trunks_json)
  VALUES (?,?,?,?,?,?,?,1,?,?,?,?,?) ON DUPLICATE KEY UPDATE occurrence_count=occurrence_count+1,last_seen_at=GREATEST(last_seen_at,VALUES(last_seen_at)),last_message=VALUES(last_message),severity=VALUES(severity),affected_ips_json=IF(VALUES(affected_ips_json)='[]',affected_ips_json,VALUES(affected_ips_json)),affected_extensions_json=IF(VALUES(affected_extensions_json)='[]',affected_extensions_json,VALUES(affected_extensions_json)),affected_trunks_json=IF(VALUES(affected_trunks_json)='[]',affected_trunks_json,VALUES(affected_trunks_json))`,[event.fingerprint,event.sourceKey,event.category,event.severity,event.eventType,event.title,event.message,sqlDate(event.occurredAt),sqlDate(event.occurredAt),json(event.ip?[event.ip]:[]),json(event.extension?[event.extension]:[]),json(event.trunk?[event.trunk]:[])]);return'created';}

export async function correlateLogEvent(event:NormalizedLogEvent){const keys:[string,string,string][]=[];if(event.linkedid)keys.push(['linkedid',event.linkedid,'Связано по linkedid']);if(event.callId)keys.push(['call_id',event.callId,'Связано по Call-ID']);if(event.ip)keys.push(['ip_address',event.ip,'Вероятно связано по IP и времени']);for(const [column,value,explanation] of keys){const rows=await queryPBXPulsDb(`SELECT id FROM log_events WHERE ${column}=? AND occurred_at BETWEEN DATE_SUB(?,INTERVAL 5 MINUTE) AND DATE_ADD(?,INTERVAL 5 MINUTE) ORDER BY occurred_at DESC LIMIT 20`,[value,sqlDate(event.occurredAt),sqlDate(event.occurredAt)]);if(rows.length<2)continue;const ids=rows.map((r:any)=>Number(r.id));const correlationKey=`${column}:${value}:${new Date(event.occurredAt).toISOString().slice(0,13)}`;const confidence=column==='linkedid'?1:column==='call_id'?0.95:0.7;await queryPBXPulsDb(`INSERT INTO log_correlations (correlation_key,correlation_type,confidence,explanation,event_ids_json,first_seen_at,last_seen_at) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE event_ids_json=VALUES(event_ids_json),last_seen_at=VALUES(last_seen_at),confidence=VALUES(confidence)`,[correlationKey,column,confidence,explanation,json(ids),sqlDate(event.occurredAt),sqlDate(event.occurredAt)]);await queryPBXPulsDb(`UPDATE log_events SET correlation_id=?,correlation_type=?,correlation_confidence=? WHERE id IN (${ids.map(()=>'?').join(',')})`,[correlationKey,column,confidence,...ids]);break;}}

export function buildEventFilter(query:Record<string,unknown>){const where:string[]=[];const params:any[]=[];const period=String(query.period||'1h');const periodMs:Record<string,number>={'15m':900000,'1h':3600000,'6h':21600000,'24h':86400000,'3d':259200000,'7d':604800000};let from=query.from?new Date(String(query.from)):new Date(Date.now()-(periodMs[period]||3600000));let to=query.to?new Date(String(query.to)):new Date();if(!Number.isFinite(from.getTime()))from=new Date(Date.now()-3600000);if(!Number.isFinite(to.getTime()))to=new Date();if(to.getTime()-from.getTime()>31*86400000)from=new Date(to.getTime()-31*86400000);where.push('occurred_at BETWEEN ? AND ?');params.push(sqlDate(from.toISOString()),sqlDate(to.toISOString()));for(const [key,col] of [['sourceKey','source_key'],['category','category'],['severity','severity'],['eventType','event_type'],['ip','ip_address'],['extension','extension_number'],['trunk','trunk'],['service','service']] as const){const v=String(query[key]||'').trim();if(v){where.push(`${col}=?`);params.push(v)}}const search=String(query.search||'').trim().slice(0,200);if(search){where.push('(title LIKE ? OR message LIKE ? OR raw_message LIKE ?)');params.push(`%${search}%`,`%${search}%`,`%${search}%`)}if(String(query.onlyRecommendations)==='true')where.push("recommendations_json IS NOT NULL AND recommendations_json<>'[]'");if(String(query.onlyNew)==='true')where.push('received_at>=DATE_SUB(NOW(),INTERVAL 5 MINUTE)');return{where:`WHERE ${where.join(' AND ')}`,params,from,to};}
function mapEvent(r:any){return{eventId:Number(r.id),occurredAt:r.occurred_at,receivedAt:r.received_at,sourceKey:r.source_key,sourceName:r.source_name,category:r.category,severity:r.severity,eventType:r.event_type,title:r.title,message:r.message,rawMessage:r.raw_message,host:r.host,process:r.process_name,pid:r.pid,module:r.module_name,ip:r.ip_address,port:r.port,protocol:r.protocol,username:r.username,extension:r.extension_number,sipPeer:r.sip_peer,trunk:r.trunk,channel:r.channel,callId:r.call_id,uniqueid:r.uniqueid,linkedid:r.linkedid,httpMethod:r.http_method,httpPath:r.http_path,httpStatus:r.http_status,service:r.service,jail:r.jail,fingerprint:r.fingerprint,count:Number(r.count||r.occurrence_count||1),firstSeenAt:r.first_seen_at||r.occurred_at,lastSeenAt:r.last_seen_at||r.occurred_at,parserConfidence:Number(r.parser_confidence||0),tags:parseJson(r.tags_json,[]),recommendedActions:parseJson(r.recommendations_json,[]),correlationId:r.correlation_id,correlationType:r.correlation_type,correlationConfidence:Number(r.correlation_confidence||0)}}
export async function listLogEvents(query:Record<string,unknown>){const f=buildEventFilter(query);const page=Math.max(1,Number(query.page)||1),pageSize=Math.max(10,Math.min(Number(query.pageSize)||50,200)),offset=(page-1)*pageSize;const grouped=String(query.grouped??'true')!=='false';if(grouped){const count=await queryPBXPulsDb(`SELECT COUNT(DISTINCT fingerprint) total FROM log_events ${f.where}`,f.params);const rows=await queryPBXPulsDb(`SELECT MAX(id) id,MAX(occurred_at) occurred_at,MAX(received_at) received_at,MAX(source_key) source_key,MAX(source_name) source_name,MAX(category) category,MAX(severity) severity,MAX(event_type) event_type,MAX(title) title,MAX(message) message,MAX(raw_message) raw_message,MAX(ip_address) ip_address,MAX(extension_number) extension_number,MAX(trunk) trunk,MAX(call_id) call_id,MAX(uniqueid) uniqueid,MAX(linkedid) linkedid,MAX(service) service,MAX(jail) jail,fingerprint,COUNT(*) count,MIN(occurred_at) first_seen_at,MAX(occurred_at) last_seen_at,MAX(parser_confidence) parser_confidence,MAX(tags_json) tags_json,MAX(recommendations_json) recommendations_json,MAX(correlation_id) correlation_id,MAX(correlation_type) correlation_type,MAX(correlation_confidence) correlation_confidence FROM log_events ${f.where} GROUP BY fingerprint ORDER BY last_seen_at DESC LIMIT ${pageSize} OFFSET ${offset}`,f.params);return{rows:rows.map(mapEvent),total:Number(count[0]?.total||0),page,pageSize,grouped:true};}const count=await queryPBXPulsDb(`SELECT COUNT(*) total FROM log_events ${f.where}`,f.params);const rows=await queryPBXPulsDb(`SELECT * FROM log_events ${f.where} ORDER BY occurred_at DESC LIMIT ${pageSize} OFFSET ${offset}`,f.params);return{rows:rows.map(mapEvent),total:Number(count[0]?.total||0),page,pageSize,grouped:false};}
export async function exportLogEvents(query:Record<string,unknown>,limit:number){const f=buildEventFilter(query);const safeLimit=Math.max(100,Math.min(Number(limit)||5000,10000));const rows=await queryPBXPulsDb(`SELECT * FROM log_events ${f.where} ORDER BY occurred_at DESC LIMIT ${safeLimit}`,f.params);return rows.map(mapEvent);}
export async function getLogEvent(id:number){const rows=await queryPBXPulsDb('SELECT * FROM log_events WHERE id=? LIMIT 1',[id]);return rows[0]?mapEvent(rows[0]):null;}
export async function getLogEventContext(id:number,lines:number){const event=await getLogEvent(id);if(!event)return null;const rows=await queryPBXPulsDb('SELECT * FROM log_events WHERE source_key=? AND occurred_at BETWEEN DATE_SUB(?,INTERVAL 2 MINUTE) AND DATE_ADD(?,INTERVAL 2 MINUTE) ORDER BY occurred_at LIMIT 100',[event.sourceKey,sqlDate(event.occurredAt),sqlDate(event.occurredAt)]);const mapped=rows.map(mapEvent),index=mapped.findIndex((r:any)=>r.eventId===id);return{event,before:mapped.slice(Math.max(0,index-lines),index),after:mapped.slice(index+1,index+1+lines)};}
export async function getLogCorrelations(id:number){const event=await getLogEvent(id);if(!event?.correlationId)return{correlation:null,events:[]};const rows=await queryPBXPulsDb('SELECT * FROM log_correlations WHERE correlation_key=? LIMIT 1',[event.correlationId]);const corr=rows[0];if(!corr)return{correlation:null,events:[]};const ids=parseJson(corr.event_ids_json,[]).filter((v:any)=>Number.isSafeInteger(Number(v))).slice(0,50);const events=ids.length?await queryPBXPulsDb(`SELECT * FROM log_events WHERE id IN (${ids.map(()=>'?').join(',')}) ORDER BY occurred_at`,ids):[];return{correlation:{...corr,eventIds:ids},events:events.map(mapEvent)};}
export async function cleanupLogAnalysisRetention(){const settings=await getLogAnalysisSettings();for(let i=0;i<5;i++){const r:any=await queryPBXPulsDb('DELETE FROM log_events WHERE occurred_at<DATE_SUB(NOW(),INTERVAL ? DAY) LIMIT 1000',[Number(settings['log_analysis.retention_days'])]);if(Number(r?.affectedRows||0)<1000)break;}for(let i=0;i<5;i++){const r:any=await queryPBXPulsDb('DELETE FROM log_event_groups WHERE last_seen_at<DATE_SUB(NOW(),INTERVAL ? DAY) LIMIT 1000',[Number(settings['log_analysis.group_retention_days'])]);if(Number(r?.affectedRows||0)<1000)break;}}

export async function getLogSummary(query:Record<string,unknown>){const f=buildEventFilter(query);const totals=await queryPBXPulsDb(`SELECT COUNT(*) total,SUM(severity='critical') critical,SUM(severity='error') errors,SUM(severity='warning') warnings,COUNT(DISTINCT fingerprint) groups,COUNT(DISTINCT CASE WHEN ip_address IS NOT NULL THEN ip_address END) externalIps,SUM(category='asterisk') asteriskEvents,SUM(category='security') securityEvents,MAX(CASE WHEN severity='critical' THEN occurred_at END) lastCritical FROM log_events ${f.where}`,f.params);const source=await queryPBXPulsDb(`SELECT SUM(active=1 AND readable=1) activeSources,SUM(read_error IS NOT NULL) sourceErrors FROM log_sources`);const rate=await queryPBXPulsDb(`SELECT COUNT(*) rate FROM log_events WHERE received_at>=DATE_SUB(NOW(),INTERVAL 1 MINUTE)`);return{...totals[0],...source[0],ratePerMinute:Number(rate[0]?.rate||0)};}
export async function getLogTimeline(query:Record<string,unknown>){const f=buildEventFilter(query);const span=f.to.getTime()-f.from.getTime();const format=span<=6*3600000?'%Y-%m-%d %H:%i':span<=3*86400000?'%Y-%m-%d %H:00':'%Y-%m-%d';return queryPBXPulsDb(`SELECT DATE_FORMAT(occurred_at,'${format}') bucket,SUM(severity='critical') critical,SUM(severity='error') errors,SUM(severity='warning') warnings,SUM(severity IN ('notice','info','debug')) info FROM log_events ${f.where} GROUP BY bucket ORDER BY bucket`,f.params);}
export async function getLogHeatmap(query:Record<string,unknown>){const f=buildEventFilter(query);return queryPBXPulsDb(`SELECT WEEKDAY(occurred_at) weekday,HOUR(occurred_at) hour,COUNT(*) count,SUM(severity IN ('critical','error')) errors,SUM(category='security') security,SUM(category='asterisk') asterisk FROM log_events ${f.where} GROUP BY weekday,hour ORDER BY weekday,hour`,f.params);}
export async function getLogTopIps(query:Record<string,unknown>){const f=buildEventFilter(query);const where=`${f.where} AND ip_address IS NOT NULL`;return queryPBXPulsDb(`SELECT ip_address ip,COUNT(*) count,SUM(event_type IN ('ssh_auth_failed','ssh_invalid_user','sip_authentication_failed')) authFailures,SUM(event_type='fail2ban_ban') bans,MAX(occurred_at) lastEventAt FROM log_events ${where} GROUP BY ip_address ORDER BY count DESC LIMIT 20`,f.params);}
export async function getLogEventTypes(query:Record<string,unknown>){const f=buildEventFilter(query);return queryPBXPulsDb(`SELECT event_type eventType,COUNT(*) count FROM log_events ${f.where} GROUP BY event_type ORDER BY count DESC LIMIT 20`,f.params);}
export async function getLogSourceDistribution(query:Record<string,unknown>){const f=buildEventFilter(query);return queryPBXPulsDb(`SELECT category,COUNT(*) count FROM log_events ${f.where} GROUP BY category ORDER BY count DESC`,f.params);}
