import React,{useEffect,useMemo,useRef,useState} from 'react';
import {AlertTriangle,Download,GitBranch,PhoneCall,Search} from 'lucide-react';

type Props={token:string;initialQuery?:string};
const fmt=(value:any)=>value?new Date(value).toLocaleString('ru-RU',{hour12:false}):'—';
const confidence:Record<string,string>={exact:'точная',high:'высокая',medium:'средняя',low:'низкая'};
const periods:Record<string,number>={'24h':1,'3d':3,'7d':7,'30d':30};

export default function CallTracePanel({token,initialQuery=''}:Props){
 const [query,setQuery]=useState(initialQuery),[queryType,setQueryType]=useState('auto'),[period,setPeriod]=useState('7d'),[candidates,setCandidates]=useState<any[]>([]),[trace,setTrace]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[includeLow,setIncludeLow]=useState(false),[rawOpen,setRawOpen]=useState(false);const controller=useRef<AbortController|null>(null);
 useEffect(()=>{if(initialQuery)setQuery(initialQuery)},[initialQuery]);useEffect(()=>()=>controller.current?.abort(),[]);
 const range=()=>{const to=new Date(),from=new Date(to.getTime()+(periods[period]||7)*-86400000);return{from:from.toISOString(),to:to.toISOString()}};
 const request=async(path:string)=>{controller.current?.abort();const c=new AbortController();controller.current=c;const r=await fetch(path,{headers:{Authorization:`Bearer ${token}`},signal:c.signal});const data=await r.json();if(!r.ok||data.success===false)throw new Error(data.error?.message||`HTTP ${r.status}`);return data};
 const search=async()=>{if(!query.trim())return;setLoading(true);setError('');setTrace(null);try{const p=new URLSearchParams({query:query.trim(),queryType,...range(),limit:'50'}),data=await request(`/api/monitoring/log-analysis/call-trace/candidates?${p}`);setCandidates(data.candidates||[]);if((data.candidates||[]).length===1)await open(data.candidates[0].linkedid)}catch(e:any){if(e.name!=='AbortError')setError(e.message)}finally{setLoading(false)}};
 const open=async(id:string)=>{setLoading(true);setError('');try{const p=new URLSearchParams({query:id,queryType:'linkedid',...range(),includeLowConfidence:String(includeLow)}),data=await request(`/api/monitoring/log-analysis/call-trace?${p}`);setTrace(data.trace);setCandidates([])}catch(e:any){if(e.name!=='AbortError')setError(e.message)}finally{setLoading(false)}};
 const download=async()=>{if(!trace)return;const p=new URLSearchParams({query:trace.linkedid,queryType:'linkedid',...range(),includeLowConfidence:String(includeLow)}),r=await fetch(`/api/monitoring/log-analysis/call-trace/export?${p}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)return;const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`pbxpuls-call-trace-${trace.linkedid}.json`;a.click();URL.revokeObjectURL(url)};
 const edges=useMemo(()=>new Map((trace?.graph?.edges||[]).map((x:any)=>[x.from,x])),[trace]);
 return <div className="space-y-4">
  <div className="rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><PhoneCall className="h-5 w-5 text-indigo-500"/><div><h3 className="font-black dark:text-white">Трассировка звонка</h3><p className="text-xs text-slate-500">CDR, CEL, Asterisk full с ротацией, Queue и SIP в одной временной шкале</p></div></div><div className="mt-4 grid gap-2 md:grid-cols-[1fr_180px_130px_auto]"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input className="input pl-9" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Номер, endpoint, Uniqueid, Linkedid, Call-ID или канал"/></label><select className="input" value={queryType} onChange={e=>setQueryType(e.target.value)}><option value="auto">Автоопределение</option><option value="phone">Телефон</option><option value="extension">Внутренний</option><option value="endpoint">Endpoint</option><option value="uniqueid">Uniqueid</option><option value="linkedid">Linkedid</option><option value="call_id">SIP Call-ID</option><option value="channel">Канал</option></select><select className="input" value={period} onChange={e=>setPeriod(e.target.value)}><option value="24h">24 часа</option><option value="3d">3 дня</option><option value="7d">7 дней</option><option value="30d">30 дней</option></select><button className="btn" disabled={loading||!query.trim()} onClick={search}>{loading?'Поиск…':'Найти звонок'}</button></div><label className="mt-3 flex items-center gap-2 text-xs"><input type="checkbox" checked={includeLow} onChange={e=>setIncludeLow(e.target.checked)}/>Показывать возможные связи с низкой уверенностью отдельно</label></div>
  {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:bg-red-950/30 dark:text-red-300"><AlertTriangle className="mr-2 inline h-4 w-4"/>{error}</div>}
  {candidates.length>0&&<div className="rounded-xl border bg-white dark:border-slate-800 dark:bg-slate-900"><h3 className="border-b p-4 text-sm font-black dark:border-slate-800 dark:text-white">Выберите звонок ({candidates.length})</h3><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr>{['Начало','Направление','Откуда → куда','DID / оператор','Результат','Длительность','CDR','Логи'].map(x=><th className="p-3 text-[10px] uppercase text-slate-500" key={x}>{x}</th>)}</tr></thead><tbody>{candidates.map(c=><tr key={c.candidateId} onClick={()=>open(c.linkedid)} className="cursor-pointer border-t hover:bg-indigo-50 dark:border-slate-800 dark:hover:bg-slate-800"><td className="p-3">{fmt(c.startedAt)}</td><td>{c.directionLabel}</td><td className="font-mono">{c.src||'—'} → {c.dst||'—'}</td><td>{c.did||c.operator||'—'}</td><td>{c.disposition}</td><td>{c.duration} сек</td><td>{c.cdrCount}</td><td>{c.logEventCount}</td></tr>)}</tbody></table></div></div>}
  {trace&&<><div className="grid gap-3 md:grid-cols-4"><div className="rounded-xl border bg-white p-4 md:col-span-2 dark:border-slate-800 dark:bg-slate-900"><div className="text-[10px] font-bold uppercase text-slate-400">Итог — {trace.summary.certainty}</div><div className="mt-1 font-black dark:text-white">{trace.summary.title}</div><p className="mt-1 text-xs text-slate-500">{trace.summary.details}</p></div>{[['Направление',trace.directionLabel],['Linkedid',trace.linkedid],['CDR / CEL',`${trace.cdrCount} / ${trace.celCount}`],['События логов',trace.logEventCount]].map(([k,v])=><div key={k} className="rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="text-[10px] font-bold uppercase text-slate-400">{k}</div><div className="mt-1 break-all font-bold dark:text-white">{v}</div></div>)}</div>
  <div className="rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 text-sm font-black dark:text-white"><GitBranch className="h-4 w-4"/>Граф каналов</h3><button className="btn" onClick={download}><Download className="h-3 w-3"/>Отчёт JSON</button></div><div className="mt-4 flex flex-wrap items-center gap-2">{(trace.graph.nodes||[]).map((n:any)=><React.Fragment key={n.id}><div className="max-w-[260px] rounded-lg border border-indigo-200 bg-indigo-50 p-3 dark:border-indigo-900 dark:bg-indigo-950/30"><div className="text-[9px] font-bold uppercase text-indigo-500">{n.type}</div><div className="break-all font-mono text-xs">{n.label}</div></div>{edges.get(n.id)&&<span className="text-[10px] font-bold text-slate-400">— {edges.get(n.id)?.type} →</span>}</React.Fragment>)}</div>{!trace.graph.nodes?.length&&<p className="mt-3 text-xs text-slate-400">Каналы не найдены.</p>}</div>
  <div className="rounded-xl border bg-white dark:border-slate-800 dark:bg-slate-900"><h3 className="border-b p-4 text-sm font-black dark:border-slate-800 dark:text-white">Временная шкала ({trace.timeline.length})</h3><div className="max-h-[620px] overflow-auto p-4"><div className="space-y-3 border-l-2 border-indigo-200 pl-5">{trace.timeline.map((e:any)=><div key={e.id} className="relative rounded-lg border p-3 text-xs dark:border-slate-800"><span className="absolute -left-[27px] top-4 h-3 w-3 rounded-full bg-indigo-500"/><div className="flex flex-wrap justify-between gap-2"><b className="dark:text-white">{e.title}</b><span className="font-mono text-[10px] text-slate-500">{fmt(e.occurredAt)}</span></div><p className="mt-1 text-slate-600 dark:text-slate-300">{e.description}</p><div className="mt-2 flex flex-wrap gap-2 text-[9px] uppercase text-slate-400"><span>{e.source}</span><span>{e.type}</span><span>уверенность: {confidence[e.confidence]||e.confidence}</span>{e.channel&&<span className="font-mono normal-case">{e.channel}</span>}</div><div className="mt-1 text-[10px] text-indigo-500">{e.correlation?.explanation}</div></div>)}</div></div></div>
  {includeLow&&trace.possibleRelations?.length>0&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-900 dark:bg-amber-950/20"><h3 className="text-sm font-black text-amber-800 dark:text-amber-300">Возможные связи ({trace.possibleRelations.length})</h3><p className="text-xs text-amber-700">Они не смешаны с основной трассировкой: совпало только близкое время.</p></div>}
  <div className="rounded-xl border bg-white dark:border-slate-800 dark:bg-slate-900"><button className="w-full p-4 text-left text-sm font-black" onClick={()=>setRawOpen(v=>!v)}>{rawOpen?'Скрыть':'Открыть'} сырые связанные данные: CDR {trace.cdrCount}, CEL {trace.celCount}, SIP {trace.sipEvents.length}, логи {trace.logEventCount}</button>{rawOpen&&<div className="max-h-[520px] overflow-auto border-t p-4 dark:border-slate-800"><pre className="whitespace-pre-wrap break-all rounded bg-slate-950 p-4 text-[10px] text-emerald-300">{JSON.stringify({cdr:trace.cdr,cel:trace.cel,sip:trace.sipEvents,logs:trace.logEvents},null,2)}</pre></div>}</div></>}
 </div>;
}
