import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, Ban, CheckCircle2, Database, Flame, Globe2, ListFilter, Loader2, LockKeyhole, Network, RefreshCw, Server, Settings, Shield, ShieldAlert, Siren } from 'lucide-react';

type TabKey = 'overview'|'events'|'sip'|'firewall'|'fail2ban'|'ports'|'checks'|'services'|'changes'|'alerts'|'settings';
type Props = { token: string; hasPermission: (permission: any) => boolean };
const tabs: Array<[TabKey,string]> = [['overview','Обзор'],['events','События'],['sip','SIP-безопасность'],['firewall','Firewall'],['fail2ban','Fail2Ban'],['ports','Открытые порты'],['checks','Проверки'],['services','Службы'],['changes','Изменения'],['alerts','Уведомления'],['settings','Настройки']];
const riskClass: Record<string,string> = { info:'bg-slate-100 text-slate-700 dark:bg-slate-700 dark:text-slate-200', low:'bg-sky-100 text-sky-800 dark:bg-sky-950/40 dark:text-sky-300', medium:'bg-amber-100 text-amber-800 dark:bg-amber-950/40 dark:text-amber-300', high:'bg-orange-100 text-orange-800 dark:bg-orange-950/40 dark:text-orange-300', critical:'bg-rose-100 text-rose-800 dark:bg-rose-950/40 dark:text-rose-300', protected:'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300' };
const statusText = (value:any) => value === null || value === undefined ? 'Неизвестно' : String(value);
const formatTime = (value:any) => value ? new Date(value).toLocaleString('ru-RU') : 'Нет данных';
const valueLabels:Record<string,string>={multiple:'Несколько механизмов',active:'Активен',inactive:'Неактивен',available:'Доступно',not_available:'Недоступно',external_possible:'Возможна внешняя доступность',externally_exposed:'Доступен извне',local_only:'Только локально',lan_only:'Только локальная сеть',critical:'Критический',high:'Высокий',medium:'Средний',low:'Низкий',info:'Информация',passed:'Пройдено',warning:'Предупреждение',failed:'Ошибка',unknown:'Неизвестно',protected:'Защищено',running:'Работает',stopped:'Остановлен',success:'Успешно',blocked:'Заблокировано',accept:'Разрешить',drop:'Отбросить',reject:'Отклонить',log:'Записать в журнал',other:'Другое',ACCEPT:'Разрешать',DROP:'Отбрасывать',REJECT:'Отклонять'};
const columnLabels:Record<string,string>={name:'Название',status:'Статус',currentlyFailed:'Ошибок сейчас',totalFailed:'Всего ошибок',currentlyBanned:'Заблокировано сейчас',totalBanned:'Всего блокировок',active:'Состояние',subState:'Подсостояние',enabled:'Автозапуск',pid:'PID',memoryBytes:'Память',cpuPercent:'CPU',restarts:'Перезапуски',startedAt:'Запущен',protocol:'Протокол',address:'Адрес',port:'Порт',process:'Процесс',service:'Служба',exposure:'Доступность',risk:'Риск',riskReason:'Причина риска',family:'Семейство',chain:'Цепочка',chainPolicy:'Политика цепочки',table:'Таблица',action:'Действие',source:'Источник',destination:'Назначение',destinationPort:'Порт назначения',interfaceIn:'Входной интерфейс',interfaceOut:'Выходной интерфейс',sourceMechanism:'Механизм',packets:'Пакеты',bytes:'Байты',category:'Категория',title:'Событие',occurrence_count:'Повторения',last_seen_at:'Последний раз'};
const formatBytes=(value:any)=>{const number=Number(value);if(!Number.isFinite(number)||number<0)return'Недоступно';if(number<1024)return`${number} Б`;if(number<1024**2)return`${(number/1024).toFixed(1)} КБ`;if(number<1024**3)return`${(number/1024**2).toFixed(1)} МБ`;return`${(number/1024**3).toFixed(1)} ГБ`;};
const formatCell=(key:string,value:any)=>{if(key==='memoryBytes')return formatBytes(value);if(key==='cpuPercent'&&(value===null||value===undefined))return'Недоступно';if(value===null||value===undefined||value==='')return'—';if(key==='startedAt'||key.endsWith('_at'))return formatTime(value);if(typeof value==='boolean')return value?'Да':'Нет';if(typeof value==='string'&&valueLabels[value])return valueLabels[value];if(typeof value==='object')return JSON.stringify(value);return String(value);};
type RefreshMode = 'economy'|'normal'|'fast';
const refreshIntervals: Record<RefreshMode, Partial<Record<TabKey,number>>> = {
  economy: { overview:30000, events:30000, sip:30000, services:30000, ports:60000, fail2ban:60000, firewall:120000, checks:300000 },
  normal: { overview:15000, events:10000, sip:15000, services:15000, ports:30000, fail2ban:30000, firewall:60000, checks:300000 },
  fast: { overview:10000, events:5000, sip:10000, services:10000, ports:15000, fail2ban:15000, firewall:30000, checks:300000 }
};
const readStoredTab = (): TabKey => { const value=localStorage.getItem('pbxpuls_security_tab') as TabKey; return tabs.some(([key])=>key===value)?value:'overview'; };
const readStoredRefreshMode = (): RefreshMode => { const value=localStorage.getItem('pbxpuls_security_refresh_mode') as RefreshMode; return value in refreshIntervals?value:'normal'; };

export default function SecurityTab({ token, hasPermission }: Props) {
  const [tab,setTab]=useState<TabKey>(readStoredTab); const [dataByTab,setDataByTab]=useState<Partial<Record<TabKey,any>>>({}); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [updatedByTab,setUpdatedByTab]=useState<Partial<Record<TabKey,string>>>({});
  const [autoRefresh,setAutoRefresh]=useState(()=>localStorage.getItem('pbxpuls_security_auto_refresh')!=='false'); const [refreshMode,setRefreshMode]=useState<RefreshMode>(readStoredRefreshMode);
  const [eventFilters,setEventFilters]=useState({severity:'',category:'',search:''}); const [whitelistIp,setWhitelistIp]=useState(''); const [whitelistComment,setWhitelistComment]=useState('');
  const [portFilters,setPortFilters]=useState({protocol:'',risk:'',exposure:'',port:'',process:'',external:false,critical:false}); const [portOffset,setPortOffset]=useState(0);
  const requestRef=useRef<AbortController|null>(null); const requestSequenceRef=useRef(0); const mountedRef=useRef(true);
  const canViewEvents=hasPermission('view_security_events'); const canManageWhitelist=hasPermission('manage_security_whitelist'); const canManageSettings=hasPermission('manage_security_settings');
  const data=dataByTab[tab]||{}; const updatedAt=updatedByTab[tab]||''; const firstLoading=loading&&!dataByTab[tab];
  const endpoint = useMemo(() => ({overview:'/api/security/overview',events:'/api/security/events',sip:'/api/security/sip/summary',firewall:'/api/security/firewall/status',fail2ban:'/api/security/fail2ban/status',ports:'/api/security/ports',checks:'/api/security/checks',services:'/api/security/services',changes:'/api/security/file-changes',alerts:'/api/security/alerts',settings:'/api/security/settings'}[tab]),[tab]);
  const request = useCallback(async (url:string, signal:AbortSignal, options:RequestInit={}) => { const response=await fetch(url,{...options,signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers||{})},cache:'no-store'}); const payload=await response.json().catch(()=>({})); if(!response.ok||payload.success===false) throw new Error(payload?.error?.message||payload?.error||'Ошибка Security API'); return payload; },[token]);
  const load = useCallback(async () => { if(document.visibilityState!=='visible')return;requestRef.current?.abort();const controller=new AbortController();requestRef.current=controller;const sequence=++requestSequenceRef.current;setLoading(true);try { let url=endpoint;if(tab==='events'){const p=new URLSearchParams(Object.entries(eventFilters).filter(([,v])=>v));url+=`?${p}`;}if(tab==='ports'){const p=new URLSearchParams({limit:'25',offset:String(portOffset)});Object.entries(portFilters).forEach(([key,value])=>{if(value)p.set(key,String(value));});url+=`?${p}`;}let payload:any;if(tab==='firewall'){const [status,rules]=await Promise.all([request(url,controller.signal),request('/api/security/firewall/rules?limit=500',controller.signal)]);payload={...status,rules:rules.rows||status.rules||[]};}else if(tab==='fail2ban'){const [status,jails]=await Promise.all([request(url,controller.signal),request('/api/security/fail2ban/jails',controller.signal)]);payload={...status,jails:jails.rows||status.jails||[]};}else{payload=await request(url,controller.signal);}let whitelist=null;if(tab==='events'&&canViewEvents)whitelist=await request('/api/security/whitelist',controller.signal).catch(()=>null);if(!mountedRef.current||sequence!==requestSequenceRef.current)return;setDataByTab(previous=>({...previous,[tab]:{...payload,whitelist:whitelist?.rows}}));setUpdatedByTab(previous=>({...previous,[tab]:new Date().toISOString()}));setError('');}catch(e:any){if(e?.name!=='AbortError'&&mountedRef.current&&sequence===requestSequenceRef.current)setError(e?.message||String(e));}finally{if(mountedRef.current&&sequence===requestSequenceRef.current){setLoading(false);requestRef.current=null;}}},[canViewEvents,endpoint,eventFilters,portFilters,portOffset,request,tab]);
  useEffect(()=>{localStorage.setItem('pbxpuls_security_tab',tab);void load();const configuredInterval=refreshIntervals[refreshMode][tab];if(!autoRefresh||!configuredInterval)return()=>{requestRef.current?.abort();};const interval=Math.max(5000,configuredInterval);const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load();},interval);return()=>{window.clearInterval(timer);requestRef.current?.abort();};},[autoRefresh,load,refreshMode,tab]);
  useEffect(()=>{const onVisibility=()=>{if(document.visibilityState==='visible')void load();else requestRef.current?.abort();};document.addEventListener('visibilitychange',onVisibility);return()=>document.removeEventListener('visibilitychange',onVisibility);},[load]);
  useEffect(()=>{mountedRef.current=true;return()=>{mountedRef.current=false;requestRef.current?.abort();};},[]);
  useEffect(()=>{localStorage.setItem('pbxpuls_security_auto_refresh',String(autoRefresh));},[autoRefresh]); useEffect(()=>{localStorage.setItem('pbxpuls_security_refresh_mode',refreshMode);},[refreshMode]);
  const mutate=useCallback((url:string,options:RequestInit)=>request(url,new AbortController().signal,options),[request]);
  const addWhitelist=async()=>{if(!whitelistIp.trim())return;try{await mutate('/api/security/whitelist',{method:'POST',body:JSON.stringify({ip:whitelistIp.trim(),comment:whitelistComment})});setWhitelistIp('');setWhitelistComment('');await load();}catch(e:any){setError(e.message);}};
  const deleteWhitelist=async(id:number)=>{if(!window.confirm('Удалить IP из белого списка PBXPuls?'))return;try{await mutate(`/api/security/whitelist/${id}`,{method:'DELETE'});await load();}catch(e:any){setError(e.message);}};
  const saveSettings=async(values:Record<string,boolean|number>,confirmFail2banActions=false)=>{try{await mutate('/api/security/settings',{method:'PUT',body:JSON.stringify({...values,confirmFail2banActions})});await load();}catch(e:any){setError(e.message);}};
  return <div className="min-h-[620px] bg-slate-50 p-4 dark:bg-slate-950/40">
    <div className="mb-4 flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2 text-lg font-black text-slate-950 dark:text-white"><Shield className="h-6 w-6 text-blue-600"/>Центр безопасности</div><div className="mt-1 text-xs text-slate-500 dark:text-slate-400">Read-only мониторинг PBXPuls, FreePBX, Asterisk и сервера</div></div><div className="flex flex-wrap items-center gap-2"><button onClick={()=>setAutoRefresh(value=>!value)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${autoRefresh?'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300':'border-slate-200 bg-white text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300'}`}>Автообновление: {autoRefresh?'Вкл.':'Выкл.'}</button><select value={refreshMode} onChange={e=>setRefreshMode(e.target.value as RefreshMode)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"><option value="economy">Экономный</option><option value="normal">Обычный</option><option value="fast">Быстрый</option></select><span className="text-[11px] text-slate-500">Обновлено: {formatTime(updatedAt)}</span>{loading&&!firstLoading&&<span className="inline-flex items-center gap-1 text-[11px] text-blue-600"><Loader2 className="h-3.5 w-3.5 animate-spin"/>Обновление…</span>}<button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-700 hover:bg-slate-50 disabled:opacity-50 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Обновить</button></div></div>
    <div className="mb-4 flex gap-2 overflow-x-auto pb-1">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-lg border px-3 py-2 text-xs font-bold ${tab===key?'border-blue-200 bg-blue-50 text-blue-700 dark:border-blue-800 dark:bg-blue-950/40 dark:text-blue-300':'border-slate-200 bg-white text-slate-600 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-300'}`}>{label}</button>)}</div>
    {error&&<div className="mb-4 flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-300"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0"/>{error}</div>}
    {firstLoading?<div className="flex min-h-72 items-center justify-center text-slate-500"><Loader2 className="mr-2 h-5 w-5 animate-spin"/>Получение реальных данных…</div>:<>
      {tab==='overview'&&<Overview data={data}/>} {tab==='events'&&<Events data={data} filters={eventFilters} setFilters={setEventFilters} canManage={canManageWhitelist} whitelistIp={whitelistIp} setWhitelistIp={setWhitelistIp} whitelistComment={whitelistComment} setWhitelistComment={setWhitelistComment} addWhitelist={addWhitelist} deleteWhitelist={deleteWhitelist}/>} {tab==='sip'&&<SimpleTable rows={data.rows||[]} empty="SIP-события за 24 часа не обнаружены или источник недоступен"/>}
      {tab==='firewall'&&<Firewall data={data}/>} {tab==='fail2ban'&&<Fail2Ban data={data}/>} {tab==='ports'&&<Ports data={data} filters={portFilters} onFilters={(next:any)=>{setPortOffset(0);setPortFilters(next);}} offset={portOffset} onOffset={setPortOffset}/>} {tab==='checks'&&<Checks rows={data.rows||[]}/>} {tab==='services'&&<Services rows={data.services||[]}/>} {tab==='changes'&&<Changes data={data}/>} {tab==='alerts'&&<Alerts rows={data.rows||[]}/>} {tab==='settings'&&<SecuritySettings settings={data.settings||{}} canManage={canManageSettings} onSave={saveSettings}/>} </>}
  </div>;
}

function Card({title,value,sub,icon:Icon=Shield,risk='info'}:any){return <div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800"><div className="flex items-center justify-between"><span className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{title}</span><Icon className="h-4 w-4 text-slate-400"/></div><div className="mt-2 text-xl font-black text-slate-950 dark:text-white">{formatCell('',value)}</div>{sub!==undefined&&sub!==null&&<div className={`mt-2 inline-flex rounded-md px-2 py-1 text-[10px] font-bold ${riskClass[risk]||riskClass.info}`}>{formatCell('',sub)}</div>}</div>}
function Overview({data}:any){const attention=data.attention||[],c=data.counters||{};return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card title="Общий уровень" value={data.level} risk={data.level} sub={data.level}/><Card title="Firewall" value={data.firewall?.status} sub={data.firewall?.mechanism||'unknown'} icon={Flame}/><Card title="Fail2Ban" value={data.fail2ban?.status} sub={data.fail2ban?.activeJails==null?'jail: неизвестно':`jail: ${data.fail2ban.activeJails}`} icon={Ban}/><Card title="События 24ч" value={data.events24h??'Нет данных'} sub={data.criticalEvents24h==null?'критические: неизвестно':`критические: ${data.criticalEvents24h}`} icon={Siren}/><Card title="Открытые порты" value={data.listeningPorts??'Нет данных'} sub={data.criticalPorts==null?'риск: неизвестно':`высокий риск: ${data.criticalPorts}`} icon={Network}/></div><div className="grid gap-2 sm:grid-cols-4"><Card title="Подтверждённые угрозы" value={c.confirmedThreats??0}/><Card title="Предупреждения" value={c.warnings??0}/><Card title="Неизвестные проверки" value={c.unknown??0}/><Card title="Информация" value={c.informational??0}/></div><div className="rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800"><div className="border-b border-slate-200 px-4 py-3 text-sm font-black dark:border-slate-700 dark:text-white">Требуют внимания</div>{attention.length?<div className="divide-y divide-slate-100 dark:divide-slate-700">{attention.map((item:any)=><div key={item.id} className="p-4"><div className="flex flex-wrap items-center gap-2"><span className={`rounded px-2 py-1 text-[10px] font-black ${riskClass[item.severity]}`}>{formatCell('',item.severity)}</span><span className="text-sm font-black text-slate-900 dark:text-white">{item.title}</span></div><div className="mt-2 text-xs text-slate-600 dark:text-slate-300">{item.summary}</div>{item.recommendation&&<div className="mt-1 text-xs text-blue-700 dark:text-blue-300">Рекомендация: {item.recommendation}</div>}</div>)}</div>:<Empty text="Активных проблем не найдено"/>}</div></div>}
function Events(p:any){const rows=p.data.rows||[];return <div className="space-y-4"><div className="grid gap-2 rounded-xl border border-slate-200 bg-white p-3 sm:grid-cols-3 dark:border-slate-700 dark:bg-slate-800"><select value={p.filters.severity} onChange={e=>p.setFilters({...p.filters,severity:e.target.value})} className="rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"><option value="">Все уровни</option>{['info','low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select><input value={p.filters.category} onChange={e=>p.setFilters({...p.filters,category:e.target.value})} placeholder="Категория" className="rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"/><input value={p.filters.search} onChange={e=>p.setFilters({...p.filters,search:e.target.value})} placeholder="IP, текст события" className="rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"/></div><SimpleTable rows={rows} empty="События не найдены"/>{p.canManage&&<div className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><div className="mb-3 text-sm font-black dark:text-white">Белый список PBXPuls</div><div className="flex flex-col gap-2 sm:flex-row"><input value={p.whitelistIp} onChange={(e:any)=>p.setWhitelistIp(e.target.value)} placeholder="IPv4 или IPv6" className="rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"/><input value={p.whitelistComment} onChange={(e:any)=>p.setWhitelistComment(e.target.value)} placeholder="Комментарий" className="flex-1 rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"/><button onClick={p.addWhitelist} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white">Добавить</button></div><div className="mt-3 flex flex-wrap gap-2">{(p.data.whitelist||[]).map((row:any)=><span key={row.id} className="inline-flex items-center gap-2 rounded-lg bg-slate-100 px-3 py-2 text-xs dark:bg-slate-700"><b>{row.ip_address}</b>{row.comment&&<span>{row.comment}</span>}<button onClick={()=>p.deleteWhitelist(row.id)} className="text-rose-600">×</button></span>)}</div></div>}</div>}
function Firewall({data}:any){return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card title="Механизм" value={data.mechanism}/><Card title="Состояние" value={statusText(data.status)}/><Card title="Правил" value={data.ruleCount??'Нет данных'}/><Card title="Политика INPUT" value={data.policies?.input||'unknown'}/></div><SimpleTable rows={data.rules||[]} empty="Правила недоступны: недостаточно прав ОС или Firewall не обнаружен"/></div>}
function Fail2Ban({data}:any){return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card title="Установлен" value={data.installed==null?'Неизвестно':data.installed?'Да':'Нет'}/><Card title="Статус" value={data.status}/><Card title="Активные jail" value={data.activeJails??'Нет данных'}/><Card title="Заблокировано" value={data.currentlyBanned??'Нет данных'}/></div><SimpleTable rows={data.jails||[]} empty="Fail2Ban jail недоступны"/><div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs font-bold text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-300"><LockKeyhole className="mr-2 inline h-4 w-4"/>Ручные ban/unban отключены серверной настройкой security.fail2ban_actions_enabled=false.</div></div>}
function Ports({data,filters,onFilters,offset,onOffset}:any){const rows=data.rows||[],limit=data.limit||25,total=data.total||0;return <div className="space-y-3"><div className="text-xs text-slate-500">Источник: ss · статус: {statusText(data.status)}. external_possible не означает подтвержденную доступность из Интернета.</div><div className="grid gap-2 rounded-xl border border-slate-200 bg-white p-3 sm:grid-cols-2 xl:grid-cols-5 dark:border-slate-700 dark:bg-slate-800"><select value={filters.protocol} onChange={e=>onFilters({...filters,protocol:e.target.value})} className="rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"><option value="">Все протоколы</option><option value="tcp">TCP</option><option value="udp">UDP</option></select><input value={filters.port} onChange={e=>onFilters({...filters,port:e.target.value})} placeholder="Порт" className="rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"/><input value={filters.process} onChange={e=>onFilters({...filters,process:e.target.value})} placeholder="Процесс" className="rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"/><select value={filters.risk} onChange={e=>onFilters({...filters,risk:e.target.value})} className="rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"><option value="">Любой риск</option>{['info','low','medium','high','critical'].map(x=><option key={x}>{x}</option>)}</select><select value={filters.exposure} onChange={e=>onFilters({...filters,exposure:e.target.value})} className="rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"><option value="">Любая доступность</option>{['local_only','lan_only','external_possible','externally_exposed','unknown'].map(x=><option key={x}>{x}</option>)}</select><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={filters.external} onChange={e=>onFilters({...filters,external:e.target.checked})}/>Только внешние</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={filters.critical} onChange={e=>onFilters({...filters,critical:e.target.checked})}/>Только critical</label></div><SimpleTable rows={rows} empty="Listening ports недоступны"/><div className="flex items-center justify-between text-xs text-slate-500"><span>{total?`${offset+1}–${Math.min(offset+limit,total)} из ${total}`:'Нет записей'}</span><div className="flex gap-2"><button disabled={offset===0} onClick={()=>onOffset(Math.max(0,offset-limit))} className="rounded border px-3 py-1 disabled:opacity-40">Назад</button><button disabled={offset+limit>=total} onClick={()=>onOffset(offset+limit)} className="rounded border px-3 py-1 disabled:opacity-40">Далее</button></div></div></div>}
function Checks({rows}:any){return <div className="grid gap-3 lg:grid-cols-2">{rows.length?rows.map((row:any)=><div key={row.id} className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800"><div className="flex items-center gap-2"><span className={`rounded px-2 py-1 text-[10px] font-black ${riskClass[row.severity]}`}>{formatCell('',row.status)}</span><b className="text-sm dark:text-white">{row.title}</b></div><p className="mt-2 text-xs text-slate-600 dark:text-slate-300">{row.summary}</p>{row.recommendation&&<p className="mt-2 text-xs text-blue-700 dark:text-blue-300">{row.recommendation}</p>}</div>):<Empty text="Проверки недоступны"/>}</div>}
function Services({rows}:any){return <SimpleTable rows={rows} empty="Сведения о службах недоступны"/>} function Changes({data}:any){return <div className="space-y-3"><div className="rounded-xl border border-slate-200 bg-white p-3 text-xs dark:border-slate-700 dark:bg-slate-800">Контроль целостности: <b>{data.fileIntegrityEnabled?'включен':'выключен'}</b>. Содержимое .env и секретных файлов не читается и не сохраняется.</div><SimpleTable rows={data.rows||[]} empty="Изменения не зафиксированы"/></div>} function Alerts({rows}:any){return <SimpleTable rows={rows} empty="Правила уведомлений недоступны"/>}
const settingDefinitions:Record<string,{name:string;description:string;unit?:string;min?:number;max?:number}>={
  'security.enabled':{name:'Мониторинг безопасности',description:'Включает безопасный сбор диагностических данных'},
  'security.event_retention_days':{name:'Хранение событий',description:'Срок хранения нормализованных событий',unit:'дней',min:1,max:3650},
  'security.raw_excerpt_enabled':{name:'Фрагменты журналов',description:'Хранить ограниченный и очищенный фрагмент исходной записи'},
  'security.raw_excerpt_max_length':{name:'Размер фрагмента журнала',description:'Максимальная длина очищенного фрагмента',unit:'символов',min:100,max:10000},
  'security.scan_interval_seconds':{name:'Интервал системной проверки',description:'Период фоновой диагностики служб, Firewall и портов',unit:'секунд',min:30,max:86400},
  'security.log_poll_interval_seconds':{name:'Интервал чтения журналов',description:'Минимальный период чтения новых записей журналов',unit:'секунд',min:5,max:3600},
  'security.file_integrity_enabled':{name:'Контроль целостности файлов',description:'Проверять метаданные и SHA-256 разрешённых критических файлов'},
  'security.file_integrity_interval_minutes':{name:'Интервал контроля файлов',description:'Период проверки целостности файлов',unit:'минут',min:5,max:10080},
  'security.geoip_enabled':{name:'Локальная GeoIP',description:'Использовать локальную GeoIP-базу, если она установлена'},
  'security.sip_new_ip_detection_enabled':{name:'Новые IP SIP-регистраций',description:'Отмечать ранее не встречавшиеся адреса регистрации'},
  'security.notification_cooldown_minutes':{name:'Пауза уведомлений',description:'Минимальный интервал повторного уведомления',unit:'минут',min:1,max:10080},
  'security.fail2ban_actions_enabled':{name:'Ручное управление Fail2Ban',description:'Разрешить подтверждённые ручные ban/unban через PBXPuls'}
};
function SecuritySettings({settings,canManage,onSave}:any){const [draft,setDraft]=useState<Record<string,any>>({});const [saving,setSaving]=useState(false);useEffect(()=>setDraft(Object.fromEntries(Object.entries(settings).filter(([key])=>key.startsWith('security.')))),[settings]);const entries=Object.entries(draft);const changed=entries.some(([key,value])=>value!==settings[key]);const save=async()=>{const enablingFail2ban=draft['security.fail2ban_actions_enabled']===true&&settings['security.fail2ban_actions_enabled']!==true;if(enablingFail2ban&&!window.confirm('Включить ручное управление Fail2Ban? Любое действие всё равно потребует отдельного подтверждения и попадёт в аудит.'))return;setSaving(true);try{await onSave(draft,enablingFail2ban);}finally{setSaving(false);}};return <div className="rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800"><div className="border-b p-4 text-sm font-black dark:border-slate-700 dark:text-white">Настройки мониторинга</div><div className="divide-y dark:divide-slate-700">{entries.map(([key,value]:any)=>{const definition:{name:string;description:string;unit?:string;min?:number;max?:number}=settingDefinitions[key]||{name:key,description:''};return <div key={key} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-bold text-slate-900 dark:text-white">{definition.name}</div><div className="mt-1 text-xs text-slate-500">{definition.description}</div>{definition.min!==undefined&&<div className="mt-1 text-[10px] text-slate-400">Допустимо: {definition.min}–{definition.max} {definition.unit||''}</div>}</div>{typeof value==='boolean'?<button disabled={!canManage} onClick={()=>setDraft(previous=>({...previous,[key]:!value}))} className={`rounded-full px-3 py-1 text-xs font-bold ${value?'bg-emerald-100 text-emerald-800':'bg-slate-100 text-slate-600'} disabled:opacity-50`}>{value?'Включено':'Выключено'}</button>:<div className="flex items-center gap-2"><input disabled={!canManage} type="number" min={definition.min} max={definition.max} value={value} onChange={e=>setDraft(previous=>({...previous,[key]:Number(e.target.value)}))} className="w-28 rounded-lg border p-2 text-xs dark:border-slate-600 dark:bg-slate-900"/><span className="text-xs text-slate-500">{definition.unit}</span></div>}</div>})}</div><div className="flex justify-end border-t p-4 dark:border-slate-700"><button disabled={!canManage||!changed||saving} onClick={()=>void save()} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{saving?'Сохранение…':'Сохранить изменения'}</button></div></div>}
function SimpleTable({rows,empty}:any){if(!rows.length)return <Empty text={empty}/>;const columns=Object.keys(rows[0]).filter(key=>!['raw','raw_excerpt','metadata_json','evidence_json','config_json','bannedIps','evidence'].includes(key)).slice(0,10);return <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500 dark:bg-slate-900"><tr>{columns.map(c=><th key={c} className="whitespace-nowrap px-3 py-3">{columnLabels[c]||c.replace(/_/g,' ')}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-700">{rows.map((row:any,i:number)=><tr key={row.id||row.name||i} className="hover:bg-slate-50 dark:hover:bg-slate-700/40">{columns.map(c=>{const formatted=formatCell(c,row[c]);return <td key={c} className="max-w-xs truncate px-3 py-3 text-slate-700 dark:text-slate-200" title={formatted}>{formatted}</td>})}</tr>)}</tbody></table></div>}
function Empty({text}:any){return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500 dark:border-slate-700 dark:bg-slate-800"><CheckCircle2 className="mx-auto mb-2 h-6 w-6 text-slate-400"/>{text}</div>}
