import type { AiPlatformStore } from '../../storage/aiPlatformStore.js';
import type { AiAuditService } from '../../audit/aiAuditService.js';
import { redactAiPlatformText, redactAiPlatformValue } from '../../core/redaction.js';
import { AgentContextBuilder } from '../../core/agentContextBuilder.js';
import type { ToolExecutor } from '../../tools/toolExecutor.js';
import type { HumanTransferService } from '../../transfer/humanTransferService.js';
import type { BusinessActionService } from '../../actions/businessActionService.js';
import type { AudioFrame } from '../media/mediaTypes.js';
import type { MediaSessionService } from '../media/mediaSessionService.js';
import { RealtimeVoiceProviderRegistry } from './realtimeVoiceProviderRegistry.js';
import { RealtimeVoiceSessionRepository } from './realtimeVoiceSessionRepository.js';
import { RealtimeVoiceError } from './realtimeVoiceErrors.js';
import type { RealtimeVoiceConfig, RealtimeVoiceEvent, RealtimeVoiceSessionProjection, RealtimeVoiceState } from './realtimeVoiceTypes.js';
import { callbackIntent, composeRealtimeInstructions, detectRealtimeTransfer } from './realtimeVoicePolicy.js';
import { readOpenAIRealtimeConfig } from './adapters/openaiRealtimeAdapter.js';

const transitions:Record<RealtimeVoiceState,RealtimeVoiceState[]>={created:['connecting','failed','cancelled'],connecting:['connected','failed','cancelled'],connected:['configured','failed','cancelled'],configured:['listening','failed','cancelled'],listening:['responding','closing','failed','cancelled'],responding:['interrupted','listening','closing','failed','cancelled'],interrupted:['listening','closing','failed','cancelled'],closing:['completed','failed','cancelled'],completed:[],failed:[],cancelled:[]};
type Runtime={tenantId:number;adapter:any;unsubscribeProvider:()=>void;unsubscribeMedia:()=>void;unsubscribeVad:()=>void;aborter:AbortController;started:number;inputFrames:number;outputFrames:number;inputAudioMs:number;outputAudioMs:number;firstInputAt:number|null;firstOutputAt:number|null;commitAt:number|null;firstResponseLatencyMs:number|null;interruptions:number;toolCalls:number;transcripts:Array<{kind:any;text:string}>;transferRequired:boolean;callbackOfferRequired:boolean;blocked:boolean;actorId:string};

export class RealtimeVoiceSessionService {
  private repo:RealtimeVoiceSessionRepository;private runtimes=new Map<number,Runtime>();
  private liveObserver:((event:{tenantId:number;voiceSessionId:number;type:'first_audio'|'barge_in'|'transfer';latencyMs:number|null;traceId:string})=>Promise<void>)|null=null;
  constructor(private store:AiPlatformStore,private audit:AiAuditService,private registry:RealtimeVoiceProviderRegistry,private media:MediaSessionService,private isEnabled:()=>Promise<boolean>,private toolExecutor:ToolExecutor|null=null,private humanTransfer:HumanTransferService|null=null,private businessActions:BusinessActionService|null=null){this.repo=new RealtimeVoiceSessionRepository(store);void businessActions}
  private async row(tenantId:number,id:number){const rows=await this.repo.get(tenantId,id);if(!rows[0])throw new RealtimeVoiceError('not_found',404,'Realtime voice session not found');return rows[0]}
  private project(row:any,runtime?:Runtime):RealtimeVoiceSessionProjection{let metadata:any={};try{metadata=JSON.parse(String(row.metadata_json||'{}'))}catch{}return{id:Number(row.id),tenantId:Number(row.tenant_id),voiceSessionId:Number(row.voice_session_id),mediaSessionId:Number(row.media_session_id),providerKey:row.provider_key,state:row.state,inputCodec:row.input_codec,outputCodec:row.output_codec,inputSampleRate:Number(row.input_sample_rate),outputSampleRate:Number(row.output_sample_rate),language:row.language,voiceKeySafe:row.voice_key_safe||null,serverVadEnabled:Boolean(row.server_vad_enabled),toolsEnabled:Boolean(row.tools_enabled),connectedAt:row.connected_at||null,firstInputAudioAt:row.first_input_audio_at||null,firstOutputAudioAt:row.first_output_audio_at||null,endedAt:row.ended_at||null,inputFrames:Number(row.input_frames),outputFrames:Number(row.output_frames),inputAudioMs:Number(row.input_audio_ms),outputAudioMs:Number(row.output_audio_ms),firstResponseLatencyMs:row.first_response_latency_ms===null?null:Number(row.first_response_latency_ms),interruptionCount:Number(row.interruption_count),toolCallCount:Number(row.tool_call_count),failureCode:row.failure_code||null,transcripts:runtime?.transcripts||metadata.transcripts||[],transferRequired:runtime?.transferRequired||Boolean(metadata.transferRequired),callbackOfferRequired:runtime?.callbackOfferRequired||Boolean(metadata.callbackOfferRequired),queueDepth:0}}
  async get(tenantId:number,id:number){return this.project(await this.row(tenantId,id),this.runtimes.get(id))}
  async list(tenantId:number,limit:number,offset:number){return(await this.repo.list(tenantId,limit,offset)).map(row=>this.project(row,this.runtimes.get(Number(row.id))))}
  private async transition(tenantId:number,id:number,to:RealtimeVoiceState,traceId:string,failureCode:string|null=null){const row=await this.row(tenantId,id);if(row.state===to)return;if(!transitions[row.state as RealtimeVoiceState]?.includes(to))throw new RealtimeVoiceError('conflict',409,'Invalid realtime voice transition');const result:any=await this.repo.transition(tenantId,id,row.state,to,failureCode);if(!result.affectedRows)throw new RealtimeVoiceError('conflict',409,'Concurrent realtime voice transition');const event=to==='connecting'?'realtime_provider_connecting':to==='connected'?'realtime_provider_connected':to==='configured'?'realtime_provider_configured':to==='responding'?'realtime_response_started':to==='completed'?'realtime_voice_session_completed':to==='failed'?'realtime_provider_failed':to==='interrupted'?'realtime_barge_in':'realtime_input_started';await this.audit.append({tenantId,traceId,actorType:'service',eventType:event as any,entityType:'realtime_voice_session',entityId:String(id),decision:to,details:{failureCode}})}
  async start(input:{tenantId:number;mediaSessionId:number;providerKey:string;traceId:string;actorId:string}){
    if(!(await this.isEnabled()))throw new RealtimeVoiceError('feature_disabled',503,'Realtime voice is disabled');
    const same=[...this.runtimes.values()].filter(runtime=>runtime.adapter.getKey()==='synthetic').length;if(input.providerKey==='synthetic'&&same>=2)throw new RealtimeVoiceError('concurrency_limited',429,'Synthetic realtime session limit reached');if(input.providerKey!=='synthetic'&&[...this.runtimes.values()].some(runtime=>runtime.adapter.getKey()!=='synthetic'))throw new RealtimeVoiceError('concurrency_limited',429,'External realtime session limit reached');
    const source=(await this.store.query(`SELECT m.id media_id,m.voice_session_id,m.transport_mode,m.state media_state,v.agent_id,v.agent_version_id,v.conversation_id,v.language,v.state voice_state,av.lifecycle_status FROM ai_voice_media_sessions m JOIN ai_voice_sessions v ON v.id=m.voice_session_id AND v.tenant_id=m.tenant_id JOIN ai_agent_versions av ON av.id=v.agent_version_id AND av.tenant_id=v.tenant_id WHERE m.id=? AND m.tenant_id=? LIMIT 1`,[input.mediaSessionId,input.tenantId]))[0];
    if(!source)throw new RealtimeVoiceError('not_found',404,'Media session not found');if(!['synthetic','audiosocket'].includes(source.transport_mode)||source.media_state!=='streaming'||source.voice_state!=='active')throw new RealtimeVoiceError('conflict',409,'Active supported media is required');if(source.lifecycle_status!=='published')throw new RealtimeVoiceError('conflict',409,'Published agent version is required');if((await this.repo.findActive(input.tenantId,input.mediaSessionId))[0])throw new RealtimeVoiceError('conflict',409,'Active realtime session already exists');
    const context:any=await new AgentContextBuilder(this.store).buildContext(input.tenantId,Number(source.agent_version_id)),instructions=composeRealtimeInstructions(context,String(source.language||'ru')),adapter=this.registry.create(input.providerKey),capabilities=adapter.getCapabilities(),format={codec:'slin16'as const,sampleRate:16000,channels:1 as const,frameDurationMs:20};
    if(!capabilities.supportedInputFormats.some(item=>item.codec===format.codec&&item.sampleRate===format.sampleRate))throw new RealtimeVoiceError('unsupported_codec',400,'Provider codec is incompatible');
    const assigned=await this.store.query(`SELECT t.tool_key,t.description,t.input_schema_json FROM ai_agent_tools at JOIN ai_tools t ON t.id=at.tool_id WHERE at.tenant_id=? AND at.agent_version_id=? AND at.enabled=1 AND t.enabled=1 AND t.risk_level='read'`,[input.tenantId,source.agent_version_id]),external=readOpenAIRealtimeConfig();
    const config:RealtimeVoiceConfig={providerKey:input.providerKey,apiKey:input.providerKey==='openai_realtime'?external.apiKey:undefined,url:input.providerKey==='openai_realtime'?external.url:undefined,model:input.providerKey==='openai_realtime'?external.model:'synthetic-voice',voice:'natural',language:String(source.language||'ru'),instructions:instructions.instructions,inputFormat:format,outputFormat:format,serverVad:capabilities.serverVad,tools:capabilities.tools?assigned.map((tool:any)=>({key:tool.tool_key,description:tool.description,inputSchema:JSON.parse(tool.input_schema_json||'{}')})):[],timeoutMs:5000};
    if(!(await adapter.validateConfig(config)).valid)throw new RealtimeVoiceError('provider_not_configured',503,'Realtime provider is not configured');
    const id=await this.repo.create({tenantId:input.tenantId,voiceSessionId:Number(source.voice_session_id),mediaSessionId:input.mediaSessionId,providerKey:input.providerKey,language:config.language,voice:config.voice||null,serverVad:config.serverVad,tools:config.tools.length>0,input:format,output:format,metadata:{instructionChecksum:instructions.checksum,agentVersionId:source.agent_version_id,transcripts:[]}});
    await this.audit.append({tenantId:input.tenantId,traceId:input.traceId,actorType:'user',actorId:input.actorId,eventType:'realtime_voice_session_created',entityType:'realtime_voice_session',entityId:String(id),decision:'created',details:{providerKey:input.providerKey,instructionChecksum:instructions.checksum}});
    const aborter=new AbortController(),runtime:Runtime={tenantId:input.tenantId,adapter,unsubscribeProvider:()=>{},unsubscribeMedia:()=>{},unsubscribeVad:()=>{},aborter,started:Date.now(),inputFrames:0,outputFrames:0,inputAudioMs:0,outputAudioMs:0,firstInputAt:null,firstOutputAt:null,commitAt:null,firstResponseLatencyMs:null,interruptions:0,toolCalls:0,transcripts:[],transferRequired:false,callbackOfferRequired:false,blocked:false,actorId:input.actorId};
    runtime.unsubscribeProvider=adapter.subscribeEvents(event=>this.handleEvent(id,input.traceId,event));this.runtimes.set(id,runtime);
    try{await this.transition(input.tenantId,id,'connecting',input.traceId);await adapter.connect(config,aborter.signal);await this.transition(input.tenantId,id,'connected',input.traceId);await adapter.configureSession(config);await this.transition(input.tenantId,id,'configured',input.traceId);runtime.unsubscribeMedia=this.media.subscribeIngress(input.tenantId,input.mediaSessionId,frame=>this.input(id,input.traceId,frame));runtime.unsubscribeVad=this.media.subscribeVad(input.tenantId,input.mediaSessionId,event=>event==='speech_ended'?this.commit(input.tenantId,id,input.traceId).then(()=>{}):this.get(input.tenantId,id).then(current=>current.state==='responding'?this.bargeIn(input.tenantId,id,input.traceId).then(()=>{}):undefined));await this.transition(input.tenantId,id,'listening',input.traceId);await this.store.query("UPDATE ai_voice_sessions SET provider_state='connected' WHERE tenant_id=? AND id=?",[input.tenantId,source.voice_session_id]);return this.get(input.tenantId,id)}catch(error){await this.fail(input.tenantId,id,input.traceId,error instanceof RealtimeVoiceError?error.code:'provider_not_configured');throw error}
  }
  private async input(id:number,traceId:string,frame:AudioFrame){const runtime=this.runtimes.get(id);if(!runtime||runtime.blocked)return;if(Date.now()-runtime.started>60000||runtime.inputFrames>=3000||Date.now()-frame.timestampMs>5000){await this.fail(runtime.tenantId,id,traceId,'realtime_limit_exceeded');return}runtime.inputFrames++;runtime.inputAudioMs+=frame.durationMs;runtime.firstInputAt??=Date.now();await runtime.adapter.appendAudio(frame);await this.persist(id)}
  async commit(tenantId:number,id:number,traceId:string){const runtime=this.runtimes.get(id);if(!runtime||runtime.tenantId!==tenantId)throw new RealtimeVoiceError('not_found',404,'Active realtime session not found');if(runtime.blocked)return this.get(tenantId,id);runtime.commitAt=Date.now();await this.audit.append({tenantId,traceId,actorType:'user',eventType:'realtime_input_committed',entityType:'realtime_voice_session',entityId:String(id),decision:'committed',details:{}});await runtime.adapter.commitInput();return this.get(tenantId,id)}
  async bargeIn(tenantId:number,id:number,traceId:string){const started=Date.now(),runtime=this.runtimes.get(id);if(!runtime||runtime.tenantId!==tenantId)throw new RealtimeVoiceError('not_found',404,'Active realtime session not found');await runtime.adapter.cancelResponse();const row=await this.row(tenantId,id);this.media.clearEgress(tenantId,Number(row.media_session_id));runtime.interruptions++;if(row.state==='responding'){await this.transition(tenantId,id,'interrupted',traceId);await this.transition(tenantId,id,'listening',traceId)}await this.liveObserver?.({tenantId,voiceSessionId:Number(row.voice_session_id),type:'barge_in',latencyMs:Date.now()-started,traceId});await this.audit.append({tenantId,traceId,actorType:'service',eventType:'realtime_response_cancelled',entityType:'realtime_voice_session',entityId:String(id),decision:'barge_in',details:{}});await this.persist(id);return this.get(tenantId,id)}
  private async handleEvent(id:number,traceId:string,event:RealtimeVoiceEvent){const runtime=this.runtimes.get(id);if(!runtime)return;const row=await this.row(runtime.tenantId,id);if(event.type==='session_connected'&&event.providerSessionRef)await this.repo.providerSession(runtime.tenantId,id,event.providerSessionRef);if(event.type==='response_started'&&!runtime.blocked&&row.state==='listening')await this.transition(runtime.tenantId,id,'responding',traceId);if(event.type==='output_audio'&&!runtime.blocked){runtime.outputFrames++;runtime.outputAudioMs+=event.frame.durationMs;runtime.firstOutputAt??=Date.now();if(runtime.firstResponseLatencyMs===null&&runtime.commitAt)runtime.firstResponseLatencyMs=runtime.firstOutputAt-runtime.commitAt;await this.media.enqueueEgress(runtime.tenantId,Number(row.media_session_id),{...event.frame,traceId,voiceSessionId:Number(row.voice_session_id),mediaSessionId:Number(row.media_session_id)});if(runtime.outputFrames===1)await this.audit.append({tenantId:runtime.tenantId,traceId,actorType:'service',eventType:'realtime_first_audio',entityType:'realtime_voice_session',entityId:String(id),decision:'output',details:{firstResponseLatencyMs:runtime.firstResponseLatencyMs}})}
    if(event.type==='transcript'&&!event.kind.endsWith('partial')){const text=redactAiPlatformText(event.text).slice(0,1000);runtime.transcripts.push({kind:event.kind,text});if(runtime.transcripts.length>20)runtime.transcripts.shift();if(event.kind==='input_final'&&detectRealtimeTransfer(text))await this.transfer(runtime,id,traceId,row,text);else if(event.kind==='input_final'&&callbackIntent(text))runtime.callbackOfferRequired=true}
    if(event.type==='tool_call'&&!runtime.blocked)await this.toolCall(runtime,id,traceId,event);
    if(event.type==='output_audio'&&runtime.outputFrames===1)await this.liveObserver?.({tenantId:runtime.tenantId,voiceSessionId:Number(row.voice_session_id),type:'first_audio',latencyMs:runtime.firstResponseLatencyMs,traceId});if(event.type==='response_completed'){const current=await this.row(runtime.tenantId,id);if(current.state==='responding'){await this.transition(runtime.tenantId,id,'listening',traceId);await this.audit.append({tenantId:runtime.tenantId,traceId,actorType:'service',eventType:'realtime_response_completed',entityType:'realtime_voice_session',entityId:String(id),decision:'completed',details:{}})}}if(event.type==='error')await this.fail(runtime.tenantId,id,traceId,event.errorCode);await this.persist(id)
  }
  private async transfer(runtime:Runtime,id:number,traceId:string,row:any,text:string){const transferStarted=Date.now();runtime.transferRequired=true;runtime.blocked=true;await runtime.adapter.cancelResponse();this.media.clearEgress(runtime.tenantId,Number(row.media_session_id));await this.liveObserver?.({tenantId:runtime.tenantId,voiceSessionId:Number(row.voice_session_id),type:'transfer',latencyMs:Date.now()-transferStarted,traceId});await this.audit.append({tenantId:runtime.tenantId,traceId,actorType:'service',eventType:'human_transfer_detected',entityType:'realtime_voice_session',entityId:String(id),decision:'transfer_required',details:{}});if(!this.humanTransfer)return;const voice=(await this.store.query('SELECT agent_id,agent_version_id,conversation_id FROM ai_voice_sessions WHERE tenant_id=? AND id=?',[runtime.tenantId,row.voice_session_id]))[0],media=(await this.store.query('SELECT transport_mode FROM ai_voice_media_sessions WHERE tenant_id=? AND id=?',[runtime.tenantId,row.media_session_id]))[0],liveTransfer=media?.transport_mode==='audiosocket'&&process.env.PBXPULS_AI_VOICE_LIVE_TRANSFER_TEST_ENABLED==='true';if(liveTransfer)await this.audit.append({tenantId:runtime.tenantId,traceId,actorType:'service',eventType:'live_voice_transfer_requested',entityType:'voice_session',entityId:String(row.voice_session_id),decision:'requested',details:{}});if(voice)await this.humanTransfer.request({tenantId:runtime.tenantId,traceId,conversationId:Number(voice.conversation_id)||null,voiceSessionId:Number(row.voice_session_id),agentId:Number(voice.agent_id),agentVersionId:Number(voice.agent_version_id),requestedByType:'service',requestedById:null,triggerType:'explicit_human_request',triggerText:text,dryRun:!liveTransfer}).catch(()=>null)}
  private async toolCall(runtime:Runtime,id:number,traceId:string,event:Extract<RealtimeVoiceEvent,{type:'tool_call'}>){runtime.toolCalls++;await this.audit.append({tenantId:runtime.tenantId,traceId,actorType:'service',eventType:'realtime_tool_call_requested',entityType:'realtime_voice_session',entityId:String(id),decision:'requested',details:{toolKey:event.toolKey}});if(runtime.toolCalls>2){await runtime.adapter.sendToolResult(event.callId,{ok:false,errorCode:'tool_loop_limit'});return}const row=await this.row(runtime.tenantId,id),tools=await this.store.query(`SELECT t.id,t.tool_key FROM ai_agent_tools at JOIN ai_tools t ON t.id=at.tool_id WHERE at.tenant_id=? AND at.agent_version_id=(SELECT agent_version_id FROM ai_voice_sessions WHERE id=? AND tenant_id=?) AND at.enabled=1 AND t.enabled=1 AND t.risk_level='read' AND t.tool_key=? LIMIT 1`,[runtime.tenantId,row.voice_session_id,runtime.tenantId,event.toolKey]);if(!tools[0]||!this.toolExecutor){await runtime.adapter.sendToolResult(event.callId,{ok:false,errorCode:'tool_not_available'});return}const voice=(await this.store.query('SELECT agent_id,agent_version_id,conversation_id FROM ai_voice_sessions WHERE tenant_id=? AND id=?',[runtime.tenantId,row.voice_session_id]))[0];try{const result=await this.toolExecutor.execute({traceId,tenantId:runtime.tenantId,installationId:'installation',actorId:runtime.actorId,actorType:'service',agentId:Number(voice.agent_id),agentVersionId:Number(voice.agent_version_id),conversationId:Number(voice.conversation_id),toolId:Number(tools[0].id),toolKey:event.toolKey,permissions:['execute_ai_read_tools'],locale:'ru',requestStartedAt:new Date().toISOString(),idempotencyKey:`realtime:${id}:${event.callId}`},event.arguments,runtime.aborter.signal);await runtime.adapter.sendToolResult(event.callId,{ok:true,data:redactAiPlatformValue(result.data).value});await this.audit.append({tenantId:runtime.tenantId,traceId,actorType:'service',eventType:'realtime_tool_call_completed',entityType:'realtime_voice_session',entityId:String(id),decision:'completed',details:{toolKey:event.toolKey}})}catch{await runtime.adapter.sendToolResult(event.callId,{ok:false,errorCode:'tool_failed'})}}
  private async persist(id:number){const runtime=this.runtimes.get(id);if(!runtime)return;await this.repo.metrics(runtime.tenantId,id,{inputFrames:runtime.inputFrames,outputFrames:runtime.outputFrames,inputAudioMs:runtime.inputAudioMs,outputAudioMs:runtime.outputAudioMs,firstInputAt:runtime.firstInputAt?new Date(runtime.firstInputAt):null,firstOutputAt:runtime.firstOutputAt?new Date(runtime.firstOutputAt):null,firstResponseLatencyMs:runtime.firstResponseLatencyMs,interruptions:runtime.interruptions,toolCalls:runtime.toolCalls,metadata:redactAiPlatformValue({transcripts:runtime.transcripts,transferRequired:runtime.transferRequired,callbackOfferRequired:runtime.callbackOfferRequired}).value})}
  async fixture(tenantId:number,id:number,fixture:'silence'|'speech'|'question'|'transfer_request'|'callback_request'|'tool_query',traceId:string){const row=await this.row(tenantId,id);await this.media.injectRealtimeFixture(tenantId,Number(row.media_session_id),fixture,traceId);return this.get(tenantId,id)}
  async closeForMediaSession(tenantId:number,mediaSessionId:number,traceId:string){const row=(await this.repo.findActive(tenantId,mediaSessionId))[0];return row?this.stop(tenantId,Number(row.id),traceId):null}
  setLiveObserver(observer:(event:{tenantId:number;voiceSessionId:number;type:'first_audio'|'barge_in'|'transfer';latencyMs:number|null;traceId:string})=>Promise<void>){this.liveObserver=observer}
  async stop(tenantId:number,id:number,traceId:string,terminal:'completed'|'cancelled'='completed'){const runtime=this.runtimes.get(id);if(runtime&&runtime.tenantId!==tenantId)throw new RealtimeVoiceError('not_found',404,'Realtime session not found');if(runtime){runtime.blocked=true;runtime.aborter.abort();runtime.unsubscribeMedia();runtime.unsubscribeVad();runtime.unsubscribeProvider();await runtime.adapter.close();await this.persist(id);this.runtimes.delete(id)}const row=await this.row(tenantId,id);if(!['completed','failed','cancelled'].includes(row.state)){if(row.state!=='closing')await this.transition(tenantId,id,'closing',traceId);await this.transition(tenantId,id,terminal,traceId)}await this.store.query("UPDATE ai_voice_sessions v JOIN ai_realtime_voice_sessions r ON r.voice_session_id=v.id SET v.provider_state='disconnected' WHERE r.tenant_id=? AND r.id=?",[tenantId,id]);return this.get(tenantId,id)}
  async fail(tenantId:number,id:number,traceId:string,code:string){const runtime=this.runtimes.get(id);if(runtime){runtime.blocked=true;runtime.aborter.abort();runtime.unsubscribeMedia();runtime.unsubscribeVad();runtime.unsubscribeProvider();await runtime.adapter.close().catch(()=>{});this.runtimes.delete(id)}const row=await this.row(tenantId,id);if(!['failed','completed','cancelled'].includes(row.state))await this.transition(tenantId,id,'failed',traceId,code);return this.get(tenantId,id)}activeCount(){return this.runtimes.size}
}
