import crypto from'node:crypto';
import type{AiPlatformStore}from'../../storage/aiPlatformStore.js';
import type{AiAuditService}from'../../audit/aiAuditService.js';
import{AiPlatformError}from'../../core/errors.js';
import{FreePbxAiExtensionAdapter}from'../../extensions/freePbxAiExtensionAdapter.js';
type Mode='disable'|'archive'|'delete';
const safeCode=(e:any)=>String(e?.message||'AGENT_DELETE_FAILED').replace(/[^A-Za-z0-9_.-]/g,'_').slice(0,64);
const parse=(v:any,fallback:any)=>{try{return JSON.parse(String(v||''))}catch{return fallback}};
export class AgentDeletionService{
 constructor(private store:AiPlatformStore,private audit:AiAuditService,private freepbx=new FreePbxAiExtensionAdapter()){}
 async report(tenantId:number,agentId:number){
  const agent=(await this.store.query('SELECT id,name,status,current_version_id FROM ai_agents WHERE tenant_id=? AND id=? LIMIT 1',[tenantId,agentId]))[0];if(!agent)throw new AiPlatformError('not_found',404,'AI-сотрудник не найден');
  const extension=(await this.store.query('SELECT * FROM ai_extensions WHERE tenant_id=? AND agent_id=? ORDER BY id DESC LIMIT 1',[tenantId,agentId]))[0]||null;
  const inspection=extension?await this.freepbx.inspect(String(extension.extension)):null;
  const count=async(sql:string,p:any[]=[tenantId,agentId])=>Number((await this.store.query(sql,p))[0]?.total||0);
  const versions=await this.store.query("SELECT lifecycle_status status,COUNT(*) total FROM ai_agent_versions WHERE tenant_id=? AND agent_id=? GROUP BY lifecycle_status",[tenantId,agentId]);
  const activeVoice=await count("SELECT COUNT(*) total FROM ai_voice_sessions WHERE tenant_id=? AND agent_id=? AND state NOT IN('completed','failed','cancelled')");
  const activeMedia=await count("SELECT COUNT(*) total FROM ai_voice_media_sessions m JOIN ai_voice_sessions v ON v.id=m.voice_session_id WHERE v.tenant_id=? AND v.agent_id=? AND m.state NOT IN('completed','failed','cancelled')");
  const activeRealtime=await count("SELECT COUNT(*) total FROM ai_realtime_voice_sessions r JOIN ai_voice_sessions v ON v.id=r.voice_session_id WHERE v.tenant_id=? AND v.agent_id=? AND r.state NOT IN('completed','failed','cancelled')");
  const activeHandoff=await count("SELECT COUNT(*) total FROM ai_handoff_events h JOIN ai_voice_sessions v ON v.id=h.voice_session_id WHERE v.tenant_id=? AND v.agent_id=? AND h.state NOT IN('completed','failed','cancelled','no_answer','busy')");
  const handoffToAgent=extension?await count("SELECT COUNT(*) total FROM ai_handoff_configs WHERE tenant_id=? AND primary_destination_type='ai_extension' AND primary_destination_ref=? AND status='active'",[tenantId,String(extension.id)]):0;
  const counts={conversations:await count('SELECT COUNT(*) total FROM ai_conversations WHERE tenant_id=? AND agent_id=?'),recordings:await count("SELECT COUNT(*) total FROM ai_voice_sessions WHERE tenant_id=? AND agent_id=? AND recording_ref_safe IS NOT NULL"),audit:await count("SELECT COUNT(*) total FROM ai_audit_log WHERE tenant_id=? AND entity_type='agent' AND entity_id=?",[tenantId,String(agentId)]),skills:await count('SELECT COUNT(*) total FROM ai_agent_skills s JOIN ai_agent_versions v ON v.id=s.agent_version_id WHERE v.tenant_id=? AND v.agent_id=?'),knowledge:await count('SELECT COUNT(*) total FROM ai_agent_knowledge WHERE tenant_id=? AND agent_id=?')};
  const blockers=[...(inspection?.dependencies||[]).map((x:any)=>({code:'FREEPBX_DEPENDENCY',...x})),...(activeVoice?[{code:'ACTIVE_CALL',type:'active_call',name:`Активных звонков: ${activeVoice}`}]:[]),...(activeMedia?[{code:'ACTIVE_MEDIA_SESSION',type:'media',name:`Активных media sessions: ${activeMedia}`}]:[]),...(activeRealtime?[{code:'ACTIVE_REALTIME_SESSION',type:'realtime',name:`Активных Realtime sessions: ${activeRealtime}`}]:[]),...(activeHandoff?[{code:'ACTIVE_HANDOFF',type:'handoff',name:`Активных переводов: ${activeHandoff}`}]:[]),...(handoffToAgent?[{code:'HANDOFF_DESTINATION',type:'handoff_destination',name:'Другой AI-сотрудник переводит на этот номер'}]:[])];
  return{agent:{id:Number(agent.id),name:agent.name,status:agent.status},extension:extension?{id:Number(extension.id),extension:extension.extension,status:extension.status,enabled:Boolean(extension.enabled),fallbackType:extension.fallback_type}:null,binding:extension?.route_binding_id?{id:Number(extension.route_binding_id)}:null,freepbx:inspection?{managed:Boolean(inspection.managedBlockPresent),miscApplications:inspection.miscApplication.length,customDestinations:inspection.customDestination.length,dependencies:inspection.dependencies}:null,versions:Object.fromEntries(versions.map((x:any)=>[x.status,Number(x.total)])),counts,active:{calls:activeVoice,mediaSessions:activeMedia,realtimeSessions:activeRealtime,handoffs:activeHandoff},blockers,canDelete:blockers.length===0,preserved:['CDR/CEL references','conversations','recording metadata','audit','published version snapshots'],removed:['draft versions','editable assignments','handoff config','AI Extension','active binding','PBXPuls-managed FreePBX objects']};
 }
 async preview(tenantId:number,agentId:number,mode:Mode,idempotencyKey:string,actor:any){
  if(!['disable','archive','delete'].includes(mode))throw new AiPlatformError('invalid_request',400,'Неверный режим');if(!/^[A-Za-z0-9_.:-]{8,100}$/.test(idempotencyKey))throw new AiPlatformError('invalid_request',400,'Valid idempotency key required');
  const old=(await this.store.query('SELECT id,preview_json FROM ai_agent_deletion_previews WHERE tenant_id=? AND idempotency_key=? LIMIT 1',[tenantId,idempotencyKey]))[0];if(old)return{previewId:Number(old.id),...parse(old.preview_json,{}),idempotent:true};
  const report=await this.report(tenantId,agentId),blocked=mode==='delete'&&!report.canDelete,preview={ready:!blocked,mode,agent:report.agent,extension:report.extension,binding:report.binding,versions:report.versions,freepbx:report.freepbx,dependencies:report.blockers,willDisable:['AI Extension','binding','handoff config'],willRemove:mode==='delete'?report.removed:[],willPreserve:report.preserved,dialplanDiff:mode==='delete'&&report.extension?[`- PBXPuls managed block ${report.extension.extension}@pbxpuls-ai`]:[],productionAffected:report.freepbx?.dependencies.length>0,automaticCall:false,requiresReload:mode==='delete',rollbackPlan:mode==='delete'?{beforeReload:'restore database states and keep managed objects',afterReloadFailure:'delete_failed; binding remains disabled; retry from verified preview',foreignObjects:'never remove'}:{database:'restore prior agent/extension/binding states',freepbx:'unchanged'}};
  const result:any=await this.store.query("INSERT INTO ai_agent_deletion_previews(tenant_id,agent_id,mode,idempotency_key,preview_json,status,created_by,expires_at)VALUES(?,?,?,?,?,?,?,DATE_ADD(NOW(),INTERVAL 30 MINUTE))",[tenantId,agentId,mode,idempotencyKey,JSON.stringify(preview),blocked?'blocked':'ready',actor.actorId]);await this.audit.append({tenantId,...actor,eventType:'agent_version_archived' as any,entityType:'agent_deletion_preview',entityId:String(result.insertId),decision:blocked?'blocked':'ready',details:{agentId,mode,blockerCount:report.blockers.length,productionAffected:preview.productionAffected}});return{previewId:Number(result.insertId),...preview}
 }
 async apply(tenantId:number,previewId:number,confirm:boolean,confirmName:string,actor:any){
  if(!confirm)throw new AiPlatformError('invalid_request',400,'Explicit confirmation required');const row=(await this.store.query('SELECT * FROM ai_agent_deletion_previews WHERE tenant_id=? AND id=? LIMIT 1',[tenantId,previewId]))[0];if(!row)throw new AiPlatformError('not_found',404,'Preview не найден');if(row.status==='applied')return{...parse(row.preview_json,{}),applied:true,idempotent:true};if(row.status!=='ready'||new Date(row.expires_at).getTime()<=Date.now())throw new AiPlatformError('conflict',409,'Preview заблокирован или истёк');const preview=parse(row.preview_json,{}),agent=preview.agent;if(String(confirmName)!==String(agent.name))throw new AiPlatformError('invalid_request',400,'Введите точное имя AI-сотрудника');
  if(row.mode==='disable')return this.disable(tenantId,row,preview,actor);
  if(row.mode==='archive')return this.archive(tenantId,row,preview,actor);
  return this.remove(tenantId,row,preview,actor);
 }
 async restore(tenantId:number,agentId:number,actor:any){const agent=(await this.store.query("SELECT id,status FROM ai_agents WHERE tenant_id=? AND id=? AND status='archived' LIMIT 1",[tenantId,agentId]))[0];if(!agent)throw new AiPlatformError('conflict',409,'Архивный AI-сотрудник не найден');await this.store.query("UPDATE ai_agents SET status=IF(current_version_id IS NULL,'draft','active'),deletion_status='disabled',archived_at=NULL,updated_at=NOW() WHERE id=?",[agentId]);await this.store.query("UPDATE ai_extensions SET status='disabled',enabled=0 WHERE tenant_id=? AND agent_id=?",[tenantId,agentId]);await this.audit.append({tenantId,...actor,eventType:'agent_version_archived' as any,entityType:'agent',entityId:String(agentId),decision:'restored_disabled'});return{id:agentId,status:'disabled',requiresEnablePreview:true,historyPreserved:true}}
 async retry(tenantId:number,agentId:number,actor:any){const agent=(await this.store.query("SELECT name FROM ai_agents WHERE tenant_id=? AND id=? AND deletion_status='delete_failed'",[tenantId,agentId]))[0];if(!agent)throw new AiPlatformError('conflict',409,'Нет failed deletion для retry');return this.preview(tenantId,agentId,'delete',`delete-retry-${agentId}-${Date.now()}`,actor)}
 private async disable(tenantId:number,row:any,p:any,actor:any){await this.store.query("UPDATE ai_agents SET deletion_status='disabling' WHERE id=?",[row.agent_id]);await this.store.query("UPDATE ai_extensions SET status='disabled',enabled=0 WHERE tenant_id=? AND agent_id=?",[tenantId,row.agent_id]);await this.store.query("UPDATE ai_voice_route_bindings b JOIN ai_extensions e ON e.route_binding_id=b.id SET b.status='disabled' WHERE e.tenant_id=? AND e.agent_id=?",[tenantId,row.agent_id]);await this.store.query("UPDATE ai_handoff_configs SET status='disabled',enabled=0 WHERE tenant_id=? AND agent_id=?",[tenantId,row.agent_id]);await this.store.query("UPDATE ai_agents SET deletion_status='disabled',updated_at=NOW() WHERE id=?",[row.agent_id]);return this.finish(tenantId,row,p,actor,'disabled')}
 private async archive(tenantId:number,row:any,p:any,actor:any){await this.store.query("UPDATE ai_agents SET deletion_status='archiving' WHERE id=?",[row.agent_id]);await this.disable(tenantId,{...row,id:-1},p,actor);await this.store.query("UPDATE ai_extensions SET status='archived',enabled=0 WHERE tenant_id=? AND agent_id=?",[tenantId,row.agent_id]);await this.store.query("UPDATE ai_agents SET status='archived',deletion_status='archived',archived_at=NOW(),updated_at=NOW() WHERE id=?",[row.agent_id]);return this.finish(tenantId,row,p,actor,'archived')}
 private async remove(tenantId:number,row:any,p:any,actor:any){const report=await this.report(tenantId,row.agent_id);if(!report.canDelete)throw new AiPlatformError('conflict',409,'Появились новые зависимости; создайте новый preview');const extension=report.extension;try{await this.store.query("UPDATE ai_agents SET deletion_status='deleting' WHERE id=?",[row.agent_id]);await this.disable(tenantId,{...row,id:-1},p,actor);if(extension){await this.store.query("UPDATE ai_agents SET deletion_status='removing_freepbx_objects' WHERE id=?",[row.agent_id]);await this.freepbx.remove(String(extension.extension));await this.store.query("UPDATE ai_agents SET deletion_status='reloading' WHERE id=?",[row.agent_id]);await this.freepbx.reload();await this.store.query("UPDATE ai_agents SET deletion_status='verifying' WHERE id=?",[row.agent_id]);const inspection=await this.freepbx.inspect(String(extension.extension));if(inspection.managedBlockPresent||inspection.miscApplication.length||inspection.customDestination.length)throw new Error('FREEPBX_OBJECTS_STILL_PRESENT')}
   const versions=await this.store.query("SELECT id FROM ai_agent_versions WHERE tenant_id=? AND agent_id=? AND lifecycle_status='draft'",[tenantId,row.agent_id]),ids=versions.map((x:any)=>Number(x.id));if(ids.length){const marks=ids.map(()=>'?').join(',');for(const table of['ai_agent_skills','ai_agent_tools','ai_agent_actions','ai_agent_prompt_versions'])await this.store.query(`DELETE FROM ${table} WHERE agent_version_id IN (${marks})`,ids);await this.store.query(`DELETE FROM ai_agent_versions WHERE id IN (${marks})`,ids)}
   await this.store.query("DELETE FROM ai_agent_knowledge WHERE tenant_id=? AND agent_id=?",[tenantId,row.agent_id]);await this.store.query("DELETE FROM ai_handoff_previews WHERE config_id IN(SELECT id FROM ai_handoff_configs WHERE tenant_id=? AND agent_id=?)",[tenantId,row.agent_id]);await this.store.query("UPDATE ai_handoff_configs SET status='archived',enabled=0,ai_extension_id=NULL,primary_destination_safe='Удалённое направление' WHERE tenant_id=? AND agent_id=?",[tenantId,row.agent_id]);if(extension){await this.store.query("DELETE FROM ai_extension_previews WHERE ai_extension_id=?",[extension.id]);await this.store.query("DELETE FROM ai_extensions WHERE tenant_id=? AND id=?",[tenantId,extension.id])}
   await this.store.query("INSERT INTO ai_deleted_agent_snapshots(tenant_id,agent_id,original_name,snapshot_json,deleted_by)VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE snapshot_json=VALUES(snapshot_json),deleted_by=VALUES(deleted_by),deleted_at=NOW()",[tenantId,row.agent_id,p.agent.name,JSON.stringify({agent:p.agent,extension:p.extension,versions:p.versions,preserved:p.willPreserve}),actor.actorId]);await this.store.query("UPDATE ai_voice_route_bindings SET status='disabled',name='Удалённый AI-сотрудник',safe_match_label='deleted',match_value_hash=NULL WHERE tenant_id=? AND agent_id=?",[tenantId,row.agent_id]);await this.store.query("UPDATE ai_agents SET name='Удалённый AI-сотрудник',agent_key=CONCAT('deleted_',id),status='archived',current_version_id=NULL,deletion_status='deleted',deleted_at=NOW(),updated_at=NOW() WHERE id=?",[row.agent_id]);return this.finish(tenantId,row,p,actor,'deleted')
  }catch(e:any){await this.store.query("UPDATE ai_agents SET deletion_status='delete_failed',deletion_error_code=? WHERE id=?",[safeCode(e),row.agent_id]);throw new AiPlatformError('conflict',409,'Удаление не завершено')}
 }
 private async finish(tenantId:number,row:any,p:any,actor:any,status:string){if(row.id>0)await this.store.query("UPDATE ai_agent_deletion_previews SET status='applied',applied_at=NOW() WHERE id=?",[row.id]);await this.audit.append({tenantId,...actor,eventType:'agent_version_archived' as any,entityType:'agent',entityId:String(row.agent_id),decision:status,details:{mode:row.mode,historyPreserved:true}});return{...p,applied:true,status,historyPreserved:true}}
}
