import type{Express}from'express';import type{VoiceAgentRouteService}from'../voiceAgentRouteService.js';
export function registerVoiceAgentRouteRoutes(app:Express,r:any,service:VoiceAgentRouteService){const{authenticated,permit,wrap,getTenantId,actor,positiveInt,store}=r;
 app.get('/api/ai-platform/voice-agents',...authenticated,permit('view_ai_voice_agents'),wrap(async(_req:any,res:any)=>res.json({success:true,rows:await service.agents(await getTenantId())})));
 app.get('/api/ai-platform/voice-agent-bindings',...authenticated,permit('view_ai_voice_agents'),wrap(async(_req:any,res:any)=>{const tenantId=await getTenantId();await service.expire(tenantId);const rows=await store.query(`SELECT id,binding_key bindingKey,name,status,match_type sourceType,safe_match_label routeLabel,agent_id agentId,agent_version_id agentVersionId,language,priority,dry_run_only dryRunOnly,route_mode mode,provider_key provider,voice_key voice,allowed_callers_json,fallback_type fallbackType,fallback_value_safe fallbackLabel,maximum_concurrent_calls maximumConcurrentCalls,effective_schedule_json,expires_at expiresAt,activation_state activationState,last_error_code lastErrorCode,created_at createdAt,updated_at updatedAt FROM ai_voice_route_bindings WHERE tenant_id=? ORDER BY priority DESC,id`,[tenantId]);res.json({success:true,rows:rows.map((row:any)=>({...row,allowedCallers:JSON.parse(row.allowed_callers_json||'[]'),allowed_callers_json:undefined,effectiveSchedule:JSON.parse(row.effective_schedule_json||'{}'),effective_schedule_json:undefined}))})}));
 app.post('/api/ai-platform/voice-agent-bindings/preview',...authenticated,permit('manage_ai_voice_routes'),wrap(async(req:any,res:any)=>res.json({success:true,data:await service.preview(await getTenantId(),req.body||{})})));
 app.post('/api/ai-platform/voice-agent-bindings',...authenticated,permit('manage_ai_voice_routes'),wrap(async(req:any,res:any)=>res.status(201).json({success:true,data:await service.create(await getTenantId(),req.body||{},actor(req))})));
 app.post('/api/ai-platform/voice-agent-bindings/:id/activate',...authenticated,permit('manage_ai_voice_routes'),wrap(async(req:any,res:any)=>res.json({success:true,data:await service.activate(await getTenantId(),positiveInt(req.params.id,'binding id'),req.body?.confirm===true,actor(req))})));
 app.post('/api/ai-platform/voice-agent-bindings/:id/disable',...authenticated,permit('manage_ai_voice_routes'),wrap(async(req:any,res:any)=>{const tenantId=await getTenantId(),id=positiveInt(req.params.id,'binding id');await store.query("UPDATE ai_voice_route_bindings SET status='disabled',activation_state='disabled',updated_at=NOW() WHERE tenant_id=? AND id=?",[tenantId,id]);await r.audit.append({tenantId,...actor(req),eventType:'voice_route_binding_updated',entityType:'voice_route_binding',entityId:String(id),decision:'disabled',details:{}});res.json({success:true,data:{id,status:'disabled'}})}));
 app.post('/api/ai-platform/voice-agent-bindings/:id/version-preview',...authenticated,permit('manage_ai_voice_routes'),wrap(async(req:any,res:any)=>res.json({success:true,data:await service.previewControlledVersionSwitch(await getTenantId(),positiveInt(req.params.id,'binding id'),positiveInt(req.body?.agentVersionId,'agent version id'))})));
 app.post('/api/ai-platform/voice-agent-bindings/:id/version-apply',...authenticated,permit('manage_ai_voice_routes'),wrap(async(req:any,res:any)=>res.json({success:true,data:await service.switchControlledVersion(await getTenantId(),positiveInt(req.params.id,'binding id'),positiveInt(req.body?.agentVersionId,'agent version id'),req.body?.confirm===true,actor(req))})));
 app.post('/api/ai-platform/voice-agents/test-binding',...authenticated,permit('test_ai_voice_agents'),wrap(async(req:any,res:any)=>{const tenantId=await getTenantId(),data=await service.create(tenantId,{...req.body,mode:'test',sourceType:'extension',bindingKey:`voice_test_${Date.now()}`,name:'Temporary controlled AI test',ttlMinutes:Math.max(5,Math.min(Number(req.body?.ttlMinutes)||30,180)),fallbackType:req.body?.fallbackType||'terminate_call'},actor(req));res.status(201).json({success:true,data:{...data,testNumberLabel:data.preview.changes.routeLabel,temporary:true}})}));
}
