import crypto from 'crypto';
import type { Express, NextFunction, Request, Response } from 'express';
import { AiPlatformError, toSafeAiPlatformError } from '../core/errors.js';
import { isAiPlatformCoreEnabled } from '../core/featureFlag.js';
import { parseJsonObject, redactAiPlatformValue } from '../core/redaction.js';
import { getInstallationTenant } from '../tenants/tenantService.js';
import { sqlAiPlatformStore, type AiPlatformStore } from '../storage/aiPlatformStore.js';
import { AiAuditService } from '../audit/aiAuditService.js';
import { AgentLifecycleService } from '../agents/agentLifecycleService.js';
import { AgentBuilderService } from '../agents/agentBuilderService.js';
import { getAIProviderRegistry } from '../providers/providerRegistry.js';
import { publicLegacyProviderConfig, readLegacyProviderConfig } from '../providers/legacyConfigReader.js';
import { getToolRegistry } from '../tools/toolRegistry.js';
import { AgentContextBuilder } from '../core/agentContextBuilder.js';
import { registerKnowledgeRoutes } from '../knowledge/api/registerKnowledgeRoutes.js';
import { registerTrainingRoutes } from '../training/api/registerTrainingRoutes.js';
import { ConversationRuntime } from '../conversations/conversationRuntime.js';
import { ConversationService } from '../conversations/conversationService.js';
import type { ProviderExecutor } from '../conversations/runtimeTypes.js';
import { ToolExecutor } from '../tools/toolExecutor.js';
import { createPBXReadExecutorRegistry } from '../tools/executors/pbxReadExecutors.js';
import type { PBXReadServices } from '../../services/pbxReadServices.js';
import type { PBXTransferService } from '../../services/pbxTransferService.js';
import { PBXTransferExecutionAdapter } from '../transfer/transferExecutionAdapter.js';
import { TransferDestinationResolver } from '../transfer/transferDestinationResolver.js';
import { HumanTransferService } from '../transfer/humanTransferService.js';
import{registerActionRoutes}from'../actions/api/registerActionRoutes.js';
import{getActionDefinitionRegistry}from'../actions/actionDefinitionRegistry.js';
import{ActionExecutorRegistry}from'../actions/actionExecutorRegistry.js';
import{CreateCallbackRequestExecutor}from'../actions/executors/createCallbackRequestExecutor.js';
import{BusinessActionService}from'../actions/businessActionService.js';
import{VoiceGatewayService}from'../voice/voiceGatewayService.js';
import{ObserverAriClientAdapter}from'../voice/ari/ariClientAdapter.js';
import{readAriConfig}from'../voice/ari/ariTypes.js';
import{AriConnectionManager}from'../voice/ari/ariConnectionManager.js';
import{registerVoiceRoutes}from'../voice/api/voiceRouter.js';
import{AriEventRouter}from'../voice/ari/ariEventRouter.js';
import{MediaTransportRegistry}from'../voice/media/mediaTransportRegistry.js';
import{SyntheticMediaAdapter}from'../voice/media/transports/syntheticMediaAdapter.js';
import{ExternalMediaAdapter}from'../voice/media/transports/externalMediaAdapter.js';
import{AudioSocketAdapter}from'../voice/media/transports/audioSocketAdapter.js';
import{MediaSessionService}from'../voice/media/mediaSessionService.js';
import{readVoiceMediaSettings}from'../voice/media/mediaGatewayControl.js';
import{registerVoiceMediaRoutes}from'../voice/media/api/mediaRouter.js';
import{RealtimeVoiceProviderRegistry}from'../voice/providers/realtimeVoiceProviderRegistry.js';
import{SyntheticRealtimeVoiceAdapter}from'../voice/providers/adapters/syntheticRealtimeVoiceAdapter.js';
import{OpenAIRealtimeAdapter,readOpenAIRealtimeConfig}from'../voice/providers/adapters/openaiRealtimeAdapter.js';
import{RealtimeVoiceSessionService}from'../voice/providers/realtimeVoiceSessionService.js';
import{readRealtimeVoiceSettings}from'../voice/providers/realtimeVoiceControl.js';
import{registerRealtimeVoiceRoutes}from'../voice/providers/api/realtimeVoiceRouter.js';
import{LiveBridgeService}from'../voice/live/liveBridgeService.js';
import{ControlledLiveVoiceService}from'../voice/live/controlledLiveVoiceService.js';
import{registerLiveVoiceRoutes}from'../voice/live/api/liveVoiceRouter.js';
import{VoiceTranscriptService}from'../voice/transcripts/voiceTranscriptService.js';
import{registerVoiceTranscriptRoutes}from'../voice/transcripts/api/voiceTranscriptRouter.js';
import{VoiceRecordingReconciliationService}from'../voice/recordings/voiceRecordingReconciliationService.js';
import{VoiceAgentRouteService}from'../voice/management/voiceAgentRouteService.js';
import{registerVoiceAgentRouteRoutes}from'../voice/management/api/voiceAgentRouteRouter.js';
import{startMediaWorker,stopMediaWorker}from'../voice/media-worker/mediaWorkerClient.js';
import{startMainEventLoopDiagnostics}from'../voice/diagnostics/mainEventLoopDiagnostics.js';
import{SkillService}from'../skills/skillService.js';
import{registerSkillRoutes}from'../skills/api/registerSkillRoutes.js';
import{OPENAI_REALTIME_VOICES,DEFAULT_RUSSIAN_TEST_PHRASE,normalizeVoiceProfile,compileVoiceProfileInstructions}from'../voice/profiles/voiceProfile.js';
import{RUSSIAN_VOICE_COMPARISON_TEXTS,buildRussianVoiceComparisonRequest}from'../voice/profiles/voiceComparison.js';
import{VoiceCatalogService,VoicePreviewCache}from'../voice/profiles/voiceCatalogService.js';
import{findAiConfigSecretField}from'../agents/agentConfigurationValidator.js';
import{normalizePronunciationEntries}from'../voice/profiles/voiceProfile.js';
import{AiExtensionService}from'../extensions/aiExtensionService.js';
import{registerAiExtensionRoutes}from'../extensions/api/aiExtensionRouter.js';

type Checker=(req:Request,permission:string)=>Promise<boolean>;
export interface AiPlatformRouterDeps { requireAuth:any; checkPermission:Checker; readLegacyDb:()=>Promise<any>; store?:AiPlatformStore; isEnabled?:()=>Promise<boolean>;sandboxProvider?:ProviderExecutor;pbxReadServices?:PBXReadServices;pbxTransferService?:PBXTransferService }
const positiveInt=(value:unknown,name:string)=>{const n=Number(value);if(!Number.isInteger(n)||n<=0)throw new AiPlatformError('invalid_request',400,`Invalid ${name}`);return n};
const page=(req:Request)=>({limit:Math.max(1,Math.min(Number(req.query.limit)||50,100)),offset:Math.max(0,(Math.max(1,Number(req.query.page)||1)-1)*Math.max(1,Math.min(Number(req.query.limit)||50,100)))});
const actor=(req:Request)=>({traceId:String(req.header('x-trace-id')||crypto.randomUUID()).slice(0,64),actorType:'user' as const,actorId:String((req as any).user?.username||'authenticated').slice(0,191)});
const fail=(res:Response,error:unknown)=>{const safe=toSafeAiPlatformError(error);return res.status(safe.statusCode).json({success:false,error:safe.message,code:safe.code})};
const wrap=(handler:(req:Request,res:Response)=>Promise<any>)=>async(req:Request,res:Response)=>{try{await handler(req,res)}catch(error){fail(res,error)}};
const safeVoiceSettings=(body:any)=>{
  const input={voiceProfile:body?.voiceProfile||{},pronunciationEntries:body?.pronunciationEntries||[]};
  const forbidden=findAiConfigSecretField(input);
  if(forbidden)throw new AiPlatformError('invalid_request',400,`Настройки не сохранены: обнаружено запрещённое поле ${forbidden}.`);
  return{profile:normalizeVoiceProfile(input.voiceProfile),entries:normalizePronunciationEntries(input.pronunciationEntries),vad:Math.max(300,Math.min(Number(body?.endOfTurnSilenceMs)||350,600))};
};

export function registerAiPlatformRoutes(app:Express,deps:AiPlatformRouterDeps){
  startMainEventLoopDiagnostics();
  const store=deps.store||sqlAiPlatformStore,audit=new AiAuditService(store),lifecycle=new AgentLifecycleService(store,audit),builder=new AgentBuilderService(store,audit),contextBuilder=new AgentContextBuilder(store),skills=new SkillService(store,audit),voiceCatalog=new VoiceCatalogService(store,audit),voicePreviewCache=new VoicePreviewCache();
  const aiExtensions=new AiExtensionService(store,audit);
  const readEnabled=deps.isEnabled||isAiPlatformCoreEnabled;
  const authenticated=[deps.requireAuth()];
  const permit=(permission:string)=>async(req:Request,res:Response,next:NextFunction)=>{
    if(await deps.checkPermission(req,permission))return next();
    try{const tenant=await getInstallationTenant(store);await audit.append({tenantId:tenant.id,...actor(req),eventType:'permission_denied',entityType:'api',entityId:req.path,decision:'denied',details:{permission}})}catch{}
    return res.status(403).json({success:false,error:'Access denied: insufficient permissions',code:'permission_denied'});
  };
  const enabled=async(req:Request,res:Response,next:NextFunction)=>{
    if(await readEnabled())return next();
    try{const tenant=await getInstallationTenant(store);await audit.append({tenantId:tenant.id,...actor(req),eventType:'feature_flag_blocked',entityType:'api',entityId:req.path,decision:'blocked',details:{flag:'ai.platform_core_enabled'}})}catch{}
    return res.status(503).json({success:false,error:'AI Platform Core is disabled',code:'feature_disabled'});
  };
  const domainRuntime={authenticated,permit,enabled,wrap,getTenantId:async()=>(await getInstallationTenant(store)).id,actor,store,audit,positiveInt,page};
  const toolExecutor=deps.pbxReadServices?new ToolExecutor(store,audit,createPBXReadExecutorRegistry(deps.pbxReadServices),{isCoreEnabled:readEnabled}):null;
  const voiceGateway=new VoiceGatewayService(store,audit);
  const mediaRegistry=new MediaTransportRegistry();mediaRegistry.register(new SyntheticMediaAdapter());mediaRegistry.register(new ExternalMediaAdapter());mediaRegistry.register(new AudioSocketAdapter());
  const mediaSessions=new MediaSessionService(store,audit,mediaRegistry,async()=>{const settings=await readVoiceMediaSettings(store);return(await readEnabled())&&settings.enabled});
  const transferAdapter=deps.pbxTransferService?new PBXTransferExecutionAdapter(deps.pbxTransferService,voiceGateway.sessions):null;
  const humanTransfer=deps.pbxTransferService?new HumanTransferService(store,audit,new TransferDestinationResolver(deps.pbxTransferService),transferAdapter,{isEnabled:readEnabled,hooks:{onTransferRequested:async({conversationId,traceId})=>{if(!conversationId)return;const rows=await store.query("SELECT id,tenant_id FROM ai_voice_sessions WHERE conversation_id=? AND state IN('active','waiting_for_media','transferring') ORDER BY id DESC LIMIT 1",[conversationId]);if(rows[0])await mediaSessions.closeForVoiceSession(Number(rows[0].tenant_id),Number(rows[0].id),traceId)}}}):null;
  const actionExecutors=new ActionExecutorRegistry();actionExecutors.register('create_callback_request',new CreateCallbackRequestExecutor(store));
  const businessActions=new BusinessActionService(store,audit,getActionDefinitionRegistry(),actionExecutors,readEnabled);
  const realtimeRegistry=new RealtimeVoiceProviderRegistry();realtimeRegistry.register('synthetic',()=>new SyntheticRealtimeVoiceAdapter());realtimeRegistry.register('openai_realtime',()=>new OpenAIRealtimeAdapter());
  const transcriptService=new VoiceTranscriptService(store),realtimeSessions=new RealtimeVoiceSessionService(store,audit,realtimeRegistry,mediaSessions,async()=>{const media=await readVoiceMediaSettings(store),realtime=await readRealtimeVoiceSettings(store);return(await readEnabled())&&media.enabled&&realtime.enabled},toolExecutor,humanTransfer,businessActions,transcriptService);
  mediaSessions.setProviderCloser((tenantId,mediaSessionId,traceId)=>realtimeSessions.closeForMediaSession(tenantId,mediaSessionId,traceId));
  const installationTenantId=async()=>(await getInstallationTenant(store)).id,ariAdapter=new ObserverAriClientAdapter(readAriConfig()),ariEvents=new AriEventRouter(voiceGateway,installationTenantId),ariManager=new AriConnectionManager(ariAdapter,audit,installationTenantId,ariEvents.handle);
  const recordingService=new VoiceRecordingReconciliationService(store,audit),liveVoice=new ControlledLiveVoiceService(store,audit,voiceGateway,ariManager,mediaSessions,realtimeSessions,new LiveBridgeService(ariAdapter),recordingService);mediaSessions.setDurationCloser((tenantId,mediaSessionId,traceId)=>liveVoice.durationLimit(tenantId,mediaSessionId,traceId));realtimeSessions.setLiveObserver(event=>liveVoice.observe(event));realtimeSessions.setControlledHangupHandler(event=>liveVoice.deterministicHangup(event.tenantId,event.voiceSessionId,event.traceId));voiceGateway.setLiveHooks({guard:input=>liveVoice.guard(input),start:input=>liveVoice.start(input)});voiceGateway.setMediaCloser(async(tenantId,voiceSessionId,traceId)=>{await liveVoice.cleanup(tenantId,voiceSessionId,traceId);return mediaSessions.closeForVoiceSession(tenantId,voiceSessionId,traceId)});
  const voiceAgentRoutes=new VoiceAgentRouteService(store,audit,ariManager);
  const sandboxProvider:ProviderExecutor=deps.sandboxProvider||(async input=>{const legacy=readLegacyProviderConfig(await deps.readLegacyDb()),config=legacy.config,adapter=getAIProviderRegistry().get(config.providerKey);let last:any;for(let attempt=0;attempt<2;attempt++)try{return await adapter.generate({messages:input.messages,model:config.model,temperature:.3,maxOutput:300,responseFormat:input.responseFormat||'text',traceId:input.traceId,timeoutMs:input.timeoutMs||15000,signal:input.signal,tools:input.tools},config)}catch(error){last=error;if(attempt||!/429|502|503|timeout|unavailable/i.test(String((error as any)?.message)))break}throw last});
  const skillClassifier=async(input:any)=>{const response=await sandboxProvider({traceId:`skill-route-${Date.now()}`,responseFormat:'json',timeoutMs:8000,messages:[{role:'system',content:'Classify the caller request using only the supplied published skill list. Return strict JSON: {\"skill_id\": number|null, \"confidence\": number, \"reason_safe\": string}. Never invent a skill.'},{role:'user',content:JSON.stringify({text:String(input.text||'').slice(0,1000),skills:(input.skills||[]).map((skill:any)=>({id:skill.id,name:skill.name,description:skill.description,intent_examples:skill.intentExamples}))})}]});try{const parsed=JSON.parse(response.content);return{skillId:Number.isInteger(parsed.skill_id)?Number(parsed.skill_id):null,confidence:Math.max(0,Math.min(1,Number(parsed.confidence)||0)),reasonSafe:String(parsed.reason_safe||'structured_classifier').replace(/[^\p{L}\p{N} _.-]/gu,'').slice(0,160)}}catch{return{skillId:null,confidence:0,reasonSafe:'classifier_invalid_response'}}};
  realtimeSessions.setSkillClassifier(skillClassifier);
  transcriptService.setAnalyzer(async({voiceSessionId,turns})=>{const response=await sandboxProvider({traceId:`post-call-${voiceSessionId}`,responseFormat:'json',timeoutMs:15000,messages:[{role:'system',content:'Return strict JSON with summary, topic, outcome, next_action, transferred, callback_requested, unresolved_issue, evidence_turn_ids. Use only supplied redacted transcript; do not infer unsupported facts.'},{role:'user',content:JSON.stringify(turns)}]});try{return JSON.parse(response.content)}catch{return{}}});
  if(!sandboxProvider.getCapabilities)sandboxProvider.getCapabilities=async()=>{const legacy=readLegacyProviderConfig(await deps.readLegacyDb());return getAIProviderRegistry().get(legacy.config.providerKey).getCapabilities()};
  const sandboxRuntime=new ConversationRuntime(store,audit,sandboxProvider,toolExecutor,humanTransfer,businessActions),conversationService=new ConversationService(store);
  const sandboxHits=new Map<string,number[]>(),sandboxActive=new Set<string>();
  const transferHits=new Map<string,number[]>();
  const sandboxGuard=(req:Request,res:Response,next:NextFunction)=>{const user=String((req as any).user?.username||'authenticated'),session=String(req.params.sessionId||''),key=`${user}:${session}`,now=Date.now();if(sandboxHits.size>1000)for(const[entry,values]of sandboxHits)if(!values.some(value=>now-value<60000))sandboxHits.delete(entry);const hits=(sandboxHits.get(user)||[]).filter(value=>now-value<60000);if(hits.length>=5)return res.status(429).json({success:false,error:'Sandbox rate limit exceeded',code:'rate_limited'});if(sandboxActive.has(key))return res.status(429).json({success:false,error:'Sandbox session turn already active',code:'concurrency_limited'});hits.push(now);sandboxHits.set(user,hits);sandboxActive.add(key);let released=false;const release=()=>{if(!released){released=true;sandboxActive.delete(key)}};res.once('finish',release);res.once('close',release);next()};

  app.get('/api/ai-platform/status',...authenticated,permit('view_ai_platform'),wrap(async(_req,res)=>{
    const coreEnabled=await readEnabled();let tenant:any=null,counts={agents:0,published:0,tools:0};
    try{tenant=await getInstallationTenant(store);const rows=await store.query(`SELECT
      (SELECT COUNT(*) FROM ai_agents WHERE tenant_id=?) agents,
      (SELECT COUNT(*) FROM ai_agents WHERE tenant_id=? AND current_version_id IS NOT NULL) published,
      (SELECT COUNT(*) FROM ai_tools WHERE tenant_id=? OR tenant_id IS NULL) tools`,[tenant.id,tenant.id,tenant.id]);counts={agents:Number(rows[0]?.agents||0),published:Number(rows[0]?.published||0),tools:Number(rows[0]?.tools||0)}}catch{}
    const providers=getAIProviderRegistry().list();res.json({success:true,enabled:coreEnabled,tenantMode:'installation',installationTenantReady:Boolean(tenant),
      providers:providers.map(item=>item.key),providerCapabilities:providers,agentsCount:counts.agents,publishedAgentsCount:counts.published,toolsCount:counts.tools,
      writeToolsEnabled:false,voiceGatewayReady:false,realtimeVoiceReady:false});
  }));

  app.get('/api/ai-platform/agents',...authenticated,permit('view_ai_platform'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),p=page(req);
    const rows=await store.query(`SELECT a.id,a.agent_key,a.name,a.agent_type,a.status,a.current_version_id,a.created_at,a.updated_at,
      v.version_number current_version_number,v.lifecycle_status current_version_status FROM ai_agents a LEFT JOIN ai_agent_versions v ON v.id=a.current_version_id
      WHERE a.tenant_id=? ORDER BY a.id DESC LIMIT ? OFFSET ?`,[tenant.id,p.limit,p.offset]);res.json({success:true,rows,page:Math.floor(p.offset/p.limit)+1,limit:p.limit});}));
  app.post('/api/ai-platform/agents',...authenticated,permit('manage_ai_agents'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store);
    const created=await lifecycle.createAgentDraft(tenant.id,{agentKey:req.body?.agentKey,name:req.body?.name,agentType:req.body?.agentType,config:parseJsonObject(req.body?.config||{},'config'),systemPrompt:String(req.body?.systemPrompt||'')},actor(req));res.status(201).json({success:true,data:created});}));
  app.get('/api/ai-platform/agents/:id',...authenticated,permit('view_ai_platform'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),id=positiveInt(req.params.id,'agent id');
    const rows=await store.query('SELECT id,agent_key,name,agent_type,status,current_version_id,created_by,created_at,updated_at FROM ai_agents WHERE id=? AND tenant_id=? LIMIT 1',[id,tenant.id]);if(!rows.length)throw new AiPlatformError('not_found',404,'Agent not found');res.json({success:true,data:rows[0]});}));
  app.get('/api/ai-platform/agents/:id/versions',...authenticated,permit('view_ai_platform'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),id=positiveInt(req.params.id,'agent id'),p=page(req);
    const rows=await store.query('SELECT id,version_number,lifecycle_status,config_json,system_prompt,checksum,created_by,created_at,published_at FROM ai_agent_versions WHERE tenant_id=? AND agent_id=? ORDER BY version_number DESC LIMIT ? OFFSET ?',[tenant.id,id,p.limit,p.offset]);res.json({success:true,rows:rows.map(row=>({...row,config:parseJsonObject(row.config_json,'config_json'),config_json:undefined})),page:Math.floor(p.offset/p.limit)+1,limit:p.limit});}));
  app.post('/api/ai-platform/agents/:id/versions',...authenticated,permit('manage_ai_agents'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),id=positiveInt(req.params.id,'agent id');const data=await builder.createDraftVersion(tenant.id,id,{config:parseJsonObject(req.body?.config||{},'config'),systemPrompt:String(req.body?.systemPrompt||''),changeReason:String(req.body?.changeReason||'')},actor(req));res.status(201).json({success:true,data});}));
  app.post('/api/ai-platform/agents/:id/versions/:versionId/publish',...authenticated,permit('publish_ai_agents'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store);res.json({success:true,data:await lifecycle.publishVersion(tenant.id,positiveInt(req.params.id,'agent id'),positiveInt(req.params.versionId,'version id'),actor(req))});}));
  app.post('/api/ai-platform/agents/:id/versions/:versionId/archive',...authenticated,permit('manage_ai_agents'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store);res.json({success:true,data:await lifecycle.archiveVersion(tenant.id,positiveInt(req.params.id,'agent id'),positiveInt(req.params.versionId,'version id'),actor(req))});}));
  app.get('/api/ai-platform/voice-profiles/options',...authenticated,permit('view_ai_platform'),enabled,wrap(async(_req,res)=>{
    res.json({success:true,data:{provider:'openai_realtime',voices:OPENAI_REALTIME_VOICES,comparisonTexts:RUSSIAN_VOICE_COMPARISON_TEXTS,testPhrase:DEFAULT_RUSSIAN_TEST_PHRASE,providerApiFields:['voice','instructions'],auditoryReviewRequired:true}});
  }));
  app.get('/api/ai-platform/voice-catalog',...authenticated,permit('view_ai_voice_catalog'),enabled,wrap(async(req,res)=>{
    const tenant=await getInstallationTenant(store),rows=await voiceCatalog.list(tenant.id,{provider:req.query.provider,active:req.query.active,gender:req.query.gender,newOnly:req.query.newOnly==='true'});
    const lastVerifiedAt=rows.map(row=>row.lastVerifiedAt).filter(Boolean).sort().at(-1)||null;
    res.json({success:true,rows:rows.map(row=>({...row,isNew:voiceCatalog.isNew(row.firstSeenAt)})),lastVerifiedAt,filters:{providers:[...new Set(rows.map(row=>row.provider))],genders:[...new Set(rows.map(row=>String(row.metadata.gender||'')).filter(Boolean))]}});
  }));
  app.post('/api/ai-platform/voice-catalog/refresh',...authenticated,permit('manage_ai_voice_catalog'),enabled,wrap(async(req,res)=>{
    const tenant=await getInstallationTenant(store),data=await voiceCatalog.refresh(tenant.id,String(req.body?.provider||'openai_realtime'),actor(req));
    res.json({success:true,data});
  }));
  app.post('/api/ai-platform/voice-profiles/preview-audio',...authenticated,permit('generate_ai_voice_preview'),enabled,wrap(async(req,res)=>{
    const tenant=await getInstallationTenant(store),current=actor(req),comparison=buildRussianVoiceComparisonRequest({...req.body?.voiceProfile,textKey:req.body?.textKey,text:req.body?.text}),profile=comparison.profile,external=readOpenAIRealtimeConfig();
    await voiceCatalog.requireAvailable(tenant.id,profile.provider,profile.voiceId);
    if(!external.configured)throw new AiPlatformError('conflict',409,'Realtime voice provider is not configured');
    const cacheKey=voicePreviewCache.key({provider:profile.provider,model:external.model,voiceId:profile.voiceId,textHash:crypto.createHash('sha256').update(comparison.text).digest('hex'),profile,output:comparison.output});
    if(req.body?.force===true)voicePreviewCache.delete(cacheKey);
    const cached=voicePreviewCache.get(cacheKey);
    if(cached){res.set('Cache-Control','private, max-age=60').set('X-Voice-Preview-Cache','hit').type('audio/wav').send(cached);return}
    const adapter=new OpenAIRealtimeAdapter(),chunks:Buffer[]=[];
    const completed=new Promise<void>((resolve,reject)=>{
      const timer=setTimeout(()=>reject(new Error('voice_preview_timeout')),20000);
      adapter.subscribeEvents(event=>{
        if(event.type==='output_audio')chunks.push(Buffer.from(event.frame.payload));
        if(event.type==='response_completed'){clearTimeout(timer);resolve()}
        if(event.type==='error'){clearTimeout(timer);reject(new Error('voice_preview_failed'))}
      });
    });
    const config:any={providerKey:'openai_realtime',apiKey:external.apiKey,url:external.url,model:external.model,voice:profile.voiceId,language:profile.locale,instructions:comparison.instructions,greetingOutputTokens:240,inputFormat:{codec:'slin16',sampleRate:16000,channels:1,frameDurationMs:20},outputFormat:comparison.output,serverVad:false,tools:[],timeoutMs:10000};
    try{await adapter.connect(config);await adapter.configureSession(config);await adapter.startInitialGreeting(comparison.text);await completed}
    catch(error){if(String((error as any)?.message||'')==='Realtime session configuration was rejected')await voiceCatalog.markUnavailable(tenant.id,profile.provider,profile.voiceId,'provider_session_config_rejected',current);throw new AiPlatformError('conflict',409,'Выбранный голос сейчас недоступен')}
    finally{await adapter.close()}
    const pcm=Buffer.concat(chunks),wav=Buffer.alloc(44+pcm.length);
    wav.write('RIFF',0);wav.writeUInt32LE(36+pcm.length,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(pcm.length,40);pcm.copy(wav,44);
    voicePreviewCache.set(cacheKey,wav);
    await audit.append({tenantId:tenant.id,...current,eventType:'voice_preview_generated' as any,entityType:'voice_catalog',entityId:`${profile.provider}:${profile.voiceId}`,decision:'generated',details:{provider:profile.provider,voiceId:profile.voiceId,textHash:crypto.createHash('sha256').update(comparison.text).digest('hex'),cacheHit:false}});
    res.set('Cache-Control','private, max-age=60').set('X-Voice-Preview-Cache','miss').set('X-Voice-Preview-Text',comparison.textKey).type('audio/wav').send(wav);
  }));
  app.get('/api/ai-platform/agents/:id/voice-settings',...authenticated,permit('view_ai_platform'),enabled,wrap(async(req,res)=>{
    const tenant=await getInstallationTenant(store),id=positiveInt(req.params.id,'agent id');
    const rows=await store.query(`SELECT v.id version_id,v.version_number,v.lifecycle_status,v.config_json FROM ai_agent_versions v JOIN ai_agents a ON a.id=v.agent_id WHERE a.id=? AND a.tenant_id=? ORDER BY v.version_number DESC LIMIT 1`,[id,tenant.id]);
    if(!rows.length)throw new AiPlatformError('not_found',404,'Agent not found');
    const config:any=parseJsonObject(rows[0].config_json||{},'config_json');
    res.json({success:true,data:{versionId:rows[0].version_id,versionNumber:rows[0].version_number,lifecycleStatus:rows[0].lifecycle_status,voiceProfile:config.voiceProfile||null,endOfTurnSilenceMs:Number(config.voice?.endOfTurnSilenceMs||450),pronunciationEntries:config.pronunciationEntries||[]}});
  }));
  app.post('/api/ai-platform/agents/:id/voice-settings/preview',...authenticated,permit('manage_ai_agents'),enabled,wrap(async(req,res)=>{
    positiveInt(req.params.id,'agent id');
    const{profile,vad,entries}=safeVoiceSettings(req.body);
    res.json({success:true,data:{voiceProfile:profile,endOfTurnSilenceMs:vad,compiledInstructions:compileVoiceProfileInstructions(profile,entries),testPhrase:DEFAULT_RUSSIAN_TEST_PHRASE,latencyEstimate:{vadMs:vad,startupBufferMs:500,providerDependent:true},changesApplied:false,auditoryReviewRequired:true}});
  }));
  app.post('/api/ai-platform/agents/:id/voice-settings/draft',...authenticated,permit('manage_ai_voice_profiles'),permit('manage_ai_agents'),enabled,wrap(async(req,res)=>{
    const tenant=await getInstallationTenant(store),id=positiveInt(req.params.id,'agent id'),{profile,vad,entries}=safeVoiceSettings(req.body);
    const rows=await store.query(`SELECT v.id, v.config_json,v.system_prompt FROM ai_agents a JOIN ai_agent_versions v ON v.id=a.current_version_id
      WHERE a.tenant_id=? AND a.id=? AND v.lifecycle_status='published' LIMIT 1`,[tenant.id,id]);
    if(!rows.length)throw new AiPlatformError('not_found',404,'Agent not found');
    const config:any=parseJsonObject(rows[0].config_json||{},'config_json');
    await voiceCatalog.requireAvailable(tenant.id,profile.provider,profile.voiceId);
    const oldVoiceId=String(config.voiceProfile?.voiceId||'');
    config.voiceProfile=profile;config.voice={...(config.voice||{}),endOfTurnSilenceMs:vad};
    delete config.voice.speakingRate;delete config.voice.pauseStyle;
    config.pronunciationEntries=entries;
    const data=await builder.createDraftVersion(tenant.id,id,{config,systemPrompt:String(rows[0].system_prompt||''),changeReason:'Voice profile settings'},actor(req));
    await store.query(`INSERT INTO ai_agent_tools(tenant_id,agent_version_id,tool_id,enabled,config_json)
      SELECT tenant_id,?,tool_id,enabled,config_json FROM ai_agent_tools WHERE tenant_id=? AND agent_version_id=?`,[data.id,tenant.id,rows[0].id]);
    await store.query(`INSERT INTO ai_agent_actions(tenant_id,agent_version_id,action_definition_id,enabled,config_json)
      SELECT tenant_id,?,action_definition_id,enabled,config_json FROM ai_agent_actions WHERE tenant_id=? AND agent_version_id=?`,[data.id,tenant.id,rows[0].id]);
    await store.query(`INSERT INTO ai_agent_skills(tenant_id,agent_version_id,skill_id,priority,enabled)
      SELECT tenant_id,?,skill_id,priority,enabled FROM ai_agent_skills WHERE tenant_id=? AND agent_version_id=?`,[data.id,tenant.id,rows[0].id]);
    await audit.append({tenantId:tenant.id,...actor(req),eventType:'voice_profile_voice_selected' as any,entityType:'agent_version',entityId:String(data.id),decision:'draft_selected',details:{agentId:id,oldVoiceId,newVoiceId:profile.voiceId,versionId:data.id}});
    res.status(201).json({success:true,data});
  }));

  app.get('/api/ai-platform/templates',...authenticated,permit('view_ai_platform'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),p=page(req);const rows=await store.query(`SELECT id,tenant_id,template_key,name,description,agent_type,industry,default_behavior_profile_id,status,created_at,updated_at FROM ai_agent_templates WHERE tenant_id=? OR tenant_id IS NULL ORDER BY tenant_id IS NULL DESC,name LIMIT ? OFFSET ?`,[tenant.id,p.limit,p.offset]);res.json({success:true,rows,page:Math.floor(p.offset/p.limit)+1,limit:p.limit});}));
  app.post('/api/ai-platform/agents/from-template',...authenticated,permit('create_ai_agents'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store);const data=await builder.createFromTemplate(tenant.id,{templateId:positiveInt(req.body?.templateId,'template id'),agentKey:req.body?.agentKey,name:req.body?.name,role:req.body?.role,behaviorProfileId:req.body?.behaviorProfileId?positiveInt(req.body.behaviorProfileId,'behavior profile id'):undefined,permissionKeys:req.body?.permissionKeys,personality:req.body?.personality,voice:req.body?.voice,farewellPolicy:req.body?.farewellPolicy},actor(req));res.status(201).json({success:true,data});}));
  app.post('/api/ai-platform/agents/:id/clone',...authenticated,permit('clone_ai_agents'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store);const data=await builder.cloneAgent(tenant.id,positiveInt(req.params.id,'agent id'),{agentKey:req.body?.agentKey,name:req.body?.name},actor(req));res.status(201).json({success:true,data});}));
  app.get('/api/ai-platform/agents/:id/configuration',...authenticated,permit('view_ai_platform'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),id=positiveInt(req.params.id,'agent id');const rows=await store.query(`SELECT a.id,a.agent_key,a.name,a.agent_type,a.status,a.current_version_id,v.id version_id,v.version_number,v.lifecycle_status,v.config_json,v.system_prompt,v.checksum FROM ai_agents a JOIN ai_agent_versions v ON v.agent_id=a.id WHERE a.id=? AND a.tenant_id=? ORDER BY v.version_number DESC LIMIT 1`,[id,tenant.id]);if(!rows.length)throw new AiPlatformError('not_found',404,'Agent not found');const row=rows[0];res.json({success:true,data:{...row,config:parseJsonObject(row.config_json,'config_json'),config_json:undefined}});}));
  app.post('/api/ai-platform/agents/:id/validate',...authenticated,permit('manage_ai_agents'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),id=positiveInt(req.params.id,'agent id');const rows=await store.query(`SELECT v.id,v.config_json,v.system_prompt,v.checksum FROM ai_agent_versions v JOIN ai_agents a ON a.id=v.agent_id WHERE a.id=? AND a.tenant_id=? ORDER BY v.version_number DESC LIMIT 1`,[id,tenant.id]);if(!rows.length)throw new AiPlatformError('not_found',404,'Agent not found');const row=rows[0],result=await builder.validateAgentConfiguration(tenant.id,{config:row.config_json,prompt:row.system_prompt,checksum:row.checksum});await audit.append({tenantId:tenant.id,...actor(req),eventType:result.valid?'agent_validation_passed':'agent_validation_failed',entityType:'agent',entityId:String(id),decision:result.valid?'allowed':'denied',details:{errors:result.errors}});res.json({success:true,data:result});}));
  app.get('/api/ai-platform/behavior-profiles',...authenticated,permit('view_ai_platform'),enabled,wrap(async(_req,res)=>{const tenant=await getInstallationTenant(store);const rows=await store.query(`SELECT id,profile_key,name,language,response_style_json,emotion_model_json,voice_behavior_json,conversation_rules_json,transfer_policy_json,safety_policy_json,personality_schema_version,personality_profile_json,created_at,updated_at FROM ai_behavior_profiles WHERE tenant_id=? ORDER BY name`,[tenant.id]);res.json({success:true,rows:rows.map(row=>({...row,responseStyle:parseJsonObject(row.response_style_json||{},'response_style_json'),emotionModel:parseJsonObject(row.emotion_model_json||{},'emotion_model_json'),voiceBehavior:parseJsonObject(row.voice_behavior_json||{},'voice_behavior_json'),conversationRules:parseJsonObject(row.conversation_rules_json||{},'conversation_rules_json'),transferPolicy:parseJsonObject(row.transfer_policy_json||{},'transfer_policy_json'),safetyPolicy:parseJsonObject(row.safety_policy_json||{},'safety_policy_json'),personality:parseJsonObject(row.personality_profile_json||{},'personality_profile_json'),response_style_json:undefined,emotion_model_json:undefined,voice_behavior_json:undefined,conversation_rules_json:undefined,transfer_policy_json:undefined,safety_policy_json:undefined,personality_profile_json:undefined}))});}));
  app.get('/api/ai-platform/transfer-policies',...authenticated,permit('manage_ai_transfer_policies'),enabled,wrap(async(_req,res)=>{const tenant=await getInstallationTenant(store);const rows=await store.query('SELECT id,tenant_id,policy_key,name,rules_json,created_at FROM ai_transfer_policies WHERE tenant_id=? OR tenant_id IS NULL ORDER BY tenant_id IS NULL DESC,name',[tenant.id]);res.json({success:true,rows:rows.map(row=>({...row,rules:parseJsonObject(row.rules_json,'rules_json'),rules_json:undefined}))});}));
  app.get('/api/ai-platform/autonomy-policies',...authenticated,permit('view_ai_platform'),enabled,wrap(async(_req,res)=>{const tenant=await getInstallationTenant(store);const rows=await store.query('SELECT id,tenant_id,policy_key,level,rules_json,created_at FROM ai_autonomy_policies WHERE tenant_id=? OR tenant_id IS NULL ORDER BY tenant_id IS NULL DESC,policy_key',[tenant.id]);res.json({success:true,rows:rows.map(row=>({...row,rules:parseJsonObject(row.rules_json,'rules_json'),rules_json:undefined}))});}));
  app.post('/api/ai-platform/agents/:id/test-session',...authenticated,permit('run_ai_test_sessions'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),agentId=positiveInt(req.params.id,'agent id');const rows=await store.query('SELECT id FROM ai_agent_versions WHERE id=? AND agent_id=? AND tenant_id=? LIMIT 1',[positiveInt(req.body?.agentVersionId,'agent version id'),agentId,tenant.id]);if(!rows.length)throw new AiPlatformError('not_found',404,'Agent version not found');const result:any=await store.query(`INSERT INTO ai_agent_test_sessions (tenant_id,agent_id,agent_version_id,started_by,status,transcript_json,result_json) VALUES (?,?,?,?,?,?,?)`,[tenant.id,agentId,Number(rows[0].id),actor(req).actorId,'created','[]','{}']);const id=Number(result.insertId||0);await audit.append({tenantId:tenant.id,...actor(req),eventType:'test_session_created',entityType:'agent_test_session',entityId:String(id),decision:'created',details:{agentId,agentVersionId:rows[0].id,llmStarted:false}});res.status(201).json({success:true,data:{id,status:'created',llmStarted:false}});}));
  app.get('/api/ai-platform/test-sessions/:id',...authenticated,permit('run_ai_test_sessions'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),id=positiveInt(req.params.id,'test session id');const rows=await store.query('SELECT id,agent_id,agent_version_id,started_by,status,transcript_json,result_json,created_at FROM ai_agent_test_sessions WHERE id=? AND tenant_id=? LIMIT 1',[id,tenant.id]);if(!rows.length)throw new AiPlatformError('not_found',404,'Test session not found');const row=rows[0];res.json({success:true,data:{...row,transcript:JSON.parse(String(row.transcript_json||'[]')),result:parseJsonObject(row.result_json||{},'result_json'),transcript_json:undefined,result_json:undefined}});}));
  app.get('/api/ai-platform/agents/:id/context-preview',...authenticated,permit('view_ai_context_preview'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),agentId=positiveInt(req.params.id,'agent id');const rows=await store.query('SELECT COALESCE(current_version_id,(SELECT id FROM ai_agent_versions WHERE agent_id=a.id AND tenant_id=a.tenant_id ORDER BY version_number DESC LIMIT 1)) version_id FROM ai_agents a WHERE id=? AND tenant_id=? LIMIT 1',[agentId,tenant.id]);const versionId=Number(rows[0]?.version_id||0);if(!versionId)throw new AiPlatformError('not_found',404,'Agent version not found');const data=await contextBuilder.buildContext(tenant.id,versionId);await audit.append({tenantId:tenant.id,...actor(req),eventType:'context_preview_requested',entityType:'agent',entityId:String(agentId),decision:'allowed',details:{agentVersionId:versionId,llmCalled:false}});res.json({success:true,data,llmCalled:false})}));

  registerKnowledgeRoutes(app,domainRuntime);
  registerTrainingRoutes(app,domainRuntime);
  registerActionRoutes(app,domainRuntime);
  registerSkillRoutes(app,domainRuntime,skills,skillClassifier);
  registerVoiceRoutes(app,domainRuntime,voiceGateway,ariManager);
  registerVoiceMediaRoutes(app,domainRuntime,mediaSessions,mediaRegistry);
  registerRealtimeVoiceRoutes(app,domainRuntime,realtimeSessions,realtimeRegistry);
  registerLiveVoiceRoutes(app,domainRuntime,liveVoice);
  registerVoiceTranscriptRoutes(app,domainRuntime,transcriptService,recordingService);
  registerVoiceAgentRouteRoutes(app,domainRuntime,voiceAgentRoutes);
  registerAiExtensionRoutes(app,domainRuntime,aiExtensions);
  app.post('/api/ai-platform/agents/:id/sandbox/start',...authenticated,permit('execute_ai_sandbox'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),agentId=positiveInt(req.params.id,'agent id'),versionId=positiveInt(req.body?.versionId,'version id'),a=actor(req);const versions=await store.query('SELECT id,lifecycle_status FROM ai_agent_versions WHERE id=? AND agent_id=? AND tenant_id=? LIMIT 1',[versionId,agentId,tenant.id]);if(!versions.length)throw new AiPlatformError('not_found',404,'Agent version not found');if(versions[0].lifecycle_status!=='published'&&!req.body?.allowDraft)throw new AiPlatformError('conflict',409,'Draft version requires explicit sandbox mode');const conversationId=await conversationService.start(tenant.id,agentId,versionId,a.actorId);const result:any=await store.query("INSERT INTO ai_agent_test_sessions(tenant_id,agent_id,agent_version_id,started_by,status,transcript_json,result_json,conversation_id) VALUES (?,?,?,?,'active','[]','{}',?)",[tenant.id,agentId,versionId,a.actorId,conversationId]);const sessionId=Number(result.insertId);await audit.append({tenantId:tenant.id,...a,eventType:'sandbox_session_started',entityType:'sandbox_session',entityId:String(sessionId),decision:'started',details:{agentId,versionId,draft:versions[0].lifecycle_status==='draft'}});res.status(201).json({success:true,data:{sessionId,conversationId,agentVersionId:versionId,status:'active'}})}));
  app.post('/api/ai-platform/sandbox/:sessionId/message',...authenticated,permit('execute_ai_sandbox'),enabled,sandboxGuard,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),a=actor(req),controller=new AbortController(),canExecuteTools=await deps.checkPermission(req,'execute_ai_read_tools');req.once('aborted',()=>controller.abort());res.json({success:true,data:await sandboxRuntime.message(tenant.id,positiveInt(req.params.sessionId,'session id'),req.body?.message,{...a,permissions:canExecuteTools?['execute_ai_read_tools']:[]},controller.signal)})}));
  app.get('/api/ai-platform/sandbox/:sessionId',...authenticated,permit('execute_ai_sandbox'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),a=actor(req),id=positiveInt(req.params.sessionId,'session id');const rows=await store.query('SELECT id,agent_id,agent_version_id,conversation_id,status,result_json,created_at FROM ai_agent_test_sessions WHERE id=? AND tenant_id=? AND started_by=? LIMIT 1',[id,tenant.id,a.actorId]);if(!rows.length)throw new AiPlatformError('not_found',404,'Sandbox session not found');const messages=await store.query('SELECT sequence_no,role,content,provider_message_id,token_json,latency_ms,created_at FROM ai_conversation_messages WHERE conversation_id=? AND tenant_id=? ORDER BY sequence_no',[rows[0].conversation_id,tenant.id]);res.json({success:true,data:{...rows[0],result:parseJsonObject(rows[0].result_json||{},'result_json'),result_json:undefined,messages}})}));
  for(const action of ['complete','cancel'] as const)app.post(`/api/ai-platform/sandbox/:sessionId/${action}`,...authenticated,permit('execute_ai_sandbox'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),a=actor(req),id=positiveInt(req.params.sessionId,'session id'),rows=await store.query("SELECT conversation_id FROM ai_agent_test_sessions WHERE id=? AND tenant_id=? AND started_by=? AND status='active' LIMIT 1",[id,tenant.id,a.actorId]);if(!rows.length)throw new AiPlatformError('not_found',404,'Active sandbox session not found');const status=action==='complete'?'completed':'cancelled';await conversationService.finish(tenant.id,rows[0].conversation_id,status);await store.query('UPDATE ai_agent_test_sessions SET status=?,result_json=? WHERE id=? AND tenant_id=?',[status,JSON.stringify({status}),id,tenant.id]);await audit.append({tenantId:tenant.id,...a,eventType:action==='complete'?'sandbox_session_completed':'sandbox_session_cancelled',entityType:'sandbox_session',entityId:String(id),decision:status});res.json({success:true,data:{id,status}})}));

  const safeTransferRow=(row:any)=>({id:Number(row.id),agentName:row.agent_name||null,status:row.status,triggerType:row.trigger_type,destinationType:row.destination_type||null,destinationSafeLabel:row.destination_value_safe||null,fallbackAction:row.fallback_action||null,failureCode:row.failure_code||null,requestedAt:row.requested_at,startedAt:row.started_at,completedAt:row.completed_at,failedAt:row.failed_at});
  app.get('/api/ai-platform/transfer-requests',...authenticated,permit('view_ai_transfer_requests'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),p=page(req),rows=await store.query('SELECT r.id,a.name agent_name,r.status,r.trigger_type,r.destination_type,r.destination_value_safe,r.fallback_action,r.failure_code,r.requested_at,r.started_at,r.completed_at,r.failed_at FROM ai_transfer_requests r JOIN ai_agents a ON a.id=r.agent_id AND a.tenant_id=r.tenant_id WHERE r.tenant_id=? ORDER BY r.id DESC LIMIT ? OFFSET ?',[tenant.id,p.limit,p.offset]),count=await store.query('SELECT COUNT(*) total FROM ai_transfer_requests WHERE tenant_id=?',[tenant.id]);res.json({success:true,rows:rows.map(safeTransferRow),pagination:{page:Math.floor(p.offset/p.limit)+1,limit:p.limit,total:Number(count[0]?.total||0)}})}));
  app.get('/api/ai-platform/transfer-requests/:id',...authenticated,permit('view_ai_transfer_requests'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),rows=await store.query('SELECT id,status,trigger_type,destination_type,destination_value_safe,fallback_action,failure_code,requested_at,started_at,completed_at,failed_at FROM ai_transfer_requests WHERE id=? AND tenant_id=? LIMIT 1',[positiveInt(req.params.id,'transfer request id'),tenant.id]);if(!rows[0])throw new AiPlatformError('not_found',404,'Transfer request not found');res.json({success:true,data:safeTransferRow(rows[0])})}));
  app.post('/api/ai-platform/transfer/dry-run',...authenticated,permit('execute_ai_sandbox'),enabled,wrap(async(req,res)=>{if(!humanTransfer)throw new AiPlatformError('storage_unavailable',503,'Transfer resolver unavailable');if(['channel','context','extension','queue','dialString','destination'].some(key=>req.body?.[key]!==undefined))throw new AiPlatformError('invalid_request',400,'Arbitrary transfer destination is forbidden');const tenant=await getInstallationTenant(store),a=actor(req);res.json({success:true,data:await humanTransfer.request({tenantId:tenant.id,traceId:a.traceId,conversationId:req.body?.conversationId?positiveInt(req.body.conversationId,'conversation id'):null,agentId:positiveInt(req.body?.agentId,'agent id'),agentVersionId:positiveInt(req.body?.agentVersionId,'agent version id'),requestedByType:a.actorType,requestedById:a.actorId,triggerType:'admin_test',dryRun:true})})}));
  app.post('/api/ai-platform/transfer/test',...authenticated,permit('test_ai_human_transfer'),permit('execute_ai_sandbox'),enabled,wrap(async(req,res)=>{if(!humanTransfer)throw new AiPlatformError('storage_unavailable',503,'Transfer adapter unavailable');if(req.body?.confirm!==true)throw new AiPlatformError('invalid_request',400,'Explicit confirmation is required');if(['channel','context','extension','queue','dialString','destination'].some(key=>req.body?.[key]!==undefined))throw new AiPlatformError('invalid_request',400,'Arbitrary transfer destination is forbidden');const liveCallId=String(req.body?.liveCallId||'').trim();if(!/^[A-Za-z0-9_.:-]{1,191}$/.test(liveCallId))throw new AiPlatformError('invalid_request',400,'Invalid live call reference');const tenant=await getInstallationTenant(store),a=actor(req),now=Date.now(),consume=(key:string,limit:number)=>{const hits=(transferHits.get(key)||[]).filter(value=>now-value<600000);if(hits.length>=limit)throw new AiPlatformError('rate_limited',429,'Transfer test rate limit exceeded');hits.push(now);transferHits.set(key,hits)};consume(`u:${tenant.id}:${a.actorId}`,3);consume(`t:${tenant.id}`,5);res.json({success:true,data:await humanTransfer.request({tenantId:tenant.id,traceId:a.traceId,conversationId:null,agentId:positiveInt(req.body?.agentId,'agent id'),agentVersionId:positiveInt(req.body?.agentVersionId,'agent version id'),requestedByType:a.actorType,requestedById:a.actorId,triggerType:'admin_test',liveCallId,dryRun:false})})}));

  app.get('/api/ai-platform/agents/:id/versions/:versionId/tools',...authenticated,permit('view_ai_tools'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),agentId=positiveInt(req.params.id,'agent id'),versionId=positiveInt(req.params.versionId,'version id'),versions=await store.query('SELECT lifecycle_status FROM ai_agent_versions WHERE id=? AND agent_id=? AND tenant_id=? LIMIT 1',[versionId,agentId,tenant.id]);if(!versions.length)throw new AiPlatformError('not_found',404,'Agent version not found');const rows=await store.query(`SELECT t.id,t.tool_key,t.description,t.risk_level,t.executor_key,t.enabled tool_enabled,at.enabled assigned FROM ai_tools t LEFT JOIN ai_agent_tools at ON at.tool_id=t.id AND at.agent_version_id=? AND at.tenant_id=? WHERE (t.tenant_id=? OR t.tenant_id IS NULL) AND t.risk_level='read' ORDER BY t.tool_key`,[versionId,tenant.id,tenant.id]);res.json({success:true,data:{agentId,versionId,lifecycleStatus:versions[0].lifecycle_status,rows:rows.map(({executor_key,...row})=>({...row,executorStatus:toolExecutor?.hasExecutor(executor_key)?'registered':'unavailable',requiredPermission:'execute_ai_read_tools'}))}})}));
  app.put('/api/ai-platform/agents/:id/versions/:versionId/tools',...authenticated,permit('manage_ai_tools'),permit('manage_ai_agents'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),agentId=positiveInt(req.params.id,'agent id'),versionId=positiveInt(req.params.versionId,'version id'),versions=await store.query('SELECT lifecycle_status FROM ai_agent_versions WHERE id=? AND agent_id=? AND tenant_id=? LIMIT 1',[versionId,agentId,tenant.id]);if(!versions.length)throw new AiPlatformError('not_found',404,'Agent version not found');if(versions[0].lifecycle_status!=='draft')throw new AiPlatformError('conflict',409,'Published agent version tools are immutable');const toolIds=Array.isArray(req.body?.toolIds)?[...new Set(req.body.toolIds.map((value:unknown)=>positiveInt(value,'tool id')))]:[];const allowed=toolIds.length?await store.query(`SELECT id FROM ai_tools WHERE id IN (${toolIds.map(()=>'?').join(',')}) AND (tenant_id=? OR tenant_id IS NULL) AND enabled=1 AND risk_level='read'`,[...toolIds,tenant.id]):[];if(allowed.length!==toolIds.length)throw new AiPlatformError('invalid_request',400,'Unknown or non-read tool');await store.query('UPDATE ai_agent_tools SET enabled=0 WHERE tenant_id=? AND agent_version_id=?',[tenant.id,versionId]);for(const toolId of toolIds)await store.query('INSERT INTO ai_agent_tools(tenant_id,agent_version_id,tool_id,enabled,config_json) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE enabled=VALUES(enabled)',[tenant.id,versionId,toolId,1,'{}']);await audit.append({tenantId:tenant.id,...actor(req),eventType:'tool_assignment_changed',entityType:'agent_version',entityId:String(versionId),decision:'updated',details:{agentId,toolCount:toolIds.length}});res.json({success:true,data:{agentId,versionId,toolIds}})}));

  app.get('/api/ai-platform/providers',...authenticated,permit('view_ai_platform'),enabled,wrap(async(_req,res)=>{const tenant=await getInstallationTenant(store),legacy=publicLegacyProviderConfig(readLegacyProviderConfig(await deps.readLegacyDb()));
    const rows=await store.query(`SELECT id,provider_key,purpose,model,status,created_at,updated_at,
      CASE WHEN base_url IS NOT NULL AND base_url<>'' THEN 1 ELSE 0 END base_url_configured,
      CASE WHEN secret_ref IS NOT NULL OR encrypted_secret IS NOT NULL THEN 1 ELSE 0 END secret_configured FROM ai_provider_configs WHERE tenant_id=? ORDER BY provider_key,purpose`,[tenant.id]);
    res.json({success:true,rows,legacyCompatibility:legacy});}));
  app.get('/api/ai-platform/providers/capabilities',...authenticated,permit('view_ai_platform'),enabled,wrap(async(_req,res)=>res.json({success:true,rows:getAIProviderRegistry().list()})));
  app.get('/api/ai-platform/tools',...authenticated,permit('view_ai_tools'),enabled,wrap(async(_req,res)=>{const tenant=await getInstallationTenant(store);
    const rows=await store.query('SELECT id,tenant_id,tool_key,version,description,risk_level,input_schema_json,output_schema_json,executor_key,enabled,created_at,updated_at FROM ai_tools WHERE tenant_id=? OR tenant_id IS NULL ORDER BY tool_key,version',[tenant.id]);
    const runtime=new Map(getToolRegistry().list().map(item=>[`${item.key}@${item.version}`,item.executorStatus]));res.json({success:true,writeToolsEnabled:false,rows:rows.map(row=>({...row,executorStatus:runtime.get(`${row.tool_key}@${row.version}`)||'disabled'}))});}));
  app.get('/api/ai-platform/audit',...authenticated,permit('view_ai_audit'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),p=page(req);
    const rows=await store.query('SELECT id,trace_id,actor_type,actor_id,event_type,entity_type,entity_id,decision,details_json,created_at FROM ai_audit_log WHERE tenant_id=? ORDER BY id DESC LIMIT ? OFFSET ?',[tenant.id,p.limit,p.offset]);
    res.json({success:true,rows:rows.map(row=>({...row,details:redactAiPlatformValue(parseJsonObject(row.details_json,'details_json')).value,details_json:undefined})),page:Math.floor(p.offset/p.limit)+1,limit:p.limit});}));
  app.get('/api/ai-platform/tool-executions',...authenticated,permit('view_ai_tool_executions'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),p=page(req),rows=await store.query('SELECT id,trace_id,conversation_id,agent_id,agent_version_id,tool_id,tool_key,status,risk_level,error_code,duration_ms,actor_id,created_at,completed_at FROM ai_tool_executions WHERE tenant_id=? ORDER BY id DESC LIMIT ? OFFSET ?',[tenant.id,p.limit,p.offset]),count=await store.query('SELECT COUNT(*) total FROM ai_tool_executions WHERE tenant_id=?',[tenant.id]),total=Number(count[0]?.total||0);res.json({success:true,rows,pagination:{page:Math.floor(p.offset/p.limit)+1,limit:p.limit,total,totalPages:Math.ceil(total/p.limit)}})}));
  app.get('/api/ai-platform/tool-executions/:id',...authenticated,permit('view_ai_tool_executions'),enabled,wrap(async(req,res)=>{const tenant=await getInstallationTenant(store),rows=await store.query('SELECT id,trace_id,conversation_id,agent_id,agent_version_id,tool_id,tool_key,status,risk_level,error_code,duration_ms,actor_id,created_at,completed_at FROM ai_tool_executions WHERE id=? AND tenant_id=? LIMIT 1',[positiveInt(req.params.id,'execution id'),tenant.id]);if(!rows.length)throw new AiPlatformError('not_found',404,'Tool execution not found');res.json({success:true,data:rows[0]})}));
  app.post('/api/ai-platform/tools/:toolId/test',...authenticated,permit('test_ai_tools'),permit('execute_ai_read_tools'),enabled,wrap(async(req,res)=>{if(!toolExecutor)throw new AiPlatformError('storage_unavailable',503,'PBX read services unavailable');const tenant=await getInstallationTenant(store),a=actor(req),versionId=positiveInt(req.body?.agentVersionId,'agent version id'),toolId=positiveInt(req.params.toolId,'tool id');const assignments=await store.query(`SELECT av.agent_id,t.tool_key FROM ai_agent_versions av JOIN ai_agent_tools at ON at.agent_version_id=av.id AND at.tenant_id=av.tenant_id AND at.enabled=1 JOIN ai_tools t ON t.id=at.tool_id AND (t.tenant_id=av.tenant_id OR t.tenant_id IS NULL) WHERE av.id=? AND av.tenant_id=? AND t.id=? LIMIT 1`,[versionId,tenant.id,toolId]);if(!assignments.length)throw new AiPlatformError('not_found',404,'Assigned tool or agent version not found');const cancellation=new AbortController();req.once('aborted',()=>cancellation.abort());const data=await toolExecutor.execute({traceId:a.traceId,tenantId:tenant.id,installationId:'installation',actorId:a.actorId,actorType:a.actorType,agentId:Number(assignments[0].agent_id),agentVersionId:versionId,conversationId:null,toolId,toolKey:String(assignments[0].tool_key),permissions:['execute_ai_read_tools'],locale:'ru',requestStartedAt:new Date().toISOString(),idempotencyKey:req.body?.idempotencyKey?String(req.body.idempotencyKey):null},parseJsonObject(req.body?.input||{},'input'),cancellation.signal);res.json({success:true,data:{id:data.id,ok:data.ok,durationMs:data.durationMs,safeSummary:'Tool execution completed',errorCode:null}})}));
  return {
    start: async()=>{const rows=await store.query("SELECT setting_key,setting_value FROM settings WHERE setting_key IN('ai.voice_gateway_auto_start','ai.platform_core_enabled','ai.voice_control_plane_enabled','ai.voice_media_transport_enabled','ai.realtime_voice_enabled')"),flags=new Map(rows.map((row:any)=>[String(row.setting_key),String(row.setting_value)])),enabledKeys=['ai.platform_core_enabled','ai.voice_control_plane_enabled','ai.voice_media_transport_enabled','ai.realtime_voice_enabled'];if(flags.get('ai.voice_gateway_auto_start')!=='true'||!enabledKeys.every(key=>flags.get(key)==='true'))return{started:false,reason:'feature_disabled'};await startMediaWorker();await ariManager.start('voice-gateway-auto-start').catch(()=>{});const tenantId=await installationTenantId(),pending=await store.query("SELECT id FROM ai_voice_sessions WHERE tenant_id=? AND state='completed' AND recording_ref_safe IS NULL ORDER BY id DESC LIMIT 20",[tenantId]);for(const row of pending)recordingService.schedule(tenantId,Number(row.id),'voice-gateway-auto-start');return{started:ariManager.status().running,state:ariManager.status().state}},
    stop: async()=>{await realtimeSessions.shutdown();await mediaSessions.shutdown();await stopMediaWorker();await ariManager.stop('voice-gateway-shutdown').catch(()=>{});return{stopped:true}},
    status:()=>ariManager.status()
  };
}
