import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Bell,CheckCircle,Loader2,Send,Trash2}from'lucide-react';

const CATEGORY_LABELS:Record<string,string>={balance:'Балансы',calls:'Звонки',telephony:'Телефония',monitoring:'Мониторинг',system:'Система',security:'Безопасность'};
const STATUS_LABELS:Record<string,string>={pending:'Ожидает',sent:'Отправлено',failed:'Ошибка',retry_scheduled:'Повтор запланирован',disabled:'Отключено',filtered_by_severity:'Отфильтровано по важности',cooldown:'Cooldown',duplicate:'Дубликат'};
export default function NotificationCenterSettings({token,canManage,canViewLog}:{token:string;canManage:boolean;canViewLog:boolean}){
 const[data,setData]=useState<any>(null),[secret,setSecret]=useState(''),[replace,setReplace]=useState(false),[preview,setPreview]=useState<any>(null),[bot,setBot]=useState<any>(null),[telegramChats,setTelegramChats]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState('load'),[message,setMessage]=useState<any>(null),[filters,setFilters]=useState({status:'',category:'',eventType:'',from:'',to:''});
 const headers=useMemo(()=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'}),[token]);
 const request=useCallback(async(path:string,options:RequestInit={})=>{const response=await fetch(path,{...options,headers}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.safeMessage||body.error||'Операция недоступна');return body},[headers]);
 const load=useCallback(async()=>{setBusy('load');try{const body=await request('/api/notifications/settings');setData(body)}catch(error:any){setMessage({error:true,text:error.message})}finally{setBusy('')}},[request]);
 const loadLog=useCallback(async()=>{if(!canViewLog)return;const query=new URLSearchParams(Object.entries(filters).filter(([,value])=>value));const body=await request(`/api/notifications/deliveries?${query}`);setRows(body.rows||[])},[canViewLog,filters,request]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(data)void loadLog()},[data,loadLog]);
 const global=data?.global||{},channel=data?.channel||{},rules=data?.rules||[],catalog=data?.catalog||[];
 const updateGlobal=(key:string,value:any)=>setData((old:any)=>({...old,global:{...old.global,[key]:value}}));const updateChannel=(key:string,value:any)=>setData((old:any)=>({...old,channel:{...old.channel,[key]:value}}));
 const updateRule=(eventType:string,patch:any)=>setData((old:any)=>({...old,rules:old.rules.map((rule:any)=>rule.eventType===eventType?{...rule,...patch}:rule)}));
 const save=async()=>{setBusy('save');setMessage(null);try{const body=await request('/api/notifications/settings',{method:'PUT',body:JSON.stringify({global,rules,channel:{enabled:channel.enabled,chatId:channel.chatId,botToken:secret,replaceToken:replace}})});setData(body);setSecret('');setReplace(false);setMessage({text:'Настройки сохранены'})}catch(error:any){setMessage({error:true,text:error.message})}finally{setBusy('')}};
 const action=async(kind:'test'|'preview'|'clear')=>{setBusy(kind);setMessage(null);try{if(kind==='test'){await request('/api/notifications/test',{method:'POST'});setMessage({text:'Тестовое сообщение доставлено'})}else if(kind==='preview'){const body=await request('/api/notifications/preview');setPreview(body.candidates||{});setMessage({text:'Предпросмотр выполнен без отправки'})}else{const body=await request('/api/notifications/telegram/token',{method:'DELETE'});setData((old:any)=>({...old,channel:body.channel}));setSecret('');setMessage({text:'Токен удалён, Telegram выключен'})}}catch(error:any){setMessage({error:true,text:error.message})}finally{setBusy('')}};
 const openBotFather=()=>{window.open('https://t.me/BotFather','_blank','noopener,noreferrer');if(navigator.clipboard?.writeText)void navigator.clipboard.writeText('/newbot').then(()=>setMessage({text:'Команда /newbot скопирована — вставьте её в BotFather и нажмите Enter'})).catch(()=>setMessage({text:'В BotFather выберите команду /newbot'}));else setMessage({text:'В BotFather выберите команду /newbot'})};
 const telegramSetup=async(kind:'check'|'discover')=>{setBusy(kind);setMessage(null);try{if(kind==='check'){const body=await request('/api/notifications/telegram/check',{method:'POST'});setBot(body.bot);setMessage({text:`Бот @${body.bot.username} доступен`})}else{const body=await request('/api/notifications/telegram/discover-chats',{method:'POST'});setTelegramChats(body.chats||[]);setMessage({text:body.chats?.length?'Доступные чаты найдены':'Чаты не найдены: добавьте бота и отправьте сообщение в группу или канал'})}}catch(error:any){setMessage({error:true,text:error.message})}finally{setBusy('')}};
 if(busy==='load'&&!data)return <div className="flex gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin"/>Загрузка…</div>;if(!data)return <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{message?.text||'Центр уведомлений недоступен'}</div>;
 const grouped=Object.keys(CATEGORY_LABELS).map(category=>({category,items:rules.filter((rule:any)=>rule.category===category)}));
 return <div className="space-y-5">
  <section className="rounded-2xl border bg-slate-50 p-5"><h4 className="flex items-center gap-2 text-sm font-black"><Bell className="h-4 w-4 text-blue-600"/>Общие настройки</h4><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3"><label className="flex items-center gap-2 text-xs font-bold"><input disabled={!canManage} type="checkbox" checked={global.enabled===true} onChange={e=>updateGlobal('enabled',e.target.checked)}/>Центр включён</label><label className="text-xs font-bold">Название АТС<input disabled={!canManage} value={global.objectName||''} onChange={e=>updateGlobal('objectName',e.target.value)} className="mt-1 w-full rounded-lg border bg-white px-3 py-2"/></label><label className="text-xs font-bold">Минимальная важность<select disabled={!canManage} value={global.minimumSeverity||'warning'} onChange={e=>updateGlobal('minimumSeverity',e.target.value)} className="mt-1 w-full rounded-lg border bg-white px-3 py-2"><option value="info">Информация</option><option value="warning">Предупреждение</option><option value="error">Ошибка</option><option value="critical">Критическая</option></select></label><label className="flex items-center gap-2 text-xs font-bold"><input disabled={!canManage} type="checkbox" checked={global.notifyOnRecovery!==false} onChange={e=>updateGlobal('notifyOnRecovery',e.target.checked)}/>Уведомлять о восстановлении</label><label className="text-xs font-bold">Стандартный cooldown, секунд<input disabled={!canManage} type="number" min="0" value={global.defaultCooldownSeconds||3600} onChange={e=>updateGlobal('defaultCooldownSeconds',Number(e.target.value))} className="mt-1 w-full rounded-lg border bg-white px-3 py-2"/></label></div></section>
  <section className="rounded-2xl border p-5">
   <h4 className="text-sm font-black">Telegram</h4>
   <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="flex items-center gap-2 text-xs font-bold"><input disabled={!canManage} type="checkbox" checked={channel.enabled===true} onChange={e=>updateChannel('enabled',e.target.checked)}/>Канал включён</label><div className="text-xs text-slate-500">Последняя доставка: {channel.lastSuccessAt||'—'}<br/>Последняя ошибка: {channel.lastError?STATUS_LABELS[channel.lastError]||channel.lastError:'—'}</div><label className="text-xs font-bold">Bot Token<input disabled={!canManage} type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder={channel.hasToken?'Токен сохранён · оставьте пустым без изменения':'Telegram Bot Token'} className="mt-1 w-full rounded-lg border px-3 py-2 font-mono"/></label><label className="text-xs font-bold">Chat ID<input disabled={!canManage} value={channel.chatId||''} onChange={e=>updateChannel('chatId',e.target.value)} placeholder="Целое число со знаком" className="mt-1 w-full rounded-lg border px-3 py-2 font-mono"/></label>{channel.hasToken&&<label className="flex items-center gap-2 text-xs"><input disabled={!canManage} type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>Разрешить замену сохранённого токена</label>}</div>
   <div className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-4"><b className="text-xs">Мастер Telegram</b><p className="mt-1 text-[11px] text-slate-600">Если бота ещё нет, кнопка откроет официальный BotFather и скопирует команду <code>/newbot</code>. Вставьте её, нажмите Enter, затем укажите название и уникальный username с окончанием <code>bot</code>. Полученный токен вставьте выше и сохраните.</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={openBotFather} className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Создать бота в Telegram</button><a href="https://web.telegram.org/a/" target="_blank" rel="noreferrer" className="rounded-lg border bg-white px-3 py-2 text-xs font-bold">Открыть Telegram Web</a><button type="button" disabled={!canManage||!channel.hasToken||!!busy} onClick={()=>void telegramSetup('check')} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold">Проверить бота</button>{bot?.username&&<><a href={`https://t.me/${bot.username}?startgroup&admin=manage_chat`} target="_blank" rel="noreferrer" className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Создать / выбрать группу</a><a href={`https://t.me/${bot.username}?startchannel&admin=post_messages`} target="_blank" rel="noreferrer" className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Создать / выбрать канал</a></>}<button type="button" disabled={!canManage||!channel.hasToken||!!busy} onClick={()=>void telegramSetup('discover')} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold">Найти Chat ID</button></div>{bot?.username&&<p className="mt-2 text-[11px] text-emerald-700">Подключён бот @{bot.username}</p>}{telegramChats.length>0&&<div className="mt-3 space-y-2">{telegramChats.map(chat=><button type="button" key={chat.chatId} onClick={()=>updateChannel('chatId',chat.chatId)} className="flex w-full items-center justify-between rounded-lg border bg-white px-3 py-2 text-left text-xs"><span><b>{chat.title}</b><small className="ml-2 text-slate-400">{chat.type}</small></span><code>{chat.chatId}</code></button>)}</div>}</div>
   <div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={!canManage||!!busy} onClick={()=>void action('test')} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-bold"><Send className="h-4 w-4"/>Тестовое сообщение</button><button type="button" disabled={!!busy} onClick={()=>void action('preview')} className="rounded-lg border px-3 py-2 text-xs font-bold">Предпросмотр</button>{channel.hasToken&&<button type="button" disabled={!canManage||!!busy} onClick={()=>window.confirm('Удалить сохранённый Telegram Bot Token?')&&void action('clear')} className="flex items-center gap-2 rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-700"><Trash2 className="h-4 w-4"/>Удалить токен</button>}</div>
  </section>
  <section className="rounded-2xl border p-5"><h4 className="text-sm font-black">События</h4><div className="mt-4 space-y-3">{grouped.map(group=>{const categoryEnabled=global.categories?.[group.category]!==false;return <div key={group.category} className="rounded-xl border"><label className="flex items-center gap-2 border-b bg-slate-50 p-3 text-xs font-black"><input disabled={!canManage} type="checkbox" checked={categoryEnabled} onChange={e=>updateGlobal('categories',{...(global.categories||{}),[group.category]:e.target.checked})}/>{CATEGORY_LABELS[group.category]}</label><div className={`space-y-2 p-3 ${categoryEnabled?'':'opacity-45'}`}>{group.items.map((rule:any)=>{const definition=catalog.find((item:any)=>item.eventType===rule.eventType);return <div key={rule.eventType} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[minmax(220px,1fr)_120px_140px_170px]"><label className="flex items-start gap-2 text-xs"><input disabled={!canManage||!categoryEnabled} type="checkbox" checked={rule.enabled===true} onChange={e=>updateRule(rule.eventType,{enabled:e.target.checked})}/><span><b>{definition?.title||rule.eventType}</b><small className="block text-slate-400">{rule.eventType}{definition?.producer==='registered'?' · источник пока не подключён':''}</small></span></label><label className="text-[10px]">Cooldown, сек.<input disabled={!canManage||!categoryEnabled} type="number" min="0" value={rule.cooldownSeconds} onChange={e=>updateRule(rule.eventType,{cooldownSeconds:Number(e.target.value)})} className="mt-1 w-full rounded border px-2 py-1"/></label><label className="flex items-center gap-2 text-[10px]"><input disabled={!canManage||!categoryEnabled} type="checkbox" checked={rule.notifyOnRecovery===true} onChange={e=>updateRule(rule.eventType,{notifyOnRecovery:e.target.checked})}/>Recovery</label><div className="text-[10px]">{rule.eventType==='balance.low'&&<label>Порог<input disabled={!canManage||!categoryEnabled} type="number" value={rule.parameters?.threshold??1500} onChange={e=>updateRule(rule.eventType,{parameters:{...rule.parameters,threshold:Number(e.target.value)}})} className="mt-1 w-full rounded border px-2 py-1"/></label>}{rule.eventType==='calls.missed_unreturned'&&<span className="block rounded border bg-slate-50 px-2 py-1">Общий SLA: {data.callQuality?.missedCallSlaMinutes??'—'} мин.</span>}{rule.eventType==='trunk.down'&&<label>Ошибок подряд<input disabled={!canManage||!categoryEnabled} type="number" min="1" value={rule.parameters?.consecutiveFailures??2} onChange={e=>updateRule(rule.eventType,{parameters:{...rule.parameters,consecutiveFailures:Number(e.target.value)}})} className="mt-1 w-full rounded border px-2 py-1"/></label>}</div></div>})}</div></div>})}</div></section>
  {preview&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs">Найдено без отправки: баланс — {preview.balance?.length||0}, пропущенные — {preview.missedCalls?.length||0}, транки — {preview.trunks?.length||0}, система — {preview.system?.length||0}.</div>}
  {message&&<div className={`flex gap-2 rounded-xl p-3 text-xs font-bold ${message.error?'bg-rose-50 text-rose-700':'bg-emerald-50 text-emerald-700'}`}><CheckCircle className="h-4 w-4"/>{message.text}</div>}
  {canManage&&<div className="flex justify-end"><button type="button" disabled={!!busy} onClick={()=>void save()} className="rounded-lg bg-blue-600 px-5 py-2 text-xs font-black text-white">{busy==='save'?'Сохранение…':'Сохранить'}</button></div>}
  {canViewLog&&<section className="rounded-2xl border p-5"><h4 className="text-sm font-black">Журнал доставок</h4><div className="my-3 grid gap-2 md:grid-cols-5"><input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})} className="rounded border p-2 text-xs"/><input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})} className="rounded border p-2 text-xs"/><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})} className="rounded border p-2 text-xs"><option value="">Все статусы</option>{Object.entries(STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})} className="rounded border p-2 text-xs"><option value="">Все категории</option>{Object.entries(CATEGORY_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input placeholder="Тип события" value={filters.eventType} onChange={e=>setFilters({...filters,eventType:e.target.value})} className="rounded border p-2 text-xs"/></div><div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th>Дата</th><th>Событие</th><th>Объект</th><th>Важность</th><th>Канал</th><th>Статус</th><th>Попытки</th><th>Ошибка</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td>{row.created_at||'—'}</td><td>{row.event_type||'—'}</td><td>{row.entity_id||'—'}</td><td>{row.severity||'—'}</td><td>{row.channel_id||'telegram'}</td><td>{STATUS_LABELS[row.status]||row.status}</td><td>{row.attempt_count}</td><td>{row.last_error||'—'}</td></tr>)}</tbody></table></div></section>}
 </div>
}
