import { useState } from 'react';

const sessionToken=()=>{try{return JSON.parse(localStorage.getItem('asterisk_cdr_session')||'{}').token||''}catch{return''}};
async function api(url:string,init:RequestInit={}){const response=await fetch(url,{...init,headers:{Authorization:`Bearer ${sessionToken()}`,'Content-Type':'application/json',...(init.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}

export default function BitrixPullSetup({onChanged}:{onChanged:()=>Promise<void>}){
 const [open,setOpen]=useState(false),[name,setName]=useState('vigodno.org'),[endpoint,setEndpoint]=useState('https://vigodno.org/local/api/pbxpuls/leads.php'),[token,setToken]=useState(''),[integrationId,setIntegrationId]=useState(''),[forms,setForms]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const connect=async()=>{setBusy(true);setError('');try{const created=await api('/api/site-forms/integrations/pull',{method:'POST',body:JSON.stringify({name,endpointUrl:endpoint,token,siteUrl:'https://vigodno.org',allowedFormIds:[]})});setIntegrationId(created.integrationId);const catalog=await api(`/api/site-forms/integrations/${created.integrationId}/pull-forms`);setForms(catalog.forms||[]);setSelected((catalog.forms||[]).filter((form:any)=>form.hasPhone).map((form:any)=>String(form.id)));setToken('')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const save=async()=>{setBusy(true);setError('');try{await api(`/api/site-forms/integrations/${integrationId}/pull-settings`,{method:'PATCH',body:JSON.stringify({formIds:selected,syncIntervalSeconds:60})});await api(`/api/site-forms/integrations/${integrationId}/sync`,{method:'POST',body:'{}'});await onChanged();setOpen(false);setIntegrationId('');setForms([])}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(!open)return <button onClick={()=>setOpen(true)} className="rounded-xl bg-violet-600 px-4 py-2 text-xs font-black text-white">Подключить 1С-Битрикс Pull API</button>;
 return <div className="rounded-2xl border border-violet-200 bg-violet-50 p-4"><div className="flex items-center justify-between"><h3 className="font-black">Подключение 1С-Битрикс</h3><button onClick={()=>setOpen(false)}>Закрыть</button></div>{error&&<div className="mt-3 rounded bg-red-50 p-2 text-xs text-red-700">{error}</div>}{!integrationId?<div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Название<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 h-9 w-full rounded border px-3"/></label><label className="text-xs font-bold">HTTPS URL Pull API<input value={endpoint} onChange={e=>setEndpoint(e.target.value)} className="mt-1 h-9 w-full rounded border px-3"/></label><label className="text-xs font-bold sm:col-span-2">Токен<input type="password" value={token} onChange={e=>setToken(e.target.value)} className="mt-1 h-9 w-full rounded border px-3" autoComplete="new-password"/></label><button disabled={busy||!token||!endpoint} onClick={()=>void connect()} className="rounded bg-violet-600 px-4 py-2 text-xs font-black text-white disabled:opacity-40">Проверить и загрузить формы</button></div>:<div className="mt-3"><div className="mb-2 flex justify-between text-xs"><b>Формы сайта</b><button onClick={()=>setSelected(forms.filter(form=>form.hasPhone).map(form=>String(form.id)))} className="text-violet-700">Выбрать с телефоном</button></div><div className="grid gap-2 sm:grid-cols-2">{forms.map(form=><label key={form.id} className="flex items-start gap-2 rounded border bg-white p-2 text-xs"><input type="checkbox" checked={selected.includes(String(form.id))} disabled={!form.hasPhone} onChange={e=>setSelected(current=>e.target.checked?[...current,String(form.id)]:current.filter(id=>id!==String(form.id)))}/><span><b>{form.name}</b><span className="block text-slate-500">ID {form.id} · результатов {form.resultsCount} · {form.hasPhone?'есть телефон':'нет телефона'}</span></span></label>)}</div><button disabled={busy||!selected.length} onClick={()=>void save()} className="mt-3 rounded bg-violet-600 px-4 py-2 text-xs font-black text-white disabled:opacity-40">Сохранить и синхронизировать</button></div>}</div>
}
