import { useMemo, useState } from 'react';
import { CheckCircle2, Download, ExternalLink, Globe2, ShieldCheck } from 'lucide-react';

const sessionToken=()=>{try{return JSON.parse(localStorage.getItem('asterisk_cdr_session')||'{}').token||''}catch{return''}};
async function api(url:string,init:RequestInit={}){const response=await fetch(url,{...init,headers:{Authorization:`Bearer ${sessionToken()}`,'Content-Type':'application/json',...(init.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}

type Step='platform'|'site'|'pair'|'select';

export default function BitrixPullSetup({onChanged}:{onChanged:()=>Promise<void>}){
 const[open,setOpen]=useState(false),[step,setStep]=useState<Step>('platform'),[siteUrl,setSiteUrl]=useState(''),[name,setName]=useState(''),[preview,setPreview]=useState<any>(null),[code,setCode]=useState(''),[integrationId,setIntegrationId]=useState(''),[sites,setSites]=useState<any[]>([]),[siteId,setSiteId]=useState(''),[forms,setForms]=useState<any[]>([]),[selected,setSelected]=useState<string[]>([]),[tracking,setTracking]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const visibleForms=useMemo(()=>forms.filter(form=>!siteId||!Array.isArray(form.siteIds)||!form.siteIds.length||form.siteIds.includes(siteId)),[forms,siteId]);
 const reset=()=>{setOpen(false);setStep('platform');setPreview(null);setCode('');setIntegrationId('');setSites([]);setForms([]);setSelected([]);setError('')};
 const inspect=async()=>{setBusy(true);setError('');try{const result=await api('/api/site-forms/integrations/bitrix-pair-preview',{method:'POST',body:JSON.stringify({siteUrl})});setPreview(result);setSiteUrl(result.siteUrl);setStep('pair')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const pair=async()=>{setBusy(true);setError('');try{const result=await api('/api/site-forms/integrations/bitrix-pair-apply',{method:'POST',body:JSON.stringify({siteUrl:preview.siteUrl,name:name||new URL(preview.siteUrl).hostname,code,previewToken:preview.previewToken})});const foundSites=result.sites||[],foundForms=result.forms||[];setIntegrationId(result.integrationId);setSites(foundSites);setForms(foundForms);const first=String(foundSites[0]?.id||'');setSiteId(first);setSelected(foundForms.filter((form:any)=>form.hasPhone&&(!first||!form.siteIds?.length||form.siteIds.includes(first))).map((form:any)=>String(form.id)));setCode('');setStep('select')}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const save=async()=>{setBusy(true);setError('');try{await api(`/api/site-forms/integrations/${integrationId}/pull-settings`,{method:'PATCH',body:JSON.stringify({formIds:selected,calltrackingSiteId:siteId,trackingEnabled:tracking,syncIntervalSeconds:60})});await api(`/api/site-forms/integrations/${integrationId}/sync`,{method:'POST',body:'{}'});await onChanged();reset()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(!open)return <button onClick={()=>setOpen(true)} className="rounded-xl bg-violet-600 px-4 py-2 text-xs font-black text-white">Добавить интеграцию</button>;
 return <div className="rounded-2xl border border-violet-200 bg-violet-50 p-4"><div className="flex items-center justify-between"><div><h3 className="font-black">Мастер подключения сайта</h3><p className="text-xs text-slate-500">Пароль администратора не передаётся в PBXPuls</p></div><button onClick={reset}>Закрыть</button></div>{error&&<div className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}
 {step==='platform'&&<div className="mt-4 grid gap-3 sm:grid-cols-2"><button onClick={()=>setStep('site')} className="rounded-xl border-2 border-violet-400 bg-white p-4 text-left"><Globe2 className="mb-2 h-5 w-5 text-violet-600"/><b>1С-Битрикс</b><span className="mt-1 block text-xs text-slate-500">Сайты, веб-формы и клики по телефонам</span></button><button disabled className="rounded-xl border bg-slate-100 p-4 text-left opacity-60"><b>WordPress</b><span className="mt-1 block text-xs text-slate-500">Будет добавлен следующим адаптером</span></button></div>}
 {step==='site'&&<div className="mt-4 space-y-3"><a href="/downloads/pbxpuls-bitrix-connector-v5.8.0.zip" download className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs font-bold text-violet-700"><Download className="h-4 w-4"/>Скачать модуль</a><div className="rounded-lg bg-white p-3 text-xs text-slate-600">Установите модуль на сайт, затем укажите адрес. PBXPuls проверит коннектор без изменений на сайте.</div><label className="block text-xs font-bold">Адрес сайта<input value={siteUrl} onChange={e=>setSiteUrl(e.target.value)} placeholder="https://example.ru" className="mt-1 h-10 w-full rounded-lg border px-3 font-normal"/></label><label className="block text-xs font-bold">Название в PBXPuls<input value={name} onChange={e=>setName(e.target.value)} placeholder="Основной сайт" className="mt-1 h-10 w-full rounded-lg border px-3 font-normal"/></label><button disabled={busy||!siteUrl} onClick={()=>void inspect()} className="rounded-lg bg-violet-600 px-4 py-2 text-xs font-black text-white disabled:opacity-40">Проверить коннектор</button></div>}
 {step==='pair'&&<div className="mt-4 space-y-3"><div className="flex items-start gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-800"><CheckCircle2 className="h-4 w-4 shrink-0"/>Коннектор найден. Откройте административную страницу сайта и создайте одноразовый код.</div><a href={`${preview.siteUrl}/local/api/pbxpuls/setup.php`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs font-bold"><ExternalLink className="h-4 w-4"/>Открыть страницу кода</a><label className="block text-xs font-bold">Одноразовый код<input inputMode="numeric" maxLength={8} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,8))} placeholder="12345678" className="mt-1 h-12 w-full rounded-lg border px-3 text-center font-mono text-xl tracking-[0.4em]"/></label><div className="rounded-lg bg-white p-3 text-xs text-slate-600"><ShieldCheck className="mr-2 inline h-4 w-4 text-emerald-600"/>Код действует 10 минут и обменивается на отдельный read-only токен.</div><button disabled={busy||code.length!==8} onClick={()=>void pair()} className="rounded-lg bg-violet-600 px-4 py-2 text-xs font-black text-white disabled:opacity-40">Подключить и найти сайты</button></div>}
 {step==='select'&&<div className="mt-4 space-y-4"><label className="block text-xs font-bold">Сайт<select value={siteId} onChange={e=>{const value=e.target.value;setSiteId(value);setSelected(forms.filter((form:any)=>form.hasPhone&&(!form.siteIds?.length||form.siteIds.includes(value))).map((form:any)=>String(form.id)))} } className="mt-1 h-10 w-full rounded-lg border bg-white px-3">{sites.map(site=><option key={site.id} value={site.id}>{site.id} — {site.name||site.domain}</option>)}</select></label><div><div className="mb-2 flex justify-between text-xs"><b>Формы сайта</b><button onClick={()=>setSelected(visibleForms.filter(form=>form.hasPhone).map(form=>String(form.id)))} className="text-violet-700">Выбрать с телефоном</button></div><div className="grid gap-2 sm:grid-cols-2">{visibleForms.map(form=><label key={form.id} className="flex items-start gap-2 rounded border bg-white p-2 text-xs"><input type="checkbox" checked={selected.includes(String(form.id))} disabled={!form.hasPhone} onChange={e=>setSelected(current=>e.target.checked?[...current,String(form.id)]:current.filter(id=>id!==String(form.id)))}/><span><b>{form.name}</b><span className="block text-slate-500">ID {form.id} · результатов {form.resultsCount} · {form.hasPhone?'есть телефон':'нет телефона'}</span></span></label>)}</div></div><label className="flex items-start gap-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs"><input type="checkbox" checked={tracking} onChange={e=>setTracking(e.target.checked)} className="mt-0.5"/><span><b>Собирать клики по телефонам</b><span className="mt-1 block text-slate-600">Модуль автоматически подключит tracker.js на сайте {siteId}. Сохраняются tel:, страница, UTM, referrer и анонимный session ID.</span></span></label><button disabled={busy||!siteId||!selected.length} onClick={()=>void save()} className="rounded-lg bg-violet-600 px-4 py-2 text-xs font-black text-white disabled:opacity-40">Сохранить и выполнить тестовую синхронизацию</button></div>}
 </div>;
}
