import { createInterfaceDateTimeFormatter } from '../../../utils/formatInterfaceDateTime';
import { useEffect, useMemo, useState } from 'react';
import { Eye, Phone, ShieldAlert, Trash2 } from 'lucide-react';

const sessionToken=()=>{try{return JSON.parse(localStorage.getItem('asterisk_cdr_session')||'{}').token||''}catch{return''}};
const statusLabels:Record<string,string>={new:'Новая',in_progress:'В работе',call_scheduled:'Запланирована',contact_attempted:'Попытка связи',contacted:'Связались',completed:'Обработана',rejected:'Отклонена',spam:'Спам',duplicate:'Дубль'};
const statusTone:Record<string,string>={new:'bg-blue-50 text-blue-700 border-blue-200',in_progress:'bg-violet-50 text-violet-700 border-violet-200',call_scheduled:'bg-amber-50 text-amber-700 border-amber-200',contact_attempted:'bg-orange-50 text-orange-700 border-orange-200',contacted:'bg-emerald-50 text-emerald-700 border-emerald-200',completed:'bg-emerald-50 text-emerald-700 border-emerald-200',rejected:'bg-rose-50 text-rose-700 border-rose-200',spam:'bg-slate-100 text-slate-600 border-slate-200',duplicate:'bg-slate-100 text-slate-600 border-slate-200'};
const callBadge=(row:any)=>row.first_answered_call_at?{label:'Дозвонились',tone:'bg-emerald-50 text-emerald-700 border-emerald-200'}:row.first_call_at?{label:'Нет ответа',tone:'bg-amber-50 text-amber-700 border-amber-200'}:{label:'Не звонили',tone:'bg-slate-50 text-slate-600 border-slate-200'};
const badge=(label:string,tone:string)=><span className={`inline-flex rounded-lg border px-2.5 py-1 text-[11px] font-bold ${tone}`}>{label}</span>;

type Props={items:any[];loading:boolean;canManage:boolean;onOpen:(row:any)=>void;onCall:(row:any)=>void;onChanged:()=>Promise<void>;onError:(message:string)=>void};

export default function SiteFormsLeadTable({items,loading,canManage,onOpen,onCall,onChanged,onError}:Props){
 const fmt = createInterfaceDateTimeFormatter();
 const [selected,setSelected]=useState<number[]>([]),[busy,setBusy]=useState(false);
 useEffect(()=>setSelected(current=>current.filter(id=>items.some(row=>Number(row.id)===id))),[items]);
 const pageIds=useMemo(()=>items.map(row=>Number(row.id)),[items]),allSelected=pageIds.length>0&&pageIds.every(id=>selected.includes(id));
 const toggle=(id:number)=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
 const request=async(url:string,body:any)=>{const response=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${sessionToken()}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data};
 const apply=async(action:'spam'|'delete',ids=selected)=>{if(!ids.length)return;setBusy(true);try{const preview=await request('/api/site-forms/leads/bulk-preview',{action,ids});if(!preview.count)throw new Error('Подходящие заявки не найдены');const verb=action==='spam'?'Отправить в спам':'Убрать из рабочего списка';if(!confirm(`${verb}: ${preview.count} заявок?\n\nОперация будет записана в журнал.`))return;await request('/api/site-forms/leads/bulk-apply',{action,ids:preview.ids,previewToken:preview.previewToken});setSelected([]);await onChanged()}catch(error:any){onError(error.message)}finally{setBusy(false)}};
 return <div className="overflow-hidden rounded-2xl border bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900">
  {selected.length>0&&<div className="flex flex-wrap items-center gap-2 border-b bg-blue-50 px-4 py-3 text-xs dark:bg-blue-950/20"><b>Выбрано: {selected.length}</b><button disabled={busy} onClick={()=>void apply('spam')} className="ml-auto inline-flex items-center gap-1 rounded-lg border border-amber-200 bg-white px-3 py-2 font-bold text-amber-700 disabled:opacity-50"><ShieldAlert className="h-4 w-4"/>В спам</button><button disabled={busy} onClick={()=>void apply('delete')} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 bg-white px-3 py-2 font-bold text-rose-700 disabled:opacity-50"><Trash2 className="h-4 w-4"/>Убрать мусор</button></div>}
  <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-slate-50 text-slate-500 dark:bg-slate-950/40"><tr><th className="w-10 px-3 py-3"><input type="checkbox" aria-label="Выбрать все на странице" checked={allSelected} onChange={()=>setSelected(allSelected?selected.filter(id=>!pageIds.includes(id)):Array.from(new Set([...selected,...pageIds])))} /></th>{['Дата и время','Имя','Телефон','Сообщение','Статус','Дозвон','Действия'].map(label=><th key={label} className="px-3 py-3 font-black">{label}</th>)}</tr></thead><tbody>{items.map(row=>{const call=callBadge(row);return <tr key={row.id} className="border-t align-top transition hover:bg-blue-50/40 dark:border-slate-800"><td className="px-3 py-3"><input type="checkbox" checked={selected.includes(Number(row.id))} onChange={()=>toggle(Number(row.id))}/></td><td className="whitespace-nowrap px-3 py-3 font-medium">{fmt(row.created_at)}</td><td className="max-w-[180px] px-3 py-3 font-bold">{row.customer_name||'Без имени'}</td><td className="whitespace-nowrap px-3 py-3"><button onClick={()=>onCall(row)} className="font-mono font-black text-blue-600">{row.phone_raw}</button></td><td className="max-w-[360px] px-3 py-3"><div className="line-clamp-3 whitespace-pre-wrap text-slate-700 dark:text-slate-200" title={row.form_message||''}>{row.form_message||'—'}</div><div className="mt-1 text-[10px] font-bold text-slate-400">{row.form_name||row.external_form_id}</div></td><td className="px-3 py-3">{badge(statusLabels[row.status]||row.status,statusTone[row.status]||statusTone.new)}</td><td className="px-3 py-3">{badge(call.label,call.tone)}</td><td className="px-3 py-3"><div className="flex gap-1"><button onClick={()=>onCall(row)} title="Позвонить" className="rounded-lg bg-emerald-100 p-2 text-emerald-700"><Phone className="h-4 w-4"/></button><button onClick={()=>onOpen(row)} title="Открыть" className="rounded-lg bg-blue-100 p-2 text-blue-700"><Eye className="h-4 w-4"/></button>{canManage&&<button onClick={()=>void apply('spam',[Number(row.id)])} title="В спам" className="rounded-lg bg-amber-100 p-2 text-amber-700"><ShieldAlert className="h-4 w-4"/></button>}</div></td></tr>})}</tbody></table>{!items.length&&!loading&&<div className="p-10 text-center text-slate-500">Заявок пока нет</div>}</div>
 </div>;
}
