import crypto from'node:crypto';
import type{AiPlatformStore}from'../../storage/aiPlatformStore.js';
import type{AiAuditService}from'../../audit/aiAuditService.js';
import{AiPlatformError}from'../../core/errors.js';
import{findAiConfigSecretField}from'../agentConfigurationValidator.js';
import{AgentBuilderService}from'../agentBuilderService.js';
import{FreePbxAiExtensionAdapter}from'../../extensions/freePbxAiExtensionAdapter.js';
import type{AiExtensionService}from'../../extensions/aiExtensionService.js';
import type{VoiceCatalogService}from'../../voice/profiles/voiceCatalogService.js';
import{AGENT_CREATION_TEMPLATES}from'./agentCreationTypes.js';

const text=(v:unknown,max=191)=>String(v||'').replace(/[<>]/g,'').trim().slice(0,max);
const object=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,any>:{};
const json=(v:any)=>JSON.stringify(v);
const key=(v:unknown)=>{const value=String(v||'');if(!/^[A-Za-z0-9_.:-]{8,100}$/.test(value))throw new AiPlatformError('invalid_request',400,'Valid idempotency key required');return value};
const slug=(name:string,id:number)=>`${name.toLowerCase().replace(/[^a-z0-9а-я]+/giu,'_').replace(/^[^a-z]+/,'').slice(0,70)||'ai_agent'}_${id}`;

export class AgentCreationService{
 constructor(private store:AiPlatformStore,private audit:AiAuditService,private extensions:AiExtensionService,private voices:VoiceCatalogService,private freepbx=new FreePbxAiExtensionAdapter()){}
 async templates(){return AGENT_CREATION_TEMPLATES}
 async listDrafts(tenantId:number,actorId:string|null){return this.store.query("SELECT id,state,name,role,extension,template_key templateKey,updated_at updatedAt,created_at createdAt FROM ai_agent_creation_drafts WHERE tenant_id=? AND created_by<=>? AND state NOT IN('active') ORDER BY id DESC",[tenantId,actorId])}
 async get(tenantId:number,id:number){const row=(await this.store.query('SELECT * FROM ai_agent_creation_drafts WHERE tenant_id=? AND id=? LIMIT 1',[tenantId,id]))[0];if(!row)throw new AiPlatformError('not_found',404,'Черновик создания не найден');return this.project(row)}
 async createDraft(tenantId:number,input:any,actor:any){
  const idem=key(input.idempotencyKey),old=(await this.store.query('SELECT id FROM ai_agent_creation_drafts WHERE tenant_id=? AND idempotency_key=? LIMIT 1',[tenantId,idem]))[0];if(old)return{...(await this.get(tenantId,Number(old.id))),idempotent:true};
  const template=String(input.templateKey||'blank'),known=AGENT_CREATION_TEMPLATES.find(x=>x.key===template);if(!known)throw new AiPlatformError('invalid_request',400,'Неизвестный шаблон');
  const payload=this.defaults(known,input);
  const result:any=await this.store.query(`INSERT INTO ai_agent_creation_drafts(tenant_id,idempotency_key,state,template_key,name,role,description,language,communication_style,greeting,extension,freepbx_display_name,fallback_type,fallback_value,provider,model,voice_id,voice_json,skills_json,knowledge_json,handoff_json,source_agent_id,created_by)
   VALUES(?,?,'draft',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[tenantId,idem,template,payload.name,payload.role,payload.description,payload.language,payload.communicationStyle,payload.greeting,payload.extension,payload.freepbxDisplayName,payload.fallbackType,payload.fallbackValue,payload.provider,payload.model,payload.voiceId,json(payload.voice),json(payload.skills),json(payload.knowledge),json(payload.handoff),payload.sourceAgentId,actor.actorId]);
  await this.audit.append({tenantId,...actor,eventType:'agent_created' as any,entityType:'agent_creation_draft',entityId:String(result.insertId),decision:'draft_started',details:{template}});
  return this.get(tenantId,Number(result.insertId));
 }
 async updateDraft(tenantId:number,id:number,input:any,actor:any){
  const current=await this.get(tenantId,id);if(!['draft','preview_ready','creation_failed'].includes(current.state))throw new AiPlatformError('conflict',409,'Черновик уже применяется');
  const payload=this.defaults(AGENT_CREATION_TEMPLATES.find(x=>x.key===(input.templateKey||current.templateKey))||AGENT_CREATION_TEMPLATES[3],{...current,...input});
  if(findAiConfigSecretField(payload))throw new AiPlatformError('invalid_request',400,'Секреты нельзя копировать в мастер');
  await this.store.query(`UPDATE ai_agent_creation_drafts SET state='draft',template_key=?,name=?,role=?,description=?,language=?,communication_style=?,greeting=?,extension=?,freepbx_display_name=?,fallback_type=?,fallback_value=?,provider=?,model=?,voice_id=?,voice_json=?,skills_json=?,knowledge_json=?,handoff_json=?,source_agent_id=?,error_code=NULL,updated_at=NOW() WHERE tenant_id=? AND id=?`,[payload.templateKey,payload.name,payload.role,payload.description,payload.language,payload.communicationStyle,payload.greeting,payload.extension,payload.freepbxDisplayName,payload.fallbackType,payload.fallbackValue,payload.provider,payload.model,payload.voiceId,json(payload.voice),json(payload.skills),json(payload.knowledge),json(payload.handoff),payload.sourceAgentId,tenantId,id]);
  await this.audit.append({tenantId,...actor,eventType:'agent_created' as any,entityType:'agent_creation_draft',entityId:String(id),decision:'draft_updated',details:{step:Number(input.step||0)}});
  return this.get(tenantId,id);
 }
 async removeDraft(tenantId:number,id:number,actor:any){const row=await this.get(tenantId,id);if(row.agentId||!['draft','preview_ready','creation_failed'].includes(row.state))throw new AiPlatformError('conflict',409,'Черновик с созданными объектами нельзя удалить');await this.store.query('DELETE FROM ai_agent_creation_previews WHERE tenant_id=? AND draft_id=?',[tenantId,id]);await this.store.query('DELETE FROM ai_agent_creation_drafts WHERE tenant_id=? AND id=?',[tenantId,id]);await this.audit.append({tenantId,...actor,eventType:'agent_created' as any,entityType:'agent_creation_draft',entityId:String(id),decision:'draft_deleted'});return{id,deleted:true,liveObjectsChanged:false}}
 async suggest(tenantId:number){return this.extensions.suggest(tenantId,206,999)}
 async validateExtension(tenantId:number,extension:string,draftId?:number){const normalized=String(extension||'').trim();if(!/^[0-9]{2,8}$/.test(normalized))return{status:'conflict',ready:false,conflicts:[{type:'validation',name:'Номер должен содержать 2–8 цифр'}]};const own=draftId?(await this.store.query('SELECT id FROM ai_agent_creation_drafts WHERE tenant_id=? AND id=? AND extension=?',[tenantId,draftId,normalized]))[0]:null,inspection=await this.freepbx.inspect(normalized),ai=(await this.store.query("SELECT id,status FROM ai_extensions WHERE tenant_id=? AND extension=? AND status<>'archived' LIMIT 1",[tenantId,normalized]))[0];const conflicts=[...inspection.conflicts,...(ai?[{type:'ai_extension',name:`AI Extension ${normalized}`}]:[])];return{status:conflicts.length?'conflict':'free',ready:!conflicts.length,ownedRetry:Boolean(own&&!conflicts.length),conflicts,inspection:{managedBlockPresent:inspection.managedBlockPresent,legacyRoutePresent:inspection.legacyRoutePresent}}}
 async preview(tenantId:number,draftId:number,idempotencyKey:string,actor:any){
  const idem=key(idempotencyKey),existing=(await this.store.query('SELECT id,preview_json,status FROM ai_agent_creation_previews WHERE tenant_id=? AND idempotency_key=? LIMIT 1',[tenantId,idem]))[0];if(existing)return{previewId:Number(existing.id),...JSON.parse(existing.preview_json),idempotent:true};
  await this.store.query("UPDATE ai_agent_creation_drafts SET state='validating',error_code=NULL,updated_at=NOW() WHERE tenant_id=? AND id=?",[tenantId,draftId]);const draft=await this.get(tenantId,draftId);
  try{
   this.validateBasics(draft);await this.voices.requireAvailable(tenantId,draft.provider,draft.voiceId);const number=await this.validateExtension(tenantId,draft.extension,draftId);if(!number.ready)throw new AiPlatformError('conflict',409,`Номер ${draft.extension} занят`);
   const duplicate=(await this.store.query("SELECT id FROM ai_agents WHERE tenant_id=? AND LOWER(name)=LOWER(?) AND status='active' LIMIT 1",[tenantId,draft.name]))[0];
   const handoff=object(draft.handoff);if(handoff.enabled){if(String(handoff.destinationId)===draft.extension)throw new AiPlatformError('conflict',409,'Передача образует цикл');const checked=await this.inspectHandoff(handoff);if(!checked.available)throw new AiPlatformError('conflict',409,'Направление передачи недоступно')}
   const preview={ready:true,applied:false,draftId,agentDraft:{name:draft.name,role:draft.role,description:draft.description,language:draft.language,duplicateNameWarning:Boolean(duplicate)},initialVersion:{draft:true,publishAfterConfirmation:true,versionNumber:1,immutableAfterPublish:true},extension:draft.extension,provider:draft.provider,model:draft.model,voice:draft.voiceId,skills:draft.skills,knowledge:draft.knowledge,handoff,freepbxObjects:{miscApplication:`AI: ${draft.name}`,customDestination:`AI: ${draft.name} (${draft.extension})`,destination:`pbxpuls-ai,${draft.extension},1`,sipEndpointCreated:false},dialplan:{context:'pbxpuls-ai',extension:draft.extension,diff:[`+ exten => ${draft.extension},1,NoOp(PBXPuls managed AI Extension ${draft.extension})`,`+ same => n,Stasis(pbxpuls-ai-control,ai_extension:${draft.extension})`],preserveOtherCustomContexts:true},records:['agent','initial draft version','initial published version','AI Extension','ai_extension binding'],productionAffected:false,dialplanAffected:true,automaticCall:false,rollbackPlan:{beforeVerification:'agent remains draft and disabled',freepbxObjects:'preserve only PBXPuls-owned objects for retry',binding:'disabled until verification',foreignObjects:'never delete',productionRoutes:'unchanged'}};
   const result:any=await this.store.query("INSERT INTO ai_agent_creation_previews(tenant_id,draft_id,idempotency_key,preview_json,status,created_by,expires_at)VALUES(?,?,?,?, 'ready',?,DATE_ADD(NOW(),INTERVAL 30 MINUTE))",[tenantId,draftId,idem,json(preview),actor.actorId]);await this.store.query("UPDATE ai_agent_creation_drafts SET state='preview_ready',updated_at=NOW() WHERE tenant_id=? AND id=?",[tenantId,draftId]);await this.audit.append({tenantId,...actor,eventType:'agent_validation_passed',entityType:'agent_creation_draft',entityId:String(draftId),decision:'preview_ready',details:{extension:draft.extension,provider:draft.provider,voice:draft.voiceId,productionAffected:false}});
   return{previewId:Number(result.insertId),...preview};
  }catch(error:any){await this.store.query("UPDATE ai_agent_creation_drafts SET state='draft',error_code=? WHERE tenant_id=? AND id=?",[String(error?.code||error?.message||'VALIDATION_FAILED').replace(/[^A-Z0-9_.-]/gi,'_').slice(0,64),tenantId,draftId]);throw error}
 }
 async apply(tenantId:number,previewId:number,confirm:boolean,actor:any){
  if(!confirm)throw new AiPlatformError('invalid_request',400,'Explicit confirmation required');const p=(await this.store.query('SELECT * FROM ai_agent_creation_previews WHERE tenant_id=? AND id=? LIMIT 1',[tenantId,previewId]))[0];if(!p)throw new AiPlatformError('not_found',404,'Preview not found');if(p.status==='applied')return{...JSON.parse(p.preview_json),applied:true,idempotent:true};if(p.status!=='ready'||new Date(p.expires_at).getTime()<=Date.now())throw new AiPlatformError('conflict',409,'Preview expired');const draft=await this.get(tenantId,Number(p.draft_id)),builder=new AgentBuilderService(this.store,this.audit);
  let agentId=Number(draft.agentId||0),versionId=Number(draft.agentVersionId||0);
  try{
   await this.store.query("UPDATE ai_agent_creation_drafts SET state='applying',error_code=NULL WHERE id=?",[draft.id]);
   if(!agentId){const behavior=(await this.store.query("SELECT id FROM ai_behavior_profiles WHERE tenant_id=? ORDER BY id LIMIT 1",[tenantId]))[0];const config=this.agentConfig(draft,Number(behavior?.id||0));const agent=await new (await import('../agentLifecycleService.js')).AgentLifecycleService(this.store,this.audit).createAgentDraft(tenantId,{agentKey:slug(draft.name,draft.id),name:draft.name,agentType:'custom',config,systemPrompt:this.prompt(draft)},actor);agentId=agent.id;versionId=agent.version.id;await this.store.query('UPDATE ai_agent_creation_drafts SET agent_id=?,agent_version_id=?,state=? WHERE id=?',[agentId,versionId,'publishing',draft.id]);await builder.publishAgent(tenantId,agentId,versionId,actor)}
   await this.store.query("UPDATE ai_agent_creation_drafts SET state='creating_extension' WHERE id=?",[draft.id]);const extPreview=await this.extensions.previewCreate(tenantId,{agentId,extension:draft.extension,displayName:draft.name,fallbackType:draft.fallbackType,fallbackValue:draft.fallbackValue,idempotencyKey:`agent-create-${draft.id}`},actor);await this.store.query('UPDATE ai_agent_creation_drafts SET ai_extension_preview_id=?,ai_extension_id=?,state=? WHERE id=?',[extPreview.previewId,extPreview.extensionId,'reloading',draft.id]);const applied=await this.extensions.apply(tenantId,extPreview.previewId,true,actor);await this.store.query("UPDATE ai_agent_creation_drafts SET state='verifying' WHERE id=?",[draft.id]);const verified=(await this.store.query("SELECT e.status,e.enabled,e.sync_status,b.status binding_status,b.match_type FROM ai_extensions e JOIN ai_voice_route_bindings b ON b.id=e.route_binding_id WHERE e.tenant_id=? AND e.id=? AND e.agent_id=? AND e.published_agent_version_id=? LIMIT 1",[tenantId,extPreview.extensionId,agentId,versionId]))[0];if(!verified||verified.status!=='active'||!Boolean(verified.enabled)||verified.sync_status!=='synced'||verified.binding_status!=='active'||verified.match_type!=='ai_extension')throw new Error('CREATION_VERIFICATION_FAILED');await this.store.query("UPDATE ai_agent_creation_drafts SET state='active',last_synced_at=NOW(),error_code=NULL WHERE id=?",[draft.id]);await this.store.query("UPDATE ai_agent_creation_previews SET status='applied',applied_at=NOW() WHERE id=?",[previewId]);return{...JSON.parse(p.preview_json),applied:true,verified:true,agentId,versionId,extensionId:extPreview.extensionId,extension:applied};
  }catch(error:any){const code=String(error?.message||'CREATION_FAILED').replace(/[^A-Z0-9_.-]/gi,'_').slice(0,64);await this.store.query("UPDATE ai_agent_creation_drafts SET state='creation_failed',error_code=? WHERE id=?",[code,draft.id]);if(agentId)await this.store.query("UPDATE ai_agents SET status='draft',current_version_id=NULL WHERE tenant_id=? AND id=?",[tenantId,agentId]);throw new AiPlatformError('conflict',409,'Создание не завершено')}
 }
 async retry(tenantId:number,id:number,actor:any){const draft=await this.get(tenantId,id);if(draft.state!=='creation_failed')throw new AiPlatformError('conflict',409,'Retry доступен только после ошибки');return this.preview(tenantId,id,`retry-${id}-${Date.now()}`,actor)}
 private async inspectHandoff(h:any){if(!['extension','queue','ring_group','ivr','custom_destination'].includes(String(h.destinationType)))throw new AiPlatformError('invalid_request',400,'Недопустимый тип направления');return new (await import('../../handoff/handoffConfigService.js')).HandoffConfigService(this.store,this.audit).inspect(String(h.destinationType),String(h.destinationId))}
 private validateBasics(d:any){if(!d.name||d.name.length>191)throw new AiPlatformError('invalid_request',400,'Укажите имя');if(!d.greeting||d.greeting.length>500)throw new AiPlatformError('invalid_request',400,'Приветствие должно содержать от 1 до 500 символов');if(!d.role||!d.description)throw new AiPlatformError('invalid_request',400,'Заполните роль и описание');if(!d.extension)throw new AiPlatformError('invalid_request',400,'Укажите внутренний номер')}
 private prompt(d:any){return`Вы — ${d.name}, ${d.role}. ${d.description}\nСтиль общения: ${d.communicationStyle}. Язык: ${d.language}. Приветствие: ${d.greeting}`.slice(0,4000)}
 private agentConfig(d:any,behaviorProfileId:number){return{role:d.role,description:d.description,language:d.language,communicationStyle:d.communicationStyle,greeting:d.greeting,behaviorProfileId,toolIds:Array.isArray(d.skills?.toolIds)?d.skills.toolIds:[],permissionKeys:[],knowledgeSourceIds:Array.isArray(d.knowledge?.sourceIds)?d.knowledge.sourceIds:[],voiceProfile:{schemaVersion:1,provider:d.provider,voiceId:d.voiceId,language:'ru',locale:d.language,pronunciationStyle:'native_neutral',speakingRate:d.voice.speakingRate||'normal',pauseStyle:d.voice.pauseStyle||'short_natural',expressiveness:'warm_moderate',pitchStyle:'neutral'},realtime:{provider:d.provider,model:d.model}}}
 private defaults(template:any,input:any){const voice={speakingRate:'normal',pauseStyle:'short_natural',testPhrase:'Здравствуйте. Чем могу помочь?',...object(input.voice)};return{templateKey:String(input.templateKey||template.key),name:text(input.name||'',191),role:text(input.role||template.role,191),description:text(input.description||'Помогает клиентам и отвечает на вопросы.',1000),language:text(input.language||'ru-RU',20),communicationStyle:text(input.communicationStyle||template.style,191),greeting:text(input.greeting||template.greeting,500),extension:text(input.extension,8),freepbxDisplayName:text(input.freepbxDisplayName||input.name||'',191),fallbackType:String(input.fallbackType||'terminate_call'),fallbackValue:text(input.fallbackValue,20),provider:String(input.provider||'openai_realtime'),model:text(input.model||'gpt-realtime-2.1',191),voiceId:text(input.voiceId||'marin',100),voice,skills:object(input.skills),knowledge:object(input.knowledge),handoff:{enabled:false,...object(input.handoff)},sourceAgentId:Number(input.sourceAgentId)||null}}
 private project(row:any){return{id:Number(row.id),state:row.state,templateKey:row.template_key,name:row.name,role:row.role,description:row.description,language:row.language,communicationStyle:row.communication_style,greeting:row.greeting,extension:row.extension,freepbxDisplayName:row.freepbx_display_name,fallbackType:row.fallback_type,fallbackValue:row.fallback_value,provider:row.provider,model:row.model,voiceId:row.voice_id,voice:JSON.parse(row.voice_json||'{}'),skills:JSON.parse(row.skills_json||'{}'),knowledge:JSON.parse(row.knowledge_json||'{}'),handoff:JSON.parse(row.handoff_json||'{}'),sourceAgentId:row.source_agent_id?Number(row.source_agent_id):null,agentId:row.agent_id?Number(row.agent_id):null,agentVersionId:row.agent_version_id?Number(row.agent_version_id):null,errorCode:row.error_code,lastSyncedAt:row.last_synced_at,createdAt:row.created_at,updatedAt:row.updated_at}}
}
